define("chartutil/d3utils",["jquery","underscore","d3","chartutil/dateUtils_CET","chartutil/stringutils"],function(e,a,c,g,f){var b={};
b.constants={};b.constants.MILLISECONDS_UNIT="ms";b.constants.granularityFormats=[];b.constants.granularityFormats.month=c.time.format.utc("%b");
b.constants.granularityFormats.week=function(h){return"wk "+h.getWeek();};b.constants.granularityFormats.day=c.time.format.utc("%e");
b.constants.granularityFormats.hour=function(i){var h=g.getAmsterdamDSTOffset(i);return new Date(i.getTime()+h*60*1000).getUTCHours();
};b.constants.granularityFormats.minute=c.time.format.utc("%_M");b.constants.granularityFormatsNonUTC={};b.constants.granularityFormatsNonUTC.minute=c.time.format("%M");
b.constants.granularityFormatsNonUTC.hour=c.time.format("%H");b.constants.granularityFormatsNonUTC.day=c.time.format("%d");
b.constants.granularityFormatsNonUTC.week=function(h){return"wk "+h.getWeek();};b.constants.granularityFormatsNonUTC.month=c.time.format.utc("%b");
b.thousandsFormatter=function(o,n,k){var l=k.ticks();var h=c.max(k.domain());var q=[{suffix:"M",value:1000000},{suffix:"K",value:1000},{suffix:"",value:1}];
var r=a.chain(q).find(function(i){return(h>=i.value);}).value();if(!r){r={suffix:"",value:1};}var j=a.chain(l).map(function(i){return(i/r.value);
}).value();var p=a.chain(j).filter(function(i){return(i%1!==0);}).value();var m=(o/r.value);if(n===0){return(String(m)+r.suffix);
}if(p.length>0){return m.toFixed(1);}return String(m);};b.numberFormatter=function(l,j){var i=[{suffix:"M",value:1000000},{suffix:"k",value:1000},{suffix:"",value:1}];
var k=c.formatPrefix(l).symbol;var h=a.filter(i,function(m){return m.suffix===k;});if(h.length){l=l/h[0].value;}else{k="";
}return(!j)?l+k:l;};b.percentageFormat=function(i){var h=i.selectAll("text");h.text(function(k,j){if(j<(h[0].length-1)){return this.textContent.replace("%","");
}return this.textContent;});};b.lastPercentageFormat=function(k,i){var l=i||5;var j=k.selectAll("text");var h;j.text(function(o,m){var n=this.textContent.replace("%","");
if(m===(j[0].length-1)){n+="%";h=c.select(this);}return n;});if(h){h.transition().duration(150).ease("linear").attr("x",l);
}};b.smartPercentageFormat=function(i){var j=true;var h=i.selectAll("text");h.each(function(n,l){var m=this.textContent.replace("%","");
var k=Number(m);if(k%1!==0){j=false;}});h.text(function(m,k){var l=this.textContent.replace("%","");if(j){if(l.indexOf(".")>-1){l=l.substring(0,l.indexOf("."));
}}if(k===h[0].length-1){l+="%";}return l;});};b.steppedLineInterpolator=function(m,q){var l=0,k=m.length,h=m[0],s=[h[0]-q,",",h[1]],j=0,r=0,o=0;
while(++l<k){j=h[0];h=m[l];r=h[0];o=h[1];s.push("H",j+q);s.push("L",r-q,",",o);}if(k>1){s.push("H",h[0]+q);}return s.join("");
};b.movingAverageInterpolator=function(h){return function(i){var j=i;i=i.map(function(o,k){var p=k+h-1;var n,m;if(p<i.length){n=j.slice(k,p+1);
m=a.reduce(n,function(r,q){return[r[0]+q[0],r[1]+q[1]];});var l=m.map(function(q){return[q[0],q[1]/h];});return l;}return undefined;
});i=i.filter(function(k){return typeof k!=="undefined";});return i.join("L");};};b.fillUTCScaleBuckets=function(j,m,l,i){var n;
switch(m){case"week":n=c.time.monday.utc.range;break;default:n=c.time[m].utc;break;}var h=c.time.scale.utc().range([0,1],0);
h.domain(j);var k=e.map(h.ticks(n,1),function(p,o){var q=g.convertToUTC(p);var r=a.find(l,function(v){var u=v.get("date");
var t=v.get("utcdate");switch(m){case"month":case"week":case"day":return u.getTime()===p.getTime();default:return t.getTime()===q.getTime();
}});if(r){return r;}else{var s=new i();s.set("date",p);s.set("utcdate",q);return s;}});return k;};b.fillTimeScaleBuckets=function(j,m,l,i){var n;
n=c.time[m];var h=c.time.scale().range([0,1],0);h.domain(j);var k=e.map(h.ticks(n,1),function(p,o){var q=g.convertToUTC(p);
var r=a.find(l,function(v){var u=v.get("date");var t=v.get("utcdate");g.roundToDay(u);return u.getTime()===p.getTime();});
if(r){return r;}else{var s=new i();s.set("date",p);s.set("utcdate",q);return s;}});return k;};b.fillTimeScaleBucketsNonBackbone=function(i,l,k){var m;
m=c.time[l];var h=c.time.scale().range([0,1],0);h.domain(i);var j=e.map(h.ticks(m,1),function(o,n){var p=g.convertToUTC(o);
var q=a.find(k,function(u){var t=u.date;var s=u.utcdate;g.roundToDay(t);return t.getTime()===o.getTime();});if(q){return q;
}else{var r={authorisations:0,total:0,abandoned:0,authRate:0,averageRate:null,averageTotal:null,rates:[]};r.date=o;r.utcdate=p;
return r;}});return j;};b.fillTimeScaleBucketsFromTemplate=function(o,j,i,k){var l;l=c.time[j];var n=c.time.format("%Y-%m-%d");
var m=c.time.scale().range([0,1],0);m.domain(o);var h=m.ticks(l,1);var p=e.map(h,function(r,q){var s=a.find(i,function(x){var v=x.date;
var w=g.trueRoundToDay(v,true);var y=g.trueRoundToDay(r,true);var u=w.getTime()===y.getTime();return u;});if(s){return s;
}else{var t=k.apply(null);t.date=r;t.dateStr=n(r);return t;}});return p;};b.spreadTimeAxisTicks=function(j){var i=j.xAxis.selectAll(".tick")[0].length,h=(j.width/i);
var k=j.xAxis.selectAll(".tick").attr("transform",function(m,l){return"translate("+((h*(l+1))-(h/2))+",0)";}).select("text").attr("transform",function(){return"translate(0,7)";
}).each(function(m,l){e(this).show();});};b.spreadXAxisTicks=function(l,k,j){if(k===0){k=7;}var i=j.selectAll(".tick")[0].length,h=(l.width/i);
var m=j.selectAll(".tick").attr("transform",function(o,n){return"translate("+((h*(n+1))-(h/2))+","+0+")";}).select("text").attr("transform",function(){return"translate(0,"+k+")";
}).each(function(o,n){e(this).show();});};b.spreadYAxisTicks=function(j,l,i){var h=i.selectAll(".tick")[0].length,m=(j.height/h);
var k=i.selectAll(".tick").attr("transform",function(o,n){return"translate("+0+","+((m*(n+1))-(m/2))+")";}).select("text").attr("transform",function(){return"translate("+l+","+0+")";
}).each(function(o,n){e(this).show();});};b.spreadTimeYAxisTicks=function(j){var h=j.yAxis.selectAll(".tick")[0].length,i=(j.height/h);
var k=j.yAxis.selectAll(".tick").attr("transform",function(m,l){return"translate(0,"+(j.height-((i*(l+1))-(i/2)))+")";}).select("text").each(function(m,l){e(this).show();
});};b.onAnimationsComplete=function(h,i){c.timer(function(){var j=0;h.$el.find("rect, line, g").each(function(k,l){if(typeof l.__transition__!=="undefined"){j++;
}});if(j===0){i.apply(h,[arguments]);return true;}});};b.closestPointOnLine=function(m,h){var l=Infinity,k=null,j=0;a.each(m.pathSegList,function(o,n){var p=i(o,h);
if(p<l){l=p;k=o;j=n;}});return{segment:k,index:j,distance:l};function i(q,p){var o=q.x-p[0],n=q.y-p[1];return o*o+n*n;}};
b.preventTickOverlap=function(k){var s=c.select(k).selectAll(".tick").style("visibility","hidden"),i=k.getBoundingClientRect().width,v=k.getBoundingClientRect().height,t=0,r=4,u=s[0].length,h=0,m=0,q=0;
var p=e(k).attr("class");if(p.indexOf("x axis")>-1){q="horizontal";}else{if(p.indexOf("y axis")){q="vertical";}}for(var l=0;
l<u;l++){var o=s[0][l],n=s[0][l+1];if(!o||!n||!o.getBoundingClientRect||!n.getBoundingClientRect){continue;}if(q==="vertical"){m=Math.max(m,o.getBoundingClientRect().height);
t=v;}else{if(q==="horizontal"){m=Math.max(m,o.getBoundingClientRect().width);t=i;}}}if(m>(t/u)){h=Math.floor(t/(m+r));var w=Math.ceil(u/h);
c.select(k).selectAll(".tick").filter(function(x,j){return(j%w)===0;}).style("visibility","visible");}else{c.select(k).selectAll(".tick").style("visibility","visible");
}};b.highlightCurrentDay=function(p,k,h){if(h){var m=new Date();var i=m.getDate();var o=m.getMonth();var l=m.getFullYear();
var q=a.first(h).date.getMonth();var n=a.first(h).date.getFullYear();var j=function(s,t){var u=document.createElementNS("http://www.w3.org/2000/svg",s);
for(var r in t){u.setAttribute(r,t[r]);}return u;};p.find("."+k+" .tick text").each(function(s){var r=e(this).text();if(s===0){r=r.replace(/\D/g,"");
}if(Number(r)===i&&q===o&&l===n){e(this).after(j("rect",{y:21,x:-6,height:3,width:12,fill:"#f1bf43"}));}});}};b.lineCreator=function(q,s,i,o,k,n){var w,m,r,v;
if(n){w=n.attr("d");}if(w){m=w.split(q);var l=s.length;r=m.length;if(l>r){k="mixin";}else{return w;}}var j=c.svg.line().interpolate("linear").x(i);
if(k==="enter"){j.y(function(x){return 0;});}else{if(k==="update"){j.y(o);}else{if(k==="mixin"){j.y(function(x){return 0;
});v=j(s);var u=v.split(q);var t=a.drop(u,r);var p=m.concat(t);var h=p.join(q);n.style("opacity",0.000001);return h;}}}v=j(s);
return v;};var d=0;b.checkLabelPos=function(h,k,l,o){var n=k.length;for(var m=0;m<n;m++){var j=k[m].targetY;var t=k[m].order;
var s=k[m].who;var q=Math.floor(j-h);if(d===0){if(q<0){d=1;}else{d=-1;}}var p=4*d;var r=q;if(r<0){r*=-1;}if(r<12){h+=p;return b.checkLabelPos(h,k,l,o);
}}d=0;k.push({targetY:h,order:l,who:o});return h;};b.getJoinAttrNoSpaces=function(k,h){var i=h||"";var l=this._getDatumValue(k,this.options.joinAttr);
var j=f.lowerCaseReplaceSpace(l,i);return j;};b.getCollectionSum=function(i,h){var j=a.reduce(i,function(k,l){return k+l[h];
},0);return j;};b.detectNestedArrays=function(h,j){var i=[];a.each(h,function(k){a.each(k,function(m,l){if(a.isArray(m)){if(j){i.push(l);
}else{i.push(m);}}});});if(j){i=a.uniq(i);}return i;};b.cloneSelection=function(i,h){i.each(function(){var j=h.node().appendChild(this.cloneNode(true));
j.setAttribute("data-clone","");});return h.selectAll("[data-clone]");};b.formatAmount=function(j,h){if(!a.isNumber(j)){return"";
}if(!a.isString(h)){return"";}var i=["IDR","JPY","KRW","VND","BYR","CVE","DJF","GHC","GNF","KMF","PYG","RWF","UGX","VUV","XAF","XOF","XPF"];
var k=a.indexOf(i,h.toUpperCase());if(k>=0){return j;}else{return c.format(",.2f")(j/100);}};b.formatAmountStringsAllowed=function(i,h){if(typeof i==="string"&&i.match(/^\d+(\.\d+)?$/)){return b.formatAmount(parseFloat(i),h);
}return b.formatAmount(Number(i),h);};b.getActualTickValues=function(h){var j=[];var i=h.selectAll("text");i.each(function(p,m){var n=/[^0-9\.]/gi;
var l=n.exec(this.textContent);var o=this.textContent.replace(/[^0-9\.]/gi,"");var k=Number(o);if(l){switch(l[0]){case"%":break;
case"k":k*=1000;break;case"M":k*=1000000;break;}}j.push(k);});return j;};return b;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);
}});