define("chartutil/domUtils",["jquery","lodash","chartutil/object2csv"],function(g,e,c){var b=["font-family","font-size","font-weight","font-style","color","text-transform","text-decoration","letter-spacing","word-spacing","line-height","text-align","vertical-align","direction","background-color","background-image","background-repeat","background-position","background-attachment","opacity","width","height","top","right","bottom","left","margin-top","margin-right","margin-bottom","margin-left","padding-top","padding-right","padding-bottom","padding-left","border-top-width","border-right-width","border-bottom-width","border-left-width","border-top-color","border-right-color","border-bottom-color","border-left-color","border-top-style","border-right-style","border-bottom-style","border-left-style","position","display","visibility","z-index","overflow-x","overflow-y","white-space","clip","float","clear","cursor","list-style-image","list-style-position","list-style-type","marker-offset"];
var f={};var d=document.body;var a=document.documentElement;f.getComputedProperties=function(k){if(typeof(k)==="undefined"){return;
}var j={},m=b.length,l=g(k).parent(),n=k;if(l.length>0){g.each(g(k).parents(),function(i,o){if(g(o).is("body")){return false;
}if(g(o).parent().length<1){n=o;g(n).hide();g("body").append(n);return false;}});}for(var h=0;h<m;h++){j[b[h]]=g(k).css(b[h]);
}j.computedWidth=g(k).width();j.computedHeight=g(k).height();if(l.length<=0||n!==k){g(n).detach();}g(n).show();return j;};
f.cloneNode=function(h,j){var i,k;if(typeof h==="object"){if(h instanceof g){i=h[0];}else{i=h;}}else{if(typeof h==="string"){i=g(h)[0];
}}k=i.cloneNode(true);k.id=j;return k;};f.applyStylesAsInline=function(n,l){var m=[];var i,h;var k=function(r,q){i=r;h=e.find(document.styleSheets,function(s){if(s.href&&s.href.indexOf(i)>-1){return s;
}});m.push(h);};l.forEach(k);var o,p;var j=function(s){o=s.cssRules;p=o.length;var t=function(u,v){v.style.cssText+=o[q].style.cssText;
};for(var q=0;q<p;q++){if(o[q].selectorText&&o[q].selectorText.indexOf(":hover")>-1||o[q].selectorText&&o[q].selectorText.indexOf(":after")>-1||o[q].selectorText&&o[q].selectorText.indexOf(":before")>-1||o[q].selectorText&&o[q].selectorText.indexOf(":first-letter")>-1){continue;
}var r=(o[q].selectorText)?o[q].selectorText.substring(1):"";if(g(n).hasClass(r)){n.style.cssText+=o[q].style.cssText;}g(n).find(o[q].selectorText).each(t);
}};m.forEach(j);};f.nodeToString=function(i){var h=new XMLSerializer();var j=h.serializeToString(i);return j;};f.nodeToBlob=function(j,i){var h=f.nodeToString(j);
return f.stringToBlobUrl(h,i);};f.stringToBlobUrl=function(l,h){var k=window.URL||window.webkitURL||window;var i=new Blob([l],{type:h});
var j=k.createObjectURL(i);return j;};f.createDownloadLink=function(k,i,j,l){var h=document.getElementById("drawAnchor")||document.createElement("a");
g(h).attr("id","drawAnchor");g(h).css("display","none");document.body.appendChild(h);h.download=i+j;h.href=k;if(l){h.click();
}return h;};f.createCSV=function(l,o,j,h){var n={data:l,fields:o,fieldNames:j,quotes:""};var i=c.convert(n);var k=f.stringToBlobUrl(i,"text/html");
var m=f.createDownloadLink(k,h,".csv",true);};f.getScrollTop=function(){if(typeof pageYOffset!=="undefined"){return pageYOffset;
}return a.clientHeight?a.scrollTop:d.scrollTop;};f.getScrollLeft=function(){if(typeof pageXOffset!=="undefined"){return pageXOffset;
}else{return a.clientWidth?a.scrollLeft:d.scrollLeft;}};f.removeDataAtrributes=function(r,h){var p,m=g(r),k=[],l=m.get(0).attributes,n=l.length;
for(p=0;p<n;p++){if(h){for(var o=0,q=h.length;o<q;o++){if(l[p].name===("data-"+h[o])){k.push(l[p].name);}}}else{if(l[p].name.substring(0,5)==="data-"){k.push(l[p].name);
}}}g.each(k,function(i,j){m.removeAttr(j);});};return f;});