define("chartutil/svgutils",["jquery","underscore","chartutil/domUtils","util/Functional"],function(e,a,d,b){var c={};c.getTransform=function(h,g){var f=g.getCTM();
return{cx:f.e,cy:f.f};};c.getScale=function(h,g){var f=g.getCTM();return{cx:f.a,cy:f.d};};c.svgToJpg=function(i,f,h,g){c.svgToImageFile(i,f,h,g,"image/jpeg",".jpg");
};c.svgToPng=function(k,f,i,g,j,h){c.svgToImageFile(k,f,i,g,"image/png",".png",j,h);};c.svgToImageFile=function(z,N,q,M,y,h,K,R){var A=false;
var x=(typeof M!=="undefined")?M.split(".")[0]:"mySvgImage";var r=(typeof y!=="undefined")?y:"image/png";var Y=(typeof h!=="undefined")?h:".png";
var v=(typeof q!=="undefined")?q:"";var X=(b.notFalsy(K))?K:"";var Q=(b.notFalsy(R))?R:0;var V,p,f,g=20,B=10;if(typeof z==="object"){if(z instanceof e){V=z[0];
}else{V=z;}}else{if(typeof z==="string"){V=e(z)[0];}}p=e(e(V).find("svg")[0]).width()+B+Q;f=e(e(V).find("svg")[0]).height()+g;
if(v.length){f+=40;}var n=V.cloneNode(true);n.id="svgHolder2";document.body.appendChild(n);var O=e(V).find("svg").css("background-color");
var S=e(n).find("svg");S[0].style.cssText+=("background: "+O);if(v.length){S.attr("height",f);var E=S[0];var D=document.createElementNS("http://www.w3.org/2000/svg","text");
D.setAttribute("x","20");D.setAttribute("y",f-20);D.setAttribute("font-family",["Open Sans","sans-serif"]);D.setAttribute("font-size","14px");
D.setAttribute("font-weight","300");D.setAttribute("fill","#4d4d4f");D.textContent=v;E.appendChild(D);}var l=S.find("g")[0];
var H=c.getScale(S[0],l);var i=c.getTransform(S[0],l);var U=i.cx;var T=i.cy;var I=Number(T)+g;if(!A){document.body.removeChild(n);
}else{e(n).css("visibility","visible");}e(l).attr("transform","translate("+U+", "+I+") scale("+H.cx+", "+H.cy+")");S.attr("width",p);
d.applyStylesAsInline(n,N);var C=new XMLSerializer();var P=C.serializeToString(e(n).find("svg")[0]);if(X.length){var L='<foreignObject width="100%" height="100%">'+X+"</foreignObject>";
var t=P.indexOf(">");var G=P.substring(0,t+1);var F=P.substring(t+1);var s=G+L+F;P=s;}var J=window.URL||window.webkitURL||window;
var k=d.stringToBlobUrl(P,"image/svg+xml;charset=utf-8");var j=e("html")[0].className.toLowerCase();if(j.indexOf("chrome")>-1&&X.length){k="data:image/svg+xml,"+P;
}var W=document.createElement("canvas");W.width=p;W.height=f;var u=W.getContext("2d");var o=new Image();var m;var w=function(){var Z=W.toDataURL(r);
m=d.createDownloadLink(Z,x,Y,!A);};o.onload=function(){u.drawImage(o,0,0);J.revokeObjectURL(k);w();};o.onerror=function(Z){if(window.console&&console.log){console.log("### svgutils::onerror:: FIRST BLOB LOAD ERROR - the browser is probably Safari e=",Z);
}};o.src=k;};c.innerHTMLShim=function(l,m){var j,n,f,h,k,i,g;while(l.firstChild){l.firstChild.parentNode.removeChild(l.firstChild);
}var o="<svg id='wrapper' xmlns='http://www.w3.org/2000/svg'>"+m+"</svg>";j=document.createElement("div");j.innerHTML=o;f=j.querySelector("svg#wrapper");
i=f.childNodes;g=[];for(h=0,k=i.length;h<k;h++){n=i[h];if(n){g.push(l.appendChild(n));}}return g;};return c;});