define("timeline/views/timeline_v7",["jquery","underscore","backbone","chartlib/chartbase","d3","util/UserPreferences","chartutil/dateUtils_CET","chartlib/events/appstateevents","timeline/events/timelineEvents","timeline/util/timelineConstants","timeline/util/timelineUtils_v7","timeline/util/reformatTimeline","timeline/util/timelineControls_v7","timeline/util/formatTicks","chartutil/stringutils","util/Analytics","chartutil/svgutils"],function(e,q,b,j,p,g,c,o,m,k,i,l,n,d,r,h,a){var f=j.extend({el:"#timelineHolder",defaults:{margin:{top:30,right:65,bottom:5,left:15}},isUnitTest_render:false,dateFormat:null,timeFormat:null,oldDateForFormatting:null,lastFormatPeriod:null,allowDrag:true,doStartupCheck:false,logTimelineCalcs:false,startupSteps:0,totalStartupSteps:9,timelineCalcReturnObj:null,oldExtent:null,compareExtents:false,allowJump:true,fixedExtent:null,moving_numDays:0,moving_numMinutes:0,dateBlock:null,dateBlockText:null,altKeyIsDown:false,hasMinStartDates:false,minStartDate_day:null,minStartDate_week:null,weekStartAdj:0,latestExceptAtDayGranularity:false,initialize:function(t){q.bindAll(this,"brushmove","brushend","brushstart");
this.startupSteps++;if(window.console&&console.log){console.log("### timeline_v7::initialize:: pOptions=",t);}if(this.collection.getValue("mondayWeek")){this.weekStartAdj=1;
k.__WEEK_FORMAT=k.__MONDAY_STR;if(window.console&&console.log){console.log("### timeline_v7::initialize:: @@@@@@@#########@@@@@@@@###### TimelineConstants.__WEEK_FORMAT=",k.__WEEK_FORMAT);
}}k.init(this.weekStartAdj);if(typeof t.unitTest_render!=="undefined"){this.isUnitTest_render=t.unitTest_render;}this.reformatTimeline=q.bind(l.reformatTimeline,this);
this.calculateTimeline=q.bind(i.calculateTimeline,this);this.processDatesForTimezone=q.bind(i.processDatesForTimezone,this);
this.finaliseTimeline=q.bind(i.finaliseTimeline,this);this.calculateExtent=q.bind(i.calculateExtent,this);this.jumpPeriod=q.bind(n.jumpPeriod,this);
this.enableControls=q.bind(n.enableControls,this);this.formatTicks=q.bind(d.formatTicks,this);if(!this.isUnitTest_render){b.on(m.MODE_CHANGED,this.onModeChange,this);
b.on(m.CALENDAR_SET,this.calendarSet,this);b.on(m.CONFIG_SAVE_REQUESTED,this.outputTimelineConfig,this);b.on(m.JUMP_PERIOD,this.jumpPeriod);
b.on(m.OUTPUT_URL,this.outputTimelineConfig,this);b.on(m.PRESET_PERIOD,this.setPreset,this);b.on(m.ALT_KEY_PRESS,this.altKeyAction,this);
b.on(m.ALT_KEY_UP,this.altKeyAction,this);}this.uid=this.collection.getValue("uid");this.timelineWidgetContainer=this.collection.getValue("widgetContainer");
var w=this.collection.getValue("formatPeriod");if(this.collection.getValue("minStartDates").length){this.hasMinStartDates=true;
var L=this.collection.getValue("minStartDates");var F=L[0];var C=L[1];if(this.collection.getValue("timeCollectionMode")===k.__LATEST){F-=1;
C-=1;}this.minStartDate_day=k.getMinDate(k.__DAY_FORMAT,F);this.minStartDate_week=k.getMinDate(k.__WEEK_FORMAT,C);}var I=this.collection.getValue("timeCollectionMode");
if(I===k.__LATEST_NOT_DAY){this.latestExceptAtDayGranularity=true;if(w===k.__WEEK_FORMAT||w===k.__MONTH_FORMAT){var K=new Date().getDate();
if(K===1){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);I=k.__LAST_FULL;}else{this.collection.setValue("timeCollectionMode",k.__LATEST);
I=k.__LATEST;}}if(w===k.__DAY_FORMAT){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);I=k.__LAST_FULL;}}if(I===k.__LATEST){k.recalculateDatesAsLatest(false,this.weekStartAdj);
}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE OPTIONS PROCESSED");
}var v=null;var G=decodeURIComponent(r.getUrlParameter("formatPeriod"));var z=decodeURIComponent(r.getUrlParameter("formatMsecs"));
var E=decodeURIComponent(r.getUrlParameter("startTimeline"));var u=decodeURIComponent(r.getUrlParameter("endTimeline"));var y=decodeURIComponent(r.getUrlParameter("startExtent"));
var J=decodeURIComponent(r.getUrlParameter("endExtent"));var H=decodeURIComponent(r.getUrlParameter("chartGranularity"));
if(G!=="undefined"&&z!=="undefined"&&E!=="undefined"&&u!=="undefined"&&y!=="undefined"&&J!=="undefined"){v={formatPeriod:G,formatMsecs:z,startTimeline:E,endTimeline:u,startExtent:y,endExtent:J};
}else{var M=g.getPreference(this.uid);if(M){v=JSON.parse(M);g.setPreference(this.uid,null);}}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE CONFIG OBJECT PROCESSED");
}var B,x,A,D;if(v){this.setFormat(v.formatPeriod,v.formatMsecs);A=new Date(Number(v.startExtent));D=new Date(Number(v.endExtent));
B=new Date(Number(v.startTimeline));x=this.createTimelineEnd(Number(v.endTimeline));if(H!=="undefined"){b.trigger(m.SET_CHART_GRAN_SELECT,H,true);
}}else{switch(w){case k.__MINUTE_FORMAT:this.setFormat(w,k.__MSECS_PER_MINUTE);A=k.__THIRTY_MINUTES_AGO;D=k.__THIS_MINUTE;
B=k.__SIXTY_ONE_MINUTES_AGO;x=this.createTimelineEnd(k.__THIS_MINUTE);break;case k.__HOUR_FORMAT:this.setFormat(w,k.__MSECS_PER_HOUR);
A=k.__TWENTY_FOUR_HOURS_AGO;D=k.__THIS_HOUR;B=k.__FORTY_EIGHT_HOURS_AGO;x=this.createTimelineEnd(k.__THIS_HOUR);break;case k.__DAY_FORMAT:this.setFormat(w,k.__MSECS_PER_DAY);
A=k.__ONE_WEEK_BEFORE_TODAY;D=k.__TODAY;B=k.__LAST_MONTH;x=this.createTimelineEnd(k.__TODAY);break;case k.__WEEK_STR:case k.__WEEK_FORMAT:this.setFormat(k.__WEEK_FORMAT,k.__MSECS_PER_WEEK);
A=k.__FOUR_WEEKS_AGO;D=k.__THIS_WEEK;B=k.__THIRTEEN_WEEKS_AGO;x=this.createTimelineEnd(k.__THIS_WEEK);break;case k.__MONTH_FORMAT:this.setFormat(w,k.__MSECS_PER_MONTH);
A=k.__TWELVE_MONTHS_AGO;D=k.__THIS_MONTH;B=k.__TWELVE_MONTHS_AGO;x=this.createTimelineEnd(k.__THIS_MONTH);break;}}this.collection.setValue("timeline",[B,x]);
this.collection.setValue("extent",[A,D]);this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE CONFIG COMPLETE: __THIS_MINUTE=",k.__THIS_MINUTE," offset=",k.__THIS_MINUTE.getTimezoneOffset());
}this.fixedExtent=this.collection.getValue("fixedExtent");this._super();this.enableControls();this.startupSteps++;if(window.console&&window.console.log){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE INIT COMPLETE!!!!!!!!!!! [*** SHOULD BE FINAL STEP! ***]");
}if(this.startupSteps===this.totalStartupSteps){var s=this.collection.getValue("startPreset");if(s!==null){this.setPreset(s);
}else{this.dispatchTimespan();}}else{if(window.console&&window.console.error){console.error("!!! The timeline has not started up correctly !!!");
}}},initRender:function(){this.setDateFormat();this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE PRE INIT-RENDER");
}this._super();this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE INIT-RENDER SUPER");
}this.xAxis.attr("transform","translate(0,"+(-20)+")");this.topSVG.classed("timeline",true).attr("width",this.width+this.options.margin.left+this.options.margin.right).attr("height",this.height+this.options.margin.top+this.options.margin.bottom);
var w="."+this.svg.attr("class");var s=this.topSVG.insert("defs",w);var u=s.append("filter").attr("id","f1").attr("x",0).attr("y",0);
u.append("feGaussianBlur").attr("in","SourceGraphic").attr("stdDeviation","2 0");this.brush=p.svg.brush().x(this.scales.x).extent(this.collection.getValue("extent")).on("brushstart",this.brushstart).on("brush",this.brushmove).on("brushend",this.brushend);
if(!this.isUnitTest_render){var v=this.svg.append("g").attr("class","brush").call(this.brush);v.selectAll("rect").attr("height",this.height);
v.selectAll(".resize").append("rect").attr("width","5px").attr("height","20px").attr("transform","translate(-2,"+this.height/4+")");
if(this.fixedExtent){v.selectAll(".resize").remove();}this.brushExtent=p.select(".brush .extent");this.brushHandles=p.selectAll(".brush .resize rect");
}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE RENDER COMPLETE!");
}b.trigger(m.SET_GRANULARITY);var t=this.collection.getValue("extent");this.oldExtent=t;if(!this.isUnitTest_render){this.updateDisplay();
this.colorizeSelection(t);}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE INIT-RENDER & STARTUP PROCESS COMPLETE");
}},setXScale:function(){this.scales.x=p.time.scale.utc().domain(this.collection.getValue("timeline")).range([0,this.width]);
},calibrateXScale:function(s){if(window.console&&window.console.log){window.console.log("\n### CALIBRATE X SCALE ---------------------- pDomain=",s);
}if(s){this.collection.setValue("timeline",s);this.scales.x.domain(s);}},setXAxis:function(){this.axes.x=p.svg.axis().scale(this.scales.x).orient("bottom").tickPadding(-15).tickSize(20).ticks(this.dateFormat).tickFormat(this.formatTicks);
},hidePreviousTick:function(t){var s=e(".x.axis .tick text");var u=e(s[0]).text("");},renderXAxis:function(){this.xAxis.call(this.axes.x).selectAll("text").attr("dx",6).style("text-anchor","start");
var s=p.selectAll(".timeline-holder .tick");s[0].forEach(function(t,u){if(t.style){t.style.display="block";}else{t.domNode.style.display="block";
}if(t&&t.textContent===""){if(t.style){t.style.display="none";}else{t.domNode.style.display="none";}}});},renderYAxis:function(){},renderData:function(){var x=this.getFormatPeriod();
var F=this.scales.x;var C=F.range()[1]-F.range()[0];var E=p.selectAll(".timeline-holder .x.axis .tick");var t=E[0].length;
var w=C/t;var B=this.height;var s=0;var D=[];var A=this;E[0].forEach(function(M,N){var J=p.select(M).datum();s=A.scales.x(J);
var K={date:J,x:s,width:w,height:B};D.push(K);if(D.length>1&&x===k.__MONTH_FORMAT){var L=D[N-1];L.width=s-L.x;}});var I=D.length;
e("#numBlocks").html(I+" blocks");switch(this.getFormatPeriod()){case k.__MONTH_FORMAT:if(I>12){console.error("Too many blocks on the timeline:",I,"when it should be 12");
}break;case k.__WEEK_FORMAT:if(I>13){console.error("Too many blocks on the timeline:",I,"when it should be 13");}break;case k.__DAY_FORMAT:if(I>32){console.error("Too many blocks on the timeline:",I,"when it should be 32");
}break;case k.__HOUR_FORMAT:if(I>49){console.error("Too many blocks on the timeline:",I,"when it should be 49");}break;case k.__MINUTE_FORMAT:if(I>61){console.error("Too many blocks on the timeline:",I,"when it should be 61");
}break;}this.svg.selectAll(".block").remove();var v=this.svg.selectAll(".block").data(D);var H=v.enter().insert("g",".brush").attr("class","block").attr("transform",function(J){return"translate("+J.x+","+0+")";
});var z=(x!==k.__MINUTE_FORMAT)?6:4;this.dateBlock=H.append("rect").attr("class","date-box").attr("x",(z/2)).attr("y",(z/2)).attr("width",function(J){return J.width-z;
}).attr("height",function(J){return J.height-z;});var u="date-box-text "+x;var y=0;var G=this.collection.getValue("forceCET");
if(G){H.append("text").attr("class","utc-time").attr("x",function(J){return(J.width/2);}).attr("y",function(J){return 10;
}).attr("text-anchor","middle").style("font-size","8px").text(function(J){if(x===k.__HOUR_FORMAT||x===k.__MINUTE_FORMAT){return p.time.format.utc("%H")(J.date);
}return"";});}this.dateBlockText=H.append("text").attr("class",u).attr("x",function(J){return(J.width/2);}).attr("y",function(J){return(((J.height+z)/2)+2);
}).attr("text-anchor","middle").text(function(P){var M=P.date;var L;switch(x){case k.__MINUTE_FORMAT:y++;L=Date.padded2(M.getMinutes());
break;case k.__HOUR_FORMAT:if(G){y++;var K=c.getAmsterdamDSTOffsetTime(M,true,(y<1));var N=c.timezoneShiftPseudoDate(M,K,false,"block",y<1);
L=c.formatPseudoDate(N,k.__FORMAT_BLOCK_PSEUDO);}else{L=Date.padded2(M.getHours());}break;case k.__DAY_FORMAT:var Q=M.getDate();
L=Date.padded2(Q);break;case k.__WEEK_FORMAT:var O=String(M.getWeek());if(O.length===1){O="0"+O;}L="wk "+O;break;case k.__MONTH_FORMAT:var J=M.getMonth();
L=c.__MONTHS_SHORT[J];break;}return L;});if(G){H.append("text").attr("class","local-time").attr("x",function(J){return(J.width/2);
}).attr("y",function(J){return 32;}).attr("text-anchor","middle").style("font-size","7px").text(function(J){if(x===k.__HOUR_FORMAT||x===k.__MINUTE_FORMAT){return p.time.format("%d/%H")(J.date);
}return"";});}},updateDisplay:function(){this.renderXAxis();this.renderData();},onModeChange:function(t,s){this[s](t);},brushstart:function(){this.compareExtents=true;
this.allowJump=true;if(this.altKeyIsDown){this.brush.clear();p.select(".brush").call(this.brush);}},brushmove:function(y){var B=this.getExtent(),z;
var x=this.getFormatPeriod();var A=this.getFormatMsecs();var D=this.collection.getValue("forceCET");var C,u="";if(p.event.mode==="move"){var t=p.time[x].round(B[0]);
var s=p.time[x].offset(t,Math.round((B[1]-B[0])/A));z=[t,s];this.extentDrag=true;}else{this.extentResize=true;z=(this.fixedExtent&&this.fixedExtent_extent)?this.fixedExtent_extent:this.snapBrush();
this.moving_numDays=Math.round(c.getNumDays(B[1],B[0]));var v=this.processDatesForTimezone(B[0],B[1],k.__BRUSHMOVE,false);
this.moving_numMinutes=v[0];if(this.compareExtents){this.compareExtents=false;this.allowJump=this.checkForNewExtent(z);}b.trigger(m.SET_DAYS,this.moving_numDays,this.moving_numMinutes);
if(this.allowJump){var w=this.checkTimeline(this.moving_numMinutes);if(w){this.colorizeBrushExtent(false);}else{this.colorizeBrushExtent(true);
}}else{this.colorizeBrushExtent(true);}}if(this.allowDrag){if(this.fixedExtent){C=(z[1]-z[0])/1000/60;if(z[0]<this.oldExtent[0]){u="left";
}else{if(z[1]>this.oldExtent[1]){u="right";}}if(C>=k.__DAY_MODE_SWITCH_POINT_MAX){if(u==="left"){z[1].setDate(z[1].getDate()-27);
z=z.map(p.time[x].round);}else{if(u==="right"){z[0].setDate(z[0].getDate()+27);z=z.map(p.time[x].round);}}this.fixedExtent_extent=z;
}}this.collection.setValue("extent",z);p.select(".brush").call(this.brush.extent(z));this.colorizeSelection(z);}},checkForNewExtent:function(s){if(Number(this.oldExtent[0])!==Number(s[0])&&Number(this.oldExtent[1])!==Number(s[1])){return false;
}else{return true;}},brushend:function(){if(this.extentDrag){h.trackEvent("Timeline_"+this.uid,"timeline.event.drag-extent");
this.extentDrag=false;}if(this.extentResize){if(this.colouredExtent){h.trackEvent("Timeline_"+this.uid,"timeline.event.resize-extent-to-jump-granularity");
}else{h.trackEvent("Timeline_"+this.uid,"timeline.event.resize-extent");}this.extentResize=false;this.colouredExtent=false;
}var u=this.collection.getValue("extent");var x=Math.round(c.getNumDays(u[1],u[0]));var w;var v=this.getFormatPeriod();var t=this.processDatesForTimezone(u[0],u[1],k.__BRUSHEND,false);
w=t[0];b.trigger(m.SET_DAYS,x,w);if(v===k.__MONTH_FORMAT||(v===k.__WEEK_FORMAT&&this.moving_numMinutes<k.__WEEK_MODE_SWITCH_POINT_MIN)||(v===k.__DAY_FORMAT&&this.moving_numMinutes<k.__DAY_MODE_SWITCH_POINT_MIN)||(v===k.__HOUR_FORMAT&&this.moving_numMinutes<k.__HOUR_MODE_SWITCH_POINT_MIN)){if(this.allowJump){this.reformatTimeline(this.moving_numMinutes,u[0]);
}}else{this.reformatTimeline(w,u[0],"stretchExtent",u[1]);}this.fixedExtent_extent=null;this.setExtent();},jumpOut:function(y){var x=this.collection.getValue("extent");
this.moving_numDays=0;this.moving_numMinutes=0;var u=this.getStartTimeline();var v=this.getEndTimeline();var w;var t=this.processDatesForTimezone(u,v,k.__JUMP_OUT,false);
w=t[0];this.reformatTimeline(w,x[0],y,x[1]);this.setExtent();},jumpIn:function(w){var v=this.collection.getValue("extent");
var u=k.__HOUR_MODE_SWITCH_POINT_MIN-1;if(this.collection.getValue("forceJumpFwd")){var t=v[1];switch(this.getFormatPeriod()){case k.__MONTH_FORMAT:t=c.adjustTime(v[1],-k.__MSECS_PER_MONTH);
break;case k.__WEEK_FORMAT:t=c.adjustTime(v[1],-k.__MSECS_PER_WEEK);break;case k.__DAY_FORMAT:t=c.adjustTime(v[1],-k.__MSECS_PER_DAY);
break;}switch(w){case k.__DAYS_BTN:if(this.getFormatPeriod()===k.__MONTH_FORMAT){t=c.adjustTime(t,-k.__MSECS_PER_DAY);}break;
}this.reformatTimeline(u,t,w);}else{this.reformatTimeline(u,v[0],w,v[1]);}this.setExtent();},switchToMinute:function(y,t,x,w){var B=(typeof x!=="undefined")?x:false;
this.setFormat(k.__MINUTE_FORMAT,k.__MSECS_PER_MINUTE);var A;var s=false;var u=c.roundToMinute(y,true);var v=this.collection.getValue("timeCollectionMode");
if(v===k.__LAST_FULL&&u.getHours()===k.__THIS_HOUR.getHours()-1&&!t&&!B){s=true;}if(!s){A=this.calculateTimeline(y,"roundToMinute",k.__MAX_MINUTES,0,B,w);
t=null;var C=k.__EXTENT_MINUTES_DEFAULT*2;if(x){t=A.endExtentDate;}this.calculateExtent(A.startDate,"roundToMinute",C,t,A.timelineEnd,k.__MINUTE_MODE_MAX_MINUTES);
}else{if(window.console&&window.console.log){window.console.log("### timeline_v7::switchToMinute:: showLatestMinutesshowLatestMinutesshowLatestMinutesshowLatestMinutes!!!!!");
}A=this.calculateTimeline(y,"roundToMinute",k.__MAX_MINUTES,60);var z=new Date(this.getStartTimeline());z=c.adjustTime(z,k.__MSECS_PER_MINUTE);
this.calculateExtent(z,"roundToMinute",k.__EXTENT_MINUTES_DEFAULT,A.timelineEnd,A.timelineEnd,k.__MINUTE_MODE_MAX_MINUTES);
}this.setSwitch();},switchToHour:function(v,s,y,t){s=null;var z=(s)?Math.floor(c.getNumMinutes(s,v)):k.__EXTENT_HOURS_DEFAULT_MAX;
var w=(z>k.__EXTENT_HOURS_DEFAULT_MAX)?k.__EXTENT_HOURS_DEFAULT_MAX*2:k.__EXTENT_HOURS_DEFAULT_MAX;var x=(this.getFormatPeriod()===k.__MINUTE_FORMAT)?k.__EXTENT_HOURS_DEFAULT_MIN:w;
this.setFormat(k.__HOUR_FORMAT,k.__MSECS_PER_HOUR);var u=this.calculateTimeline(v,"roundToHour",k.__MAX_HOURS,0,y,t);if(y){s=u.endExtentDate;
}this.calculateExtent(u.startDate,"roundToHour",x,s,u.timelineEnd,k.__HOUR_MODE_MAX_HOURS);this.setSwitch();},switchToDay:function(v,s,x,t){if(this.latestExceptAtDayGranularity){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);
k.init(this.weekStartAdj);}var w=(this.getFormatPeriod()===k.__HOUR_FORMAT)?k.__EXTENT_DAYS_DEFAULT_MIN:k.__EXTENT_DAYS_DEFAULT_MAX;
this.setFormat(k.__DAY_FORMAT,k.__MSECS_PER_DAY);var u=this.calculateTimeline(v,"roundToDay",k.__MAX_DAYS,null,x,t);if(x){s=u.endExtentDate;
}this.calculateExtent(u.startDate,"roundToDay",w,s,u.timelineEnd,k.__DAY_MODE_MAX_DAYS);this.setSwitch();},switchToWeek:function(w,s,x,u){if(this.latestExceptAtDayGranularity){var t=new Date().getDate();
if(t===1){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);k.init(this.weekStartAdj);}else{this.collection.setValue("timeCollectionMode",k.__LATEST);
k.recalculateDatesAsLatest(false,this.weekStartAdj);}}this.setFormat(k.__WEEK_FORMAT,k.__MSECS_PER_WEEK);var v=this.calculateTimeline(w,"roundToWeek",k.__MAX_WEEKS,null,x,u);
if(x){s=v.endExtentDate;}this.calculateExtent(v.startDate,"roundToWeek",k.__EXTENT_WEEKS_DEFAULT,s,v.timelineEnd,k.__WEEK_MODE_MAX_DAYS);
this.setSwitch();},switchToMonth:function(x,t){if(this.latestExceptAtDayGranularity){var v=new Date().getDate();if(v===1){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);
k.init(this.weekStartAdj);}else{this.collection.setValue("timeCollectionMode",k.__LATEST);k.recalculateDatesAsLatest(false,this.weekStartAdj);
}}this.setFormat(k.__MONTH_FORMAT,k.__MSECS_PER_MONTH);var A=c.roundToMonth(k.__TODAY,true);var w=this.collection.getValue("timeCollectionMode");
if(w===k.__LATEST&&k.__TODAY.getDate()!==1){A.setMonth(A.getMonth()+1);}var y=k.__TWELVE_MONTHS_AGO;var s=A;s.setTime(s.getTime()-1);
this.calibrateXScale([y,s]);var u=x;var B=c.roundToMonth(u,true);if(B<k.__TWELVE_MONTHS_AGO){B.setMonth(B.getMonth()+1);}if(w===k.__LATEST){var z=c.roundToMonth(t,true);
z.setMonth(z.getMonth()+1);t=z;}this.calculateExtent(B,"roundToMonth",k.__EXTENT_MONTHS_DEFAULT,t,s,10000000);this.setSwitch();
},setFormat:function(t,s){this.lastFormatPeriod=this.collection.getValue("formatPeriod");this.collection.setValue("formatPeriod",t);
this.collection.setValue("formatMsecs",s);b.trigger(m.SET_DISPLAY);},getFormatPeriod:function(){return this.collection.getValue("formatPeriod");
},getFormatMsecs:function(){return this.collection.getValue("formatMsecs");},setExtent:function(){if(this.brush.empty()&&this.altKeyIsDown){return;
}var s=this.snapBrush();this.collection.setValue("extent",s);if(this.logTimelineCalcs&&window.console&&window.console.log){window.console.log("### setExtent extent1 (snapbrush)=",s);
}if(this.isUnitTest_render){return;}p.select(".brush").call(this.brush.extent(s));this.colorizeSelection(s);this.oldExtent=s;
this.dispatchTimespan();this.enableControls();},snapBrush:function(){var v=false;var u=this.getExtent(),t;var s=this.getFormatPeriod();
t=u.map(p.time[s].round);if(v&&window.console&&window.console.log){window.console.log("\n### SNAPBRUSH extent0=",u);window.console.log("### SNAPBRUSH extent1=",t);
}if(t[0]>=t[1]){if(v&&window.console&&window.console.log){window.console.log("### timeline_v7::snapBrush:: POCK!!!!!!");}if(u[0]>=this.getEndTimeline()){if(v&&window.console&&window.console.log){window.console.log("### ---------> LEFT DRAGGED PAST END extent mins=",u[0].getMinutes());
}u[0].setMinutes(u[0].getMinutes()-1);}else{if(u[1]<=this.getStartTimeline()){if(v&&window.console&&window.console.log){window.console.log("### ---------> RIGHT DRAGGED PAST START extent mins=",u[1].getMinutes());
}u[1].setMinutes(u[1].getMinutes()+1);}}t[0]=p.time[s].floor(u[0]);t[1]=p.time[s].ceil(u[1]);if(v&&window.console&&window.console.log){window.console.log("### SNAPBRUSH pocked extent0=",u);
window.console.log("### SNAPBRUSH pocked extent1=",t);}if(t[0]<this.getStartTimeline()){if(v&&window.console&&window.console.log){window.console.log("### timeline_v7::snapBrush:: extra check - start extent proceeds start timeline");
}t[0]=p.time[s].round(this.getStartTimeline());}if(t[1]>this.getEndTimeline()){if(v&&window.console&&window.console.log){window.console.log("### timeline_v7::snapBrush:: extra check - end extent exceeds end timeline: endTimeline=",this.getEndTimeline());
}t[1]=p.time[s].round(this.getEndTimeline());}}return t;},setSwitch:function(){if(this.isUnitTest_render){return;}this.timelineCalcReturnObj=null;
this.setDateFormat();this.axes.x.ticks(this.dateFormat);this.updateDisplay();var s=this;setTimeout(function(){b.trigger(m.SET_DAYS,0,0);
},10);this.colorizeBrushExtent(true);this.allowDrag=false;setTimeout(function(){s.allowDrag=true;},10);},colorizeBrushExtent:function(s){if(s){this.colouredExtent=false;
this.brushExtent.style("fill","none");this.brushExtent.style("stroke","#4c4c4c");this.brushHandles.style("fill","#4c4c4c");
this.brushHandles.style("stroke","#4c4c4c");}else{this.colouredExtent=true;this.brushExtent.style("fill","green");this.brushExtent.style("fill-opacity",0.25);
this.brushExtent.style("stroke","green");this.brushHandles.style("fill","green");this.brushHandles.style("stroke","green");
}},checkTimeline:function(u){var s=this.collection.getValue("baseGranularity");var t=this.getFormatPeriod();if(t===k.__MINUTE_FORMAT){if(u>=k.__MINUTE_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__HOUR_FORMAT){if(u>0&&u<k.__HOUR_MODE_SWITCH_POINT_MIN&&s<k.__HOUR_GRANULARITY){return true;}if(u>k.__HOUR_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__DAY_FORMAT){if(u>0&&u<k.__DAY_MODE_SWITCH_POINT_MIN&&s<k.__DAY_GRANULARITY){return true;}if(u>=k.__DAY_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__WEEK_FORMAT){if(u>0&&u<k.__WEEK_MODE_SWITCH_POINT_MIN&&s<k.__WEEK_GRANULARITY){return true;}if(u>=k.__WEEK_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__MONTH_FORMAT){if(u>0&&u<k.__MONTH_MODE_SWITCH_POINT_MIN&&s<k.__MONTH_GRANULARITY){return true;}}}}}}return false;
},colorizeSelection:function(s){this.dateBlock.classed("selected",function(u){var t=s[0]<=u.date&&u.date<s[1];return t;});
this.dateBlockText.classed("selected",function(u){var t=s[0]<=u.date&&u.date<s[1];return t;});},getStartTimeline:function(){return this.collection.getValue("timeline")[0];
},getEndTimeline:function(){return this.collection.getValue("timeline")[1];},getExtent:function(){return this.brush.extent();
},createTimelineEnd:function(s){var t=new Date(s);t.setTime(t.getTime()-1);return t;},dispatchTimespan:function(){var F=this.collection.getValue("extent");
var w=this.getFormatPeriod();if(this.weekStartAdj===1&&w===k.__MONDAY_STR){w=k.__WEEK_STR;}var A,v,C;var B=this.collection.getValue("forceCET");
if(B&&(w===k.__HOUR_FORMAT||w===k.__MINUTE_FORMAT)){var y=c.getUTCValues(F[0],true);var x=c.getUTCValues(F[1],true);var u=c.getAmsterdamDSTOffsetTime(F[0],true,false);
var E=c.timezoneShiftPseudoDate(F[0],u,true,"output",false);u=c.getAmsterdamDSTOffsetTime(F[1],true,false);var t=c.adjustTime(F[1],-(1));
var z=c.timezoneShiftPseudoDate(t,u,true,"output",false);this.collection.setValue("extentUTC",[y,x]);this.collection.setValue("extentAMS",[E,z]);
if(window.console&&window.console.log){window.console.log("\n### DISPATCHTIMESPAN start date utc values parsed=",c.formatPseudoDate(y,k.__FORMAT_DATE_UTC));
window.console.log("### DISPATCHTIMESPAN end date utc values parsed  =",c.formatPseudoDate(x,k.__FORMAT_DATE_UTC));window.console.log("###\n");
}if(this.timelineWidgetContainer&&this.timelineWidgetContainer.jquery){A=c.formatPseudoDate(y,"yyyy-mm-dd H:M:S");v=c.formatPseudoDate(x,"yyyy-mm-dd H:M:S");
C=[A,v,w];C=[C];this.timelineWidgetContainer.trigger("timelineTimespanSet",C);}b.trigger(m.TIMESPAN_SET_UTC,this.collection);
b.trigger(o.CHANGE_REQUESTED);}else{if(window.console&&window.console.log){window.console.log("\n###");window.console.log("### DISPATCHTIMESPAN this.getExtent()   =",this.collection.getValue("extent"));
window.console.log("###\n");}if(this.timelineWidgetContainer&&this.timelineWidgetContainer.jquery){var D=this.collection.getValue("extent");
if(w===k.__HOUR_FORMAT||w===k.__MINUTE_FORMAT){A=p.time.format("%Y-%m-%d-%H-%M")(D[0]);v=p.time.format("%Y-%m-%d-%H-%M")(D[1]);
}else{A=p.time.format("%Y-%m-%d")(D[0]);v=p.time.format("%Y-%m-%d")(D[1]);}this.timelineWidgetContainer.trigger(m.TIMESPAN_SET,[A,v,w]);
C=[A,v,w];C=[C];this.timelineWidgetContainer.trigger("timelineTimespanSet",C);}b.trigger(m.TIMESPAN_SET,this.collection);
b.trigger(o.CHANGE_REQUESTED);b.trigger(m.SET_CALENDAR);}},setDateFormat:function(){switch(this.getFormatPeriod()){case k.__MINUTE_FORMAT:this.dateFormat=p.time.minutes;
this.timeFormat=p.time.format(k.__FORMAT_MINUTES);break;case k.__HOUR_FORMAT:this.dateFormat=p.time.hours;this.timeFormat=p.time.format(k.__FORMAT_HOURS);
break;case k.__DAY_FORMAT:this.dateFormat=p.time.days;this.timeFormat=p.time.format(k.__FORMAT_DAYS);break;case k.__WEEK_FORMAT:this.dateFormat=(this.weekStartAdj===0)?p.time.weeks:p.time.mondays;
this.timeFormat=p.time.format(k.__FORMAT_WEEKS);break;case k.__MONTH_FORMAT:this.dateFormat=p.time.months;this.timeFormat=p.time.format(k.__FORMAT_MONTHS);
break;}},calendarSet:function(t,y){var v=this.collection.getValue("baseGranularity");this.moving_numDays=0;this.moving_numMinutes=0;
var x=t.split("-");var u=new Date(x[0],x[1]-1,x[2]);var B=y.split("-");var A=new Date(B[0],B[1]-1,Number(B[2])+1);var z=Math.floor(c.getNumDays(A,u));
var w=Math.floor(c.getNumMinutes(A,u));var s;if(z<k.__CALENDER_DAY_GRANULARITY){s=k.__DAY_GRANULARITY;}else{if(z>=k.__CALENDER_DAY_GRANULARITY&&z<k.__CALENDER_WEEK_GRANULARITY){s=k.__WEEK_GRANULARITY;
}else{if(z>=k.__CALENDER_WEEK_GRANULARITY){s=k.__MONTH_GRANULARITY;}}}if(s<v){b.trigger(m.SET_CALENDAR,this.getExtent());
return;}this.collection.setValue("extent",[u,A]);this.brush.extent([u,A]);b.trigger(m.SET_DAYS,z,0,this.getExtent());this.reformatTimeline(w,u,s,A);
this.setExtent();},outputTimelineConfig:function(u){var v=(typeof u!=="undefined")?u:false;var D=this.getStartTimeline();
var A=new Date(this.getEndTimeline());A.setTime(A.getTime()+1);var F=this.collection.getValue("extent");var E=F[0];var x=F[1];
var z=this.getFormatPeriod();var B=this.getFormatMsecs();if(v){var w={formatPeriod:z,formatMsecs:B,startTimeline:D.getTime(),endTimeline:A.getTime(),startExtent:E.getTime(),endExtent:x.getTime(),setActiveAccountKey:adyen.currentAccount,chartGranularity:this.collection.getValue("chartGranularity")};
var t="?"+e.param(w);window.history.pushState("test","Title",window.location.origin+window.location.pathname+t);}else{var y={formatPeriod:z,formatMsecs:B,startTimeline:D.getTime(),endTimeline:A.getTime(),startExtent:E.getTime(),endExtent:x.getTime(),setActiveAccountKey:adyen.currentAccount,chartGranularity:this.collection.getValue("chartGranularity")};
var C=JSON.stringify(y);g.setPreference(this.uid,C);b.trigger(m.TIMESPAN_CONFIG_CREATED);}},altKeyAction:function(s){this.altKeyIsDown=s;
if(!this.altKeyIsDown){if(this.brush.empty()){this.brush.extent(this.oldExtent);this.setExtent();}}},setPreset:function(v){h.trackEvent("Timeline_"+this.uid,"timeline.event.preset-"+v);
this.moving_numDays=0;this.moving_numMinutes=0;switch(v){case k.__PRESET_LAST_7_DAYS:this.reformatTimeline(-1,k.__ONE_WEEK_BEFORE_TODAY,k.__DAY_GRANULARITY,k.__TODAY);
break;case k.__PRESET_LAST_4_WEEKS:this.reformatTimeline(-1,k.__FOUR_WEEKS_AGO,k.__WEEK_GRANULARITY);break;case k.__PRESET_LAST_30_DAYS:this.reformatTimeline(-1,k.__THIRTY_DAYS_AGO,k.__DAY_GRANULARITY,k.__TODAY);
break;case k.__PRESET_LAST_YEAR:this.reformatTimeline(-1,k.__TWELVE_MONTHS_AGO,k.__MONTH_GRANULARITY,k.__TODAY);break;case k.__PRESET_LAST_MONTH:this.reformatTimeline(-1,k.__THIS_MONTH,k.__MONTH_GRANULARITY,k.__TODAY);
break;case k.__PRESET_THIS_MINUTE:var u=new Date(k.__THIS_MINUTE);u.setMinutes(u.getMinutes()-1);this.reformatTimeline(-1,u,k.__MINUTE_GRANULARITY,k.__THIS_MINUTE);
break;case k.__PRESET_THIS_HOUR:var t=new Date(k.__THIS_HOUR);t.setHours(t.getHours()-1);this.reformatTimeline(-1,t,k.__HOUR_GRANULARITY,k.__THIS_HOUR);
break;case k.__PRESET_THIS_DAY:this.reformatTimeline(-1,k.__ONE_DAY_AGO,k.__DAY_GRANULARITY,k.__TODAY);break;case k.__PRESET_THIS_WEEK:var s=new Date(k.__THIS_WEEK);
s.setDate(s.getDate()-7);this.reformatTimeline(-1,s,k.__WEEK_GRANULARITY,k.__THIS_WEEK);break;}this.setExtent();}});return f;
},function(a){if(window.console&&window.console.log){window.console.log("TIMELINE JS ERROR =",a);}});