define("timeline/util/timelineConstants",["jquery","chartutil/dateUtils_CET","util/Console"],function(e,d,c){var g,f,a,b,i;
var h={};h.isInited=false;h.__WEEK_STR="week";h.__MONDAY_STR="monday";h.__MAX_MINUTES=61;h.__MAX_HOURS=2940;h.__MAX_DAYS=46080;
h.__MAX_WEEKS=131040;h.__EXTENT_MINUTES_DEFAULT=30;h.__EXTENT_HOURS_DEFAULT_MIN=60;h.__EXTENT_HOURS_DEFAULT_MAX=1440;h.__EXTENT_DAYS_DEFAULT_MIN=2880;
h.__EXTENT_DAYS_DEFAULT_MAX=10080;h.__EXTENT_WEEKS_DEFAULT=40320;h.__EXTENT_MONTHS_DEFAULT=131040;h.__MINUTE_MODE_MAX_MINUTES=60;
h.__HOUR_MODE_MAX_HOURS=2880;h.__DAY_MODE_MAX_DAYS=44640;h.__WEEK_MODE_MAX_DAYS=120960;h.__MINUTE_MODE_SWITCH_POINT_MAX=61;
h.__HOUR_MODE_SWITCH_POINT_MIN=45;h.__HOUR_MODE_SWITCH_POINT_MAX=2910;h.__DAY_MODE_SWITCH_POINT_MIN=1000;h.__DAY_MODE_SWITCH_POINT_MAX=45372;
h.__WEEK_MODE_SWITCH_POINT_MIN=8640;h.__WEEK_MODE_SWITCH_POINT_MAX=126000;h.__MONTH_MODE_SWITCH_POINT_MIN=37440;h.__CALENDER_DAY_GRANULARITY=32;
h.__CALENDER_WEEK_GRANULARITY=85;h.__MSECS_PER_MINUTE=60000;h.__MSECS_PER_HOUR=3600000;h.__MSECS_PER_DAY=86400000;h.__MSECS_PER_WEEK=h.__MSECS_PER_DAY*7;
h.__MSECS_PER_MONTH=h.__MSECS_PER_DAY*30;h.__FORMAT_MINUTES="%H:%M";h.__FORMAT_HOURS="%d %b";h.__FORMAT_DAYS="%d %b '%y";
h.__FORMAT_WEEKS="%b %Y";h.__FORMAT_MONTHS="%Y";h.__FORMAT_DATE="%d %b %Y";h.__FORMAT_HOURS_PSEUDO="dd N";h.__FORMAT_MINUTES_PSEUDO="H:M";
h.__FORMAT_BLOCK_PSEUDO="H";h.__FORMAT_DATE_UTC="yyyy-mm-dd H:M:S";h.__FORMAT_DATE_PSEUDO="yyyy-mm-dd";h.__MINUTES_BTN="minutesBtn";
h.__HOURS_BTN="hoursBtn";h.__DAYS_BTN="daysBtn";h.__WEEKS_BTN="weeksBtn";h.__MONTHS_BTN="monthsBtn";h.__MINUTE_FORMAT="minute";
h.__HOUR_FORMAT="hour";h.__DAY_FORMAT="day";h.__WEEK_FORMAT="week";h.__MONTH_FORMAT="month";h.__MINUTE_GRANULARITY=1;h.__HOUR_GRANULARITY=2;
h.__DAY_GRANULARITY=3;h.__WEEK_GRANULARITY=4;h.__MONTH_GRANULARITY=5;h.__LAST_FULL="lastFull";h.__LATEST="latest";h.__LATEST_NOT_DAY="latestExceptAtDayGranularity";
h.__NOW="now";h.__FWD="fwd";h.__START_EXTENT="start";h.__END_EXTENT="end";h.__BACK="back";h.__THEN="then";h.__JUMP_PERIOD_DAY=31;
h.__JUMP_PERIOD_WEEK=7*12;h.granularityDict={};h.granularityDict[h.__MINUTE_FORMAT]=h.__MINUTE_GRANULARITY;h.granularityDict[h.__HOUR_FORMAT]=h.__HOUR_GRANULARITY;
h.granularityDict[h.__DAY_FORMAT]=h.__DAY_GRANULARITY;h.granularityDict[h.__WEEK_FORMAT]=h.__WEEK_GRANULARITY;h.granularityDict[h.__MONDAY_STR]=h.__WEEK_GRANULARITY;
h.granularityDict[h.__MONTH_FORMAT]=h.__MONTH_GRANULARITY;h.__ONE_OFF_ADJUST="oneOffAdjust";h.__FINALISE_TIMELINE="finaliseTimeline";
h.__CALCULATE_EXTENT="calculateExtent";h.__BRUSHMOVE="brushmove";h.__BRUSHEND="brushend";h.__JUMP_OUT="jumpOut";h.__PRESET_LAST_7_DAYS="last7Days";
h.__PRESET_LAST_30_DAYS="last30Days";h.__PRESET_LAST_4_WEEKS="last4Weeks";h.__PRESET_LAST_YEAR="lastYear";h.__PRESET_LAST_MONTH="lastMonth";
h.__PRESET_THIS_MINUTE="thisMinute";h.__PRESET_THIS_HOUR="thisHour";h.__PRESET_THIS_DAY="thisDay";h.__PRESET_THIS_WEEK="thisWeek";
h.init=function(k){var l=new Date();var p=l;var n,o,m,j,q;g=n=p.getFullYear();f=o=p.getMonth();a=m=p.getDate();b=j=p.getHours();
i=q=p.getMinutes();h.__THIS_HOUR=new Date(n,o,m,j);h.__TODAY=new Date(n,o,m);h.__TWELVE_MONTHS_AGO=new Date(n,o-12);h.__THIS_MINUTE=new Date(n,o,m,j,q);
h.__THIRTY_MINUTES_AGO=new Date(n,o,m,j,q-30);h.__SIXTY_ONE_MINUTES_AGO=new Date(n,o,m,j,q-61);h.__TWENTY_FOUR_HOURS_AGO=new Date(n,o,m,j-24);
h.__FORTY_EIGHT_HOURS_AGO=new Date(n,o,m,j-49);h.__THIS_WEEK=d.roundToWeek(h.__TODAY,true,k);h.__ONE_WEEK_BEFORE_TODAY=new Date(n,o,m-7);
h.__FOUR_WEEKS_AGO=d.roundToWeek(new Date(n,o,m-28),true,k);h.__THIS_MONTH=d.roundToMonth(h.__TODAY,true);h.__LAST_MONTH=new Date(n,o,m-32);
h.__THIRTEEN_WEEKS_AGO=d.roundToWeek(new Date(n,o,m-(7*13)),true,k);h.__ONE_DAY_AGO=new Date(n,o,m-1);h.__THIRTY_DAYS_AGO=new Date(n,o,m-30);
h.isInited=true;};h.recalculateDatesAsLatest=function(j,l){var r,q,m,o,n;if(!j){r=g;q=f;m=a;o=b;n=i;}else{var k=new Date();
r=k.getFullYear();q=k.getMonth();m=k.getDate();o=k.getHours();n=k.getMinutes();}h.__THIS_HOUR=new Date(r,q,m,o+1);h.__FORTY_EIGHT_HOURS_AGO=new Date(r,q,m,o-48);
h.__TODAY=new Date(r,q,m+1);h.__THIS_MINUTE=new Date(r,q,m,o,n+1);h.__SIXTY_ONE_MINUTES_AGO=new Date(r,q,m,o,n-60);var p=new Date(r,q,h.__TODAY.getDate()+7);
h.__THIS_WEEK=d.roundToWeek(p,false,l);h.__THIRTEEN_WEEKS_AGO=new Date(r,q,h.__THIS_WEEK.getDate()-(7*13));h.__TWENTY_FOUR_HOURS_AGO=new Date(r,q,h.__TODAY.getDate()-1,o-23);
h.__ONE_WEEK_BEFORE_TODAY=new Date(r,q,m-6);h.__FOUR_WEEKS_AGO=new Date(r,q,h.__THIS_WEEK.getDate()-28);h.__THIS_MONTH=new Date(r,q+1);
h.__LAST_MONTH=new Date(r,q,m-31);h.__TWELVE_MONTHS_AGO=new Date(r,q-11);h.__ONE_DAY_AGO=new Date(r,q,m);h.__THIRTY_DAYS_AGO=new Date(r,q,m-29);
};h.getMinDate=function(k,j){var l=null;switch(k){case h.__DAY_FORMAT:l=new Date(g,f,a-j);break;case h.__WEEK_FORMAT:l=new Date(g,f,h.__THIS_WEEK.getDate()-(7*j));
break;}return l;};return h;});define("timeline/events/timelineEvents",[],function(){var a={};a.MODE_CHANGED="timeline.timelineEvents.timelineModeChanged";
a.SET_DISPLAY="timeline.timelineEvents.timelineSetDisplay";a.SET_DAYS="timeline.timelineEvents.timelineSetDays";a.SET_GRANULARITY="timeline.timelineEvents.timelineSetGranularity";
a.SET_CALENDAR="timeline.timelineEvents.timelineSetCalendar";a.CALENDAR_SET="timeline.timelineEvents.timelineCalendarSet";
a.TIMESPAN_SET="timeline.timelineEvents.timelineTimespanSet";a.TIMESPAN_SET_UTC="timeline.timelineEvents.timelineTimespanSetUtc";
a.TIMELINE_CONFIG_SET="timeline.timelineEvents.timelineConfigSet";a.CONFIG_SAVE_REQUESTED="timeline.timelineEvents.configSaveRequested";
a.TIMESPAN_CONFIG_CREATED="timeline.timelineEvents.timelineConfigCreated";a.JUMP_PERIOD="timeline.timelineEvents.jumpPeriod";
a.DISABLE_CONTROLS="timeline.timelineEvents.disableControls";a.ENABLE_CONTROLS="timeline.timelineEvents.enableControls";a.OUTPUT_URL="timeline.timelineEvents.outputUrl";
a.ALT_KEY_PRESS="timeline.timelineEvents.altKey";a.ALT_KEY_UP="timeline.timelineEvents.altKeyUp";a.PRESET_PERIOD="timeline.timelineEvents.presetPeriod";
a.COMBO_ERROR="timeline.timelineEvents.comboError";a.COMBO_SUCCES="timeline.timelineEvents.comboSucces";a.SET_CHART_GRAN_SELECT="timeline.timelineEvents.setChartGranularitySelect";
return a;});define("timeline/models/timelineState",["jquery","underscore","backbone","timeline/util/timelineConstants","timeline/events/timelineEvents","chartutil/dateUtils_CET"],function(d,c,g,a,f,e){var b=g.Model.extend({defaults:{uid:"timeline",widgetContainer:null,timeCollectionMode:a.__LAST_FULL,formatPeriod:a.__DAY_FORMAT,baseGranularity:a.__DAY_GRANULARITY,startPreset:null,fixedExtent:false,calendar:true,controls:true,forceJumpFwd:false,presets:[],allowDynamicPresets:false,mondayWeek:false,minStartDates:[],loadQueue:false,config:false,chartGranularity:a.__DAY_FORMAT,chartGranularityDisabled:false,dynamicGranularityDisabling:false,granularityDisablingConstraints:{day:1,week:7,month:29},forceCET:false,formatMsecs:a.__MSECS_PER_DAY,timeline:[],extent:null,extentUTC:null,extentAMS:null}});
return b;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);}});define("timeline/util/timelineUtils_v7",["jquery","chartutil/dateUtils_CET","timeline/util/timelineConstants","chartutil/stringutils"],function(b,e,a,d){var c={};
c.calculateTimeline=function(n,r,u,v,p,g){if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n###----------------------------");
window.console.log("### calculateTimeline:: pSelectionStart (desired start date)=",n," ***");window.console.log("### calculateTimeline:: pRoundingFn=",r);
window.console.log("### calculateTimeline::pTimelineMax (max poss. amt)=",u);window.console.log("### calculateTimeline::pLatestMinutesException (undefined=0) =",v);
window.console.log("### calculateTimeline::pJumpPeriod (undefined=false) =",p);window.console.log("###----------------------------\n");
}var f=(typeof p!=="undefined")?p:false;var t=(typeof v!=="undefined")?v:0;var i=this.collection.getValue("formatPeriod");
var y=0;if(this.hasMinStartDates){switch(i){case a.__DAY_FORMAT:if(n<this.minStartDate_day){y=(this.minStartDate_day-n)/a.__MSECS_PER_MINUTE;
n=this.minStartDate_day;}break;case a.__WEEK_FORMAT:if(n<this.minStartDate_week){y=(this.minStartDate_week-n)/a.__MSECS_PER_MINUTE;
n=this.minStartDate_week;}break;}}var o=e[r](n,true,this.weekStartAdj);if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("### calculateTimeline:: timelineCalcReturnObj=",this.timelineCalcReturnObj);
window.console.log("### calculateTimeline:: ROUNDED (",r,") startDate=",o," ***");}var m=(this.collection&&typeof this.collection.getValue("forceCET")!=="undefined")?this.collection.getValue("forceCET"):true;
if(m){var s=this.processDatesForTimezone(o,o,a.__ONE_OFF_ADJUST,false);o=s[0];}this.timelineCalcReturnObj={};if(!f){this.timelineCalcReturnObj.startDate=o;
}else{var j=this.getExtent();var l=new Date(j[0]);var k=new Date(j[1]);var h=g;var w=(f===a.__BACK)?-(h-y):h;switch(f){case a.__END_EXTENT:l=o;
k=e.adjustTime(k,w*+(a.__MSECS_PER_MINUTE));break;case a.__FWD:case a.__BACK:l=e.adjustTime(l,w*+(a.__MSECS_PER_MINUTE));
k=e.adjustTime(k,w*+(a.__MSECS_PER_MINUTE));break;}this.timelineCalcReturnObj.endExtentDate=k;this.timelineCalcReturnObj.startDate=l;
}if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("### calculateTimeline::timelineCalcReturnObj=",this.timelineCalcReturnObj);
}var x=e.adjustTime(o,((u+t)*a.__MSECS_PER_MINUTE));if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateTimeline: TIMELINE START date=",o," ***");window.console.log("### calculateTimeline: TIMELINE END   date=",x," ***");
window.console.log("\n### calculateTimeline: TIMELINE START date (as utc)=",o.toUTCString());window.console.log("### calculateTimeline: TIMELINE END date (as utc)=",x.toUTCString());
window.console.log("### calculateTimeline: TIMELINE END (",(((u+t)))," minutes forward from start date)");window.console.log("### calculateTimeline: TIMELINE END (",(((u+t)/60))," hours forward from start date)");
window.console.log("### calculateTimeline: TIMELINE END (",(((u+t)/60)/24)," days forward from start date)");window.console.log("### ----------------------------------\n");
}var q=this.finaliseTimeline(o,x,r,u);this.timelineCalcReturnObj.timelineStart=q[0];this.timelineCalcReturnObj.timelineEnd=q[1];
if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateTimeline: RETURNING timelineCalcReturnObj=",this.timelineCalcReturnObj);window.console.log("### ----------------------------------\n");
}return this.timelineCalcReturnObj;};c.finaliseTimeline=function(i,l,h,g){var m=i;var f=l;var p=e[h](a.__THIS_MINUTE,true,this.weekStartAdj);
var k=this.timeCollectionMode||this.collection.getValue("timeCollectionMode");if(k===a.__LATEST){var j=this.formatPeriod||this.collection.getValue("formatPeriod");
switch(j){case a.__HOUR_FORMAT:p=e.adjustTime(p,(60*a.__MSECS_PER_MINUTE));break;case a.__DAY_FORMAT:p.setDate(p.getDate()+1);
break;case a.__WEEK_FORMAT:p.setDate(p.getDate()+7);break;}}if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### finaliseTimeline timelineStart=",m," ***");window.console.log("### finaliseTimeline timelineEnd=",f," ***");
window.console.log("### *********** finaliseTimeline: timelineLimit=",p,"***********");window.console.log("### ----------------------------------\n");
}if(f>p){var o=Math.floor(e.getNumMinutes(f,p,false));if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log('### finaliseTimeline Timeline end is IN FUTURE... "now" (timelineLimit) is: ',p);window.console.log("### finaliseTimeline Timeline end is IN FUTURE by: ",Math.floor(e.getNumMinutes(f,p,false))," minutes (with tz)");
window.console.log("### finaliseTimeline Timeline end is IN FUTURE by: ",Math.floor(e.getNumMinutes(f,p,true))," minutes (disregard tz)");
window.console.log("### finaliseTimeline Timeline diffTime amount used: ",o);window.console.log("### ----------------------------------\n");
}f=p;m=e.adjustTime(f,-(g*a.__MSECS_PER_MINUTE));if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### CALCULATED by finaliseTimeline: TIMELINE START date       =",m," ***");window.console.log("### CALCULATED by finaliseTimeline: TIMELINE END date (+1 sec) =",f," ***");
window.console.log("### ----------------------------------\n");}if(this.getFormatPeriod()===a.__DAY_FORMAT||this.getFormatPeriod()===a.__WEEK_FORMAT){h="true"+d.capitaliseFirstLetter(h);
}m=e[h](m,true,this.weekStartAdj);if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### CALCULATED by finaliseTimeline: (ROUNDED) TIMELINE START date       =",m," ***");window.console.log("### ----------------------------------\n");
}}var n=this.processDatesForTimezone(m,f,a.__FINALISE_TIMELINE,this.logTimelineCalcs,null,p);m=n[0];f=n[1];f.setTime(f.getTime()-1);
if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### FINALISED by finaliseTimeline: TIMELINE START date       =",m," ***");window.console.log("### FINALISED by finaliseTimeline: TIMELINE END date (-1 sec)=",f," ***");
window.console.log("### ----------------------------------\n");}this.calibrateXScale([m,f]);return[m,f];};c.processDatesForTimezone=function(f,m,k,g,h,n){if(window.console&&window.console.log&&g){window.console.log("\n### ----------------------------------");
window.console.log("### processDatesForTimezone: ",k);}var l=this.getFormatPeriod();var i=e.assessDates(f,m,g);switch(k){case a.__ONE_OFF_ADJUST:if(this.lastFormatPeriod!==a.__HOUR_FORMAT&&this.lastFormatPeriod!==a.__MINUTE_FORMAT&&(l===a.__HOUR_FORMAT||l===a.__MINUTE_FORMAT)){var j=e.getAmsterdamDSTOffset_minusTZ(f);
f=e.timezoneShiftDate(f,e.__FWD,j,"startDate",0,0);if(window.console&&window.console.log&&g){window.console.log("\n### ################################");
window.console.log("### SPECIAL ADJUSTMENT TO TIMELINE - FIRST GRANULARITY JUMP ");window.console.log("### __HOUR_FORMAT adjusting startDate amsOffset = ",j);
window.console.log("### __HOUR_FORMAT adjusting adjusted startDate = ",f," ***");window.console.log("### ###############################\n");
}}break;case a.__FINALISE_TIMELINE:if(a.granularityDict[l]>a.__HOUR_GRANULARITY){if(i.tzOffsetDiff<0){m=e.adjustTime(m,(i.tzOffsetDiff*a.__MSECS_PER_MINUTE));
if(window.console&&window.console.log&&g){window.console.log("### processDatesForTimezone case:",k," (summer) corrected pEndDate=",m);
}}if(i.tzOffsetDiff>0&&m<n){m=e.adjustTime(m,(i.tzOffsetDiff*a.__MSECS_PER_MINUTE));if(window.console&&window.console.log&&g){window.console.log("### processDatesForTimezone case:",k," (winter) corrected pEndDate=",m);
}}}break;case a.__CALCULATE_EXTENT:if(l===a.__HOUR_FORMAT){if(i.startDstOffset<i.endDstOffset){if(h!==(a.__EXTENT_HOURS_DEFAULT_MAX*2)){m=e.adjustTime(m,(i.dstOffsetDiff*a.__MSECS_PER_MINUTE));
if(window.console&&window.console.log&&g){window.console.log("### processDatesForTimezone case:",k," corrected (winter) pEndDate=",m);
}}}else{if(!i.isSummerDST){m=e.adjustTime(m,(i.dstOffsetDiff*a.__MSECS_PER_MINUTE));if(window.console&&window.console.log&&g){window.console.log("### processDatesForTimezone case:",k," corrected (summer) pEndDate=",m);
}}}}break;case a.__BRUSHMOVE:case a.__BRUSHEND:case a.__JUMP_OUT:m=i.numMinutesTz;f=m;if(l===a.__HOUR_FORMAT||l===a.__MINUTE_FORMAT){if(i.tzOffsetDiff!==0){f=i.numMinutesNoTz;
}}break;}if(window.console&&window.console.log&&g){window.console.log("### end processDatesForTimezone: ",k);window.console.log("### ----------------------------------\n");
}return[f,m];};c.calculateExtent=function(i,k,j,g,n,h){var l=false;if(g){if(typeof g!=="undefined"){l=true;}}if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent: pStartDate (for extent)=",i," ***");window.console.log("### calculateExtent: pRoundingFn=",k);
window.console.log("### calculateExtent: (default) pExtentLength=",j,"(",e.convertMinutesToUnit(j,this.getFormatPeriod()),")");
window.console.log("### calculateExtent: (suggested) pEndExtentDate=",g," ***");window.console.log("### calculateExtent: pTimelineEnd=",n);
window.console.log("### calculateExtent: (default) pMaxExtent=",h,"(",e.convertMinutesToUnit(h,this.getFormatPeriod()),")");
window.console.log("### ----------------------------------\n");}var p=i;var r=j;if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent: extentLength=",r,"minutes (with tz)","(",e.convertMinutesToUnit(r,this.getFormatPeriod()),")");
window.console.log("### ----------------------------------\n");}if(l){r=Math.floor(e.getNumMinutes(g,p));if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent: hasCalExtentEndDate=",l);window.console.log("### calculateExtent: RECALULATED extentLength=",r,"minutes (with tz)","(",e.convertMinutesToUnit(r,this.getFormatPeriod()),")");
window.console.log("### calculateExtent: RECALULATED extentLength=",Math.floor(e.getNumMinutes(g,p,true))," minutes (disregard tz)");
window.console.log("### ----------------------------------\n");}}var m=e.adjustTime(p,(r*a.__MSECS_PER_MINUTE));if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent DESIRED endExtentDate=",m," ***");window.console.log("### ----------------------------------\n");
}if(m>n){var f=Math.floor(e.getNumMinutes(m,n));if(f>0){if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### @start endExtentDate EXCEEDS pTimelineEnd ###");window.console.log("### calculateExtent EXTENT BREAKS - TOO FAR PAST END OF TIMELINE by ",f,"minutes (with tz)","(",e.convertMinutesToUnit(f,this.getFormatPeriod()),")");
window.console.log("### calculateExtent EXTENT BREAKS - TOO FAR PAST END OF TIMELINE by ",Math.floor(e.getNumMinutes(m,n,true))," minutes (disregard tz)");
window.console.log("### ----------------------------------\n");}m=e.adjustTime(m,-(f*a.__MSECS_PER_MINUTE));if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent ADJUSTED endExtentDate=",m," ***");window.console.log("### @end endExtentDate EXCEEDS pTimelineEnd ###");
window.console.log("### ----------------------------------\n");}}if(!l){if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
window.console.log("!!!!!!!!!!!!!!!!!!!!!!!### NO CAL EXTENT!!!!!!!!!!!!!!!!");window.console.log("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
}}else{var o=Math.floor(e.getNumMinutes(m,p));f=o-h;if(f>0){if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
window.console.log("!!!!!!!!!!!!!!!!!!!!!!!### HAS CAL EXTENT - endExtentDate > pTimelineEnd !!!!!!!!!!!!!!!!");window.console.log("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
window.console.log("\n### ----------------------------------");window.console.log("### @start extentLength EXCEEDS max allowable (pMaxExtent) ###");
window.console.log("### calculateExtent ACTUAL extentLength (based on start & end dates)=",o,"(",e.convertMinutesToUnit(o,this.getFormatPeriod()),")");
window.console.log("### calculateExtent ACTUAL extentLength exceeds default max (pMaxExtent) by",f);window.console.log("### ----------------------------------\n");
}m=e.adjustTime(m,-(f*a.__MSECS_PER_MINUTE));if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent ADJUSTED endExtentDate=",m," ***");window.console.log("### @end extentLength EXCEEDS max allowable (pMaxExtent) ###");
window.console.log("### ----------------------------------\n");}}}}if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent final CALCULATED (prior to correction) startExtentDate=",p," ***");window.console.log("### calculateExtent final CALCULATED (prior to correction) endExtentDate=",m," ***");
window.console.log("### ----------------------------------\n");}var q=this.processDatesForTimezone(p,m,a.__CALCULATE_EXTENT,this.logTimelineCalcs,r);
p=q[0];m=q[1];if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### ----------------------------------");
window.console.log("### calculateExtent FINALISED startExtentDate=",p," ***");window.console.log("### calculateExtent FINALISED endExtentDate=",m," ***");
window.console.log("### ----------------------------------\n");}if(this.collection){this.collection.setValue("extent",[p,m]);
}this.brush.extent([p,m]);if(window.console&&window.console.log&&this.logTimelineCalcs){window.console.log("\n### calculateExtent EXTENT=",this.getExtent(),"\n");
}};return c;});define("timeline/util/timelineControls_v7",["jquery","backbone","chartutil/dateUtils_CET","timeline/util/timelineConstants","timeline/events/timelineEvents","util/Analytics"],function(c,g,e,b,d,a){var f={};
f.jumpPeriod=function(i){var q,o;var p,l,n,r,m;var j=this.formatPeriod||this.collection.getValue("formatPeriod");var h=b.granularityDict[j];
switch(i){case b.__FWD:a.trackEvent("Timeline_"+this.uid,"timeline.event.next-period-forward");n=b.__FWD;q=this.getEndTimeline();
l=this.getEndTimeline();o=new Date(l);switch(j){case b.__MINUTE_FORMAT:o=e.adjustTime(o,+(60*b.__MSECS_PER_MINUTE));m=b.__THIS_MINUTE;
break;case b.__HOUR_FORMAT:o=e.adjustTime(o,+(48*b.__MSECS_PER_HOUR));m=b.__THIS_HOUR;break;case b.__DAY_FORMAT:o.setDate(o.getDate()+b.__JUMP_PERIOD_DAY);
m=b.__TODAY;break;case b.__WEEK_FORMAT:o.setDate(o.getDate()+b.__JUMP_PERIOD_WEEK);m=b.__THIS_WEEK;break;}if(o>m){o=m;}r=e.getNumMinutes(o,l,true);
break;case b.__START_EXTENT:q=(this.collection)?this.collection.getValue("extent")[0]:this.getExtent()[0];n=b.__START_EXTENT;
break;case b.__END_EXTENT:q=(this.collection)?this.collection.getValue("extent")[1]:this.getExtent()[1];q=e.adjustTime(q,-(b.__MSECS_PER_MINUTE));
n=b.__END_EXTENT;r=e.getNumMinutes(this.collection.getValue("extent")[0],this.collection.getValue("extent")[1],true);r-=1;
break;case b.__BACK:a.trackEvent("Timeline_"+this.uid,"timeline.event.next-period-back");n=b.__BACK;p=this.getStartTimeline();
q=new Date(p);switch(j){case b.__MINUTE_FORMAT:q=e.adjustTime(q,-(60*b.__MSECS_PER_MINUTE));break;case b.__HOUR_FORMAT:q=e.adjustTime(q,-(48*b.__MSECS_PER_HOUR));
break;case b.__DAY_FORMAT:q.setDate(q.getDate()-b.__JUMP_PERIOD_DAY);break;case b.__WEEK_FORMAT:q.setDate(q.getDate()-b.__JUMP_PERIOD_WEEK);
break;}if(q<b.__TWELVE_MONTHS_AGO){q=b.__TWELVE_MONTHS_AGO;}r=e.getNumMinutes(q,p,true);break;}var k=this;setTimeout(function(){r=Math.floor(r);
if(window.console&&window.console.log){window.console.log("### timelineControls_v7:: s0:: ",q);window.console.log("### timelineControls_v7:: changeAgent:: ",h);
window.console.log("### timelineControls_v7:: jumpAmt:: ",r);}k.reformatTimeline(-1,q,h,null,n,r);k.setExtent();var s=c("#timelineHolder");
s.removeClass("translateBack");s.removeClass("translateFwd");},250);};f.enableControls=function(){var h=false;var r=this.getStartTimeline();
var o=new Date(this.getEndTimeline());o.setTime(o.getTime()+1);var u=(this.collection)?this.collection.getValue("extent"):this.getExtent();
var t=u[0];var j=u[1];var l=b.__TWELVE_MONTHS_AGO,k;var i,p;var n=this.formatPeriod||this.collection.getValue("formatPeriod");
if(window.console&&window.console.log&&h){window.console.log("### timelineControls_v7::enableControls:: startExtent=",t);
window.console.log("### timelineControls_v7::enableControls:: endExtent=",j);window.console.log("### timelineControls_v7::enableControls:: formatPeriod=",n);
}switch(n){case b.__MINUTE_FORMAT:i=b.__THIS_MINUTE;p=new Date(i.getFullYear(),i.getMonth(),i.getDate(),i.getHours(),i.getMinutes()-1);
k=new Date(l.getFullYear(),l.getMonth(),l.getDate(),l.getHours(),l.getMinutes()+1);break;case b.__HOUR_FORMAT:i=b.__THIS_HOUR;
p=new Date(i.getFullYear(),i.getMonth(),i.getDate(),i.getHours()-1);k=new Date(l.getFullYear(),l.getMonth(),l.getDate(),l.getHours()+1);
break;case b.__DAY_FORMAT:i=b.__TODAY;p=new Date(i.getFullYear(),i.getMonth(),i.getDate()-1);if(this.hasMinStartDates){l=this.minStartDate_day;
}k=new Date(l.getFullYear(),l.getMonth(),l.getDate()+1);break;case b.__WEEK_FORMAT:i=b.__THIS_WEEK;p=new Date(i.getFullYear(),i.getMonth(),i.getDate()-7);
if(this.hasMinStartDates){l=this.minStartDate_week;}k=new Date(l.getFullYear(),l.getMonth(),l.getDate()+7);break;case b.__MONTH_FORMAT:i=b.__THIS_MONTH;
p=new Date(i.getFullYear(),i.getMonth()-1);k=new Date(l.getFullYear(),l.getMonth()+1);break;}if(window.console&&window.console.log&&h){window.console.log("### endTimeline=",this.getEndTimeline());
window.console.log("### endTimeline [as time]=",this.getEndTimeline().getTime());window.console.log("### endTimeline adj=",o);
window.console.log("### endTimeline adj [as time]=",o.getTime());window.console.log("### endExtent=",j);window.console.log("### now=",i);
window.console.log("### then=",l);}var m=false;var q=false;if(o<i){if(window.console&&window.console.log&&h){window.console.log("### enableControls:: endTimeline < now SO enable fwd button");
}g.trigger(d.ENABLE_CONTROLS,b.__FWD);}else{m=true;}if(r>l){if(window.console&&window.console.log&&h){window.console.log("### enableControls:: startTimeline > then SO enable back button");
}g.trigger(d.ENABLE_CONTROLS,b.__BACK);}else{q=true;}if(q){if(t<=r){if(window.console&&window.console.log&&h){window.console.log("### backBtnIsDisabled & startExtent = startTimeline");
}g.trigger(d.ENABLE_CONTROLS,b.__END_EXTENT);return;}}if(window.console&&window.console.log&&h){window.console.log("### fwdBtnIsDisabled=",m);
window.console.log("### enable backBtnIsDisabled=",q);}if(t<=r){if(window.console&&window.console.log&&h){window.console.log("### enable end extent btn ONLY");
}g.trigger(d.ENABLE_CONTROLS,b.__END_EXTENT);return;}if(window.console&&window.console.log&&h){window.console.log("### enable BOTH extent btns");
}g.trigger(d.ENABLE_CONTROLS,b.__START_EXTENT);g.trigger(d.ENABLE_CONTROLS,b.__END_EXTENT);};return f;});define("timeline/views/ui/timelineUI_v7",["jquery","underscore","backbone","d3","chartutil/dateUtils_CET","timeline/events/timelineEvents","timeline/util/timelineConstants","chartlib/events/appstateevents","chartlib/chartBaseEvents","chartutil/domUtils","util/Analytics"],function(c,j,i,l,b,k,f,d,g,a,h){var e=i.View.extend({el:"#timelineUI",events:{"click #monthsBtn":"onModeButtonClick","click #weeksBtn":"onModeButtonClick","click #daysBtn":"onModeButtonClick","click #hoursBtn":"onModeButtonClick","click #minutesBtn":"onModeButtonClick","change #timelineChartGranularity":"onConfigChange","change #timelinePresetsSelect":"onPreset"},version:4,hasControls:false,hasChartPresets:false,allowDynamicPresets:false,initialize:function(){this._super();
j.bindAll(this,"onPeriodJump","onOutputURL");this.presets=this.$("#timelinePresets");this.presetsSelect=this.$("#timelinePresetsSelect");
this.monthsBtn=this.$("#monthsBtn");this.weeksBtn=this.$("#weeksBtn");this.daysBtn=this.$("#daysBtn");this.hoursBtn=this.$("#hoursBtn");
this.minutesBtn=this.$("#minutesBtn");this.daysTxt=this.$("#numDaysMove");this.minutesTxt=this.$("#numMinutesMove");this.datesTxt=this.$("#dateSelected");
this.loader=c("#timelineLoader");this.controls=c("#timelineControls");this.tzWarning=c("#amsTimeWarning");this.uid=this.collection.getValue("uid");
i.on(k.SET_DISPLAY,this.configureDisplay,this);i.on(k.SET_DAYS,this.displayDays,this);i.on(k.TIMESPAN_SET,this.displayDates,this);
i.on(k.TIMESPAN_SET_UTC,this.displayDates,this);i.on(k.SET_GRANULARITY,this.hideModeButtons,this);i.on(k.SET_CHART_GRAN_SELECT,this.setChartGranularity,this);
i.on(d.STATE_CHANGED,this.showLoader,this);if(arguments[0].loadQueue){i.on(d.RENDER_CHARTS,this.hideLoader,this);}else{i.on(g.DATA_LOADED,this.hideLoader,this);
}if(this.collection.getValue("dynamicGranularityDisabling")&&this.collection.getValue("config")){i.on(k.TIMESPAN_SET,this.dynamicGranularityDisabling,this);
}if(this.collection.getValue("config")===true){var m=this.collection.getValue("chartGranularity");var p=this.collection.getValue("baseGranularity");
var q=this.$("#timelineConfigUI");q.css("display","block");this.$(".tl-config-opt").each(function(w,y){var v=c(y);var x=Number(v.attr("data-rel"));
if(x<p){v.remove();}});this.chartGranSelect=this.$("#timelineChartGranularity");this.setChartGranularity(m,false);this.chartGranDisabled=this.collection.getValue("chartGranularityDisabled");
if(this.chartGranDisabled){this.chartGranSelect.attr("disabled",true);this.$("#timelineChartGranularity + span").css("display","none");
var o=this.$("#timelineChartGranularity option:selected").text();this.$("#timelineChartGranularity option:selected").text("Show in: "+o);
}}if(this.collection.getValue("controls")===true){this.hasControls=true;this.controls.css("display","block");i.on(k.DISABLE_CONTROLS,this.disableControls,this);
i.on(k.ENABLE_CONTROLS,this.enableControls,this);var s=c("#jumpBackBtn");s.attr("data-action",f.__BACK);s.on("click",this.onPeriodJump);
this.extentEndBtn=c("#jumpExtentEndBtn");this.extentEndBtn.attr("data-action",f.__END_EXTENT);this.extentEndBtn.on("click",this.onPeriodJump);
this.extentStartBtn=c("#jumpExtentStartBtn");this.extentStartBtn.attr("data-action",f.__START_EXTENT);this.extentStartBtn.on("click",this.onPeriodJump);
var n=c("#jumpFwdBtn");n.attr("data-action",f.__FWD);n.on("click",this.onPeriodJump);this.controlBtns={};this.controlBtns[f.__BACK]=s;
this.controlBtns[f.__FWD]=n;this.controlBtns[f.__END_EXTENT]=this.extentEndBtn;this.controlBtns[f.__START_EXTENT]=this.extentStartBtn;
this.disableControls("startup");var t=this;c("body").keydown(function(v){if(v.keyCode===85&&v.ctrlKey){i.trigger(k.OUTPUT_URL,true);
}});c("#outputURL").css("display","block");c("#outputURL").on("click",this.onOutputURL);}var u=this.collection.getValue("presets");
if(u.length){this.hasChartPresets=true;var r;this.presets.css("display","block");if(j.contains(u,f.__PRESET_LAST_7_DAYS)){r='<option value="'+f.__PRESET_LAST_7_DAYS+'">Last 7 days</option>';
this.presetsSelect.append(r);}if(j.contains(u,f.__PRESET_LAST_4_WEEKS)){r='<option value="'+f.__PRESET_LAST_4_WEEKS+'">Last 4 weeks</option>';
this.presetsSelect.append(r);}if(j.contains(u,f.__PRESET_LAST_30_DAYS)){r='<option value="'+f.__PRESET_LAST_30_DAYS+'">Last 30 days</option>';
this.presetsSelect.append(r);}if(j.contains(u,f.__PRESET_LAST_YEAR)){r='<option value="'+f.__PRESET_LAST_YEAR+'">Last year</option>';
this.presetsSelect.append(r);}}this.allowDynamicPresets=this.collection.getValue("allowDynamicPresets");if(this.allowDynamicPresets){this.presets.css("display","block");
}if(this.hasControls||this.collection.getValue("forceCET")===true){this.increaseHeight();}c("body").keydown(function(v){if(v.altKey){i.trigger(k.ALT_KEY_PRESS,true);
}});c("body").keyup(function(v){if(v.keyCode===18){i.trigger(k.ALT_KEY_UP,false);}});},dynamicGranularityDisabling:function(){var p=this.collection.getValue("extent");
var m=Math.floor(b.getNumDays(p[1],p[0]));var r=this.collection.getValue("granularityDisablingConstraints");for(var q in r){var o=this.chartGranSelect.find('option[value="'+q+'"]');
if(m<=r[q]){var n=this.chartGranSelect.val();if(n===q&&o.prev()&&o.prev()[0].index>0){this.setChartGranularity(o.prev().val(),true);
}o.addClass("disabled");}else{o.removeClass("disabled");o.prop("disabled",false);}}},increaseHeight:function(){var r=this.$el.parent();
var n=r.height();var o=c("#configUI").height();var p=(o)?15:5;this.$el.parent().css("height",(n+20)+"px");var m=a.getComputedProperties(this.loader);
var q=parseInt(m.top);this.loader.css("top",(q+o+p)+"px");this.loader.css("display","none");},setChartGranularity:function(m,n){if(this.chartGranSelect&&!this.chartGranDisabled){this.chartGranSelect.val(m);
}if(n){this.collection.setValue("chartGranularity",m);}},onModeButtonClick:function(n){var p=c(n.currentTarget);var o=p.attr("data-action");
var m=p.text().toLowerCase();var q=m.substring(0,m.length-1);this.setChartGranularity(q,true);if(o!==""){h.trackEvent("Timeline_"+this.uid,"timeline.event.granularity-button-"+c(n.currentTarget).attr("id"));
i.trigger(k.MODE_CHANGED,c(n.currentTarget).attr("id"),o);}},onConfigChange:function(m){if(window.console&&console.log){console.log("### timelineUI_v7::onConfigChange:: VALUE=",c(m.currentTarget).val());
}if(c(m.currentTarget).val()==="default"){return;}this.collection.setValue("chartGranularity",c(m.currentTarget).val());i.trigger(d.CHANGE_REQUESTED);
},onOutputURL:function(){i.trigger(k.OUTPUT_URL,true);},configureDisplay:function(){var p=this.collection.getValue("formatPeriod");
var q='<i class="icon-chevron-left"></i>';var m='<i class="icon-chevron-right"></i>';var n=c("#jumpBackBtn");var o=c("#jumpFwdBtn");
n.show();o.show();switch(p){case f.__MINUTE_FORMAT:this.minutesBtn.toggleClass("disabled",true);this.monthsBtn.toggleClass("disabled",false);
this.weeksBtn.toggleClass("disabled",false);this.daysBtn.toggleClass("disabled",false);this.hoursBtn.toggleClass("disabled",false);
this.monthsBtn.attr("data-action","jumpOut");this.weeksBtn.attr("data-action","jumpOut");this.daysBtn.attr("data-action","jumpOut");
this.hoursBtn.attr("data-action","jumpOut");this.minutesBtn.attr("data-action","");n.html(q+" previous 60 mins");o.html("next 60 mins "+m);
if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_MINUTE,"Latest minute");}break;case f.__HOUR_FORMAT:this.hoursBtn.toggleClass("disabled",true);
this.monthsBtn.toggleClass("disabled",false);this.weeksBtn.toggleClass("disabled",false);this.daysBtn.toggleClass("disabled",false);
this.minutesBtn.toggleClass("disabled",false);this.monthsBtn.attr("data-action","jumpOut");this.weeksBtn.attr("data-action","jumpOut");
this.daysBtn.attr("data-action","jumpOut");this.minutesBtn.attr("data-action","jumpIn");this.hoursBtn.attr("data-action","");
n.html(q+" previous 48 hours");o.html("next 48 hours "+m);if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_HOUR,"Latest hour");
}break;case f.__DAY_FORMAT:this.daysBtn.toggleClass("disabled",true);this.monthsBtn.toggleClass("disabled",false);this.weeksBtn.toggleClass("disabled",false);
this.hoursBtn.toggleClass("disabled",false);this.minutesBtn.toggleClass("disabled",false);this.monthsBtn.attr("data-action","jumpOut");
this.weeksBtn.attr("data-action","jumpOut");this.hoursBtn.attr("data-action","jumpIn");this.minutesBtn.attr("data-action","jumpIn");
this.daysBtn.attr("data-action","");n.html(q+" previous 31 days");o.html("next 31 days "+m);if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_DAY,"Latest day");
}break;case f.__WEEK_FORMAT:this.weeksBtn.toggleClass("disabled",true);this.monthsBtn.toggleClass("disabled",false);this.daysBtn.toggleClass("disabled",false);
this.hoursBtn.toggleClass("disabled",false);this.minutesBtn.toggleClass("disabled",false);this.monthsBtn.attr("data-action","jumpOut");
this.daysBtn.attr("data-action","jumpIn");this.hoursBtn.attr("data-action","jumpIn");this.minutesBtn.attr("data-action","jumpIn");
this.weeksBtn.attr("data-action","");n.html(q+" previous 12 weeks");o.html("next 12 weeks "+m);if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_WEEK,"Latest week");
}break;case f.__MONTH_FORMAT:this.monthsBtn.toggleClass("disabled",true);this.daysBtn.toggleClass("disabled",false);this.weeksBtn.toggleClass("disabled",false);
this.hoursBtn.toggleClass("disabled",false);this.minutesBtn.toggleClass("disabled",false);this.weeksBtn.attr("data-action","jumpIn");
this.daysBtn.attr("data-action","jumpIn");this.hoursBtn.attr("data-action","jumpIn");this.minutesBtn.attr("data-action","jumpIn");
this.monthsBtn.attr("data-action","");n.hide();o.hide();if(this.allowDynamicPresets){this.addDynamicPreset(null);}break;}if(this.hasControls){if(p===f.__MINUTE_FORMAT){this.extentEndBtn.css("display","inline-block");
this.extentStartBtn.css("display","inline-block");}else{this.extentEndBtn.css("display","none");this.extentStartBtn.css("display","none");
}}},displayDays:function(o,n){if(o===0){var m=this.collection.getValue("extent");o=Math.floor(b.getNumDays(m[1],m[0]));n=Math.floor(b.getNumMinutes(m[1],m[0]));
}this.daysTxt.html('numDays:  <span style="color:#000">'+o+"<span>");this.minutesTxt.html('numMinutes:  <span style="color:#000">'+n+"<span>");
},displayDates:function(){this.showLoader();this.tzWarning.css("display","none");var m=(this.collection&&typeof this.collection.getValue("forceCET")!=="undefined")?this.collection.getValue("forceCET"):true;
if(m&&((this.collection.getValue("formatPeriod")===f.__HOUR_FORMAT||this.collection.getValue("formatPeriod")===f.__MINUTE_FORMAT))){this.tzWarning.css("display","block");
}},hideModeButtons:function(){var m=this.collection.getValue("baseGranularity");switch(m){case f.__HOUR_GRANULARITY:this.minutesBtn.remove();
break;case f.__DAY_GRANULARITY:this.hoursBtn.remove();this.minutesBtn.remove();break;case f.__WEEK_GRANULARITY:this.daysBtn.remove();
this.hoursBtn.remove();this.minutesBtn.remove();break;case f.__MONTH_GRANULARITY:this.weeksBtn.remove();this.daysBtn.remove();
this.hoursBtn.remove();this.minutesBtn.remove();break;}},showLoader:function(){this.loader.css("display","block");},hideLoader:function(){this.loader.css("display","none");
},onPeriodJump:function(n){this.disableControls("periodJump");var m=c("#timelineHolder");var p=this.$el.parent().find(".block");
l.selectAll(p).classed("gaussian-blur-x",true);var o=c(n.currentTarget).attr("data-action");switch(o){case f.__THEN:case f.__BACK:m.addClass("translateBack");
break;case f.__NOW:case f.__FWD:m.addClass("translateFwd");break;}i.trigger(k.JUMP_PERIOD,o);},disableControls:function(m){j.each(this.controlBtns,function(o,p,n){n[p].addClass("disabled");
});},enableControls:function(m){this.controlBtns[m].removeClass("disabled");},addDynamicPreset:function(n,p){var m=this.presetsSelect.find('[data-rel="latest-period"]');
if(m.length){m.remove();}if(n){var o='<option data-rel="latest-period" value="'+n+'">'+p+"</option>";this.presetsSelect.append(o);
}},onPreset:function(p){var o=c(p.currentTarget).val();var m;if(o===f.__PRESET_LAST_7_DAYS){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_7_DAYS);
this.setChartGranularity(f.__DAY_FORMAT,true);}if(o===f.__PRESET_LAST_4_WEEKS){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_4_WEEKS);
this.setChartGranularity(f.__WEEK_FORMAT,true);}if(o===f.__PRESET_LAST_30_DAYS){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_30_DAYS);
this.setChartGranularity(f.__DAY_FORMAT,true);}if(o===f.__PRESET_LAST_YEAR){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_YEAR);
this.setChartGranularity(f.__MONTH_FORMAT,true);}var n=(this.collection.getValue("mondayWeek"))?1:0;if(o===f.__PRESET_THIS_MINUTE){if(this.collection.getValue("timeCollectionMode")===f.__LATEST){f.recalculateDatesAsLatest(true,n);
}i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_MINUTE);this.setChartGranularity(f.__MINUTE_FORMAT,true);}if(o===f.__PRESET_THIS_HOUR){if(this.collection.getValue("timeCollectionMode")===f.__LATEST){f.recalculateDatesAsLatest(true,n);
}i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_HOUR);this.setChartGranularity(f.__HOUR_FORMAT,true);}if(o===f.__PRESET_THIS_DAY){i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_DAY);
this.setChartGranularity(f.__DAY_FORMAT,true);}if(o===f.__PRESET_THIS_WEEK){i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_WEEK);
this.setChartGranularity(f.__WEEK_FORMAT,true);}this.presetsSelect.val("hgdfkj");}});return e;});define("timeline/util/formatTicks",["jquery","chartutil/dateUtils_CET","timeline/util/timelineConstants"],function(b,d,a){var c={};
c.formatTicks=function(m,f){var j=this;var h=0;var l=this.collection.getValue("forceCET");var g=j.getFormatPeriod();var e,k;
if(f===0){if(l){if(g===a.__HOUR_FORMAT){h++;e=d.getAmsterdamDSTOffsetTime(m,true,false);k=d.timezoneShiftPseudoDate(m,e,false,"tick",h<1);
j.oldDateForFormatting=k;return d.formatPseudoDate(k,a.__FORMAT_HOURS_PSEUDO);}else{if(g===a.__MINUTE_FORMAT){h++;e=d.getAmsterdamDSTOffsetTime(m,true,false);
k=d.timezoneShiftPseudoDate(m,e,false,"tick",h<1);j.oldDateForFormatting=k;return d.formatPseudoDate(k,a.__FORMAT_MINUTES_PSEUDO);
}else{j.oldDateForFormatting=m;return j.timeFormat(m);}}}else{j.oldDateForFormatting=m;return j.timeFormat(m);}}switch(g){case a.__MINUTE_FORMAT:if(l){h++;
e=d.getAmsterdamDSTOffsetTime(m,true,false);k=d.timezoneShiftPseudoDate(m,e,false,"tick",h<1);if(k.utcHours!==j.oldDateForFormatting.utcHours){if(f<=2){j.hidePreviousTick(f);
}j.oldDateForFormatting=k;return d.formatPseudoDate(k,a.__FORMAT_MINUTES_PSEUDO);}else{return"";}}else{if(m.getHours()!==j.oldDateForFormatting.getHours()){if(f<=4){j.hidePreviousTick(f);
}j.oldDateForFormatting=m;return j.timeFormat(m);}else{return"";}}break;case a.__HOUR_FORMAT:if(l){h++;e=d.getAmsterdamDSTOffsetTime(m,true,false);
k=d.timezoneShiftPseudoDate(m,e,false,"tick",h<1);if(k.date!==j.oldDateForFormatting.date){if(f<=3){j.hidePreviousTick(f);
}j.oldDateForFormatting=k;return d.formatPseudoDate(k,a.__FORMAT_HOURS_PSEUDO);}else{return"";}}else{if(m.getDate()!==j.oldDateForFormatting.getDate()){if(f<=3){j.hidePreviousTick(f);
}j.oldDateForFormatting=m;return j.timeFormat(m);}else{return"";}}break;case a.__DAY_FORMAT:case a.__WEEK_FORMAT:if(m.getFullYear()!==j.oldDateForFormatting.getFullYear()||m.getMonth()!==j.oldDateForFormatting.getMonth()){if(g===a.__DAY_FORMAT&&f===1){j.hidePreviousTick(f);
}j.oldDateForFormatting=m;return j.timeFormat(m);}else{return"";}break;case a.__MONTH_FORMAT:if(m.getFullYear()!==j.oldDateForFormatting.getFullYear()){j.oldDateForFormatting=m;
return j.timeFormat(m);}else{return"";}break;}};return c;});define("timeline/collections/timelineData",["jquery","underscore","backbone","timeline/models/timelineState","chartutil/objectutils","chartlib/events/appstateevents","chartlib/chartBaseEvents","map/events/worldevents"],function(c,b,e,a){var d=e.Collection.extend({model:a,getValue:function(f){return this.at(0).get(f);
},setValue:function(f,g){this.at(0).set(f,g);},getDates:function(){return this.at(0).get("extent");}});return d;});define("timeline/util/reformatTimeline",["jquery","backbone","chartutil/dateUtils_CET","timeline/util/timelineConstants","timeline/events/timelineEvents"],function(b,f,e,a,d){var c={};
c.reformatTimeline=function(o,h,j,g,n,l){var i=this.baseGranularity||this.collection.getValue("baseGranularity");var k=this.formatPeriod||this.collection.getValue("formatPeriod");
f.trigger(d.DISABLE_CONTROLS,"reformatTimeline");if(this.logTimelineCalcs&&window.console&&window.console.log){window.console.log("reformatTimeline formatPeriod =",k," pNumMinutes=",o,"  startDate=",h,"  pChangeAgent=",j,"  pEndExtentDate=",g,"  pJumpPeriod=",n);
}var r=(this.collection)?this.collection.getValue("timeline"):null;var q=(r)?r[0]:this.scales.x.domain()[0];var m=(r)?r[1]:this.scales.x.domain()[1];
var p=(typeof n!=="undefined")?n:false;if(k===a.__MINUTE_FORMAT){if(j===a.__DAYS_BTN||j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 6");
}this.switchToDay(h,g);return true;}if(j===a.__WEEKS_BTN||j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 6");
}this.switchToWeek(h,g);return true;}if(j===a.__MONTHS_BTN||j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 5");
}this.switchToMonth(h,g);return true;}if(o>=a.__MINUTE_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 4");
}this.switchToHour(h,g);return true;}if(j===a.__MINUTE_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 5 (IN MINUTE, STAY IN MINUTE)");
}this.switchToMinute(h,g,p,l);return true;}}else{if(k===a.__HOUR_FORMAT){if(j===a.__WEEKS_BTN||j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 5");
}this.switchToWeek(h,g);return true;}if(j===a.__MONTHS_BTN||j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 4");
}this.switchToMonth(h,g);return true;}if(j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 7");
}this.switchToDay(h,g);return true;}if(o>0&&o<a.__HOUR_MODE_SWITCH_POINT_MIN&&i<a.__HOUR_GRANULARITY){if(window.console&&window.console.log){window.console.log("### reformatTimeline ACTION: switchToMinute 1");
}this.switchToMinute(h,g);return true;}if(o>=a.__HOUR_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 4");
}this.switchToDay(h,g);return true;}if(j===a.__HOUR_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 5 (IN HOUR, STAY IN HOUR)");
}this.switchToHour(h,g,p,l);return true;}}else{if(k===a.__DAY_FORMAT){if(j===a.__MINUTES_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 2");
}this.switchToMinute(h,g);return true;}if(j===a.__MONTHS_BTN||j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 1");
}this.switchToMonth(h,g);return true;}if(o>0&&o<a.__DAY_MODE_SWITCH_POINT_MIN&&i<a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("### reformatTimeline ACTION: switchToHour 1");
}this.switchToHour(h,g);return true;}if(o>=a.__DAY_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 1");
}this.switchToWeek(h,g);return"switchToWeek 1";}if(j===a.__DAY_GRANULARITY){if(o===-1){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 5b (IN DAY, STAY IN DAY) - ACCEPT SWITCH");
}this.switchToDay(h,g,p,l);return true;}else{if(h<q||g>m){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 5a (IN DAY, STAY IN DAY) - ACCEPT SWITCH");
}this.switchToDay(h,g);return true;}else{if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 5 - REJECT SWITCH");
}return false;}}}if(j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 7 pNumMinutes=",o);
}this.switchToWeek(h,g);return true;}}else{if(k===a.__WEEK_FORMAT){if(j===a.__MINUTES_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 3");
}this.switchToMinute(h,g);return true;}if(j===a.__HOURS_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 2");
}this.switchToHour(h,g);return true;}if(o>0&&o<a.__WEEK_MODE_SWITCH_POINT_MIN&&i<a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 1");
}this.switchToDay(h,g);return true;}if(o>a.__WEEK_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 2");
}this.switchToMonth(h,g);return true;}if(j===a.__WEEK_GRANULARITY){if(o===-1){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 2b (IN WEEK, STAY IN WEEK) - ACCEPT SWITCH");
}this.switchToWeek(h,g,p,l);return true;}else{if(h<q||g>m){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 2a (IN WEEK, STAY IN WEEK) - ACCEPT SWITCH");
}this.switchToWeek(h,g);return true;}else{if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 2 - REJECT SWITCH");
}return false;}}}if(j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 2 ");
}this.switchToDay(h,g);return true;}if(j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 6 pNumMinutes=",o);
}this.switchToMonth(h,g);return true;}}else{if(k===a.__MONTH_FORMAT){if(j===a.__MINUTES_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 4");
}this.switchToMinute(h,g);return true;}if(j===a.__DAYS_BTN||j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 3");
}this.switchToDay(h,g);return true;}if(j===a.__HOURS_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 3");
}this.switchToHour(h,g);return true;}if(o>0&&o<a.__MONTH_MODE_SWITCH_POINT_MIN&&i<a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("---> reformatTimeline ACTION: switchToWeek 3  pNumMinutes=",o);
}this.switchToWeek(h,g);return true;}if(j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 3 (IN MONTH, STAY IN MONTH)");
}this.switchToMonth(h,g);return true;}if(j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 4 pNumMinutes=",o);
}this.switchToWeek(h,g);return true;}}}}}}return false;};return c;});define("timeline/views/ui/calendarUI_v7",["jquery","underscore","backbone","timeline/events/timelineEvents","timeline/util/timelineConstants","calendar/datepicker","chartlib/chartBaseEvents","chartutil/dateUtils_CET","util/Analytics"],function(b,i,h,j,d,c,e,a,g){var f=h.View.extend({el:"#calendarUI",useLatestDay:false,formatPeriod:null,initialize:function(){this._super(arguments);
i.bindAll(this,"setCalendar","checkDate","clearErrors","setCalendarForHoursOrMinutes","submitDates");h.on(j.SET_CALENDAR,this.setCalendar);
h.on(j.TIMESPAN_SET_UTC,this.setCalendarForHoursOrMinutes);h.on(j.TIMESPAN_SET,this.clearErrors,this);if(this.collection&&this.collection.getValue("timeCollectionMode")===d.__LATEST){this.useLatestDay=true;
}this.uid=this.collection.getValue("uid");this.$el.css("display","block");this.startDate=b("#datepickStart");this.endDate=b("#datepickEnd");
this.dpStartElement=this.startDate;this.dpEndElement=this.endDate;this.dpStartIcon=b("#datepickStart-icon");this.dpEndIcon=b("#datepickEnd-icon");
var k=b("#checkMessage")[0];this.dpStart=new c(this.dpStartElement[0],{dateFormat:"Y-m-d",useToday:this.useLatestDay,linkedToTimeline:true},k,this.dpStartIcon[0]);
this.dpEnd=new c(this.dpEndElement[0],{dateFormat:"Y-m-d",useToday:this.useLatestDay,linkedToTimeline:false},k,this.dpEndIcon[0]);
this.startDate.on("change",{datepicker:this.dpStart},this.checkDate);this.endDate.on("change",{datepicker:this.dpEnd},this.checkDate);
},setCalendar:function(){this.dpStartIcon.css("visibility","visible");this.dpEndIcon.css("visibility","visible");this.dpStartElement.prop("readonly",0);
this.dpEndElement.prop("readonly",0);this.dpStartElement.css("color","#444");this.dpEndElement.css("color","#444");var m=this.collection.getValue("extent");
var o=1;if((m[0].getFullYear()===m[1].getFullYear())&&(m[0].getMonth()===m[1].getMonth())&&m[0].getDate()===m[1].getDate()){o=0;
}var k=new Date(m[1].getFullYear(),m[1].getMonth(),m[1].getDate()-o);var n=m[0].toFormattedString();var l=k.toFormattedString();
this.startDate.val(n);this.endDate.val(l);this.dpStart.updateMonth(m[0].getMonth(),m[0].getFullYear());this.dpEnd.updateMonth(k.getMonth(),k.getFullYear());
},setCalendarForHoursOrMinutes:function(){this.clearErrors();var m=this.collection.getValue("formatPeriod");if(m===d.__HOUR_FORMAT||m===d.__MINUTE_FORMAT){this.dpStartIcon.css("visibility","hidden");
this.dpEndIcon.css("visibility","hidden");this.dpStartElement.prop("readonly",1);this.dpEndElement.prop("readonly",1);this.dpStartElement.css("color","#aaa");
this.dpEndElement.css("color","#aaa");}var l=this.collection.getValue("extentAMS");var k=a.formatPseudoDate(l[0],d.__FORMAT_DATE_PSEUDO);
var n=a.formatPseudoDate(l[1],d.__FORMAT_DATE_PSEUDO);this.startDate.val(k);this.endDate.val(n);},checkDate:function(m){var l=m.data.datepicker;
var k={};k.data={startDate:this.startDate[0],endDate:this.endDate[0],callback:this.submitDates,useToday:this.useLatestDay,granularity:this.collection.getValue("formatPeriod")};
l.checkDate(k);},submitDates:function(l,k){l=l.replace(/\//g,"-");k=k.replace(/\//g,"-");g.trackEvent("Timeline_"+this.uid,"timeline.event.calendar");
h.trigger(j.CALENDAR_SET,l,k);},clearErrors:function(){this.dpStart.clearMessage();this.dpEnd.clearMessage();}});return f;
});define("timeline/views/timeline_v7",["jquery","underscore","backbone","chartlib/chartbase","d3","util/UserPreferences","chartutil/dateUtils_CET","chartlib/events/appstateevents","timeline/events/timelineEvents","timeline/util/timelineConstants","timeline/util/timelineUtils_v7","timeline/util/reformatTimeline","timeline/util/timelineControls_v7","timeline/util/formatTicks","chartutil/stringutils","util/Analytics","chartutil/svgutils"],function(e,q,b,j,p,g,c,o,m,k,i,l,n,d,r,h,a){var f=j.extend({el:"#timelineHolder",defaults:{margin:{top:30,right:65,bottom:5,left:15}},isUnitTest_render:false,dateFormat:null,timeFormat:null,oldDateForFormatting:null,lastFormatPeriod:null,allowDrag:true,doStartupCheck:false,logTimelineCalcs:false,startupSteps:0,totalStartupSteps:9,timelineCalcReturnObj:null,oldExtent:null,compareExtents:false,allowJump:true,fixedExtent:null,moving_numDays:0,moving_numMinutes:0,dateBlock:null,dateBlockText:null,altKeyIsDown:false,hasMinStartDates:false,minStartDate_day:null,minStartDate_week:null,weekStartAdj:0,latestExceptAtDayGranularity:false,initialize:function(t){q.bindAll(this,"brushmove","brushend","brushstart");
this.startupSteps++;if(window.console&&console.log){console.log("### timeline_v7::initialize:: pOptions=",t);}if(this.collection.getValue("mondayWeek")){this.weekStartAdj=1;
k.__WEEK_FORMAT=k.__MONDAY_STR;if(window.console&&console.log){console.log("### timeline_v7::initialize:: @@@@@@@#########@@@@@@@@###### TimelineConstants.__WEEK_FORMAT=",k.__WEEK_FORMAT);
}}k.init(this.weekStartAdj);if(typeof t.unitTest_render!=="undefined"){this.isUnitTest_render=t.unitTest_render;}this.reformatTimeline=q.bind(l.reformatTimeline,this);
this.calculateTimeline=q.bind(i.calculateTimeline,this);this.processDatesForTimezone=q.bind(i.processDatesForTimezone,this);
this.finaliseTimeline=q.bind(i.finaliseTimeline,this);this.calculateExtent=q.bind(i.calculateExtent,this);this.jumpPeriod=q.bind(n.jumpPeriod,this);
this.enableControls=q.bind(n.enableControls,this);this.formatTicks=q.bind(d.formatTicks,this);if(!this.isUnitTest_render){b.on(m.MODE_CHANGED,this.onModeChange,this);
b.on(m.CALENDAR_SET,this.calendarSet,this);b.on(m.CONFIG_SAVE_REQUESTED,this.outputTimelineConfig,this);b.on(m.JUMP_PERIOD,this.jumpPeriod);
b.on(m.OUTPUT_URL,this.outputTimelineConfig,this);b.on(m.PRESET_PERIOD,this.setPreset,this);b.on(m.ALT_KEY_PRESS,this.altKeyAction,this);
b.on(m.ALT_KEY_UP,this.altKeyAction,this);}this.uid=this.collection.getValue("uid");this.timelineWidgetContainer=this.collection.getValue("widgetContainer");
var w=this.collection.getValue("formatPeriod");if(this.collection.getValue("minStartDates").length){this.hasMinStartDates=true;
var L=this.collection.getValue("minStartDates");var F=L[0];var C=L[1];if(this.collection.getValue("timeCollectionMode")===k.__LATEST){F-=1;
C-=1;}this.minStartDate_day=k.getMinDate(k.__DAY_FORMAT,F);this.minStartDate_week=k.getMinDate(k.__WEEK_FORMAT,C);}var I=this.collection.getValue("timeCollectionMode");
if(I===k.__LATEST_NOT_DAY){this.latestExceptAtDayGranularity=true;if(w===k.__WEEK_FORMAT||w===k.__MONTH_FORMAT){var K=new Date().getDate();
if(K===1){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);I=k.__LAST_FULL;}else{this.collection.setValue("timeCollectionMode",k.__LATEST);
I=k.__LATEST;}}if(w===k.__DAY_FORMAT){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);I=k.__LAST_FULL;}}if(I===k.__LATEST){k.recalculateDatesAsLatest(false,this.weekStartAdj);
}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE OPTIONS PROCESSED");
}var v=null;var G=decodeURIComponent(r.getUrlParameter("formatPeriod"));var z=decodeURIComponent(r.getUrlParameter("formatMsecs"));
var E=decodeURIComponent(r.getUrlParameter("startTimeline"));var u=decodeURIComponent(r.getUrlParameter("endTimeline"));var y=decodeURIComponent(r.getUrlParameter("startExtent"));
var J=decodeURIComponent(r.getUrlParameter("endExtent"));var H=decodeURIComponent(r.getUrlParameter("chartGranularity"));
if(G!=="undefined"&&z!=="undefined"&&E!=="undefined"&&u!=="undefined"&&y!=="undefined"&&J!=="undefined"){v={formatPeriod:G,formatMsecs:z,startTimeline:E,endTimeline:u,startExtent:y,endExtent:J};
}else{var M=g.getPreference(this.uid);if(M){v=JSON.parse(M);g.setPreference(this.uid,null);}}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE CONFIG OBJECT PROCESSED");
}var B,x,A,D;if(v){this.setFormat(v.formatPeriod,v.formatMsecs);A=new Date(Number(v.startExtent));D=new Date(Number(v.endExtent));
B=new Date(Number(v.startTimeline));x=this.createTimelineEnd(Number(v.endTimeline));if(H!=="undefined"){b.trigger(m.SET_CHART_GRAN_SELECT,H,true);
}}else{switch(w){case k.__MINUTE_FORMAT:this.setFormat(w,k.__MSECS_PER_MINUTE);A=k.__THIRTY_MINUTES_AGO;D=k.__THIS_MINUTE;
B=k.__SIXTY_ONE_MINUTES_AGO;x=this.createTimelineEnd(k.__THIS_MINUTE);break;case k.__HOUR_FORMAT:this.setFormat(w,k.__MSECS_PER_HOUR);
A=k.__TWENTY_FOUR_HOURS_AGO;D=k.__THIS_HOUR;B=k.__FORTY_EIGHT_HOURS_AGO;x=this.createTimelineEnd(k.__THIS_HOUR);break;case k.__DAY_FORMAT:this.setFormat(w,k.__MSECS_PER_DAY);
A=k.__ONE_WEEK_BEFORE_TODAY;D=k.__TODAY;B=k.__LAST_MONTH;x=this.createTimelineEnd(k.__TODAY);break;case k.__WEEK_STR:case k.__WEEK_FORMAT:this.setFormat(k.__WEEK_FORMAT,k.__MSECS_PER_WEEK);
A=k.__FOUR_WEEKS_AGO;D=k.__THIS_WEEK;B=k.__THIRTEEN_WEEKS_AGO;x=this.createTimelineEnd(k.__THIS_WEEK);break;case k.__MONTH_FORMAT:this.setFormat(w,k.__MSECS_PER_MONTH);
A=k.__TWELVE_MONTHS_AGO;D=k.__THIS_MONTH;B=k.__TWELVE_MONTHS_AGO;x=this.createTimelineEnd(k.__THIS_MONTH);break;}}this.collection.setValue("timeline",[B,x]);
this.collection.setValue("extent",[A,D]);this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE CONFIG COMPLETE: __THIS_MINUTE=",k.__THIS_MINUTE," offset=",k.__THIS_MINUTE.getTimezoneOffset());
}this.fixedExtent=this.collection.getValue("fixedExtent");this._super();this.enableControls();this.startupSteps++;if(window.console&&window.console.log){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE INIT COMPLETE!!!!!!!!!!! [*** SHOULD BE FINAL STEP! ***]");
}if(this.startupSteps===this.totalStartupSteps){var s=this.collection.getValue("startPreset");if(s!==null){this.setPreset(s);
}else{this.dispatchTimespan();}}else{if(window.console&&window.console.error){console.error("!!! The timeline has not started up correctly !!!");
}}},initRender:function(){this.setDateFormat();this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE PRE INIT-RENDER");
}this._super();this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE INIT-RENDER SUPER");
}this.xAxis.attr("transform","translate(0,"+(-20)+")");this.topSVG.classed("timeline",true).attr("width",this.width+this.options.margin.left+this.options.margin.right).attr("height",this.height+this.options.margin.top+this.options.margin.bottom);
var w="."+this.svg.attr("class");var s=this.topSVG.insert("defs",w);var u=s.append("filter").attr("id","f1").attr("x",0).attr("y",0);
u.append("feGaussianBlur").attr("in","SourceGraphic").attr("stdDeviation","2 0");this.brush=p.svg.brush().x(this.scales.x).extent(this.collection.getValue("extent")).on("brushstart",this.brushstart).on("brush",this.brushmove).on("brushend",this.brushend);
if(!this.isUnitTest_render){var v=this.svg.append("g").attr("class","brush").call(this.brush);v.selectAll("rect").attr("height",this.height);
v.selectAll(".resize").append("rect").attr("width","5px").attr("height","20px").attr("transform","translate(-2,"+this.height/4+")");
if(this.fixedExtent){v.selectAll(".resize").remove();}this.brushExtent=p.select(".brush .extent");this.brushHandles=p.selectAll(".brush .resize rect");
}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE RENDER COMPLETE!");
}b.trigger(m.SET_GRANULARITY);var t=this.collection.getValue("extent");this.oldExtent=t;if(!this.isUnitTest_render){this.updateDisplay();
this.colorizeSelection(t);}this.startupSteps++;if(window.console&&window.console.log&&this.doStartupCheck){window.console.log("### startUp step ",this.startupSteps," of ",this.totalStartupSteps," : TIMELINE INIT-RENDER & STARTUP PROCESS COMPLETE");
}},setXScale:function(){this.scales.x=p.time.scale.utc().domain(this.collection.getValue("timeline")).range([0,this.width]);
},calibrateXScale:function(s){if(window.console&&window.console.log){window.console.log("\n### CALIBRATE X SCALE ---------------------- pDomain=",s);
}if(s){this.collection.setValue("timeline",s);this.scales.x.domain(s);}},setXAxis:function(){this.axes.x=p.svg.axis().scale(this.scales.x).orient("bottom").tickPadding(-15).tickSize(20).ticks(this.dateFormat).tickFormat(this.formatTicks);
},hidePreviousTick:function(t){var s=e(".x.axis .tick text");var u=e(s[0]).text("");},renderXAxis:function(){this.xAxis.call(this.axes.x).selectAll("text").attr("dx",6).style("text-anchor","start");
var s=p.selectAll(".timeline-holder .tick");s[0].forEach(function(t,u){if(t.style){t.style.display="block";}else{t.domNode.style.display="block";
}if(t&&t.textContent===""){if(t.style){t.style.display="none";}else{t.domNode.style.display="none";}}});},renderYAxis:function(){},renderData:function(){var x=this.getFormatPeriod();
var F=this.scales.x;var C=F.range()[1]-F.range()[0];var E=p.selectAll(".timeline-holder .x.axis .tick");var t=E[0].length;
var w=C/t;var B=this.height;var s=0;var D=[];var A=this;E[0].forEach(function(M,N){var J=p.select(M).datum();s=A.scales.x(J);
var K={date:J,x:s,width:w,height:B};D.push(K);if(D.length>1&&x===k.__MONTH_FORMAT){var L=D[N-1];L.width=s-L.x;}});var I=D.length;
e("#numBlocks").html(I+" blocks");switch(this.getFormatPeriod()){case k.__MONTH_FORMAT:if(I>12){console.error("Too many blocks on the timeline:",I,"when it should be 12");
}break;case k.__WEEK_FORMAT:if(I>13){console.error("Too many blocks on the timeline:",I,"when it should be 13");}break;case k.__DAY_FORMAT:if(I>32){console.error("Too many blocks on the timeline:",I,"when it should be 32");
}break;case k.__HOUR_FORMAT:if(I>49){console.error("Too many blocks on the timeline:",I,"when it should be 49");}break;case k.__MINUTE_FORMAT:if(I>61){console.error("Too many blocks on the timeline:",I,"when it should be 61");
}break;}this.svg.selectAll(".block").remove();var v=this.svg.selectAll(".block").data(D);var H=v.enter().insert("g",".brush").attr("class","block").attr("transform",function(J){return"translate("+J.x+","+0+")";
});var z=(x!==k.__MINUTE_FORMAT)?6:4;this.dateBlock=H.append("rect").attr("class","date-box").attr("x",(z/2)).attr("y",(z/2)).attr("width",function(J){return J.width-z;
}).attr("height",function(J){return J.height-z;});var u="date-box-text "+x;var y=0;var G=this.collection.getValue("forceCET");
if(G){H.append("text").attr("class","utc-time").attr("x",function(J){return(J.width/2);}).attr("y",function(J){return 10;
}).attr("text-anchor","middle").style("font-size","8px").text(function(J){if(x===k.__HOUR_FORMAT||x===k.__MINUTE_FORMAT){return p.time.format.utc("%H")(J.date);
}return"";});}this.dateBlockText=H.append("text").attr("class",u).attr("x",function(J){return(J.width/2);}).attr("y",function(J){return(((J.height+z)/2)+2);
}).attr("text-anchor","middle").text(function(P){var M=P.date;var L;switch(x){case k.__MINUTE_FORMAT:y++;L=Date.padded2(M.getMinutes());
break;case k.__HOUR_FORMAT:if(G){y++;var K=c.getAmsterdamDSTOffsetTime(M,true,(y<1));var N=c.timezoneShiftPseudoDate(M,K,false,"block",y<1);
L=c.formatPseudoDate(N,k.__FORMAT_BLOCK_PSEUDO);}else{L=Date.padded2(M.getHours());}break;case k.__DAY_FORMAT:var Q=M.getDate();
L=Date.padded2(Q);break;case k.__WEEK_FORMAT:var O=String(M.getWeek());if(O.length===1){O="0"+O;}L="wk "+O;break;case k.__MONTH_FORMAT:var J=M.getMonth();
L=c.__MONTHS_SHORT[J];break;}return L;});if(G){H.append("text").attr("class","local-time").attr("x",function(J){return(J.width/2);
}).attr("y",function(J){return 32;}).attr("text-anchor","middle").style("font-size","7px").text(function(J){if(x===k.__HOUR_FORMAT||x===k.__MINUTE_FORMAT){return p.time.format("%d/%H")(J.date);
}return"";});}},updateDisplay:function(){this.renderXAxis();this.renderData();},onModeChange:function(t,s){this[s](t);},brushstart:function(){this.compareExtents=true;
this.allowJump=true;if(this.altKeyIsDown){this.brush.clear();p.select(".brush").call(this.brush);}},brushmove:function(y){var B=this.getExtent(),z;
var x=this.getFormatPeriod();var A=this.getFormatMsecs();var D=this.collection.getValue("forceCET");var C,u="";if(p.event.mode==="move"){var t=p.time[x].round(B[0]);
var s=p.time[x].offset(t,Math.round((B[1]-B[0])/A));z=[t,s];this.extentDrag=true;}else{this.extentResize=true;z=(this.fixedExtent&&this.fixedExtent_extent)?this.fixedExtent_extent:this.snapBrush();
this.moving_numDays=Math.round(c.getNumDays(B[1],B[0]));var v=this.processDatesForTimezone(B[0],B[1],k.__BRUSHMOVE,false);
this.moving_numMinutes=v[0];if(this.compareExtents){this.compareExtents=false;this.allowJump=this.checkForNewExtent(z);}b.trigger(m.SET_DAYS,this.moving_numDays,this.moving_numMinutes);
if(this.allowJump){var w=this.checkTimeline(this.moving_numMinutes);if(w){this.colorizeBrushExtent(false);}else{this.colorizeBrushExtent(true);
}}else{this.colorizeBrushExtent(true);}}if(this.allowDrag){if(this.fixedExtent){C=(z[1]-z[0])/1000/60;if(z[0]<this.oldExtent[0]){u="left";
}else{if(z[1]>this.oldExtent[1]){u="right";}}if(C>=k.__DAY_MODE_SWITCH_POINT_MAX){if(u==="left"){z[1].setDate(z[1].getDate()-27);
z=z.map(p.time[x].round);}else{if(u==="right"){z[0].setDate(z[0].getDate()+27);z=z.map(p.time[x].round);}}this.fixedExtent_extent=z;
}}this.collection.setValue("extent",z);p.select(".brush").call(this.brush.extent(z));this.colorizeSelection(z);}},checkForNewExtent:function(s){if(Number(this.oldExtent[0])!==Number(s[0])&&Number(this.oldExtent[1])!==Number(s[1])){return false;
}else{return true;}},brushend:function(){if(this.extentDrag){h.trackEvent("Timeline_"+this.uid,"timeline.event.drag-extent");
this.extentDrag=false;}if(this.extentResize){if(this.colouredExtent){h.trackEvent("Timeline_"+this.uid,"timeline.event.resize-extent-to-jump-granularity");
}else{h.trackEvent("Timeline_"+this.uid,"timeline.event.resize-extent");}this.extentResize=false;this.colouredExtent=false;
}var u=this.collection.getValue("extent");var x=Math.round(c.getNumDays(u[1],u[0]));var w;var v=this.getFormatPeriod();var t=this.processDatesForTimezone(u[0],u[1],k.__BRUSHEND,false);
w=t[0];b.trigger(m.SET_DAYS,x,w);if(v===k.__MONTH_FORMAT||(v===k.__WEEK_FORMAT&&this.moving_numMinutes<k.__WEEK_MODE_SWITCH_POINT_MIN)||(v===k.__DAY_FORMAT&&this.moving_numMinutes<k.__DAY_MODE_SWITCH_POINT_MIN)||(v===k.__HOUR_FORMAT&&this.moving_numMinutes<k.__HOUR_MODE_SWITCH_POINT_MIN)){if(this.allowJump){this.reformatTimeline(this.moving_numMinutes,u[0]);
}}else{this.reformatTimeline(w,u[0],"stretchExtent",u[1]);}this.fixedExtent_extent=null;this.setExtent();},jumpOut:function(y){var x=this.collection.getValue("extent");
this.moving_numDays=0;this.moving_numMinutes=0;var u=this.getStartTimeline();var v=this.getEndTimeline();var w;var t=this.processDatesForTimezone(u,v,k.__JUMP_OUT,false);
w=t[0];this.reformatTimeline(w,x[0],y,x[1]);this.setExtent();},jumpIn:function(w){var v=this.collection.getValue("extent");
var u=k.__HOUR_MODE_SWITCH_POINT_MIN-1;if(this.collection.getValue("forceJumpFwd")){var t=v[1];switch(this.getFormatPeriod()){case k.__MONTH_FORMAT:t=c.adjustTime(v[1],-k.__MSECS_PER_MONTH);
break;case k.__WEEK_FORMAT:t=c.adjustTime(v[1],-k.__MSECS_PER_WEEK);break;case k.__DAY_FORMAT:t=c.adjustTime(v[1],-k.__MSECS_PER_DAY);
break;}switch(w){case k.__DAYS_BTN:if(this.getFormatPeriod()===k.__MONTH_FORMAT){t=c.adjustTime(t,-k.__MSECS_PER_DAY);}break;
}this.reformatTimeline(u,t,w);}else{this.reformatTimeline(u,v[0],w,v[1]);}this.setExtent();},switchToMinute:function(y,t,x,w){var B=(typeof x!=="undefined")?x:false;
this.setFormat(k.__MINUTE_FORMAT,k.__MSECS_PER_MINUTE);var A;var s=false;var u=c.roundToMinute(y,true);var v=this.collection.getValue("timeCollectionMode");
if(v===k.__LAST_FULL&&u.getHours()===k.__THIS_HOUR.getHours()-1&&!t&&!B){s=true;}if(!s){A=this.calculateTimeline(y,"roundToMinute",k.__MAX_MINUTES,0,B,w);
t=null;var C=k.__EXTENT_MINUTES_DEFAULT*2;if(x){t=A.endExtentDate;}this.calculateExtent(A.startDate,"roundToMinute",C,t,A.timelineEnd,k.__MINUTE_MODE_MAX_MINUTES);
}else{if(window.console&&window.console.log){window.console.log("### timeline_v7::switchToMinute:: showLatestMinutesshowLatestMinutesshowLatestMinutesshowLatestMinutes!!!!!");
}A=this.calculateTimeline(y,"roundToMinute",k.__MAX_MINUTES,60);var z=new Date(this.getStartTimeline());z=c.adjustTime(z,k.__MSECS_PER_MINUTE);
this.calculateExtent(z,"roundToMinute",k.__EXTENT_MINUTES_DEFAULT,A.timelineEnd,A.timelineEnd,k.__MINUTE_MODE_MAX_MINUTES);
}this.setSwitch();},switchToHour:function(v,s,y,t){s=null;var z=(s)?Math.floor(c.getNumMinutes(s,v)):k.__EXTENT_HOURS_DEFAULT_MAX;
var w=(z>k.__EXTENT_HOURS_DEFAULT_MAX)?k.__EXTENT_HOURS_DEFAULT_MAX*2:k.__EXTENT_HOURS_DEFAULT_MAX;var x=(this.getFormatPeriod()===k.__MINUTE_FORMAT)?k.__EXTENT_HOURS_DEFAULT_MIN:w;
this.setFormat(k.__HOUR_FORMAT,k.__MSECS_PER_HOUR);var u=this.calculateTimeline(v,"roundToHour",k.__MAX_HOURS,0,y,t);if(y){s=u.endExtentDate;
}this.calculateExtent(u.startDate,"roundToHour",x,s,u.timelineEnd,k.__HOUR_MODE_MAX_HOURS);this.setSwitch();},switchToDay:function(v,s,x,t){if(this.latestExceptAtDayGranularity){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);
k.init(this.weekStartAdj);}var w=(this.getFormatPeriod()===k.__HOUR_FORMAT)?k.__EXTENT_DAYS_DEFAULT_MIN:k.__EXTENT_DAYS_DEFAULT_MAX;
this.setFormat(k.__DAY_FORMAT,k.__MSECS_PER_DAY);var u=this.calculateTimeline(v,"roundToDay",k.__MAX_DAYS,null,x,t);if(x){s=u.endExtentDate;
}this.calculateExtent(u.startDate,"roundToDay",w,s,u.timelineEnd,k.__DAY_MODE_MAX_DAYS);this.setSwitch();},switchToWeek:function(w,s,x,u){if(this.latestExceptAtDayGranularity){var t=new Date().getDate();
if(t===1){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);k.init(this.weekStartAdj);}else{this.collection.setValue("timeCollectionMode",k.__LATEST);
k.recalculateDatesAsLatest(false,this.weekStartAdj);}}this.setFormat(k.__WEEK_FORMAT,k.__MSECS_PER_WEEK);var v=this.calculateTimeline(w,"roundToWeek",k.__MAX_WEEKS,null,x,u);
if(x){s=v.endExtentDate;}this.calculateExtent(v.startDate,"roundToWeek",k.__EXTENT_WEEKS_DEFAULT,s,v.timelineEnd,k.__WEEK_MODE_MAX_DAYS);
this.setSwitch();},switchToMonth:function(x,t){if(this.latestExceptAtDayGranularity){var v=new Date().getDate();if(v===1){this.collection.setValue("timeCollectionMode",k.__LAST_FULL);
k.init(this.weekStartAdj);}else{this.collection.setValue("timeCollectionMode",k.__LATEST);k.recalculateDatesAsLatest(false,this.weekStartAdj);
}}this.setFormat(k.__MONTH_FORMAT,k.__MSECS_PER_MONTH);var A=c.roundToMonth(k.__TODAY,true);var w=this.collection.getValue("timeCollectionMode");
if(w===k.__LATEST&&k.__TODAY.getDate()!==1){A.setMonth(A.getMonth()+1);}var y=k.__TWELVE_MONTHS_AGO;var s=A;s.setTime(s.getTime()-1);
this.calibrateXScale([y,s]);var u=x;var B=c.roundToMonth(u,true);if(B<k.__TWELVE_MONTHS_AGO){B.setMonth(B.getMonth()+1);}if(w===k.__LATEST){var z=c.roundToMonth(t,true);
z.setMonth(z.getMonth()+1);t=z;}this.calculateExtent(B,"roundToMonth",k.__EXTENT_MONTHS_DEFAULT,t,s,10000000);this.setSwitch();
},setFormat:function(t,s){this.lastFormatPeriod=this.collection.getValue("formatPeriod");this.collection.setValue("formatPeriod",t);
this.collection.setValue("formatMsecs",s);b.trigger(m.SET_DISPLAY);},getFormatPeriod:function(){return this.collection.getValue("formatPeriod");
},getFormatMsecs:function(){return this.collection.getValue("formatMsecs");},setExtent:function(){if(this.brush.empty()&&this.altKeyIsDown){return;
}var s=this.snapBrush();this.collection.setValue("extent",s);if(this.logTimelineCalcs&&window.console&&window.console.log){window.console.log("### setExtent extent1 (snapbrush)=",s);
}if(this.isUnitTest_render){return;}p.select(".brush").call(this.brush.extent(s));this.colorizeSelection(s);this.oldExtent=s;
this.dispatchTimespan();this.enableControls();},snapBrush:function(){var v=false;var u=this.getExtent(),t;var s=this.getFormatPeriod();
t=u.map(p.time[s].round);if(v&&window.console&&window.console.log){window.console.log("\n### SNAPBRUSH extent0=",u);window.console.log("### SNAPBRUSH extent1=",t);
}if(t[0]>=t[1]){if(v&&window.console&&window.console.log){window.console.log("### timeline_v7::snapBrush:: POCK!!!!!!");}if(u[0]>=this.getEndTimeline()){if(v&&window.console&&window.console.log){window.console.log("### ---------> LEFT DRAGGED PAST END extent mins=",u[0].getMinutes());
}u[0].setMinutes(u[0].getMinutes()-1);}else{if(u[1]<=this.getStartTimeline()){if(v&&window.console&&window.console.log){window.console.log("### ---------> RIGHT DRAGGED PAST START extent mins=",u[1].getMinutes());
}u[1].setMinutes(u[1].getMinutes()+1);}}t[0]=p.time[s].floor(u[0]);t[1]=p.time[s].ceil(u[1]);if(v&&window.console&&window.console.log){window.console.log("### SNAPBRUSH pocked extent0=",u);
window.console.log("### SNAPBRUSH pocked extent1=",t);}if(t[0]<this.getStartTimeline()){if(v&&window.console&&window.console.log){window.console.log("### timeline_v7::snapBrush:: extra check - start extent proceeds start timeline");
}t[0]=p.time[s].round(this.getStartTimeline());}if(t[1]>this.getEndTimeline()){if(v&&window.console&&window.console.log){window.console.log("### timeline_v7::snapBrush:: extra check - end extent exceeds end timeline: endTimeline=",this.getEndTimeline());
}t[1]=p.time[s].round(this.getEndTimeline());}}return t;},setSwitch:function(){if(this.isUnitTest_render){return;}this.timelineCalcReturnObj=null;
this.setDateFormat();this.axes.x.ticks(this.dateFormat);this.updateDisplay();var s=this;setTimeout(function(){b.trigger(m.SET_DAYS,0,0);
},10);this.colorizeBrushExtent(true);this.allowDrag=false;setTimeout(function(){s.allowDrag=true;},10);},colorizeBrushExtent:function(s){if(s){this.colouredExtent=false;
this.brushExtent.style("fill","none");this.brushExtent.style("stroke","#4c4c4c");this.brushHandles.style("fill","#4c4c4c");
this.brushHandles.style("stroke","#4c4c4c");}else{this.colouredExtent=true;this.brushExtent.style("fill","green");this.brushExtent.style("fill-opacity",0.25);
this.brushExtent.style("stroke","green");this.brushHandles.style("fill","green");this.brushHandles.style("stroke","green");
}},checkTimeline:function(u){var s=this.collection.getValue("baseGranularity");var t=this.getFormatPeriod();if(t===k.__MINUTE_FORMAT){if(u>=k.__MINUTE_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__HOUR_FORMAT){if(u>0&&u<k.__HOUR_MODE_SWITCH_POINT_MIN&&s<k.__HOUR_GRANULARITY){return true;}if(u>k.__HOUR_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__DAY_FORMAT){if(u>0&&u<k.__DAY_MODE_SWITCH_POINT_MIN&&s<k.__DAY_GRANULARITY){return true;}if(u>=k.__DAY_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__WEEK_FORMAT){if(u>0&&u<k.__WEEK_MODE_SWITCH_POINT_MIN&&s<k.__WEEK_GRANULARITY){return true;}if(u>=k.__WEEK_MODE_SWITCH_POINT_MAX){return true;
}}else{if(t===k.__MONTH_FORMAT){if(u>0&&u<k.__MONTH_MODE_SWITCH_POINT_MIN&&s<k.__MONTH_GRANULARITY){return true;}}}}}}return false;
},colorizeSelection:function(s){this.dateBlock.classed("selected",function(u){var t=s[0]<=u.date&&u.date<s[1];return t;});
this.dateBlockText.classed("selected",function(u){var t=s[0]<=u.date&&u.date<s[1];return t;});},getStartTimeline:function(){return this.collection.getValue("timeline")[0];
},getEndTimeline:function(){return this.collection.getValue("timeline")[1];},getExtent:function(){return this.brush.extent();
},createTimelineEnd:function(s){var t=new Date(s);t.setTime(t.getTime()-1);return t;},dispatchTimespan:function(){var F=this.collection.getValue("extent");
var w=this.getFormatPeriod();if(this.weekStartAdj===1&&w===k.__MONDAY_STR){w=k.__WEEK_STR;}var A,v,C;var B=this.collection.getValue("forceCET");
if(B&&(w===k.__HOUR_FORMAT||w===k.__MINUTE_FORMAT)){var y=c.getUTCValues(F[0],true);var x=c.getUTCValues(F[1],true);var u=c.getAmsterdamDSTOffsetTime(F[0],true,false);
var E=c.timezoneShiftPseudoDate(F[0],u,true,"output",false);u=c.getAmsterdamDSTOffsetTime(F[1],true,false);var t=c.adjustTime(F[1],-(1));
var z=c.timezoneShiftPseudoDate(t,u,true,"output",false);this.collection.setValue("extentUTC",[y,x]);this.collection.setValue("extentAMS",[E,z]);
if(window.console&&window.console.log){window.console.log("\n### DISPATCHTIMESPAN start date utc values parsed=",c.formatPseudoDate(y,k.__FORMAT_DATE_UTC));
window.console.log("### DISPATCHTIMESPAN end date utc values parsed  =",c.formatPseudoDate(x,k.__FORMAT_DATE_UTC));window.console.log("###\n");
}if(this.timelineWidgetContainer&&this.timelineWidgetContainer.jquery){A=c.formatPseudoDate(y,"yyyy-mm-dd H:M:S");v=c.formatPseudoDate(x,"yyyy-mm-dd H:M:S");
C=[A,v,w];C=[C];this.timelineWidgetContainer.trigger("timelineTimespanSet",C);}b.trigger(m.TIMESPAN_SET_UTC,this.collection);
b.trigger(o.CHANGE_REQUESTED);}else{if(window.console&&window.console.log){window.console.log("\n###");window.console.log("### DISPATCHTIMESPAN this.getExtent()   =",this.collection.getValue("extent"));
window.console.log("###\n");}if(this.timelineWidgetContainer&&this.timelineWidgetContainer.jquery){var D=this.collection.getValue("extent");
if(w===k.__HOUR_FORMAT||w===k.__MINUTE_FORMAT){A=p.time.format("%Y-%m-%d-%H-%M")(D[0]);v=p.time.format("%Y-%m-%d-%H-%M")(D[1]);
}else{A=p.time.format("%Y-%m-%d")(D[0]);v=p.time.format("%Y-%m-%d")(D[1]);}this.timelineWidgetContainer.trigger(m.TIMESPAN_SET,[A,v,w]);
C=[A,v,w];C=[C];this.timelineWidgetContainer.trigger("timelineTimespanSet",C);}b.trigger(m.TIMESPAN_SET,this.collection);
b.trigger(o.CHANGE_REQUESTED);b.trigger(m.SET_CALENDAR);}},setDateFormat:function(){switch(this.getFormatPeriod()){case k.__MINUTE_FORMAT:this.dateFormat=p.time.minutes;
this.timeFormat=p.time.format(k.__FORMAT_MINUTES);break;case k.__HOUR_FORMAT:this.dateFormat=p.time.hours;this.timeFormat=p.time.format(k.__FORMAT_HOURS);
break;case k.__DAY_FORMAT:this.dateFormat=p.time.days;this.timeFormat=p.time.format(k.__FORMAT_DAYS);break;case k.__WEEK_FORMAT:this.dateFormat=(this.weekStartAdj===0)?p.time.weeks:p.time.mondays;
this.timeFormat=p.time.format(k.__FORMAT_WEEKS);break;case k.__MONTH_FORMAT:this.dateFormat=p.time.months;this.timeFormat=p.time.format(k.__FORMAT_MONTHS);
break;}},calendarSet:function(t,y){var v=this.collection.getValue("baseGranularity");this.moving_numDays=0;this.moving_numMinutes=0;
var x=t.split("-");var u=new Date(x[0],x[1]-1,x[2]);var B=y.split("-");var A=new Date(B[0],B[1]-1,Number(B[2])+1);var z=Math.floor(c.getNumDays(A,u));
var w=Math.floor(c.getNumMinutes(A,u));var s;if(z<k.__CALENDER_DAY_GRANULARITY){s=k.__DAY_GRANULARITY;}else{if(z>=k.__CALENDER_DAY_GRANULARITY&&z<k.__CALENDER_WEEK_GRANULARITY){s=k.__WEEK_GRANULARITY;
}else{if(z>=k.__CALENDER_WEEK_GRANULARITY){s=k.__MONTH_GRANULARITY;}}}if(s<v){b.trigger(m.SET_CALENDAR,this.getExtent());
return;}this.collection.setValue("extent",[u,A]);this.brush.extent([u,A]);b.trigger(m.SET_DAYS,z,0,this.getExtent());this.reformatTimeline(w,u,s,A);
this.setExtent();},outputTimelineConfig:function(u){var v=(typeof u!=="undefined")?u:false;var D=this.getStartTimeline();
var A=new Date(this.getEndTimeline());A.setTime(A.getTime()+1);var F=this.collection.getValue("extent");var E=F[0];var x=F[1];
var z=this.getFormatPeriod();var B=this.getFormatMsecs();if(v){var w={formatPeriod:z,formatMsecs:B,startTimeline:D.getTime(),endTimeline:A.getTime(),startExtent:E.getTime(),endExtent:x.getTime(),setActiveAccountKey:adyen.currentAccount,chartGranularity:this.collection.getValue("chartGranularity")};
var t="?"+e.param(w);window.history.pushState("test","Title",window.location.origin+window.location.pathname+t);}else{var y={formatPeriod:z,formatMsecs:B,startTimeline:D.getTime(),endTimeline:A.getTime(),startExtent:E.getTime(),endExtent:x.getTime(),setActiveAccountKey:adyen.currentAccount,chartGranularity:this.collection.getValue("chartGranularity")};
var C=JSON.stringify(y);g.setPreference(this.uid,C);b.trigger(m.TIMESPAN_CONFIG_CREATED);}},altKeyAction:function(s){this.altKeyIsDown=s;
if(!this.altKeyIsDown){if(this.brush.empty()){this.brush.extent(this.oldExtent);this.setExtent();}}},setPreset:function(v){h.trackEvent("Timeline_"+this.uid,"timeline.event.preset-"+v);
this.moving_numDays=0;this.moving_numMinutes=0;switch(v){case k.__PRESET_LAST_7_DAYS:this.reformatTimeline(-1,k.__ONE_WEEK_BEFORE_TODAY,k.__DAY_GRANULARITY,k.__TODAY);
break;case k.__PRESET_LAST_4_WEEKS:this.reformatTimeline(-1,k.__FOUR_WEEKS_AGO,k.__WEEK_GRANULARITY);break;case k.__PRESET_LAST_30_DAYS:this.reformatTimeline(-1,k.__THIRTY_DAYS_AGO,k.__DAY_GRANULARITY,k.__TODAY);
break;case k.__PRESET_LAST_YEAR:this.reformatTimeline(-1,k.__TWELVE_MONTHS_AGO,k.__MONTH_GRANULARITY,k.__TODAY);break;case k.__PRESET_LAST_MONTH:this.reformatTimeline(-1,k.__THIS_MONTH,k.__MONTH_GRANULARITY,k.__TODAY);
break;case k.__PRESET_THIS_MINUTE:var u=new Date(k.__THIS_MINUTE);u.setMinutes(u.getMinutes()-1);this.reformatTimeline(-1,u,k.__MINUTE_GRANULARITY,k.__THIS_MINUTE);
break;case k.__PRESET_THIS_HOUR:var t=new Date(k.__THIS_HOUR);t.setHours(t.getHours()-1);this.reformatTimeline(-1,t,k.__HOUR_GRANULARITY,k.__THIS_HOUR);
break;case k.__PRESET_THIS_DAY:this.reformatTimeline(-1,k.__ONE_DAY_AGO,k.__DAY_GRANULARITY,k.__TODAY);break;case k.__PRESET_THIS_WEEK:var s=new Date(k.__THIS_WEEK);
s.setDate(s.getDate()-7);this.reformatTimeline(-1,s,k.__WEEK_GRANULARITY,k.__THIS_WEEK);break;}this.setExtent();}});return f;
},function(a){if(window.console&&window.console.log){window.console.log("TIMELINE JS ERROR =",a);}});define("timeline/views/timelineFacade",["jquery","underscore","backbone","timeline/views/timeline_v7","timeline/models/timelineState","timeline/collections/timelineData","timeline/views/ui/timelineUI_v7","timeline/views/ui/calendarUI_v7"],function(a,h,g,d,b,c,e,f){var i=g.View.extend({initialize:function(){this._super();
this.initModels(arguments[0]);this.initCollections();this.initViews();},initModels:function(j){this.timelineState=new b(j);
},initCollections:function(){this.timelineData=new c([this.timelineState]);},initViews:function(){this.timelineUI=new e({collection:this.timelineData,loadQueue:this.timelineState.get("loadQueue")});
if(this.timelineState.get("calendar")){this.calendarUI=new f({collection:this.timelineData});}this.timeline=new d({collection:this.timelineData});
},getDates:function(){return this.timelineData.getValue("extent");},getDatesUTC:function(){return this.timelineData.getValue("extentUTC");
},getDatesAMS:function(){return this.timelineData.getValue("extentAMS");},getGranularity:function(){return this.timelineData.getValue("formatPeriod");
},getChartGranularity:function(){return this.timelineData.getValue("chartGranularity");},getForceCET:function(){return this.timelineData.getValue("forceCET");
},getHasConfig:function(){return this.timelineData.getValue("config");}});return i;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);
}});