define("chart/widgetFramework/composed/riskReport/formatters/riskChecksStackedFormatter",["jqueryExtended","underscore","d3","chartutil/stringutils","chartutil/dateUtils_CET","chart/widgetFramework/core/constants/DataConstants","chartutil/domUtils","chartutil/d3utils"],function(a,g,h,b,c,e,f,i){var d=function(m,j,l,n){var k={};
k.data=m;k.options=j;k.formattedData={};k.comparator=null;k.reverseDirection=false;k.sortKey="chargeback";k.timeline=l;k.id=n;
k.numChecksToShow=10;k.formatData=function(){var q=[],o=this;var p=g.keys(this.data.riskCheckStatistics);if(p.length===0){return[];
}g.each(p,function(x){var y=h.format("0,000");var v=o.data.riskCheckStatistics[x];var t={};t.riskCheck=(x.length>57)?a.trim(x).substring(0,54).trim(this)+"...":x;
t.total=v.Total;t.checks=[];var s=g.keys(v);var u=0,w=h.format(".1f");g.each(s,function(C){var A=b.lowercaseFirstLetter(C);
var B=b.camelToDash(A);if(C!=="Total"){var z={};z.name=B;z.value=v[C];z.percent=w((z.value/t.total)*100)+"%";z.startX=u;z.endX=z.startX+z.value;
u=z.endX;t.checks.push(z);t[A]=z.value;t[A+"Perc"]=z.percent;t[A+"TT"]=y(z.value);}else{t.totalTT=y(t.total);}});q.push(t);
});var r=g.cloneDeep(q);this.masterData=g.filter(r,function(s){return s.total!==0;});if(this.sortKey){this.reverseDirection=true;
this.sortData(this.sortKey,true);}return{chartData:this.formattedData};};k.sortData=function(o,q){if(q!==true&&o===this.sortKey){return;
}if(o!=="total"){g.each(this.masterData,function(v){var u=[];var t=v.checks;var s=g.findWhere(t,{name:o});g.each(t,function(w){if(w===s){u.unshift(w);
}else{u.push(w);}});var r=0;g.each(u,function(w){w.startX=r;w.endX=w.startX+w.value;r=w.endX;});v.checks=u;});}this.sortKey=o;
this.comparator=(o!=="total")?this.compareFunction:this.compareFunctionTotal;var p=g.sortBy(this.masterData,this.comparator,this);
if(this.reverseDirection){p.reverse();}this.masterData=g.cloneDeep(p);p.length=(p.length>this.numChecksToShow)?this.numChecksToShow:p.length;
this.formattedData=p.reverse();if(q===true){return;}this.$el.trigger(e.FORMATTER_INFORM_WIDGET,{type:e.SORTED_DATA,data:{chartData:this.formattedData}});
};k.compareFunction=function(p){var o=g.findWhere(p.checks,{name:this.sortKey});return o.value;};k.compareFunctionTotal=function(o){return o[this.sortKey];
};k.downloadCSV=function(){var o=["riskCheck","total","refusedByBankPerc","refusedByBank","refusedByRiskPerc","refusedByRisk","chargebackPerc","chargeback","authorisedPerc","authorised"];
var p=["Risk Check","Total","Refused by bank %","Refused by bank tx","Refused by RevenueProtect %","Refused by RevenueProtect tx","Chargebacks %","Chargebacks tx","Authorized %","Authorized tx"];
f.createCSV(this.formattedData,o,p,"riskChecks");};k.getData=function(){return(this.formattedData)?this.formattedData:this.formatData();
};k.setRawData=function(o){this.data=o;};k.retrieveData=function(o){return this.formattedData[o];};return k;};return d;});
