define("chart/widgetFramework/core/drivers/axisBaseView",["jquery","underscore","d3","util/Functional","util/ObjectSuper","chart/widgetFramework/core/drivers/baseView","chart/widgetFramework/core/mixins/barDrawingUtils","chart/widgetFramework/core/mixins/lineDrawingUtils","chartutil/d3utils","chart/widgetFramework/core/constants/WidgetConstants","chart/widgetFramework/core/mixins/formats"],function(d,i,l,b,h,f,g,a,k,e,c){var j=function(q,m){var p={barHeight:null,barWidth:null};
var n=i.defaults(q,p);var o=f(n,m);var r=h(o);o.isBarChart=true;o.hasXAxis=true;o.hasYAxis=true;o.init=function(){r.init();
this.createDimensionStorageObjects();if(this.isBarChart){this.barUtils=g();}else{this.lineUtils=a();}this.barPositioningFn=null;
this.bandSize=0;this.barSize=0;this.granularityFormats={};this.granularityFormats.day=l.time.format("%d");this.granularityFormats.day_start=l.time.format("%b %d");
this.granularityFormats.month=l.time.format("%b");this.granularityFormats.month_start=l.time.format("%b '%y");};o.setBandSizes=function(){if(b.notFalsy(this.data)){var s,t=this.getData();
if(typeof t==="function"){s=t().length;}else{s=t.length;}if(this.options.variation===e.VERTICAL){this.bandSize=(this.width/s);
this.barSize=this.horizBarSize=(this.bandSize*(1-this.options.barPadding));}else{this.bandSize=(this.height/s);this.barSize=this.vertBarSize=(this.bandSize*(1-this.options.barPadding));
}}};o.setNestedAttr=function(v,u,x){if(b.falsy(v)){return;}var w=(u===true||u===false)?u:null;var t=(x===true||x===false)?x:null;
if(typeof this.options.nestedAttr!=="undefined"&&typeof this.options.nestedAttr==="string"){v=this.options.nestedAttr;}if((typeof v!=="undefined"&&typeof v==="string")){this.nestedAttr=v;
if(w){this.options.nestedXAttr=v;if(t===null||t){this.options.nestedYAttr=v;}}if(t){this.options.nestedYAttr=v;}return;}var y=k.detectNestedArrays(v,true);
var s=y.length;if(s===1){this.nestedAttr=y[0];if(w){this.options.nestedXAttr=y[0];if(t===null||t){this.options.nestedYAttr=y[0];
}}if(t){this.options.nestedYAttr=y[0];}}else{if(s===0){if(window.console&&console.log){console.error("### baseAxisView::setNestedAttr:: I can find no nested data to use to set nestedAttr!");
}}else{if(window.console&&console.log){console.error("### baseAxisView::feedData:: I'm confused over what the nestedAttr should be: ",y);
}}}};o.initRender=function(){r.initRender();this.renderTickDelay=this.options.yAxisTranTime+50;this.axisGroup=this.mainGroup.insert("g",".chart-elements-holder").attr("class","axis-elements-holder");
if(!b.falsy(this.dimensionsXArray)){i.each(this.dimensionsXArray,function(t){var s=o.axisGroup.append("g").attr("class",("x axis "+t)).attr("opacity",0.000001).attr("transform","translate(0,0)");
o.xAxesHolders[t]=s;});if(this.dimensionsXArray.length===1){this.options.xAttr=this.dimensionsXArray[0];}}else{this.xAxis=this.axisGroup.append("g").attr("class",("x axis")).attr("opacity",0.000001).attr("transform","translate(0,0)");
}if(!b.falsy(this.dimensionsYArray)){i.each(this.dimensionsYArray,function(t){var s=o.axisGroup.append("g").attr("class",("y axis "+t)).attr("opacity",0.000001);
o.yAxesHolders[t]=s;});if(this.dimensionsYArray.length===1){this.options.yAttr=this.dimensionsYArray[0];}}else{this.yAxis=this.axisGroup.append("g").attr("class",("y axis")).attr("opacity",0.000001);
}this.setScales();this.setAxes();};o.render=function(){this.chartHeight=this.$el.height();this.chartWidth=this.$el.width();
if(this.options.barHeight!==null&&b.notFalsy(this.data)){this.height=(this.data.length*this.options.barHeight);this.chartHeight=this.height+this.options.margin.top+this.options.margin.bottom;
this.$el.css("height",this.chartHeight+"px");}if(this.options.barWidth!==null&&b.notFalsy(this.data)){this.width=(this.data.length*this.options.barWidth);
this.chartWidth=this.width+this.options.margin.left+this.options.margin.right;this.$el.css("width",this.chartWidth+"px");
}this.topSVG.attr("width",this.chartWidth+"px").attr("height",this.chartHeight+"px");this.showCharts();this.update();return this;
};o.update=function(){this.calibrateScales();this.renderXAxis();this.renderYAxis();this.setBandSizes();if(this.isBarChart){this.barUtils.chartWidth=this.width;
this.barUtils.chartHeight=this.height;if(this.options.variation===e.VERTICAL){if(this.dimensionsXArray.length===1||!this.hasXAxis){this.barPositioningFn=this.barUtils.barPosition(this.options.centerBars,this.bandSize,this.getXScale(),this.options.xAttr);
}}else{if(this.dimensionsYArray.length===1||!this.hasYAxis){this.barPositioningFn=this.barUtils.barPosition(this.options.centerBars,this.bandSize,this.getYScale(),this.options.yAttr);
}}}this.renderData();};o.createDimensionStorageObjects=function(u){var t=true,s=true;if(u){if(u.indexOf("x")===-1){t=false;
}if(u.indexOf("y")===-1){s=false;}}if(t){this.dimensionsXArray=[];this.xScaleCreationFns={};this.xAxisCreationFns={};this.calibrateXScaleFns={};
this.formatXAxisFns={};this.renderXAxisFns={};this.xAxesHolders={};}if(s){this.dimensionsYArray=[];this.yScaleCreationFns={};
this.yAxisCreationFns={};this.calibrateYScaleFns={};this.formatYAxisFns={};this.renderYAxisFns={};this.yAxesHolders={};}};
o.setScales=function(){this.scales={};this.setXScale();this.setYScale();};o.calibrateScales=function(){this.calibrateXScale();
this.calibrateYScale();};o.setAxes=function(){this.axes={};this.setXAxis();this.setYAxis();};o.setXScale=function(){this.callFunctionsByKey(this.dimensionsXArray,this.xScaleCreationFns);
};o.setYScale=function(){this.callFunctionsByKey(this.dimensionsYArray,this.yScaleCreationFns);};o.setXAxis=function(){this.callFunctionsByKey(this.dimensionsXArray,this.xAxisCreationFns);
};o.setYAxis=function(){this.callFunctionsByKey(this.dimensionsYArray,this.yAxisCreationFns);};o.formatXAxis=function(){this.callFunctionsByKey(this.dimensionsXArray,this.formatXAxisFns);
};o.formatYAxis=function(){this.callFunctionsByKey(this.dimensionsYArray,this.formatYAxisFns);};o.calibrateXScale=function(){this.callFunctionsByKey(this.dimensionsXArray,this.calibrateXScaleFns);
};o.calibrateYScale=function(){this.callFunctionsByKey(this.dimensionsYArray,this.calibrateYScaleFns);};o.renderXAxis=function(){this.formatXAxis();
this.callFunctionsByKey(this.dimensionsXArray,this.renderXAxisFns);};o.renderYAxis=function(){this.formatYAxis();this.callFunctionsByKey(this.dimensionsYArray,this.renderYAxisFns);
if(this.options.suffixLastYTickOnly){c.lastTickFormat(this,this.options.yAxisIsPercent);setTimeout(function(){c.lastTickFormat(o,o.options.yAxisIsPercent);
},o.renderTickDelay);}};o.callFunctionsByKey=function(t,s){i.each(t,function(u){s[u].apply(o);});};o.getXScale=function(){return this.scales[this.options.xAttr]||null;
};o.getYScale=function(){return this.scales[this.options.yAttr]||null;};o.showCharts=function(){this.$el.find(".no-data-text").remove();
var s=this.$el.children().not(".no-data-text");s.each(function(){var t=d(this)[0].className.baseVal;if(t&&t.indexOf(o.chartType)>-1){d(this).show();
}});};o.createOptions=function(s){i.assign(this.options,s);};o.reset=function(){this.$el.width(this.options.width);this.$el.height(this.options.height);
var u=this.options.margin;this.width=this.$el.width()-(u.left+u.right);this.height=this.$el.height()-(u.top+u.bottom);this.mainGroup.attr("transform","translate("+u.left+","+u.top+")");
var w=this.options.xAttr;this.options.xAttr=this.dimensionsXArray[0];var v=this.axisGroup.select(".x.axis."+w).attr("class",("x axis "+this.options.xAttr)).attr("opacity",0.000001).attr("transform","translate(0,0)");
o.xAxesHolders[this.options.xAttr]=v;var t=this.options.yAttr;this.options.yAttr=this.dimensionsYArray[0];var s=this.axisGroup.select(".y.axis."+t).attr("class",("y axis "+this.options.yAttr)).attr("opacity",0.000001);
o.yAxesHolders[this.options.yAttr]=s;this.setScales();this.setAxes();};return o;};return j;});