define("chart/widgetFramework/core/drivers/baseView",["jquery","underscore","d3","chart/widgetFramework/core/drivers/tooltipCode","util/Functional"],function(f,b,d,e,c){var a=function(k,h){var l={joinAttr:null,barPadding:0,margin:{top:0,right:0,bottom:0,left:0},xAttr:"x",xScale:"linear",yAttr:"y",yScale:"linear",textAnchor:"start"};
var m=500;var i=50;var j={};j.el=h;e(j);j.init=function(){b.bindAll(this,"render");this.options=b.defaults(k,l);this.$el=f(this.el);
this.id=this.options.type;if(!this.options.outerPadding){this.options.outerPadding=this.options.barPadding;}var p=this.options.margin;
if(b.keys(p).length===0){this.options.margin={top:0,right:0,bottom:0,left:0};}this.htmlObjects=(this.options.templateStyle==="html")?true:false;
var n=c.getValueOrDefault(this.options,m,"width");this.$el.width(n);var o=c.getValueOrDefault(this.options,i,"height");this.$el.height(o);
};j.feedData=function(n){var o;this.rawData=n;if(b.has(this.options,"dataSubset")){o=g(n,this.options.dataSubset);}else{o=g(n);
}this.data=o.chartData;this.extraData=o.extraData||{};this.configData=o.config||{};if(!c.existy(this.data)){this.hideCharts("no data to display");
return;}return o;};j.setBandSizes=function(){};j.initRender=function(){var n=(this.chartType)?"chartbase-svg "+this.chartType+" "+this.$el.attr("id"):"chartbase-svg "+this.$el.attr("id");
var o=this.options.margin;this.width=this.$el.width()-(o.left+o.right);this.height=this.$el.height()-(o.top+o.bottom);if(this.htmlObjects){this.topSVG=this.topSVG||d.select(this.el).append("div").attr("class","chartbase-svg");
this.mainGroup=this.mainGroup||this.topSVG.append("div").attr("class","main-group").style("transform","translate("+o.left+"px,"+o.top+"px)");
this.chartGroup=this.mainGroup.append("div").attr("class","chart-elements-holder");}else{this.topSVG=this.topSVG||d.select(this.el).append("svg").attr("class",n);
this.mainGroup=this.mainGroup||this.topSVG.append("g").attr("class","main-group").attr("transform","translate("+o.left+","+o.top+")");
this.chartGroup=this.mainGroup.append("g").attr("class","chart-elements-holder");}};j.render=function(){this.chartHeight=this.$el.height();
this.chartWidth=this.$el.width();if(this.htmlObjects){this.topSVG.style("width",this.chartWidth+"px").style("height",this.chartHeight+"px");
}else{this.topSVG.attr("width",this.chartWidth+"px").attr("height",this.chartHeight+"px");}this.showCharts();this.update();
return this;};j.update=function(){this.setBandSizes();this.renderData();};j.renderData=function(){if(!c.existy(this.data)){return;
}};j.hideCharts=function(n){this.$el.find(".no-data-text").remove();var p=c.existy(n)?n:"no data to display";var r=this.height/2;
var q=this.width/2;var o=f('<div class="no-data-text"><text style="color: #ccc; font-size: 14px; position: relative; top:'+r+"px; left:"+q+'px;">'+p+"</text></div>");
this.$el.not(this.$el.has(".no-data-text")).prepend(o);this.$el.children().not(".no-data-text").hide();o.show();};j.showCharts=function(){this.$el.find(".no-data-text").remove();
this.$el.children().not(".no-data-text").show();};j.getData=function(){return function(){return j.data;};};j.getPrimaryDataJoin=function(){var n=this.options.joinAttr;
return this.getDataJoin(n);};j.getDataJoin=function(n){return function(p,o){if(n&&b(p).has(n)){return p[n];}else{return o;
}};};j.getXAttrVal=function(n){return this._getDatumValue(n,this.options.xAttr);};j.getYAttrVal=function(n){return this._getDatumValue(n,this.options.yAttr);
};j._getDatumValue=function(o,n){return o?o[n]:null;};var g=function(p,q){var o=b.cloneDeep(p);var n={};if(o.config){n.config=o.config;
}if(o.chartData){n.chartData=(q)?o.chartData[q]:o.chartData;}if(o.extraData){n.extraData=o.extraData;}if(b.keys(n)){return n;
}return(q)?o[q]:o;};return j;};return a;});