define("timeline/views/ui/calendarUI_v7",["jquery","underscore","backbone","timeline/events/timelineEvents","timeline/util/timelineConstants","calendar/datepicker","chartlib/chartBaseEvents","chartutil/dateUtils_CET","util/Analytics"],function(b,i,h,j,d,c,e,a,g){var f=h.View.extend({el:"#calendarUI",useLatestDay:false,formatPeriod:null,initialize:function(){this._super(arguments);
i.bindAll(this,"setCalendar","checkDate","clearErrors","setCalendarForHoursOrMinutes","submitDates");h.on(j.SET_CALENDAR,this.setCalendar);
h.on(j.TIMESPAN_SET_UTC,this.setCalendarForHoursOrMinutes);h.on(j.TIMESPAN_SET,this.clearErrors,this);if(this.collection&&this.collection.getValue("timeCollectionMode")===d.__LATEST){this.useLatestDay=true;
}this.uid=this.collection.getValue("uid");this.$el.css("display","block");this.startDate=b("#datepickStart");this.endDate=b("#datepickEnd");
this.dpStartElement=this.startDate;this.dpEndElement=this.endDate;this.dpStartIcon=b("#datepickStart-icon");this.dpEndIcon=b("#datepickEnd-icon");
var k=b("#checkMessage")[0];this.dpStart=new c(this.dpStartElement[0],{dateFormat:"Y-m-d",useToday:this.useLatestDay,linkedToTimeline:true},k,this.dpStartIcon[0]);
this.dpEnd=new c(this.dpEndElement[0],{dateFormat:"Y-m-d",useToday:this.useLatestDay,linkedToTimeline:false},k,this.dpEndIcon[0]);
this.startDate.on("change",{datepicker:this.dpStart},this.checkDate);this.endDate.on("change",{datepicker:this.dpEnd},this.checkDate);
},setCalendar:function(){this.dpStartIcon.css("visibility","visible");this.dpEndIcon.css("visibility","visible");this.dpStartElement.prop("readonly",0);
this.dpEndElement.prop("readonly",0);this.dpStartElement.css("color","#444");this.dpEndElement.css("color","#444");var m=this.collection.getValue("extent");
var o=1;if((m[0].getFullYear()===m[1].getFullYear())&&(m[0].getMonth()===m[1].getMonth())&&m[0].getDate()===m[1].getDate()){o=0;
}var k=new Date(m[1].getFullYear(),m[1].getMonth(),m[1].getDate()-o);var n=m[0].toFormattedString();var l=k.toFormattedString();
this.startDate.val(n);this.endDate.val(l);this.dpStart.updateMonth(m[0].getMonth(),m[0].getFullYear());this.dpEnd.updateMonth(k.getMonth(),k.getFullYear());
},setCalendarForHoursOrMinutes:function(){this.clearErrors();var m=this.collection.getValue("formatPeriod");if(m===d.__HOUR_FORMAT||m===d.__MINUTE_FORMAT){this.dpStartIcon.css("visibility","hidden");
this.dpEndIcon.css("visibility","hidden");this.dpStartElement.prop("readonly",1);this.dpEndElement.prop("readonly",1);this.dpStartElement.css("color","#aaa");
this.dpEndElement.css("color","#aaa");}var l=this.collection.getValue("extentAMS");var k=a.formatPseudoDate(l[0],d.__FORMAT_DATE_PSEUDO);
var n=a.formatPseudoDate(l[1],d.__FORMAT_DATE_PSEUDO);this.startDate.val(k);this.endDate.val(n);},checkDate:function(m){var l=m.data.datepicker;
var k={};k.data={startDate:this.startDate[0],endDate:this.endDate[0],callback:this.submitDates,useToday:this.useLatestDay,granularity:this.collection.getValue("formatPeriod")};
l.checkDate(k);},submitDates:function(l,k){l=l.replace(/\//g,"-");k=k.replace(/\//g,"-");g.trackEvent("Timeline_"+this.uid,"timeline.event.calendar");
h.trigger(j.CALENDAR_SET,l,k);},clearErrors:function(){this.dpStart.clearMessage();this.dpEnd.clearMessage();}});return f;
});