define("chart/widgetFramework/core/DataFetcher",["jqueryExtended","underscore","chart/widgetFramework/core/drivers/observableCode","chart/widgetFramework/core/Dataset","chart/widgetFramework/core/constants/DataConstants","chart/widgetFramework/core/constants/UIConstants","chartutil/domUtils"],function(a,n,b,e,i,l,k){var d=false;
var m="color:dodgerblue;font-size:1em";var c=false;var g="color:darkolivegreen;font-size:1em";var h=false;var j="color:darkorange;font-size:1em";
var f=false;var o=function(p){a("#devl-switch-button").parent().hide();a("#devl-container").hide();var s={};b(s,"fetcher");
s.init=function(){this.$el=p.getNode();this.id=this.$el.attr("id");var u=this.$el.attr("name");this.parameters=this.getParameters(p);
if(this.parameters.options){var v=n.keys(this.parameters.options);n.each(v,function(x){if(x.toLowerCase().indexOf("hash")>-1){s.parameters.options[x]=adyen[s.parameters.options[x]];
}});}if(this.parameters.options){this.parameters.options.cb=new Date().getTime();}var w=this.createDataset(this.parameters);
this.datasetObject={name:u,dataset:w,container:this.$el};k.removeDataAtrributes(this.$el,["options"]);};s.onDataLoaded=function(v,u){this.setProperty("changeObject",{type:i.NEW_DATA_AVAILABLE,data:u});
};s.getParameters=function(u){var x=u.getNode().data();var v;if(n.keys(x).length){v=x;}else{u.parameters.listensTo=a.parseJSON(u.parameters.listensTo);
u.parameters.options=a.parseJSON(u.parameters.options);v=u.parameters;}var w={};if(n.keys(v).length){w.src=v.src;w.listensTo=v.listensTo;
w.options=v.options;if(n.has(w.options,"granularity")){this.startGranularity=w.options.granularity;}else{if(n.has(w.options,"period")){this.startGranularity=w.options.period;
}}w.service=v.service;}else{throw"The parameters are not well defined"+v;}return w;};s.setData=function(u){if(window.console&&console.log&&d){console.log("%c\n################",g);
console.log("%c### START STAGE :: DataFetcher::setData  ::"+this.id+":: DEFERRED RESOLVED",g);console.log("%c################",g);
}this.data=u;this.onDataLoaded(null,u);};s.getData=function(){return this.data;};s.createDataset=function(v){if(v.service){return{fetchData:function(y){var x=new a.Deferred();
require([v.service],function(z){z.fetchData(v.options).then(function(A){x.resolve(A);},function(A){x.reject(A);});},function(){if(window.console&&console.warn){console.warn("DataFetcher:: Error loading dataService '"+v.service+"'",arguments);
}});return x.promise();}};}var u=adyen.config[v.src];if(typeof u==="undefined"){u=v.src;}var w=new e(u,this);return w;};s.getInstance=function(){return this;
};s.onPassThruData=function(u){this.setData(u);};s.onTimeData=function(w,x,v){var u;if(this.parameters.options){u=q(this.parameters.options,[w]);
}setTimeout(function(){r(u,v,s.datasetObject);},10);};s.fetchNewDataAction=function(){t(arguments[0],arguments[2]);};s.widgetAppStartup=function(x,u,w){var v=x||this.parameters.options;
this.basicDataFetch(v,u,w);};s.basicDataFetch=function(w,u,v){r(w,v,u);};var q=function(x,u){var v=u;v=n.flatten(v);var w=n.keys(x);
n.each(w,function(y){if(y.toLowerCase().indexOf("startdate")>-1||y.toLowerCase().indexOf("bdate")>-1){x[y]=v[0];}if(y.toLowerCase().indexOf("enddate")>-1||y.toLowerCase().indexOf("edate")>-1){x[y]=v[1];
}if(y.toLowerCase().indexOf("granularity")>-1||y.toLowerCase().indexOf("period")>-1){if(s.startGranularity===null){x[y]=v[2];
}}});return x;};var t=function(y,u,w){var x=s.parameters.options;var v=n.assign(x,y);r(v,u,w);};var r=function(v,u,w){if(window.console&&console.log&&d){console.log("### DataFetcher:: "+s.id+" fetchData (type: "+u+" ):: pParams=",v);
}s.datasetObject.dataset.fetchData(v).then(function(x){s.$el.trigger(i.FETCH_DATA_SUCCESS);s.setData(x);},function(z,x,y){s.$el.trigger(i.FETCH_DATA_ERROR,{error:x,exception:y});
if(window.console&&console.log){console.log("### DataFetcher:: "+s.id+" DATA LOAD (type: "+u+" ) ERROR!:: ",arguments);}});
};s.init();if(window.console&&console.log&&f){console.log("\n### DatFetcher2::constructor:: calling pWidgetApi.ready()");
}p.ready();return s;};return o;});