Date.prototype.getWeek=function(e){var d=(typeof e!=="undefined")?e:false;var a=new Date(this.getTime());a.setHours(0,0,0,0);
a.setDate(a.getDate()+1);a.setDate(a.getDate()+3-(a.getDay()+6)%7);var c=new Date(a.getFullYear(),0,4);var b=1+Math.round(((a.getTime()-c.getTime())/86400000-3+(c.getDay()+6)%7)/7);
if(d){b=Date.padded2(b);}return b;};Date.padded2=function(a){var b=parseInt(a,10);if(a<10){b="0"+b;}return b;};Date.prototype.getPaddedMinutes=function(){return Date.padded2(this.getMinutes());
};Date.prototype.toFormattedString=function(b){var a;var c=this.getFullYear()+"-"+Date.padded2(this.getMonth()+1)+"-"+Date.padded2(this.getDate());
if(b){a=Date.padded2(this.getHours());c+=" "+a+":"+this.getPaddedMinutes();}return c;};Date.prototype.toFormattedTimeString=function(b){var a;
var c=this.getFullYear()+"-"+Date.padded2(this.getMonth()+1)+"-"+Date.padded2(this.getDate());a=Date.padded2(this.getHours());
c+="T"+a+":"+this.getPaddedMinutes();c+=":00";if(b){c+=".000Z";}return c;};Date.parseFormattedString=function(b){var c="([0-9]{4})(-([0-9]{1,2})(-([0-9]{1,2})( ([0-9]{1,2}):([0-9]{2})?)?)?)?";
var f=b.match(new RegExp(c,"i"));if(f===null){return Date.parse(b);}var e=0;var a=new Date(f[1],0,1);if(f[3]){a.setMonth(f[3]-1);
}if(f[5]){a.setDate(f[5]);}if(f[7]){a.setHours(f[7]);}if(f[8]){a.setMinutes(f[8]);}if(f[0]){a.setSeconds(f[0]);}if(f[2]){a.setMilliseconds(Number("0."+f[2]));
}if(f[4]){e=(Number(f[6]))+Number(f[8]);e=((f[5]=="-")?1:-1);}return a;};define("chartutil/dateUtils_CET",["jquery","d3","underscore"],function(f,d,c){var b=60000;
var h=3600000;var e=86400000;var a=e*7;var g={};g.__DAYS_SHORT=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];g.__MONTHS_SHORT=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
g.__FWD="fwd";g.__BACK="back";g.getNumDays=function(k,j){if(typeof k==="undefined"||typeof j==="undefined"){console.error("DATE NOT SPECIFIED in getNumDays()");
}var i=(k-j)/e;return(i<0)?i*-1:i;};g.getDSTAdjustment=function(k,j){var m=k.getTimezoneOffset();var l=j.getTimezoneOffset();
var i=0;if(k>j){i=(l-m);}else{i=(m-l);}return i;};g.getNumHours=function(l,j){if(typeof l==="undefined"||typeof j==="undefined"){console.error("DATE NOT SPECIFIED in getNumHours()");
}var i=g.getDSTAdjustment(l,j);var k=(l-j)/h;return(k<0)?(k*-1)+i:k+i;};g.getNumMinutes=function(k,j,m){if(typeof k==="undefined"||typeof j==="undefined"){console.error("DATE NOT SPECIFIED in getNumMinutes()");
}var i=(m===true)?0:g.getDSTAdjustment(k,j);var l=(k-j)/b;return(l<0)?(l*-1)+i:l+i;};g.getDateOfISOWeek=function(i,j,k){var m=new Date(j,0,1),l=m.getTimezoneOffset();
if(k&&window.console&&console.log){console.log("### dateUtils_CET::getDateOfISOWeek:: d=",m);}m.setDate(m.getDate()+4-(m.getDay()||7));
m.setTime(m.getTime()+a*(i+(j===m.getFullYear()?-1:0)));m.setTime(m.getTime()+(m.getTimezoneOffset()-l)*60*1000);m.setDate(m.getDate()-4);
if(k&&window.console&&window.console.log){window.console.log("### dateUtils_CET::getDateOfISOWeek:: week:",i," =",m);}return m;
};g.roundToMinute=function(j,k){var i=(typeof k!=="undefined")?k:false;var l=d.time.minute.floor(j);return l;};g.roundToHour=function(i,j){var k=d.time.hour.floor(i);
return k;};g.roundToDay=function(j,k){var i=(typeof k!=="undefined")?k:false;var m=j.getHours();var l=j;if(i){l=new Date(j.getFullYear(),j.getMonth(),j.getDate(),j.getHours()-m);
}else{l.setHours(l.getHours()-m);}return l;};g.trueRoundToDay=function(j,k){var i=(typeof k!=="undefined")?k:false;var l;
if(j.getHours()>=12){if(i){l=new Date(d.time.day.ceil(j));}else{l=d.time.day.ceil(j);}}else{if(i){l=new Date(d.time.day.floor(j));
}else{l=d.time.day.floor(j);}}return l;};g.roundToWeek=function(k,l,j){var n=(typeof j!=="undefined"&&typeof j==="number")?j:0;
var i=(typeof l!=="undefined")?l:false;var o=k.getDay();var m=k;if(i){m=new Date(k.getFullYear(),k.getMonth(),k.getDate()-(o-n));
}else{m.setDate(m.getDate()-(o-n));}return m;};g.trueRoundToWeek=function(k,l,j){var n=(typeof j!=="undefined"&&typeof j==="number")?j:0;
var i=(typeof l!=="undefined")?l:false;var o=k.getDay();var m=k;if(o<3){if(i){m=new Date(k.getFullYear(),k.getMonth(),k.getDate()-(o-n));
}else{m.setDate(m.getDate()-(o-n));}}else{if(i){m=new Date(k.getFullYear(),k.getMonth(),k.getDate()+(7-(o-n)));}else{m.setDate(m.getDate()+(7-(o-n)));
}}return m;};g.roundToMonth=function(j,k){var i=(typeof k!=="undefined")?k:false;var m=j.getDate()-1;var l=j;if(i){l=new Date(j.getFullYear(),j.getMonth(),j.getDate()-m);
}else{l.setDate(l.getDate()-m);}return l;};g.convertToUTC=function(i){return new Date(g.viewAsUTC(i));};g.viewAsUTC=function(i){return i.toUTCString();
};g.convertToUTC2=function(k){var j=k.toUTCString();var l=j.split(" ");var i=l[4].split(":");return new Date(l[3],c.indexOf(g.__MONTHS_SHORT,l[2]),l[1],i[0],i[1],i[2]);
};g.convertToOffset=function(i,l){var j=g.convertToUTC(i);var k=l*60*1000;j.setTime(j.getTime()+k);return j;};g.adjustTime=function(j,l){var k=j.getTime();
var i=new Date();i.setTime(k+l);return i;};g.getSummerDSTDate=function(i){var j=Math.ceil(31-((((5*i.getFullYear())/4)+4)%7));
return j;};g.getAmsterdamDSTSummerBoundary=function(j){var k=Math.ceil(31-((((5*j.getFullYear())/4)+4)%7));var i=Date.UTC(j.getFullYear(),2,k,1,0);
return i;};g.getWinterDSTDate=function(j){var i=Math.ceil(31-((((5*j.getFullYear())/4)+1)%7));return i;};g.getAmsterdamDSTWinterBoundary=function(j){var k=Math.ceil(31-((((5*j.getFullYear())/4)+1)%7));
var i=Date.UTC(j.getFullYear(),9,k,1,0);return i;};g.isWinterDSTBoundary=function(i,j){var k=g.getWinterDSTDate(i);if(window.console&&window.console.log&&j){window.console.log("\n### DETECTING WINTER DST BOUNDARY dstDate=",k);
window.console.log("### DETECTING DST BOUNDARY startDate.getUTCMonth()=",i.getUTCMonth());window.console.log("### DETECTING DST BOUNDARY startDate.getUTCDate()=",i.getUTCDate());
window.console.log("### DETECTING DST BOUNDARY startDate.getUTCHours()=",i.getUTCHours());}if(i.getUTCMonth()===9&&i.getUTCDate()===k&&i.getUTCHours()===0){if(window.console&&window.console.log&&j){window.console.log("### DETECTED WINTER DST BOUNDARY DATE!!!!!!!!\n");
}return true;}else{if(window.console&&window.console.log&&j){window.console.log("### NOT A BOUNDARY DATE!!!!!!!!\n");}return false;
}};g.isSummerDSTBoundary=function(i,j){var k=g.getSummerDSTDate(i);if(window.console&&window.console.log&&j){window.console.log("\n### DETECTING SUMMER DST BOUNDARY dstDate=",k);
window.console.log("### DETECTING DST BOUNDARY startDate.getUTCMonth()=",i.getUTCMonth());window.console.log("### DETECTING DST BOUNDARY startDate.getUTCDate()=",i.getUTCDate());
window.console.log("### DETECTING DST BOUNDARY startDate.getUTCHours()=",i.getUTCHours());}if(i.getUTCMonth()===2&&i.getUTCDate()===k&&i.getUTCHours()===0){if(window.console&&window.console.log&&j){window.console.log("### DETECTED SUMMER DST BOUNDARY DATE!!!!!!!!\n");
}return true;}else{if(window.console&&window.console.log&&j){window.console.log("### NOT A BOUNDARY DATE!!!!!!!!\n");}return false;
}};g.sameTzOffset=function(k,j,l){var i=k.getTimezoneOffset();var m=j.getTimezoneOffset();if(window.console&&window.console.log&&l){window.console.log("\n### sameTzOffset::startTz=",i);
window.console.log("### sameTzOffset::endTz=",m,"\n");}if(i===m){return true;}return false;};g.getTzOffsetDiff=function(k,j,l){var i=k.getTimezoneOffset();
var n=j.getTimezoneOffset();var m=n-i;if(window.console&&window.console.log&&l){window.console.log("\n### DateUtils::getTzOffsetDiff::startTz=",i);
window.console.log("### DateUtils::getTzOffsetDiff::endTz=",n);window.console.log("### DateUtils::getTzOffsetDiff::diff=",m,"\n");
}return m;};g.convertDateToAMS=function(i){var k=g.getAmsterdamDSTOffsetTime(i,true);var j=g.timezoneShiftDate(i,g.__BACK,k,"startDate",0,0);
return j;};g.getAmsterdamDSTOffset=function(k,m,l){var j=g.getAmsterdamDSTSummerBoundary(k);var i=g.getAmsterdamDSTWinterBoundary(k);
if(k.getTime()>j&&k.getTime()<i){return 120;}return 60;};g.getAmsterdamDSTOffset_minusTZ=function(k,m){if(window.console&&window.console.log&&m){window.console.log("###");
window.console.log("### getAmsterdamDSTOffset_minusTZ:: date =",k);window.console.log("### utc str=",k.toUTCString());}var j=g.getAmsterdamDSTSummerBoundary(k);
var i=g.getAmsterdamDSTWinterBoundary(k);var l=k.getTime();if(window.console&&window.console.log&&m){window.console.log("### orig millis = ",l);
window.console.log("### utc millis = ",(l+(k.getTimezoneOffset()*60000)));}l=l-(k.getTimezoneOffset()*60000);if(window.console&&window.console.log&&m){window.console.log("### final millis = ",l);
window.console.log("### millis as date = ",new Date(l));window.console.log("### millis as utc date = ",new Date(l).toUTCString());
window.console.log("### summerTime = ",j);window.console.log("### winterTime = ",i);window.console.log("### end getAmsterdamDSTOffset_minusTZ");
}if(l>j&&l<i){return -120;}return -60;};g.getAmsterdamDSTOffsetTime=function(p,i,k){if(window.console&&window.console.log&&k){window.console.log("\n\n### getAmsterdamDSTOffsetTime:: date =",p);
window.console.log("### utc str=",p.toUTCString());}var o=(typeof i!=="undefined")?i:false;var q=g.getAmsterdamDSTSummerBoundary(p);
var l=g.getAmsterdamDSTWinterBoundary(p);var m=p.getTime();var n=m+(p.getTimezoneOffset()*60000);if(window.console&&window.console.log&&k){window.console.log("### utcMillis   = ",n);
window.console.log("### localMillis = ",m);}var j=n;if(o===true){j=m;}if(window.console&&window.console.log&&k){window.console.log("### compareMillis as date = ",new Date(j).toUTCString());
window.console.log("### end getAmsterdamDSTOffsetTime\n");}if(j>=q&&j<l){return -120;}return -60;};g.assessDates=function(k,r,l){var m=g.getAmsterdamDSTOffsetTime(k,true);
var j=g.getAmsterdamDSTOffsetTime(r,true);var n=j-m;if(window.console&&window.console.log&&l){window.console.log("\n###----------------------------");
window.console.log("### DateUtils.assessDates pStartDate=",k," ***");window.console.log("### DateUtils.assessDates pEndDate  =",r," ***");
window.console.log("### DateUtils.assessDates startDstOffset (local)=",m);window.console.log("### DateUtils.assessDates endDstOffset (local)=",j);
window.console.log("### DateUtils.assessDates startDstOffset (utc)=",g.getAmsterdamDSTOffsetTime(k,false));window.console.log("### DateUtils.assessDates endDstOffset (utc)  =",g.getAmsterdamDSTOffsetTime(r,false));
window.console.log("### DateUtils.assessDates dstOffsetDiff  =",n);}var s=g.getTzOffsetDiff(k,r,l);var i=g.isSummerDSTBoundary(k,false);
var p=g.isWinterDSTBoundary(k,false);var q=Math.round(g.getNumMinutes(k,r));var o=Math.round(g.getNumMinutes(k,r,true));if(window.console&&window.console.log&&l){window.console.log("### DateUtils.assessDates pStartDate isSummerDST =",i);
window.console.log("### DateUtils.assessDates pStartDate isWinterDST =",p);window.console.log("### DateUtils.assessDates numMinutes diff      (with tz)    =",q);
window.console.log("### DateUtils.assessDates numMinutes diff (disregard tz)    =",o);window.console.log("###----------------------------\n");
}return{startDstOffset:m,endDstOffset:j,dstOffsetDiff:n,tzOffsetDiff:s,isSummerDST:i,isWinterDST:p,numMinutesTz:q,numMinutesNoTz:o};
};g.convertMinutesToUnit=function(k,i){var j;switch(i){case"month":j=k/60/24/7+" weeks";break;case"week":case"day":j=k/60/24+" days";
break;case"hour":j=k/60+" hours";break;case"minute":j=k+" minutes";break;}return j;};g.timezoneShiftDate=function(u,i,n,l,p,m){var t,r,k,j,o,s;
var q=(i===g.__FWD)?1:-1;t=u.getTimezoneOffset();r=t-n;r*=q;k=new Date(u.getTime());j=(k.getTime()+(k.getTimezoneOffset()*60000));
o=k.getTimezoneOffset();if(window.console&&window.console.log&&p<m){window.console.log("\n## timezoneShiftDate:: now=",k,"offset=",o);
window.console.log("### formatting ",l," date.utc=",u.toUTCString());}k.setTime(j-((k.getTimezoneOffset()+r)*60000));if(window.console&&window.console.log&&p<m){window.console.log("### now -1=",k,"offset=",k.getTimezoneOffset());
window.console.log("### re-assessed amsOffset = ",g.getAmsterdamDSTOffset_minusTZ(k));}if(k.getTimezoneOffset()!==o){s=k.getTimezoneOffset()-o;
s*=q;if(window.console&&window.console.log&&p<m){window.console.log("### -----------------------------------reappliedOffset=",s);
}j=(k.getTime()+(k.getTimezoneOffset()*60000));k.setTime(j-((k.getTimezoneOffset()-s)*60000));if(window.console&&window.console.log&&p<m){window.console.log("### nowagain=",k,"offset=",k.getTimezoneOffset());
}}if(window.console&&window.console.log&&p<m){window.console.log("### formatting localOffset=",t);window.console.log("### formatting amsOffset=",n);
window.console.log("### formatting applied offset=",r);window.console.log("### formatting direction=",q);window.console.log("### end timezoneShiftDate \n");
}return k;};g.timezoneShiftPseudoDate=function(n,x,i,j,o){if(window.console&&window.console.log&&o){window.console.log("\n### timezoneShiftPseudoDate:");
window.console.log(j," ### pDate=",n,"offset=",n.getTimezoneOffset());window.console.log(j," ### date utc = ",n.toUTCString());
window.console.log(j," ### pAmsOffset = ",x);window.console.log(j," ### pIsoOutput = ",i);}var k=g.getUTCValues(n,i);k.utcHours=parseInt(k.hours,10);
var q=parseInt(k.hours,10)-(x/60);if(q>23){q-=24;}q=Date.padded2(q);k.hours=q;var r=n.getTime()+(n.getTimezoneOffset()*60000);
var t=n.getTimezoneOffset()-x;var s=r-((n.getTimezoneOffset()-t)*60000);var l=new Date(s);var p=l.getFullYear();var u=l.getMonth();
var z=l.getDate();var w=g.__DAYS_SHORT[l.getDay()];var A=g.__MONTHS_SHORT[u];k.date=(k.date!==z)?z:k.date;if(k.month!==u){k.month=u;
if(i===true){k.month+=1;}}else{k.month=k.month;}k.year=(k.year!==p)?p:k.year;k.namedDay=(k.namedDay!==w)?w:k.namedDay;k.namedMonth=(k.namedMonth!==A)?A:k.namedMonth;
if(window.console&&window.console.log&&o){window.console.log(j," ### psDateObj=",k);window.console.log(j," ### amsDate=",l);
window.console.log(j," ### amsDate day,date,y= ",w," ",z," ",p);}var v=" ";var B=k.namedDay+v+k.namedMonth+v+k.date+v+k.year+v+k.hours+":"+k.minutes;
if(window.console&&window.console.log&&o){window.console.log(j," ### pseudoDateStr=",B);}return k;};g.getUTCValues=function(p,s){var l=(typeof s!=="undefined")?s:false;
var i=p.toUTCString();var r=i.split(" ");var o=p.getUTCMonth();if(l){o+=1;}var j=r[0];j=j.substring(0,j.length-1);var n=r[2];
var k=p.toString().split(" ");var m=k[5]+" "+k[6];var q={};q.year=p.getUTCFullYear();q.month=o;q.date=p.getUTCDate();q.hours=Date.padded2(p.getUTCHours());
q.minutes=Date.padded2(p.getUTCMinutes());q.seconds="00";q.namedDay=j;q.namedMonth=n;q.tz=m;return q;};g.formatPseudoDate=function(x,v){v=v+"";
var z="";var o=0;var s="";var k="";var t=x.year+"";var j=x.month;var p=x.namedMonth;var r=x.date;var i=x.namedDay;var w=x.hours;
var q=x.minutes;var n=x.seconds;var l=x.tz;var u={};u.y="'"+t.substring(2,4);u.yyyy=t;u.yy=t.substring(2,4);u.m=j;u.mm=Date.padded2(j);
u.N=p;u.d=r;u.dd=Date.padded2(r);u.D=i;u.H=w;u.M=q;u.S=n;u.T=l;while(o<v.length){s=v.charAt(o);k="";while((v.charAt(o)==s)&&(o<v.length)){k+=v.charAt(o++);
}if(u[k]!=null){z=z+u[k];}else{z=z+k;}}return z;};g.convertUTCTimestampToAMSDate=function(k){var j=new Date(k);var l=g.convertToUTC(j);
var i=g.getAmsterdamDSTOffset(l);j=g.convertToOffset(j,i);return j;};g.convertToAmsterdamTimezone=function(i){var l=moment(i);
var j=l.isDST();if(!j){l.add(1,"hour");}var k=moment.tz(l.format(),"Europe/Amsterdam");return moment(k).valueOf();};g.getUserFriendlyDate=function(o,n,m){var p="th",i,q,r;
var l=new Date(o);if(n){l.setDate(l.getDate()-1);}i=l.getDate();var k=m||"%B %e";r=d.time.format(k)(l);q=c.last(String(i));
if(q==="1"&&i!==11){p="st";}if(q==="2"&&i!==12){p="nd";}if(q==="3"&&i!==13){p="rd";}var j=r+p;return j;};return g;});