define("chart/widgetFramework/core/mixins/formats",["d3","jquery","chartutil/d3utils"],function(c,d,b){var a={};a.defaultNoOp=function(e){if(e==="getInfo"){return"returns unformatted value - useful for testing";
}return function(f){return f;};};a.defaultLinearFormat=function(e){if(e==="getInfo"){return"Adds SI Prefix to 1st tick. Compares tick to see if any have decimal values";
}return function(g,f){return b.thousandsFormatter(g,f,this.scales[e]);};};a.linearFormatSmartRounding=function(e){if(e==="getInfo"){return"0 < Ticks < 10 that have a form like 2.0 are rounded, other ticks are rounded to 2 significant digits";
}return function(g){var f=Math.abs(g);if(g%1===0&&f<10){return c.format(",.0f")(g);}else{if(f<1){return c.format(",.1r")(g);
}else{return c.format(",.2r")(g);}}};};a.linearFormatSmartRoundingSI=function(e){if(e==="getInfo"){return"Numbers rounded to 2 significant digits. SI suffix added";
}return function(h){var f=Math.abs(h);if(h%1===0&&f<10){return c.format(",.0f")(h);}else{if(f<1){return c.format(",.1r")(h);
}else{var g=Number(c.format(",.2r")(h).replace(/[,\.]/g,""));return b.numberFormatter(g);}}};};a.thousandsLinearFormat=function(e){if(e==="getInfo"){return"Adds SI Prefix to all ticks";
}return function(f){return b.numberFormatter(f);};};a.roundNumberFormat=function(e){if(e==="getInfo"){return"Rounds, no decimal places";
}return function(f){return c.format(".0f")(f);};};a.integerFormat=function(e){if(e==="getInfo"){return"Rounds, no decimal places";
}return function(f){return c.format(",d")(f);};};a.firstNumberOnlyFormat=function(e){if(e==="getInfo"){return"Only returns first value, unformatted. Other ticks are hidden";
}return function(g,f){return(f===0)?g:"";};};a.defaultPercentNoSymbol=function(e){if(e==="getInfo"){return"Value *= 100. Rounds result. No % symbol";
}return function(f){return Math.round(f*100);};};a.defaultPercentFormat=function(e){if(e==="getInfo"){return"Value *= 100. Suffix with '%'";
}return function(f){return c.format("%")(f);};};a.percentFormat=function(e){if(e==="getInfo"){return"Don't *= 100. Ticks to 1 decimal place with % symbol";
}return function(f){return c.format(".1f")(f)+"%";};};a.percentFormatSmartRounding=function(e){if(e==="getInfo"){return"Don't *= 100. 0 < Ticks < 10 that have a form like 2.0 are rounded, other ticks are rounded to 2 significant digits. With % symbol at the end";
}return function(g){var f=Math.abs(g);if(g%1===0&&f<10){return c.format(",.0f")(g)+"%";}else{if(f<1){return c.format(",.1r")(g)+"%";
}else{return c.format(",.2r")(g)+"%";}}};};a.percentFormatSmartRounding2=function(e){if(e==="getInfo"){return"Don't *= 100. Detects whole number or 1 dec place or 2 dec places. % symbol at the end";
}return function(j){var g=j%1;if(g===0){return c.format(",.0f")(j)+"%";}else{var h=g.toFixed(2);var i=h.indexOf(".");var f=h.substr(i+1);
if(f.charAt(1)==="0"){return c.format(",.1f")(j)+"%";}else{return c.format(",.2f")(j)+"%";}}};};a.percentFormat_2dec=function(e){if(e==="getInfo"){return"Don't *= 100. Ticks to 2 decimal places with % symbol";
}return function(f){return c.format(".2f")(f)+"%";};};a.firstPercentFormat=function(e){if(e==="getInfo"){return"Don't *= 100. Ticks to 1 decimal place. '%' only on 1st tick";
}return function(g,f){return(f>0)?g:c.format(".1f")(g)+"%";};};a.firstPercentOnlyFormat=function(e){if(e==="getInfo"){return"Don't *= 100. 1st tick to 1 decimal place with '%'. Other ticks hidden";
}return function(g,f){return(f===0)?c.format(".1f")(g)+"%":"";};};a.defaultTimeFormat=function(f,e){if(f==="getInfo"){return"Expects date. Return formatted day|week|month (%d|wk + num|%b)";
}return function(g){return b.constants.granularityFormatsNonUTC[e](g);};};a.timeSimple=function(e){if(e==="getInfo"){return"Returns tick index + 1";
}return function(g,f){return parseInt((f+1).toString());};};a.timeMonthFormat=function(e){if(e==="getInfo"){return"Show short month name";
}var f=c.time.format("%d");return function(g){return f(g);};};a.firstTimeFormatWidget=function(e){if(e==="getInfo"){return"Returns formatted date. First tick has extra info e.g. day + month";
}return function(k,f){var j=(this.configData&&this.configData.granularity)?this.configData.granularity:"day";var g=c.time.format("%d");
if(j==="week"||j==="monday"){return(f>0)?"wk "+k.getWeek(true):k.getFullYear()+" wk "+k.getWeek(true);}var h;if(f>0){h=(this.granularityFormats)?this.granularityFormats[j]:g;
}else{if(this.granularityFormats){h=(this.granularityFormats[j+"_start"])?this.granularityFormats[j+"_start"]:this.granularityFormats[j];
}else{h=g;}}return h(k);};};a.defaultOrdinalFormat=function(e){if(e==="getInfo"){return"Expects string: if more than 14 chars reduce to 11 & add '...'";
}return function(f){return(f.length>14)?d.trim(f).substring(0,11).trim(this)+"...":f;};};a.fullOrdinalFormat=function(e){if(e==="getInfo"){return"Expects string: Returns full, untruncated string";
}return function(f){return f;};};a.ordinalRemoveLabel=function(){return function(e){return(e.toLowerCase().indexOf(this.stripLabel)>-1)?"":e;
};};a.euroFormat=function(e){if(e==="getInfo"){return"Forces numbers to two decimal places. Adds euro symbol";}return function(f){return"\u20AC "+c.format(".2f")(f);
};};a.euroFormatSmartRounding=function(e){if(e==="getInfo"){return"Forces numbers to be rounded to 2 significant digits for better overall rounding (but round numbers between 0 and 9 are rounded). Adds euro symbol to front";
}return function(g){var f=Math.abs(g);if(g%1===0&&f<10){return"\u20AC "+c.format(",.0f")(g);}else{if(f<1){return"\u20AC "+c.format(",.1r")(g);
}else{return"\u20AC "+c.format(",.2r")(g);}}};};a.euroFormatSmartRoundingSI=function(e){if(e==="getInfo"){return"Numbers rounded to 2 significant digits. Adds euro symbol to front. SI suffix to rear";
}return function(h){var f=Math.abs(h);if(h%1===0&&f<10){return"\u20AC "+c.format(",.0f")(h);}else{if(f<1){return"\u20AC "+c.format(",.1r")(h);
}else{var g=Number(c.format(",.2r")(h).replace(/[,\.]/g,""));return"\u20AC "+b.numberFormatter(g);}}};};a.lastTickFormat=function(e,i,h){var g=[];
var f=6;e.dimensionsYArray.forEach(function(l){var k=e.yAxesHolders[l].selectAll("text");var j;k.each(function(p,n){var o=this.textContent.replace(/[^0-9\.]/gi,"");
var m=Number(o);if(h){m=c.format(h)(m);}g.push(m);if(n===(k[0].length-1)){j=c.select(this);}});if(i){b.smartPercentageFormat(e.yAxesHolders[l]);
}else{k.text(function(n,m){if(m<g.length-1){return g[m];}else{return this.textContent;}});}if(j){if(j.text().indexOf("k")>-1){f=3;
}if(j.text().indexOf("M")===-1&&j.text().indexOf("k")===-1&&j.text().indexOf("%")===-1){f=j.attr("x");}j.transition().duration(150).ease("linear").attr("x",f);
}});};return a;});