define("jqueryExtended",["jquery"],function(a){a.fn.findOne=a.fn.findOne||function(c){try{var g,f=0,d=this.length;while(f<d&&(g=this[f].querySelector(c))===null){f++;
}return a(g);}catch(h){return this.find(c).first();}};if(a.browser&&a.browser.msie&&parseInt(a.browser.version,10)<=8){a.fn.scrollDetached=function(c){return a(this).each(function(){var d=this;
clearInterval(this.detachedScrollInterval);this.detachedScrollInterval=setInterval(function(){if(d.hasScrolled){d.hasScrolled=false;
c();}},500);a(this).scroll(function(){d.hasScrolled=true;});});};}else{a.fn.scrollDetached=a.fn.scroll;}a.typeofDeep=a.typeofDeep||function b(d,e){var c;
e=e||window;if(typeof d!=="string"||typeof e!=="object"||e===null){return"undefined";}while((c=d.indexOf("."))>-1){var f=d.substring(0,c);
d=d.substring(c+1);if(typeof e[f]==="undefined"){return"undefined";}e=e[f];}return typeof e[d];};a.isUndefined=a.isUndefined||function(c,d){return a.typeofDeep(c,d)==="undefined";
};a.fn.removeTextNodes=function(){return a(this).contents().filter(function(){return this.nodeType===3;}).remove();};a.fn.scrollIntoView=function(){return this.each(function(){this.scrollIntoView();
});};a.fn.isAfter=function(c){return this.prevAll(c).length!==0;};a.fn.isBefore=function(c){return this.nextAll(c).length!==0;
};a.fn.getOrGenerateId=function(){var c=this[0];if(!c.id){a.fn.getOrGenerateId.counter=a.fn.getOrGenerateId.counter||0;var d="ca-node-",e=d+(++a.fn.getOrGenerateId.counter);
while(document.getElementById(e)){e=d+(++a.fn.getOrGenerateId.counter);}c.id=e;}return c.id;};a.fn.realWidth=function(){var d=a(this);
var e=d.clone();e.css("visibility","hidden");a("body").append(e);var c=e.width();e.remove();return c;};a.fn.realHeight=function(){var d=a(this);
var e=d.clone();e.css("visibility","hidden");a("body").append(e);var c=e.height();e.remove();return c;};a.fn.hideWithEvent=function(c){var e=a(this);
var d=e.css("display");e.hide();if(e.css("display")!==d){if(typeof c==="function"){c();}else{e.trigger.apply(e,arguments);
}}};a.fn.showWithEvent=function(c){var e=a(this);var d=e.css("display");e.show();if(e.css("display")!==d){if(typeof c==="function"){c();
}else{e.trigger.apply(e,arguments);}}};a.fn.loadEnriched=function(e,f,c){var d=a(this);if(typeof f==="function"){c=f;f=null;
}require(["Constants","util/Ajax"],function(g){d.ajaxLoad(e,f,function(i,j,h){if(typeof c==="function"){c(i,j,h);}d.trigger(g.EV_CONTENT_MERGED);
});});};a.fn.enrich=function(){require(["Constants"],function(c){a(this).trigger(c.EV_CONTENT_MERGED);});};a.fn.serializeObject=function(){var d={};
var c=this.serializeArray();a.each(c,function(){if(d[this.name]!==undefined){if(!d[this.name].push){d[this.name]=[d[this.name]];
}d[this.name].push(this.value||"");}else{d[this.name]=this.value||"";}});return d;};return a;});