define("chart/widgetFramework/core/mixins/widgetAxes",["d3","jquery","underscore","chartutil/d3utils","chart/widgetFramework/core/mixins/formats","util/Functional"],function(f,g,a,e,h,b){var d=function(i){if(i&&typeof h[i]==="function"){return true;
}return false;};var c={};c.getOrdinalXAxis=function(i,j){return c.getDefaultXAxis(i,j);};c.getLinearXAxis=function(i,j){return c.getDefaultXAxis(i,j);
};c.getTimeXAxis=function(i,j){return c.getDefaultXAxis(i,j);};c.getDefaultXAxis=function(i,j){return function(){var k=(j.drawTickToChartSize)?-this.height:0;
this.axes[i]=f.svg.axis().orient(j.align).tickSize(k);};};c.getFormatOrdinalXAxis=function(i,j){return function(){this.axes[i].tickFormat((d(j.tickFormat))?g.proxy(h[j.tickFormat](i),this):g.proxy(h.defaultOrdinalFormat(i),this));
};};c.getFormatLinearXAxis=function(i,j){return function(){this.axes[i].tickFormat((d(j.tickFormat))?g.proxy(h[j.tickFormat](i),this):g.proxy(h.defaultLinearFormat(i),this));
};};c.getFormatTimeXAxis=function(i,j){return function(){var k=(this.configData&&this.configData.granularity)?this.configData.granularity:"day";
this.axes[i].ticks(f.time[k],1).tickFormat((d(j.tickFormat))?g.proxy(h[j.tickFormat](i,k),this):g.proxy(h.defaultTimeFormat(i,k),this));
};};c.getRenderOrdinalXAxis=function(i,j){return c.getRenderDefaultXAxis(i,j);};c.getRenderLinearXAxis=function(i,j){return c.getRenderDefaultXAxis(i,j);
};c.getRenderTimeXAxis=function(i,j){return c.getRenderDefaultXAxis(i,j);};c.getRenderDefaultXAxis=function(i,j){return function(){var r=this;
var k=r.xAxesHolders[i];var n=r.scales[i];var m=r.axes[i];if(r.options.barHeight!==null&&j.drawTickToChartSize===true){m.tickSize(-r.height);
}if(b.existy(j.ticks)){m.ticks(j.ticks);}var s=(typeof j.axisTranTime!=="undefined")?j.axisTranTime:500;var q=j.axisDelayTime||0;
var l=(j.align==="bottom")?r.height:0;k.call(m.scale(n)).transition().duration(s).delay(q).ease("exp-in-out").attr("opacity",1).attr("transform","translate(0,"+l+")").each("start",function(){if(!j.allowTickOverlap){e.preventTickOverlap(this);
}});var p=0;if(b.notFalsy(j.tickTransform)){var o=j.tickTransform;if(j.centerTicks){p=o[1]||0;}else{if(b.existy(o[1])){p=o[1];
}k.selectAll(".tick").select("text").attr("transform",function(){return"translate("+o[0]+","+p+")";});}}if(j.centerTicks){e.spreadXAxisTicks(r,p,k);
}};};c.getOrdinalYAxis=function(i,j){return c.getDefaultYAxis(i,j);};c.getLinearYAxis=function(i,j){return c.getDefaultYAxis(i,j);
};c.getDefaultYAxis=function(i,j){return function(){var k=(j.drawTickToChartSize)?-this.width:0;this.axes[i]=f.svg.axis().orient(j.align).tickSize(k);
};};c.getFormatOrdinalYAxis=function(i,j){return function(){this.axes[i].tickFormat((d(j.tickFormat))?g.proxy(h[j.tickFormat](i),this):g.proxy(h.defaultOrdinalFormat(i),this));
};};c.getFormatLinearYAxis=function(i,j){return function(){this.axes[i].tickFormat((d(j.tickFormat))?g.proxy(h[j.tickFormat](i),this):g.proxy(h.defaultLinearFormat(i),this));
};};c.getRenderOrdinalYAxis=function(i,j){return c.getRenderDefaultYAxis(i,j);};c.getRenderLinearYAxis=function(i,j){return c.getRenderDefaultYAxis(i,j);
};c.getRenderDefaultYAxis=function(i,j){return function(){var r=this;var k=r.yAxesHolders[i];var m=r.scales[i];var l=r.axes[i];
if(r.options.barWidth!==null&&j.drawTickToChartSize===true){l.tickSize(-r.width);}if(b.existy(j.ticks)){l.ticks(j.ticks);
}var s=(typeof j.axisTranTime!=="undefined")?j.axisTranTime:500;var p=j.axisDelayTime||0;k.attr("transform",function(){var t=0;
if(j.align==="right"){t=r.width;}return"translate("+t+",0)";}).transition().duration(s).delay(p).ease("exp-in-out").attr("opacity",1).call(l.scale(m));
var q=0,o=0;if(!b.falsy(j.tickTransform)){var n=j.tickTransform;if(j.centerTicks){if(n.length===1){q=0;}else{q=n[0];}}else{if(n.length===1){q=0;
o=n[0];}else{q=n[0];o=n[1];}k.selectAll(".tick").select("text").attr("transform",function(){return"translate("+q+","+o+")";
});}}if(j.centerTicks){e.spreadYAxisTicks(r,q,k);}};};c.moveLinesToBack=function(){this.xAxis.selectAll("line").each(function(){if(typeof this.raphaelNode!=="undefined"){this.raphaelNode.toBack();
}});};return c;});