define("timeline/util/timelineControls_v7",["jquery","backbone","chartutil/dateUtils_CET","timeline/util/timelineConstants","timeline/events/timelineEvents","util/Analytics"],function(c,g,e,b,d,a){var f={};
f.jumpPeriod=function(i){var q,o;var p,l,n,r,m;var j=this.formatPeriod||this.collection.getValue("formatPeriod");var h=b.granularityDict[j];
switch(i){case b.__FWD:a.trackEvent("Timeline_"+this.uid,"timeline.event.next-period-forward");n=b.__FWD;q=this.getEndTimeline();
l=this.getEndTimeline();o=new Date(l);switch(j){case b.__MINUTE_FORMAT:o=e.adjustTime(o,+(60*b.__MSECS_PER_MINUTE));m=b.__THIS_MINUTE;
break;case b.__HOUR_FORMAT:o=e.adjustTime(o,+(48*b.__MSECS_PER_HOUR));m=b.__THIS_HOUR;break;case b.__DAY_FORMAT:o.setDate(o.getDate()+b.__JUMP_PERIOD_DAY);
m=b.__TODAY;break;case b.__WEEK_FORMAT:o.setDate(o.getDate()+b.__JUMP_PERIOD_WEEK);m=b.__THIS_WEEK;break;}if(o>m){o=m;}r=e.getNumMinutes(o,l,true);
break;case b.__START_EXTENT:q=(this.collection)?this.collection.getValue("extent")[0]:this.getExtent()[0];n=b.__START_EXTENT;
break;case b.__END_EXTENT:q=(this.collection)?this.collection.getValue("extent")[1]:this.getExtent()[1];q=e.adjustTime(q,-(b.__MSECS_PER_MINUTE));
n=b.__END_EXTENT;r=e.getNumMinutes(this.collection.getValue("extent")[0],this.collection.getValue("extent")[1],true);r-=1;
break;case b.__BACK:a.trackEvent("Timeline_"+this.uid,"timeline.event.next-period-back");n=b.__BACK;p=this.getStartTimeline();
q=new Date(p);switch(j){case b.__MINUTE_FORMAT:q=e.adjustTime(q,-(60*b.__MSECS_PER_MINUTE));break;case b.__HOUR_FORMAT:q=e.adjustTime(q,-(48*b.__MSECS_PER_HOUR));
break;case b.__DAY_FORMAT:q.setDate(q.getDate()-b.__JUMP_PERIOD_DAY);break;case b.__WEEK_FORMAT:q.setDate(q.getDate()-b.__JUMP_PERIOD_WEEK);
break;}if(q<b.__TWELVE_MONTHS_AGO){q=b.__TWELVE_MONTHS_AGO;}r=e.getNumMinutes(q,p,true);break;}var k=this;setTimeout(function(){r=Math.floor(r);
if(window.console&&window.console.log){window.console.log("### timelineControls_v7:: s0:: ",q);window.console.log("### timelineControls_v7:: changeAgent:: ",h);
window.console.log("### timelineControls_v7:: jumpAmt:: ",r);}k.reformatTimeline(-1,q,h,null,n,r);k.setExtent();var s=c("#timelineHolder");
s.removeClass("translateBack");s.removeClass("translateFwd");},250);};f.enableControls=function(){var h=false;var r=this.getStartTimeline();
var o=new Date(this.getEndTimeline());o.setTime(o.getTime()+1);var u=(this.collection)?this.collection.getValue("extent"):this.getExtent();
var t=u[0];var j=u[1];var l=b.__TWELVE_MONTHS_AGO,k;var i,p;var n=this.formatPeriod||this.collection.getValue("formatPeriod");
if(window.console&&window.console.log&&h){window.console.log("### timelineControls_v7::enableControls:: startExtent=",t);
window.console.log("### timelineControls_v7::enableControls:: endExtent=",j);window.console.log("### timelineControls_v7::enableControls:: formatPeriod=",n);
}switch(n){case b.__MINUTE_FORMAT:i=b.__THIS_MINUTE;p=new Date(i.getFullYear(),i.getMonth(),i.getDate(),i.getHours(),i.getMinutes()-1);
k=new Date(l.getFullYear(),l.getMonth(),l.getDate(),l.getHours(),l.getMinutes()+1);break;case b.__HOUR_FORMAT:i=b.__THIS_HOUR;
p=new Date(i.getFullYear(),i.getMonth(),i.getDate(),i.getHours()-1);k=new Date(l.getFullYear(),l.getMonth(),l.getDate(),l.getHours()+1);
break;case b.__DAY_FORMAT:i=b.__TODAY;p=new Date(i.getFullYear(),i.getMonth(),i.getDate()-1);if(this.hasMinStartDates){l=this.minStartDate_day;
}k=new Date(l.getFullYear(),l.getMonth(),l.getDate()+1);break;case b.__WEEK_FORMAT:i=b.__THIS_WEEK;p=new Date(i.getFullYear(),i.getMonth(),i.getDate()-7);
if(this.hasMinStartDates){l=this.minStartDate_week;}k=new Date(l.getFullYear(),l.getMonth(),l.getDate()+7);break;case b.__MONTH_FORMAT:i=b.__THIS_MONTH;
p=new Date(i.getFullYear(),i.getMonth()-1);k=new Date(l.getFullYear(),l.getMonth()+1);break;}if(window.console&&window.console.log&&h){window.console.log("### endTimeline=",this.getEndTimeline());
window.console.log("### endTimeline [as time]=",this.getEndTimeline().getTime());window.console.log("### endTimeline adj=",o);
window.console.log("### endTimeline adj [as time]=",o.getTime());window.console.log("### endExtent=",j);window.console.log("### now=",i);
window.console.log("### then=",l);}var m=false;var q=false;if(o<i){if(window.console&&window.console.log&&h){window.console.log("### enableControls:: endTimeline < now SO enable fwd button");
}g.trigger(d.ENABLE_CONTROLS,b.__FWD);}else{m=true;}if(r>l){if(window.console&&window.console.log&&h){window.console.log("### enableControls:: startTimeline > then SO enable back button");
}g.trigger(d.ENABLE_CONTROLS,b.__BACK);}else{q=true;}if(q){if(t<=r){if(window.console&&window.console.log&&h){window.console.log("### backBtnIsDisabled & startExtent = startTimeline");
}g.trigger(d.ENABLE_CONTROLS,b.__END_EXTENT);return;}}if(window.console&&window.console.log&&h){window.console.log("### fwdBtnIsDisabled=",m);
window.console.log("### enable backBtnIsDisabled=",q);}if(t<=r){if(window.console&&window.console.log&&h){window.console.log("### enable end extent btn ONLY");
}g.trigger(d.ENABLE_CONTROLS,b.__END_EXTENT);return;}if(window.console&&window.console.log&&h){window.console.log("### enable BOTH extent btns");
}g.trigger(d.ENABLE_CONTROLS,b.__START_EXTENT);g.trigger(d.ENABLE_CONTROLS,b.__END_EXTENT);};return f;});