define("timeline/util/timelineConstants",["jquery","chartutil/dateUtils_CET","util/Console"],function(e,d,c){var g,f,a,b,i;
var h={};h.isInited=false;h.__WEEK_STR="week";h.__MONDAY_STR="monday";h.__MAX_MINUTES=61;h.__MAX_HOURS=2940;h.__MAX_DAYS=46080;
h.__MAX_WEEKS=131040;h.__EXTENT_MINUTES_DEFAULT=30;h.__EXTENT_HOURS_DEFAULT_MIN=60;h.__EXTENT_HOURS_DEFAULT_MAX=1440;h.__EXTENT_DAYS_DEFAULT_MIN=2880;
h.__EXTENT_DAYS_DEFAULT_MAX=10080;h.__EXTENT_WEEKS_DEFAULT=40320;h.__EXTENT_MONTHS_DEFAULT=131040;h.__MINUTE_MODE_MAX_MINUTES=60;
h.__HOUR_MODE_MAX_HOURS=2880;h.__DAY_MODE_MAX_DAYS=44640;h.__WEEK_MODE_MAX_DAYS=120960;h.__MINUTE_MODE_SWITCH_POINT_MAX=61;
h.__HOUR_MODE_SWITCH_POINT_MIN=45;h.__HOUR_MODE_SWITCH_POINT_MAX=2910;h.__DAY_MODE_SWITCH_POINT_MIN=1000;h.__DAY_MODE_SWITCH_POINT_MAX=45372;
h.__WEEK_MODE_SWITCH_POINT_MIN=8640;h.__WEEK_MODE_SWITCH_POINT_MAX=126000;h.__MONTH_MODE_SWITCH_POINT_MIN=37440;h.__CALENDER_DAY_GRANULARITY=32;
h.__CALENDER_WEEK_GRANULARITY=85;h.__MSECS_PER_MINUTE=60000;h.__MSECS_PER_HOUR=3600000;h.__MSECS_PER_DAY=86400000;h.__MSECS_PER_WEEK=h.__MSECS_PER_DAY*7;
h.__MSECS_PER_MONTH=h.__MSECS_PER_DAY*30;h.__FORMAT_MINUTES="%H:%M";h.__FORMAT_HOURS="%d %b";h.__FORMAT_DAYS="%d %b '%y";
h.__FORMAT_WEEKS="%b %Y";h.__FORMAT_MONTHS="%Y";h.__FORMAT_DATE="%d %b %Y";h.__FORMAT_HOURS_PSEUDO="dd N";h.__FORMAT_MINUTES_PSEUDO="H:M";
h.__FORMAT_BLOCK_PSEUDO="H";h.__FORMAT_DATE_UTC="yyyy-mm-dd H:M:S";h.__FORMAT_DATE_PSEUDO="yyyy-mm-dd";h.__MINUTES_BTN="minutesBtn";
h.__HOURS_BTN="hoursBtn";h.__DAYS_BTN="daysBtn";h.__WEEKS_BTN="weeksBtn";h.__MONTHS_BTN="monthsBtn";h.__MINUTE_FORMAT="minute";
h.__HOUR_FORMAT="hour";h.__DAY_FORMAT="day";h.__WEEK_FORMAT="week";h.__MONTH_FORMAT="month";h.__MINUTE_GRANULARITY=1;h.__HOUR_GRANULARITY=2;
h.__DAY_GRANULARITY=3;h.__WEEK_GRANULARITY=4;h.__MONTH_GRANULARITY=5;h.__LAST_FULL="lastFull";h.__LATEST="latest";h.__LATEST_NOT_DAY="latestExceptAtDayGranularity";
h.__NOW="now";h.__FWD="fwd";h.__START_EXTENT="start";h.__END_EXTENT="end";h.__BACK="back";h.__THEN="then";h.__JUMP_PERIOD_DAY=31;
h.__JUMP_PERIOD_WEEK=7*12;h.granularityDict={};h.granularityDict[h.__MINUTE_FORMAT]=h.__MINUTE_GRANULARITY;h.granularityDict[h.__HOUR_FORMAT]=h.__HOUR_GRANULARITY;
h.granularityDict[h.__DAY_FORMAT]=h.__DAY_GRANULARITY;h.granularityDict[h.__WEEK_FORMAT]=h.__WEEK_GRANULARITY;h.granularityDict[h.__MONDAY_STR]=h.__WEEK_GRANULARITY;
h.granularityDict[h.__MONTH_FORMAT]=h.__MONTH_GRANULARITY;h.__ONE_OFF_ADJUST="oneOffAdjust";h.__FINALISE_TIMELINE="finaliseTimeline";
h.__CALCULATE_EXTENT="calculateExtent";h.__BRUSHMOVE="brushmove";h.__BRUSHEND="brushend";h.__JUMP_OUT="jumpOut";h.__PRESET_LAST_7_DAYS="last7Days";
h.__PRESET_LAST_30_DAYS="last30Days";h.__PRESET_LAST_4_WEEKS="last4Weeks";h.__PRESET_LAST_YEAR="lastYear";h.__PRESET_LAST_MONTH="lastMonth";
h.__PRESET_THIS_MINUTE="thisMinute";h.__PRESET_THIS_HOUR="thisHour";h.__PRESET_THIS_DAY="thisDay";h.__PRESET_THIS_WEEK="thisWeek";
h.init=function(k){var l=new Date();var p=l;var n,o,m,j,q;g=n=p.getFullYear();f=o=p.getMonth();a=m=p.getDate();b=j=p.getHours();
i=q=p.getMinutes();h.__THIS_HOUR=new Date(n,o,m,j);h.__TODAY=new Date(n,o,m);h.__TWELVE_MONTHS_AGO=new Date(n,o-12);h.__THIS_MINUTE=new Date(n,o,m,j,q);
h.__THIRTY_MINUTES_AGO=new Date(n,o,m,j,q-30);h.__SIXTY_ONE_MINUTES_AGO=new Date(n,o,m,j,q-61);h.__TWENTY_FOUR_HOURS_AGO=new Date(n,o,m,j-24);
h.__FORTY_EIGHT_HOURS_AGO=new Date(n,o,m,j-49);h.__THIS_WEEK=d.roundToWeek(h.__TODAY,true,k);h.__ONE_WEEK_BEFORE_TODAY=new Date(n,o,m-7);
h.__FOUR_WEEKS_AGO=d.roundToWeek(new Date(n,o,m-28),true,k);h.__THIS_MONTH=d.roundToMonth(h.__TODAY,true);h.__LAST_MONTH=new Date(n,o,m-32);
h.__THIRTEEN_WEEKS_AGO=d.roundToWeek(new Date(n,o,m-(7*13)),true,k);h.__ONE_DAY_AGO=new Date(n,o,m-1);h.__THIRTY_DAYS_AGO=new Date(n,o,m-30);
h.isInited=true;};h.recalculateDatesAsLatest=function(j,l){var r,q,m,o,n;if(!j){r=g;q=f;m=a;o=b;n=i;}else{var k=new Date();
r=k.getFullYear();q=k.getMonth();m=k.getDate();o=k.getHours();n=k.getMinutes();}h.__THIS_HOUR=new Date(r,q,m,o+1);h.__FORTY_EIGHT_HOURS_AGO=new Date(r,q,m,o-48);
h.__TODAY=new Date(r,q,m+1);h.__THIS_MINUTE=new Date(r,q,m,o,n+1);h.__SIXTY_ONE_MINUTES_AGO=new Date(r,q,m,o,n-60);var p=new Date(r,q,h.__TODAY.getDate()+7);
h.__THIS_WEEK=d.roundToWeek(p,false,l);h.__THIRTEEN_WEEKS_AGO=new Date(r,q,h.__THIS_WEEK.getDate()-(7*13));h.__TWENTY_FOUR_HOURS_AGO=new Date(r,q,h.__TODAY.getDate()-1,o-23);
h.__ONE_WEEK_BEFORE_TODAY=new Date(r,q,m-6);h.__FOUR_WEEKS_AGO=new Date(r,q,h.__THIS_WEEK.getDate()-28);h.__THIS_MONTH=new Date(r,q+1);
h.__LAST_MONTH=new Date(r,q,m-31);h.__TWELVE_MONTHS_AGO=new Date(r,q-11);h.__ONE_DAY_AGO=new Date(r,q,m);h.__THIRTY_DAYS_AGO=new Date(r,q,m-29);
};h.getMinDate=function(k,j){var l=null;switch(k){case h.__DAY_FORMAT:l=new Date(g,f,a-j);break;case h.__WEEK_FORMAT:l=new Date(g,f,h.__THIS_WEEK.getDate()-(7*j));
break;}return l;};return h;});