define("timeline/events/timelineEvents",[],function(){var a={};a.MODE_CHANGED="timeline.timelineEvents.timelineModeChanged";
a.SET_DISPLAY="timeline.timelineEvents.timelineSetDisplay";a.SET_DAYS="timeline.timelineEvents.timelineSetDays";a.SET_GRANULARITY="timeline.timelineEvents.timelineSetGranularity";
a.SET_CALENDAR="timeline.timelineEvents.timelineSetCalendar";a.CALENDAR_SET="timeline.timelineEvents.timelineCalendarSet";
a.TIMESPAN_SET="timeline.timelineEvents.timelineTimespanSet";a.TIMESPAN_SET_UTC="timeline.timelineEvents.timelineTimespanSetUtc";
a.TIMELINE_CONFIG_SET="timeline.timelineEvents.timelineConfigSet";a.CONFIG_SAVE_REQUESTED="timeline.timelineEvents.configSaveRequested";
a.TIMESPAN_CONFIG_CREATED="timeline.timelineEvents.timelineConfigCreated";a.JUMP_PERIOD="timeline.timelineEvents.jumpPeriod";
a.DISABLE_CONTROLS="timeline.timelineEvents.disableControls";a.ENABLE_CONTROLS="timeline.timelineEvents.enableControls";a.OUTPUT_URL="timeline.timelineEvents.outputUrl";
a.ALT_KEY_PRESS="timeline.timelineEvents.altKey";a.ALT_KEY_UP="timeline.timelineEvents.altKeyUp";a.PRESET_PERIOD="timeline.timelineEvents.presetPeriod";
a.COMBO_ERROR="timeline.timelineEvents.comboError";a.COMBO_SUCCES="timeline.timelineEvents.comboSucces";a.SET_CHART_GRAN_SELECT="timeline.timelineEvents.setChartGranularitySelect";
return a;});