define("chart/widgetFramework/core/drivers/basicChartDriver",["jquery","underscore","d3","chart/widgetFramework/core/drivers/tooltipCode","util/Functional"],function(e,a,c,d,b){var f=function(o,h){var l;
var j={joinAttr:null,barHeight:null,barPadding:0,margin:{top:0,right:0,bottom:0,left:0},xAttr:"x",xScale:"linear",yAttr:"y",yScale:"linear",textAnchor:"start"};
var k=500;var g=50;l={};l.el=h;d(l);l.init=function(){a.bindAll(this,"render");this.options=a.defaults(o,j);if(!this.options.outerPadding){this.options.outerPadding=this.options.barPadding;
}this.htmlObjects=(this.options.templateStyle==="html")?true:false;this.id=this.options.type;this.$el=e(this.el);if(b.truthy(this.options.width)&&this.options.width<=0){this.options.width=null;
}if(b.truthy(this.options.height)&&this.options.height<=0){this.options.height=null;}var p=m(this.options);this.$el.width(p);
var q=n(this.options);this.$el.height(q);};l.feedData=function(p){this.rawData=p;if(a.has(this.options,"dataSubset")){this.data=i(p,this.options.dataSubset);
}else{this.data=i(p);}if(!b.existy(this.data)){this.hideCharts("no data to display");return;}return this.data;};var i=function(r,s){var q=a.cloneDeep(r);
var p={};if(q.config){p.config=q.config;}if(q.chartData){p.chartData=(s)?q.chartData[s]:q.chartData;}if(q.extraData){p.extraData=q.extraData;
}if(a.keys(p)){return p;}return(s)?q[s]:q;};l.setBandSizes=function(){};l.initRender=function(){var p=this.options.margin;
if(a.keys(p).length===0){p={top:0,right:0,bottom:0,left:0};}this.width=this.$el.width()-(p.left+p.right);this.height=this.$el.height()-(p.top+p.bottom);
if(this.htmlObjects){this.topSVG=this.topSVG||c.select(this.el).append("div").attr("class","chartbase-svg");this.topSVG.style("width",this.$el.width()+"px").style("height",this.$el.height()+"px");
this.mainGroup=this.mainGroup||this.topSVG.append("div").attr("class","main-group").style("transform","translate("+p.left+"px,"+p.top+"px)");
this.chartGroup=this.mainGroup.append("div").attr("class","chart-elements-holder");}else{this.topSVG=this.topSVG||c.select(this.el).append("svg").attr("class","chartbase-svg");
this.topSVG.attr("width",this.$el.width()+"px").attr("height",this.$el.height()+"px");this.mainGroup=this.mainGroup||this.topSVG.append("g").attr("class","main-group").attr("transform","translate("+p.left+","+p.top+")");
this.chartGroup=this.mainGroup.append("g").attr("class","chart-elements-holder");}};l.render=function(){this.topSVG.attr("width",this.$el.width()+"px").attr("height",this.$el.height()+"px");
this.showCharts();this.update();return this;};l.update=function(){this.setBandSizes();this.renderData();};l.renderData=function(){if(!b.existy(this.data)){return;
}};l.setupUiComponents=function(s){for(var r=0;r<s.length;r++){if(s[r]&&s[r].type==="tooltip"){var q=s[r].module;var p=s[r].options;
this.setupTooltip(q,p);}}};l.hideCharts=function(p){this.$el.find(".no-data-text").remove();var r=b.existy(p)?p:"no data to display";
var t=this.height/2;var s=this.width/2;var q=e('<div class="no-data-text"><text style="color: #ccc; font-size: 14px; position: relative; top:'+t+"px; left:"+s+'px;">'+r+"</text></div>");
this.$el.not(this.$el.has(".no-data-text")).prepend(q);this.$el.children().not(".no-data-text").hide();q.show();};l.showCharts=function(){this.$el.find(".no-data-text").remove();
this.$el.children().not(".no-data-text").show();};l.getData=function(){return function(){return l.data;};};l.getPrimaryDataJoin=function(){var p=this.options.joinAttr;
return this.getDataJoin(p);};l.getDataJoin=function(p){return function(r,q){if(p&&a(r).has(p)){return r[p];}else{return q;
}};};l.getX=function(p){return this._getDatumValue(p,this.options.xAttr);};l.getY=function(p){return this._getDatumValue(p,this.options.yAttr);
};l._getDatumValue=function(q,p){return q?q[p]:null;};var m=function(p){var q=b.defaults({width:k});return q(p,"width");};
var n=function(p){var q=b.defaults({height:g});return q(p,"height");};return l;};return f;});