define("chart/widgetFramework/core/ActionCommander",["jqueryExtended","lodash","util/Console","util/Analytics"],function(e,c,b,a){function d(f){var h="color:red;font-size:1em";
var g={};g.init=function(){g.parameters=g.getParameters(f);g.$node=g.$el=f.getNode();g.widgetInstances=[];g.actions=(g.parameters.actions||[]);
g.actionsFilePromise=new e.Deferred();if(g.parameters.actionsFile){g.getActions(g.parameters.actionsFile);}else{g.actionsFilePromise.resolve();
}};g.getParameters=function(i){var j=i.getNode().data();return{actions:j.actions,actionsFile:j.actionsfile};};g.getActions=function(i){g.$node.widget().then(function(){require([i],function(j){g.actions=g.actions.concat(j.actions);
g.actionsFilePromise.resolve();},function(j){b.log("VizComp:: Formatter widget error: ",j);});});};g.pushAllInstances=function(i){c.each(i,function(j){g.widgetInstances.push(j);
j.ac=g;});g.setUpEventsPromise=new e.Deferred();g.actionsFilePromise.done(function(){g.setUpEvents();});return g.setUpEventsPromise;
};g.setUpEvents=function(i){var j=(i||g.actions);c.each(j,function(l){if(c.isArray(l.source)){var k=l.source;c.each(k,function(m){g.setUpEvent(l,m);
});}else{g.setUpEvent(l);}});g.setUpEventsPromise.resolve();};g.setUpEvent=function(k,j){j=(typeof j==="undefined")?k.source:j;
var l=(j.indexOf("#")>-1)?j.substring(1):j;var i=c.findWhere(g.widgetInstances,{id:l});if(i){g.bindSourceEvent(i.$el,k);}else{if(e(j).length>0){g.bindSourceEvent(e(j),k);
}else{try{if(e("#"+j).length>0){g.bindSourceEvent(e("#"+j),k);}}catch(m){}}}};g.bindSourceEvent=function(j,i){j.on(i.event,i.lazySelector,function(n,m){if(i.target||i.callMethod||i.toggle){g.bindTargetEvent(i,m,e(this),n);
var l=i.toggle;if(l&&(l.length>0)){g.toggleButtons(e(this),l,g.actions);}}else{if(i.track){var k=i.track;a.trackEvent(k.category,k.action,k.name,k.weight);
}}});};g.bindTargetEvent=function(j,n,m,i){var k=g.getEventData(j,n,m);var q=j.callMethod;var l=[];var p;if(j.target){if(c.isArray(j.target)){c.each(j.target,function(r){p=(r.indexOf("#")>-1)?r.substring(1):r;
var s=c.findWhere(g.widgetInstances,{id:p});if(!c.includes(l,s)){l.push(s);}});c.each(l,function(r){g.executeCallMethod(r,k,q,m,j.event,i);
});}else{p=(j.target.indexOf("#")>-1)?j.target.substring(1):j.target;var o=c.findWhere(g.widgetInstances,{id:p});g.executeCallMethod(o,k,q,m,j.event,i);
}}else{if(q&&c.isFunction(q)){g.executeCallMethod(null,k,q,m,j.event,i);}}};g.getEventData=function(l,k,j){var i=l.getterMethod;
if(l.data){return l.data;}if(i&&typeof i==="function"){return i.call(g,j,k);}else{if(i){return i;}}if(i&&typeof(j[i])==="function"){return j[i](k);
}if(k){return(k.data||k);}return null;};g.executeCallMethod=function(j,o,i,l,k,n){if(j&&i){var m=j.getInstance();if(m&&typeof m[i]==="function"){m[i].apply(m,[o,l,k]);
}}else{if(typeof i==="function"){i(o,l,n);}else{if(window.console&&b.log){b.log("%c\n################",h);b.warn('%c### ActionCommander::executeCallMethod:: No target can be found on which to execute a function called "'+i+'". Check your actions file - you are probably setting something as a target that is not currently present in the DOM',h);
b.log("%c################",h);}}}};g.unbindEvents=function(i){i=(i||g.actions);c.each(i,function(k){var j=c.findWhere(g.widgetInstances,{id:k.source});
if(j){j.$el.unbind(k.event);}else{if(e(k.source).length>0){e(k.source).unbind(k.event);}else{try{if(e("#"+k.source).length>0){e("#"+k.source).unbind(k.event);
}}catch(l){}}}});};g.toggleButtons=function(m,l,n){var k,j,i;c.each(n,function(o){if(c.isArray(o.source)){i=o.toggle;c.each(o.source,function(p){if(p.indexOf("#")>-1||p.indexOf(".")===0){k=p;
}else{k=("#"+p);}j=e(k);if(j&&(i===l)){j.removeClass("active");}});}else{if(o.source.indexOf("#")>-1||o.source.indexOf(".")===0){k=o.source;
}else{k=("#"+o.source);}j=e(k);i=o.toggle;if(j&&(i===l)){j.removeClass("active");}}});m.addClass("active");};g.init();f.ready();
return g;}return d;});