define("chartlib/basicChart",["jquery","underscore","chartlib/chartbase","d3"],function(e,a,d,c){var b=d.extend({defaults:{barPadding:0.2,yScale:"ordinal",textAnchor:"start"},IE_tooltip_timeout:null,initialize:function(){a.bindAll(this,"showTooltip","hideTooltip","showToolTip_fromText","hideToolTip_fromText","textClicked","render");
this.addListeners();this._super();},addListeners:function(){if(this.collection){this.listenTo(this.collection,"reset",this.render);
}},setXScale:function(){this.scales.x=c.scale[this.options.xScale]().range([0,this.width]);},calibrateXScale:function(){this.scales.x.domain([0,c.max(this.collection.pluck(this.options.xAttr))]);
},setYScale:function(){this.scales.y=c.scale[this.options.yScale]();},calibrateYScale:function(){this.scales.y.domain(this.collection.pluck(this.options.yAttr)).rangeRoundBands([this.height,0],this.options.barPadding);
},setXAxis:function(){this.axes.x=c.svg.axis().scale(this.scales.x).orient("bottom").tickSize(-this.height).tickFormat(c.format("1s"));
},formatXAxis:function(){},setYAxis:function(){this.axes.y=c.svg.axis().scale(this.scales.y).orient("left");},formatYAxis:function(){},renderXAxis:function(){var g=this.axes.x;
if(this.options.barHeight!==null){g.tickSize(-this.height);}var f=(this.options.delay)?this.options.delay:500;this.xAxis.attr("opacity",1).call(g).transition().duration(500).delay(f).ease("exp-in-out").attr("transform","translate(0,"+this.height+")");
this.xAxis.selectAll("line").each(function(h){if(typeof this.raphaelNode!=="undefined"){this.raphaelNode.toBack();}});},renderYAxis:function(){this.yAxis.transition().duration(500).ease("exp-in-out").call(this.axes.y);
if(this.options.showTipFromText){this.yAxis.selectAll(".tick text").classed("active",true).on("mouseover",this.showToolTip_fromText).on("mouseout",this.hideToolTip_fromText);
}if(this.options.isClickable&&this.options.clickFromText){this.yAxis.selectAll(".tick text").classed("hand-cursor active",true).on("click",this.textClicked);
}},renderData:function(){var l=this,n=this.options,f=this.scales.y,m=500;var k=this.svg.selectAll(".bar").data(this.collection.models,this.joinData);
var j=k.enter().append("g").attr("class","bar full").attr("transform",function(o){return"translate(0,"+f(l.getY(o))+")";});
j.append("text").attr("class","barless-chart-text").attr("x",function(o){return l.options.totalLabelOffset;}).attr("y",f.rangeBand()/2).attr("dy",".35em").text(function(o){return l.getX(o);
}).attr("font-size","12px").attr("text-anchor",l.options.textAnchor).attr("fill-opacity",0);var g=k.select(".barless-chart-text").text(function(o){return l.getX(o);
});var h=c.transition(k);h.select(".barless-chart-text").attr("y",f.rangeBand()/2).attr("fill-opacity",1);h.transition().duration(m).attr("transform",function(o){return"translate(0,"+f(l.getY(o))+")";
});var i=c.transition(k.exit()).transition().duration(m).attr("transform",function(o){return"translate(0,"+l.height+")";}).remove();
i.selectAll("text").attr("fill-opacity",0);if(this.options.tooltip){k.classed("active",true);j.on("mouseover",function(o){l.showTooltip(o,this,false);
}).on("mouseout",function(o){l.hideTooltip(false);});}if(this.options.isClickable){j.on("click",l.onBarClicked);k.classed({"hand-cursor active":true});
}},showTooltip:function(m,i,f){this.renderTooltipContent(m,i);if(typeof window.SVGElement==="undefined"){var g=e(i)[0].raphaelNode[0];
var h=e(g).offset().top;var l=e(g).offset().left+Number(g.clientWidth);var k=5;var j=e(".d3-tip");j.css({width:"auto","text-align":"center",display:"block",padding:"4px 6px",opacity:"1",left:(l+10)+"px",top:(h-k)+"px"});
j.addClass("on");this.tip.show(m,i);return;}if(f!==true){this.tip.show(m,i);}else{this.tip.show(m,i.node());}},showToolTip_fromText:function(f){var g=this.getElementFromAttrValue(".bar.full",this.options.yAttr,f);
this.showTooltip(g.datum(),g,true);return g;},hideTooltip:function(f){if(typeof window.SVGElement==="undefined"){var h=e(".d3-tip");
var g=this;if(f){window.clearTimeout(this.IE_tooltip_timeout);this.IE_tooltip_timeout=setTimeout(function(){h.css("display","none");
g.tip.hide();},1000);}else{h.css("display","none");g.tip.hide();}return;}this.tip.hide();},hideToolTip_fromText:function(f){var g=this.getElementFromAttrValue(".bar.full",this.options.yAttr,f);
this.hideTooltip(true);return g;},getElementFromAttrValue:function(h,k,g){var l=this.el.className;var i=l.replace(/\s+/g,".");
var f=c.selectAll("."+i+" "+h);var j=f.filter(function(n,m){return n.attributes[k]===g;});return j;},textClicked:function(f){var g=this.getElementFromAttrValue(".bar.full",this.options.yAttr,f);
g.on("click")(g.datum());},onBarClicked:function(){},renderTooltipContent:function(){}});return b;});