define("chartlib/timeVertBarChart",["jquery","underscore","d3","chartlib/vertbarchart","chartutil/d3utils","chartutil/dateUtils_CET"],function(f,b,e,d,c,g){var a=d.extend({granularityFormats:[],defaults:{barPadding:0.1,margin:{top:10,right:10,bottom:40,left:50},tooltip:true},initialize:function(){this.granularityFormats.month=e.time.format.utc("%b");
this.granularityFormats.week=function(h){return"wk "+h.getWeek();};this.granularityFormats.day=e.time.format.utc("%e");this.granularityFormats.hour=function(i){var h=g.getAmsterdamDSTOffset(i);
return new Date(i.getTime()+h*60*1000).getUTCHours();};this.granularityFormats.minute=e.time.format.utc("%_M");this._super(arguments);
},setXScale:function(){this.scales.x=e.time.scale.utc().range([0,this.width],this.options.barPadding);},calibrateXScale:function(){var h=this.collection.getDateExtent();
this.scales.x.domain(h);this.scales.x.ticks(this.collection.getIntervalFormat(),1);},setXAxis:function(){this.axes.x=e.svg.axis().scale(this.scales.x).orient("bottom").tickSize(0);
},formatXAxis:function(){var j=this,i=this.axes.x,k=this.collection.getGranularity(),h=j.scales.x.ticks(e.time[k].utc,1).length;
if(h>40){k="month";}i.ticks(e.time[k].utc,1).tickFormat(j.granularityFormats[k]);},renderXAxis:function(){this.formatXAxis();
this._super();c.spreadTimeAxisTicks(this);},formatYAxis:function(){var h=this;if(this.options.percentile){this.axes.y.tickFormat(e.format("%"));
}else{this.axes.y.tickFormat(function(k,j){return c.thousandsFormatter(k,j,h.scales.y);});}},renderYAxis:function(){this.formatYAxis();
this._super();if(this.options.percentile){c.percentageFormat(this.yAxis);}},renderData:function(){var n=this,p=this.scales.x,o=this.scales.y,m=this.collection.getGranularity(),i=p.ticks(e.time[m].utc,1).length,k=(n.width/i),q=(k*(1-this.options.barPadding))/2;
var l=this.svg.selectAll(".bar").data(n.collection.models,this.joinData);var j=l.enter().append("g").attr("class","bar").append("rect");
l.transition().duration(500).ease("exp-in-out").attr("transform",function(s,r){return"translate("+((k*(r+1))-(k/2))+",0)";
}).select("rect").attr("transform",function(){return"translate("+(-q/2)+",0)";}).attr("width",q).attr("y",function(r){return o(n.getY(r));
}).attr("height",function(r){return n.height-o(n.getY(r));});if(this.options.tooltip){l.classed("active",true);j.on("mouseenter",function(r){n.showTooltip(r,this,false);
}).on("mouseout",this.tip.hide);}var h=l.exit().transition();h.attr("transform",function(){return"translate(0,0)";}).select("rect").transition().attr("width",0);
h.remove();},renderTooltipContent:function(i){var h=this;h.tip.html(function(k){var j="<div class='csr-col' style='width:220px'>";
j+="<div class='csr-col two a'><b>x:</b></div><div class='csr-col two a'>"+h.getX(k)+"</div>";j+="<div class='csr-col two a'><b>y:</b></div><div class='csr-col two a'>"+h.getY(k)+"</div>";
j+="</div>";return j;});this.tip.attr("class","d3-tip");this.tip.direction("n");this.tip.offset([-10,0]);}});return a;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);
}});