define("chart/widgetFramework/composed/chargebackReport/chargebackMediator",["jqueryExtended","d3","lodash","chart/widgetFramework/core/BasicMediator","util/ObjectSuper","chartutil/numberutils","chart/widgetFramework/core/constants/UIConstants","chartutil/cssutils"],function(a,i,f,e,c,g,d,h){function b(j){var k;
k=e(j,true);var l=c(k);k.init=function(){l.init();k.rankedChartID="Count";this.$sortButtonRefCountry=a("#countryCountTitle");
this.$sortButtonRefPaymentMethod=a("#paymentMethodCountTitle");this.$sortButtonRefAcquirer=a("#acquirerCountTitle");this.actionCommanderExclusionArray=["actioncommander","timeline"];
};k.getAdditionalDOMElements=function(){l.getAdditionalDOMElements();this.timelineInstances=[];this.$allTimelines=j.__$node.find("[data-widget*=Timeline]");
this.totalDomElements+=this.$allTimelines.length;};k.getWidgets=function(){l.getWidgets();this.getWidgetInstances(this.$allTimelines,this.timelineInstances,"Timelines");
};k.onNotifiedFetcher=function(o,n){l.onNotifiedFetcher(o,n);if(n==="issuerCountriesFetcher"){var s,r=this.$el.find("#issuerCountry"),m=false;
s='<option value="">-- all Issuer Countries --</option>';f.each(o.changeObject.data,function(u){if(!u){return;}if(f.isObject(u)){if(k.storedIssuerCountry&&k.storedIssuerCountry===u.countryCode){m=true;
}s+='<option value="'+u.countryCode+'">'+u.countryName+"</option>";}else{if(k.storedIssuerCountry&&k.storedIssuerCountry===u){m=true;
}s+='<option value="'+u+'">'+u+"</option>";}});r.html(s);if(this.storedIssuerCountry&&m){a("#issuerCountry").val(this.storedIssuerCountry);
}}if(n==="activePaymentMethodsFetcher"){var t,p=this.$el.find("#paymentMethod"),q=false;t='<option value="">-- all Payment Methods --</option>';
f.each(o.changeObject.data,function(u){if(k.storedPaymentMethod&&k.storedPaymentMethod===u){q=true;}t+='<option value="'+u+'">'+u+"</option>";
});p.html(t);if(this.storedPaymentMethod&&q){a("#paymentMethod").val(this.storedPaymentMethod);}}};k.onNotifiedFormatter=function(p,o){l.onNotifiedFormatter(p,o);
if(o==="masterFormatter"&&p.changeObject.data){k.renderTotals(p.changeObject.data);}var q,t,r,s,n,m;if(o==="countryBarFormatter"){this.$el.find(".country-grouped-bar-chart .chart-elements-holder").each(function(){i.select(a(this)[0]).classed("barchart-ranked",false);
});i.selectAll("#country"+k.rankedChartID+"BarChart .chart-elements-holder").classed("barchart-ranked",true);q=this.getInstanceById("#countryBarFormatter");
t=q.getSortDirection();r=this.$sortButtonRefCountry.find(".arrow")[0];s=(t)?180:0;n=(t)?-0.5:0.5;m=(t)?1:-0.5;h.rotateElement2(r,s,n,m);
}if(o==="acquirerBarFormatter"){this.$el.find(".acquirer-grouped-bar-chart .chart-elements-holder").each(function(){i.select(a(this)[0]).classed("barchart-ranked",false);
});i.selectAll("#acquirer"+k.rankedChartID+"BarChart .chart-elements-holder").classed("barchart-ranked",true);q=this.getInstanceById("#acquirerBarFormatter");
t=q.getSortDirection();r=this.$sortButtonRefAcquirer.find(".arrow")[0];s=(t)?180:0;n=(t)?-0.5:0.5;m=(t)?1:-0.5;h.rotateElement2(r,s,n,m);
}if(o==="paymentMethodBarFormatter"){this.$el.find(".paymentMethod-grouped-bar-chart .chart-elements-holder").each(function(){i.select(a(this)[0]).classed("barchart-ranked",false);
});i.selectAll("#paymentMethod"+k.rankedChartID+"BarChart .chart-elements-holder").classed("barchart-ranked",true);q=this.getInstanceById("#paymentMethodBarFormatter");
t=q.getSortDirection();r=this.$sortButtonRefPaymentMethod.find(".arrow")[0];s=(t)?180:0;n=(t)?-0.5:0.5;m=(t)?1:-0.5;h.rotateElement2(r,s,n,m);
}};k.onNotifiedViewCreator=function(q,o){l.onNotifiedViewCreator(q,o);var n=q.changeObject;var p=n.type;var m;if(o==="countryRateBarChart"){if(p===d.CHART_FIRST_RENDER||p===d.CHART_UPDATED){m=this.getInstanceById("countryBrushBarChart",this.chartInstances).getInstance();
if(m){m.startBrush();}}}if(o==="paymentMethodRateBarChart"){if(p===d.CHART_FIRST_RENDER||p===d.CHART_UPDATED){m=this.getInstanceById("paymentMethodBrushBarChart",this.chartInstances).getInstance();
if(m){m.startBrush();}}}};k.renderTotals=function(o){var m=i.format(",.0f");var p=i.format(".2f");var n={chargebackVol:0,chargebackAmt:0,avgChargebackAmt:0,chargebackRate:0,authVol:0};
f.each(o,function(q){n.chargebackVol+=q.chargebackCount;n.chargebackAmt+=q.chargebackEurAmount/100;n.authVol+=q.authorisedCount;
});n.avgChargebackAmt=(n.chargebackAmt>0||n.chargebackVol>0)?n.chargebackAmt/n.chargebackVol:0;n.chargebackRate=(n.chargebackVol>0||n.authVol>0)?(n.chargebackVol/n.authVol)*100:0;
g.animateValue(a("#chargebackVol span"),n.chargebackVol,m);g.animateValue(a("#chargebackAmt span"),n.chargebackAmt,m);g.animateValue(a("#avgChargebackAmt span"),n.avgChargebackAmt,p);
g.animateValue(a("#chargebackRate span"),n.chargebackRate,p);};k.onTimeData=function(){if(a("#issuerCountry").val()!==""){this.storedIssuerCountry=a("#issuerCountry").val();
}else{this.storedIssuerCountry=null;}if(a("#paymentMethod").val()!==""){this.storedPaymentMethod=a("#paymentMethod").val();
}else{this.storedPaymentMethod=null;}};k.reformatData=function(n){var m=this.$el.find("#countryBarCountAmountSpan");m.text(n);
var o=this.$el.find("#paymentMethodCountAmountSpan");o.text(n);};k.reformatDataChargebacksNof=function(o){var m="#"+o.source+"TitleText";
var n=this.$el.find(m);if(o.type==="chargebacks"){n.text("Chargebacks");}else{n.text("Notifications of fraud");}};k.getInstance=function(){return this;
};k.sortData=function(n,m){if(n==="chargebackCount"){k.rankedChartID="Count";}else{if(n==="chargebackEurAmount"){k.rankedChartID="Amount";
}else{if(n==="chargebackRate"){k.rankedChartID="Rate";}}}if(m.attr("id").indexOf("country")>-1){this.$sortButtonRefCountry=m;
}else{if(m.attr("id").indexOf("paymentMethod")>-1){this.$sortButtonRefPaymentMethod=m;}else{if(m.attr("id").indexOf("acquirer")>-1){this.$sortButtonRefAcquirer=m;
}}}};k.init();j.ready();return k;}return b;});