define("baselinerates/collections/baselineData",["jquery","underscore","backbone","d3","baselinerates/models/transaction","chartlib/events/appstateevents","chartutil/stringutils","chartutil/d3utils","chartutil/backbone/CollectionUtils"],function(b,g,f,i,e,c,a,j,d){var h=f.Collection.extend({model:e,url:adyen.config.baseLineURL,loaded:b.Deferred(),granularity:"day",intervalFormat:null,lastModelDate:null,dateExtent:[],movingAverageNum:7,movingAverageDirection:"backward",initialize:function(){g.bindAll(this,"loadBaselineData","onLoaded","onError","getDateExtent","getLastModelDate","getLastAverageDate","getTruncatedData","getMaxAuthrate");
f.on(c.STATE_CHANGED,this.loadBaselineData);this.comparator="utcdate";this._super(arguments);},loadBaselineData:function(n){var m=/\s/;
var l=n.get("bdate").replace(m,"T")+"+0000";var k=n.get("edate").replace(m,"T")+"+0000";switch(this.granularity){case"week":this.intervalFormat=i.time.monday.utc.range;
break;default:this.intervalFormat=i.time[this.granularity].utc;break;}this.dateExtent=[i.time.format.utc("%Y-%m-%dT%H:%M:%S%Z").parse(l),i.time.format.utc("%Y-%m-%dT%H:%M:%S%Z").parse(k)];
switch(this.granularity){case"week":this.dateExtent[1]=i.time.day.utc.offset(this.dateExtent[1],1);break;}this.loaded=b.Deferred();
this.fetch({reset:true});},fetch:function(l){var m=i.time.format.utc("%Y-%m-%d");var k={reportCode:"chart_baseline_report",reportstartdate:m(this.dateExtent[0]),reportenddate:m(this.dateExtent[1]),format:"JSON",formHash:adyen.formHash};
l.url=adyen.base+this.url+"&cb="+new Date().getTime();l.success=this.onLoaded;l.error=this.onError;l.reset=false;l.sort=false;
l.type="POST";l.data=k;this._super(l);},parse:function(l){if(window.console&&console.log){console.log("### baselineData::parse:: RAW data=",l);
}this.dateExtent[1]=i.time[this.granularity].utc.offset(this.dateExtent[1],-1);if(l["default"]&&l["default"].rows){var k=l["default"].rows;
g.map(k,function(m){if(!m.auths||m.auths===0){m.auths=m.payout_auths;}});return g.map(k,function(n,m){return k[m];});}return null;
},onError:function(m,l,k){if(l.getResponseHeader("content-type").indexOf("text/html")>-1){}if(window.console&&console.log){console.log("responseTimeData load error: ",m,l.getResponseHeader("content-type"),k);
}this.loaded.reject();},onLoaded:function(){if(typeof(this.last())!=="undefined"){this.lastModelDate=this.last().get("utcdate");
}else{this.lastModelDate=this.getDateExtent()[0];}var k=j.fillUTCScaleBuckets(this.getDateExtent(),this.granularity,this.models,e);
this.set(k,{silent:true});this.calculateMovingAverages();this.trigger("reset");this.loaded.resolve();},calculateMovingAverages:function(){var k=this;
this.each(function(p,l){var q=k.movingAverageDirection==="forward"?(l+1)+k.movingAverageNum:(l+1)-k.movingAverageNum;var n,o,m;
if((k.movingAverageDirection==="forward"&&q<k.length)||(k.movingAverageDirection==="backward"&&q>-1)){n=k.movingAverageDirection==="forward"?k.models.slice(l+1,q):k.models.slice(q,l+1);
o=g.reduceRight(n,function(r,s){return r+s.get("total");},0);m=g.reduceRight(n,function(r,s){return r+s.get("authorisations");
},0);p.set("averageTotal",o/k.movingAverageNum);p.set("averageRate",m/o||0);}});},getMaxAuthrate:function(){return Math.max.apply(null,this.pluck("authRate"));
},getGranularity:function(){return this.granularity;},getDateExtent:function(){return this.dateExtent;},getIntervalFormat:function(){return this.intervalFormat;
},getTotalsSum:function(){return this.sumOf("total");},getAuthorisationsSum:function(){return this.sumOf("authorisations");
},getRatesSum:function(){return(this.getAuthorisationsSum()/this.getTotalsSum())||0;},getTruncatedData:function(){var k=this;
return this.filter(function(l){return l.get("utcdate").getTime()<=k.getLastModelDate().getTime();});},getLastModelDate:function(){return this.lastModelDate;
},getLastAverageDate:function(){return i.time.day.utc.offset(this.getLastModelDate(),this.movingAverageNum);},getLoaded:function(){return this.loaded.promise();
}});return h;},function(a){if(window.console&&console.log){console.log("APP JS ERROR = "+a);}});