define("pmc/views/app",["jquery","underscore","backbone","d3","chartutil/backbone/r2d3app","chartlib/chartLoadQueue","map/views/ui/mappanel","map/views/ui/mapui","map/views/charts/mapchart","chartlib/ui/collapsiblePanel","pmc/views/ui/paymentMethodTxUI","pmc/views/charts/paymentMethodTransaction","pmc/views/ui/paymentMethodVolumeUI","pmc/views/charts/paymentMethodVolume","pmc/views/charts/paymentMethodConversion","pmc/views/charts/paymentMethodCountryTotal","pmc/views/charts/paymentMethodCountryVolume","pmc/views/charts/paymentMethodCountryBarPie","pmc/views/charts/paymentMethodCountryConversion","chartlib/ui/csvdownload","chartlib/ui/snapshot","pmc/models/appstate","pmc/collections/paymentMethodTransactionData","pmc/collections/paymentMethodVolumeData","pmc/collections/paymentMethodCountryData","map/collections/mapdata","chartlib/events/appstateevents","pmc/events/pmEvents","map/events/worldevents","chartlib/chartBaseEvents","timeline/events/timelineEvents","timeline/views/timelineFacade","timeline/util/timelineConstants"],function(k,G,c,F,z,H,w,n,y,p,C,h,B,A,o,E,v,t,i,m,l,r,q,g,b,f,D,a,e,j,u,d,s){var x=window.adyen||{};
x.jsbase=x.jsbase||"";return z.extend({el:k("#d3canvas"),deferredArray:[],successfulLinkedDataLoadArray:[],numCollections:0,numLinkedCollections:0,uid:"pmc",hasLoadQueue:true,initialize:function(){this._super();
this.volumeDisplay=k("#pmVolumeTotalText");this.countryDisplay=k("#countryVolumeTotalText");if(typeof window.SVGElement==="undefined"){var I=k("#ie8_d3CanvasCover");
I.css("height",this.$el.height());I.css("display","block");}c.on(j.REGISTER_DEFERRED,this.registerDeferred,this);c.on(D.CHANGE_REQUESTED,this.changeState,this);
c.on(e.TOTAL_SESSIONS,this.setTotal,this);c.on(a.COUNTRIES_TOTAL,this.setTotal,this);c.on(a.VOLUME_TOTAL,this.setTotal,this);
c.on(u.TIMESPAN_CONFIG_CREATED,this.onTimelineConfig,this);if(this.hasLoadQueue){c.on(D.RENDER_CHARTS,this.renderCharts,this);
}this.initModels();this.initCollections();this.initViews();this.hasMapData=0;this.hasCountryData=0;this.pms_country=0;this.pms_overall=0;
},initModels:function(){this.appState=new r();},initCollections:function(){if(this.hasLoadQueue){this.loadQueue=new H();}this.mapData=new f();
this.addCollection(false);this.pmTransactionData=new q([],{isLinked:true});this.addCollection(true);this.pmVolumeData=new g([],{isLinked:true});
this.addCollection(true);this.pmCountryData=new b();this.addCollection(false);},initViews:function(){var P=new w({collection:this.mapData,model:this.appState}).render();
var M=new n({collection:this.mapData});var L=new y({collection:this.mapData});var V=new p({el:this.$(".panel.payment-methods")});
var N=new C({collection:this.pmTransactionData});var R=new h({collection:this.pmTransactionData});var I=new B({collection:this.pmVolumeData});
var Q=new A({collection:this.pmVolumeData});var S=new o({collection:this.pmVolumeData});var O=new E({collection:this.pmCountryData});
var J=new v({collection:this.pmCountryData});var U=new t({collection:this.pmCountryData});var T=new i({collection:this.pmCountryData});
new m({el:".world-csvdownload",collection:this.mapData});new m({el:".payment-methods-csvdownload",collection:this.pmVolumeData});
new m({el:".payment-methods-country-csvdownload",collection:this.pmCountryData});this.timeline=new d({version:7,timeCollectionMode:s.__LAST_FULL,formatPeriod:s.__DAY_FORMAT,baseGranularity:s.__DAY_GRANULARITY,calendar:true,controls:true,presets:[],loadQueue:this.hasLoadQueue,config:false,chartGranularity:s.__MINUTE_FORMAT,forceCET:false});
this.appState.addConfig({timeline:this.timeline,config:null,hasMap:true});var K=new l({el:".world-snapshot",snapshotEl:".worldvolume-chart",styleSheets:["chartlib/css/modules.css","paymentMethods/css/modules.css"],title:"WorldVolume",timeline:this.timeline});
},addCollection:function(I){this.numCollections++;if(I){this.numLinkedCollections++;}},changeState:function(){this.$el.css("pointer-events","none");
this.$("svg rect").css("pointer-events","none");this.$("svg text").css("pointer-events","none");this.$el.fadeTo(0,0.35);if(typeof window.SVGElement==="undefined"){var J=k("#ie8_d3CanvasCover");
J.css("height",this.$el.height());J.css("display","block");}this.deferredArray=[];this.stopListening();this.successfulLinkedDataLoadArray=[];
this.hasMapData=0;this.hasCountryData=0;this.hasVolumeData=0;this.pms_country=0;this.pms_overall=0;var I=this.pms_country+" payment methods - Total Sessions: <b>"+0+"</b>";
this.countryDisplay.html(I);this.volumeDisplay.html("Total Payment Methods: <b>"+0+"</b>");},registerDeferred:function(K,I,J){K.collection=J;
var M=this.deferredArray;M.push(K);var L=this;K.done(function(O,N){L.checkDeferredsCallback(M);}).fail(function(O,N){L.checkDeferredsCallback(M);
});},checkDeferredsCallback:function(I){var J=G.every(I,function(K){return K.state()==="resolved"||K.state()==="rejected";
});if(J){this.dataAttempted(I);}},hideCover:function(){this.$el.css("pointer-events","auto");this.$("svg rect").css("pointer-events","auto");
this.$("svg text").css("pointer-events","auto");this.$el.fadeTo(500,1);if(typeof window.SVGElement==="undefined"){var I=k("#ie8_d3CanvasCover");
I.css("display","none");}},renderCharts:function(){this.hideCover();},dataAttempted:function(J){if(window.console&&window.console.log){window.console.log("### ALL DATA LOADS HAVE REPORTED BACK pDefArray=",J);
}var K=this;var I=0;if(!this.hasLoadQueue){setTimeout(function(){c.trigger(j.DATA_LOADED);K.hideCover();},10);}else{c.trigger(j.DATA_LOADED);
}G.each(J,function(L){if(L.collection.isLinked){I++;}});if(I===this.numLinkedCollections){G.each(J,function(L){if(L.state()==="resolved"&&L.collection.isLinked){K.successfulLinkedDataLoadArray.push(L.collection);
if(!L.collection.hasParsedData){K.listenTo(L.collection,"reset",function(M){if(window.console&&window.console.log){window.console.log("### APPVIEW LISTEN FOR RESET id=",M._listenerId);
}K.checkDataLoadArray();});}}});K.checkDataLoadArray();}},checkDataLoadArray:function(){var I=G.every(this.successfulLinkedDataLoadArray,function(J){return J.hasParsedData;
});if(I){this.triggerStartEvent();}},triggerStartEvent:function(){var I=G.find(this.successfulLinkedDataLoadArray,function(J){return J instanceof g;
});if(I){setTimeout(function(){c.trigger(a.COLLECTION_SORTED,I.models,I);},10);}},setTotal:function(J,L,K){var M;if(K==="mapdata"){this.hasMapData=J;
}if(K==="PaymentMethodCountryData"){this.hasCountryData=J;this.pms_country=L;}if(K==="PaymentMethodVolumeData"){this.hasVolumeData=J;
this.pms_overall=L;if(window.console&&window.console.log){window.console.log("### app::setTotal:: this.pms_overall=",this.pms_overall);
}}var I=F.format("0,000");if(this.hasVolumeData>0&&this.hasCountryData>0){M=this.pms_country+" payment methods - Total Sessions: <strong>"+I(this.hasCountryData);
M+="</strong> from <b>"+I(this.hasMapData)+"</b>";M+=" ("+((this.hasCountryData*100)/this.hasMapData).toFixed(1)+"%)";this.countryDisplay.html(M);
}else{if(this.hasVolumeData===0&&this.hasCountryData>0){M=this.pms_country+" payment methods - Total Sessions: <b>"+I(this.hasCountryData)+"</b>";
this.countryDisplay.html(M);}}this.volumeDisplay.html("Total Payment Methods: <b>"+this.pms_overall+"</b>");}});},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);
}});