define("timeline/util/reformatTimeline",["jquery","backbone","chartutil/dateUtils_CET","timeline/util/timelineConstants","timeline/events/timelineEvents"],function(b,f,e,a,d){var c={};
c.reformatTimeline=function(o,h,j,g,n,l){var i=this.baseGranularity||this.collection.getValue("baseGranularity");var k=this.formatPeriod||this.collection.getValue("formatPeriod");
f.trigger(d.DISABLE_CONTROLS,"reformatTimeline");if(this.logTimelineCalcs&&window.console&&window.console.log){window.console.log("reformatTimeline formatPeriod =",k," pNumMinutes=",o,"  startDate=",h,"  pChangeAgent=",j,"  pEndExtentDate=",g,"  pJumpPeriod=",n);
}var r=(this.collection)?this.collection.getValue("timeline"):null;var q=(r)?r[0]:this.scales.x.domain()[0];var m=(r)?r[1]:this.scales.x.domain()[1];
var p=(typeof n!=="undefined")?n:false;if(k===a.__MINUTE_FORMAT){if(j===a.__DAYS_BTN||j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 6");
}this.switchToDay(h,g);return true;}if(j===a.__WEEKS_BTN||j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 6");
}this.switchToWeek(h,g);return true;}if(j===a.__MONTHS_BTN||j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 5");
}this.switchToMonth(h,g);return true;}if(o>=a.__MINUTE_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 4");
}this.switchToHour(h,g);return true;}if(j===a.__MINUTE_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 5 (IN MINUTE, STAY IN MINUTE)");
}this.switchToMinute(h,g,p,l);return true;}}else{if(k===a.__HOUR_FORMAT){if(j===a.__WEEKS_BTN||j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 5");
}this.switchToWeek(h,g);return true;}if(j===a.__MONTHS_BTN||j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 4");
}this.switchToMonth(h,g);return true;}if(j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 7");
}this.switchToDay(h,g);return true;}if(o>0&&o<a.__HOUR_MODE_SWITCH_POINT_MIN&&i<a.__HOUR_GRANULARITY){if(window.console&&window.console.log){window.console.log("### reformatTimeline ACTION: switchToMinute 1");
}this.switchToMinute(h,g);return true;}if(o>=a.__HOUR_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 4");
}this.switchToDay(h,g);return true;}if(j===a.__HOUR_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 5 (IN HOUR, STAY IN HOUR)");
}this.switchToHour(h,g,p,l);return true;}}else{if(k===a.__DAY_FORMAT){if(j===a.__MINUTES_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 2");
}this.switchToMinute(h,g);return true;}if(j===a.__MONTHS_BTN||j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 1");
}this.switchToMonth(h,g);return true;}if(o>0&&o<a.__DAY_MODE_SWITCH_POINT_MIN&&i<a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("### reformatTimeline ACTION: switchToHour 1");
}this.switchToHour(h,g);return true;}if(o>=a.__DAY_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 1");
}this.switchToWeek(h,g);return"switchToWeek 1";}if(j===a.__DAY_GRANULARITY){if(o===-1){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 5b (IN DAY, STAY IN DAY) - ACCEPT SWITCH");
}this.switchToDay(h,g,p,l);return true;}else{if(h<q||g>m){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 5a (IN DAY, STAY IN DAY) - ACCEPT SWITCH");
}this.switchToDay(h,g);return true;}else{if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 5 - REJECT SWITCH");
}return false;}}}if(j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 7 pNumMinutes=",o);
}this.switchToWeek(h,g);return true;}}else{if(k===a.__WEEK_FORMAT){if(j===a.__MINUTES_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 3");
}this.switchToMinute(h,g);return true;}if(j===a.__HOURS_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 2");
}this.switchToHour(h,g);return true;}if(o>0&&o<a.__WEEK_MODE_SWITCH_POINT_MIN&&i<a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 1");
}this.switchToDay(h,g);return true;}if(o>a.__WEEK_MODE_SWITCH_POINT_MAX){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 2");
}this.switchToMonth(h,g);return true;}if(j===a.__WEEK_GRANULARITY){if(o===-1){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 2b (IN WEEK, STAY IN WEEK) - ACCEPT SWITCH");
}this.switchToWeek(h,g,p,l);return true;}else{if(h<q||g>m){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 2a (IN WEEK, STAY IN WEEK) - ACCEPT SWITCH");
}this.switchToWeek(h,g);return true;}else{if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 2 - REJECT SWITCH");
}return false;}}}if(j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 2 ");
}this.switchToDay(h,g);return true;}if(j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 6 pNumMinutes=",o);
}this.switchToMonth(h,g);return true;}}else{if(k===a.__MONTH_FORMAT){if(j===a.__MINUTES_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMinute 4");
}this.switchToMinute(h,g);return true;}if(j===a.__DAYS_BTN||j===a.__DAY_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToDay 3");
}this.switchToDay(h,g);return true;}if(j===a.__HOURS_BTN){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToHour 3");
}this.switchToHour(h,g);return true;}if(o>0&&o<a.__MONTH_MODE_SWITCH_POINT_MIN&&i<a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("---> reformatTimeline ACTION: switchToWeek 3  pNumMinutes=",o);
}this.switchToWeek(h,g);return true;}if(j===a.__MONTH_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToMonth 3 (IN MONTH, STAY IN MONTH)");
}this.switchToMonth(h,g);return true;}if(j===a.__WEEK_GRANULARITY){if(window.console&&window.console.log){window.console.log("reformatTimeline ACTION: switchToWeek 4 pNumMinutes=",o);
}this.switchToWeek(h,g);return true;}}}}}}return false;};return c;});