define("calendar/datepicker",["util/Date"],function(h){var i=31;var j=12;var F=12;var u=false;var e=false;var q=[],l=new Date(),C={current:{year:function(){return l.getFullYear();
},month:{integer:function(){return l.getMonth();},string:function(K,I){var J=l.getMonth();return E(J,K,I);}},day:function(){return l.getDate();
}},month:{string:function(K,L,I){var J=L;return E(J,K,I);},numDays:function(J,I){return(J===1&&!(I&3)&&(I%100||!(I%400)))?29:a[J];
}}},a=[31,28,31,30,31,30,31,31,30,31,30,31],B=[],s={calendarClick:function(L){if(L.target.className){switch(L.target.className){case"prev-month":case"prevMonth":this.currentMonthView--;
if(this.currentMonthView<0){this.currentYearView--;this.currentMonthView=11;}z.call(this);break;case"next-month":case"nextMonth":this.currentMonthView++;
if(this.currentMonthView>11){this.currentYearView++;this.currentMonthView=0;}z.call(this);break;case"day":var I=this.currentMonthView;
if(L.target.parentNode.className==="prev-day"){I-=1;}if(L.target.parentNode.className==="next-day"){I+=1;}var K=new Date(this.currentYearView,I,L.target.innerHTML);
this.chosenDate=h.toFormattedString(K);this.element.value=p(K.getTime(),this.config);if("createEvent" in document){var J=document.createEvent("HTMLEvents");
J.initEvent("change",false,true);this.element.dispatchEvent(J);}else{this.element.fireEvent("onchange");}z.call(this);this.close();
break;}}},documentClick:function(J){if(J.target!=this.element&&J.target!=this.calendar&&J.target!==this.icon){var I=J.target.parentNode;
if(I!=this.calender){while(I!=this.calendar){I=I.parentNode;if(I===null){this.close();break;}}}}}};function p(L,K){var N="",I=new Date(L),M={d:function(){var O=M.j();
return(O<10)?"0"+O:O;},D:function(){return K.weekdays[M.w()].substring(0,3);},j:function(){return I.getDate();},l:function(){return K.weekdays[M.w()];
},S:function(){return K.suffix[M.j()]||K.defaultSuffix;},w:function(){return I.getDay();},F:function(){return E(M.n(),true,K.months);
},m:function(){var O=M.n()+1;return(O<10)?"0"+O:O;},M:function(){return E(M.n(),false,K.months);},n:function(){return I.getMonth();
},Y:function(){return I.getFullYear();},y:function(){return M.Y().toString().substring(2,4);}},J=K.dateFormat.split("");r(J,function(P,O){if(M[P]&&J[O-1]!=="\\"){N+=M[P]();
}else{if(P!=="\\"){N+=P;}}});return N;}function r(J,L){var K=0,I=J.length;for(K;K<I;K++){if(L(J[K],K)===false){break;}}}function t(K,J,L){if(K.addEventListener){K.addEventListener(J,L,false);
}else{if(K.attachEvent){var I=function(M){M=M||window.event;M.preventDefault=(function(N){return function(){N.returnValue=false;
};})(M);M.stopPropagation=(function(N){return function(){N.cancelBubble=true;};})(M);M.target=M.srcElement;L.call(K,M);};
K.attachEvent("on"+J,I);}}}function x(J,I,K){if(J.removeEventListener){J.removeEventListener(I,K,false);}else{if(J.detachEvent){J.detachEvent("on"+I,K);
}}}function g(M,I,L){var J;if(!(M in B)){B[M]=document.createElement(M);}J=B[M].cloneNode(false);if(I){for(var K in I){J[K]=I[K];
}}if(L){if(typeof(L)==="object"){J.appendChild(L);}else{J.innerHTML=L;}}return J;}function E(J,K,I){return((K===true)?I[J]:((I[J].length>3)?I[J].substring(0,3):I[J]));
}function H(I,K,J){return I===C.current.day()&&K===C.current.month.integer()&&J===C.current.year();}function d(L,K,J,N){var P=this.chosenDate.split("-");
var I=Number(P[2]);var O=Number(P[1])-1;var M=Number(P[0]);if(I===L&&O===K&&M===Number(J)){return true;}return false;}function w(J,P,O,L){var I=(L)?0:1;
var K=new Date(O,P,J);var N=new Date();N.setDate(N.getDate()-I);var M;if(e){M=new Date(N.getFullYear(),N.getMonth()-(11+I));
}else{M=new Date(N.getFullYear(),N.getMonth(),N.getDate());M.setMonth(M.getMonth()-F);M.setHours(0,0,0,0);}return(K>N||K<M);
}function G(I){var J=document.createDocumentFragment();r(I,function(K){J.appendChild(g("th",{},K.substring(0,2)));});return J;
}function z(){while(this.calendarBody.hasChildNodes()){this.calendarBody.removeChild(this.calendarBody.lastChild);}this.chosenDate=this.element.value;
var J=new Date(this.currentYearView,this.currentMonthView,1).getDay(),I=C.month.numDays(this.currentMonthView,this.currentYearView);
this.currentMonth.innerHTML=C.month.string(this.config.fullCurrentMonth,this.currentMonthView,this.config.months)+" "+this.currentYearView;
this.calendarBody.appendChild(v.call(this,J,I,this.currentMonthView,this.currentYearView,this.config.useToday,this.calendarBody,"rebuildCalendar"));
}function b(J,L,K,I){return g("span",{className:"current-month"},C.month.string(J.fullCurrentMonth,L,I)+" "+K);}function c(J,N,M){var I=g("div",{className:"months"}),L=g("span",{className:"prev-month"},g("span",{className:"prevMonth"},"&lt;")),K=g("span",{className:"next-month"},g("span",{className:"nextMonth"},"&gt;"));
I.appendChild(L);I.appendChild(K);return I;}function v(ab,I,Y,ak,aj,V,W){var U=document.createDocumentFragment(),O=g("tr"),ae=0,ah,ac,al=0,J;
var N=new Date(ak,Y,1);for(ah=1;ah<=ab;ah++){var ai=new Date(ak,Y,N.getDate()-((ab+1)-ah));var X=ai.getDate();var S="prev-day";
ac=w(X,ai.getMonth(),ai.getFullYear(),aj)?"out-of-range":null;J=d.call(this,X,ai.getMonth(),ai.getFullYear())?"chosen":null;
if(ac){S=S+" "+ac;}if(J){S=S+" "+J;}var aa={className:S};O.appendChild(g("td",aa,g("span",{className:"day"},X)));ae++;}for(ah=1;
ah<=I;ah++){if(ae===7){U.appendChild(O);O=g("tr");ae=0;}var Z=H(ah,Y,ak)?"today":null;ac=w(ah,Y,ak,aj)?"out-of-range":null;
J=d.call(this,ah,Y,ak)?"chosen":null;var L=(Z)?Z:null;if(ac){if(L){L=L+" "+ac;}else{L=ac;}al++;}if(J){L=L+" "+J;}var K=(L)?{className:L}:null;
O.appendChild(g("td",K,g("span",{className:"day"},ah)));ae++;}var af=new Date(ak,Y,ah-1);if(al===I){var R;var Q=A(h.toFormattedString(af),aj);
if(Q){if(V.parentNode){R=V.parentNode.parentNode.getElementsByClassName("next-month")[0];R.className=R.className+" disabled";
}}else{if(V.parentNode){R=V.parentNode.parentNode.getElementsByClassName("prev-month")[0];R.className=R.className+" disabled";
}}}else{if(V.parentNode){var ag=V.parentNode.parentNode.getElementsByClassName("next-month")[0];ag.className="next-month";
var P=V.parentNode.parentNode.getElementsByClassName("prev-month")[0];P.className="prev-month";}}for(ah=1;ah<=(7-ae);ah++){var M="next-day";
ac=w(af.getDate()+ah,Y,ak,aj)?"out-of-range":null;var T=new Date(ak,Y,af.getDate()+ah);J=d.call(this,T.getDate(),T.getMonth(),T.getFullYear())?"chosen":null;
if(ac){M=M+" "+ac;}if(J){M=M+" "+J;}var ad={className:M};O.appendChild(g("td",ad,g("span",{className:"day"},ah)));}U.appendChild(O);
return U;}function o(){this.chosenDate=this.element.value;var J=new Date(this.currentYearView,this.currentMonthView,1).getDay(),M=C.month.numDays(this.currentMonthView,this.currentYearView),P=this;
var O=0,N=0,L=this.element;if(L.offsetParent){do{O+=L.offsetLeft;N+=L.offsetTop;L=L.offsetParent;}while(L);}var Q=g("div",{className:"calendar"});
Q.style.cssText="display: none; position: absolute; top: "+(N+this.element.offsetHeight)+"px; left: "+O+"px; z-index: 100;";
this.currentMonth=b(this.config,this.currentMonthView,this.currentYearView,this.config.months);var I=c(this.config,this.currentMonthView,this.currentYearView);
I.appendChild(this.currentMonth);var K=g("table",{className:"datepicker-table"},g("thead",null,g("tr",{className:"weekdays"},G(this.config.weekdays))));
this.calendarBody=g("tbody");this.calendarBody.appendChild(v.call(this,J,M,this.currentMonthView,this.currentYearView,this.config.useToday,this.calendarBody,"buildCalendar"));
K.appendChild(this.calendarBody);Q.appendChild(I);Q.appendChild(K);document.body.appendChild(Q);t(Q,"click",function(R){s.calendarClick.call(P,R);
});return Q;}function A(K,R,Q){var M=new Date(K);M.setHours(0,0,0,0);var I=(R)?0:1;var O=new Date();var P=new Date(O.getFullYear(),O.getMonth(),O.getDate()-I);
if(R){if(Q==="month"){var L=new Date(O.getFullYear(),O.getMonth()+1);return(M>L);}else{if(Q==="week"){var N=new Date(O.getFullYear(),O.getMonth(),P.getDate()+7);
var J=N.getDay();N.setDate(N.getDate()-J);return(M>N);}}}return(M>P);}function f(K,L){var J=new Date(K);J.setHours(0,0,0,0);
var I=(L)?0:1;var N=new Date();N.setDate(N.getDate()-I);var M;if(e){M=new Date(N.getFullYear(),N.getMonth()-(11+I));}else{M=new Date(N.getFullYear(),N.getMonth(),N.getDate());
M.setMonth(M.getMonth()-F);M.setHours(0,0,0,0);}return(J<M);}function k(L,J){var I=new Date(L);I.setHours(0,0,0,0);var K=new Date(J);
K.setHours(0,0,0,0);if(e){return(I<=K);}else{return(I<K);}}function D(S){try{var R=2;var K=1;var L=0;S=S.replace(/-/g,"/").replace(/\./g,"/");
var N=S.split("/");var M=true;if(!(N[R].length===1||N[R].length===2)){M=false;}if(M&&!(N[K].length===1||N[K].length===2)){M=false;
}if(M&&N[L].length!==4){M=false;}if(M){var Q=parseInt(N[R],10);var O=parseInt(N[K],10);var I=parseInt(N[L],10);if(I>1900&&I<9999){M=true;
if(O<=12&&O>0){M=true;var J=(((I%4)===0)&&((I%100)!==0)||((I%400)===0));if(O===2){M=J?Q<=29:Q<=28;}else{if((O===4)||(O===6)||(O===9)||(O===11)){M=(Q>0&&Q<=30);
}else{M=(Q>0&&Q<=31);}}}else{M=false;}}else{M=false;}}return M;}catch(P){return false;}}function n(K,J){var N=new Date(J);
N.setHours(0,0,0,0);N.setDate(N.getDate()-1);if(K==="day"){N.setDate(N.getDate()-i);}else{if(K==="week"){N.setDate(N.getDate()-j*7);
}else{N.setMonth(N.getMonth()-F);}}var I=N.getDate();var L=N.getMonth()+1;var M=N.getFullYear();if(I<10){I="0"+I;}if(L<10){L="0"+L;
}return M+"-"+L+"-"+I;}function m(J,I){if(I){I.innerHTML=J;}}var y=function(K,N,O,L,J){var I=this;this.element=K;u=(typeof J!=="undefined")?true:false;
e=(typeof N.linkedToTimeline!=="undefined")?N.linkedToTimeline:true;this.inputLeft=0;this.inputTop=0;this.config={fullCurrentMonth:true,dateFormat:"F jS, Y",weekdays:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],months:["January","February","March","April","May","June","July","August","September","October","November","December"],suffix:{1:"st",2:"nd",3:"rd",21:"st",22:"nd",23:"rd",31:"st"},defaultSuffix:"th",useToday:true};
this.currentYearView=C.current.year();this.currentMonthView=C.current.month.integer();if(N){for(var M in N){if(this.config.hasOwnProperty(M)){this.config[M]=N[M];
}}}this.documentClick=function(P){s.documentClick.call(I,P);};this.open=function(S){var R=0,P=0,Q=I.element;if(I.inputLeft===0){if(Q.offsetParent){do{R+=Q.offsetLeft;
P+=Q.offsetTop;Q=Q.offsetParent;}while(Q);}I.inputLeft=R;I.inputTop=P;I.calendar.style.left=I.inputLeft+"px";I.calendar.style.top=I.inputTop+I.element.offsetHeight+"px";
}t(document,"click",I.documentClick);r(q,function(T){if(T!=I){T.close();}});I.calendar.style.display="block";};this.close=function(){x(document,"click",I.documentClick);
I.calendar.style.display="none";};this.calendar=o.call(this);q.push(this);if(O){this.errorField=O;}if(L){this.icon=L;t(L,"click",this.open);
}else{if(this.element.nodeName.toLowerCase()==="input"){t(this.element,"focus",this.open);}else{t(this.element,"click",this.open);
}}this.clearMessage=function(){m("",I.errorField);};this.updateMonth=function(Q,P){this.currentMonthView=Q;this.currentYearView=P;
z.call(this);};this.checkDate=function(U){var P=U.data.startDate.value;var S=U.data.endDate.value;var V=U.data.callback;var R=U.data.useToday;
var T=U.data.granularity;var Q=(R)?"today.":"yesterday.";if(!D(P)){m("The start date either doesn't exist or is not in a valid format, please check the format: yyyy-mm-dd.",I.errorField);
return false;}if(!D(S)){m("The end date either doesn't exist or is not in a valid format, please check the format: yyyy-mm-dd.",I.errorField);
return false;}if(A(P,R,T)){m("The start date is set in the future, data can only be shown up until "+Q,I.errorField);return false;
}if(A(S,R,T)){m("The end date is set in the future, data can only be shown up until "+Q,I.errorField);return false;}if(f(P,R)){m("The start date is more than 1 year in the past.",I.errorField);
return false;}if(!k(P,S)){if(e){m("The start date is set after the end date, please make sure the start date is before (or the same as) the end date.",I.errorField);
}else{m("The start date is set after (or is the same as) the end date, please make sure the start date is before the end date.",I.errorField);
}return false;}m("",I.errorField);if(!u){V(P,S);return true;}var W;if(k(n("day",S),P)){W="day";V(P,S,W);}else{if(k(n("week",S),P)){W="week";
V(P,S,W);}else{if(k(n("month",S),P)){W="month";V(P,S,W);}}}};this.checkDateSingle=function(T){var P=T.data.startDate.value;
var U=T.data.callback;var R=T.data.useToday;var S=T.data.granularity;var Q=(R)?"today.":"yesterday.";if(!D(P)){m("The start date either doesn't exist or is not in a valid format, please check the format: yyyy-mm-dd.",I.errorField);
return false;}if(A(P,R,S)){m("The start date is set in the future, data can only be shown up until "+Q,I.errorField);return false;
}if(f(P,R)){m("The start date is more than 1 year in the past.",I.errorField);return false;}m("",I.errorField);U(P);return true;
};this.checkGranularity=function(Q,S,P){var R=n(P,S);if(!k(R,Q)){m("The time period is too long for this step size.",I.errorField);
return false;}else{m("",I.errorField);return true;}};};return y;});