define("conversion/collections/mapdata",["jquery","underscore","backbone","map/models/region","chartutil/objectutils","chartlib/events/appstateevents","map/collections/mapdata"],function(f,a,h,e,g,c,d){var b=d.extend({formatRegion:function(m){var i=m.attr("toolText").match(/([^\s]+)/);
var l=i===null?0:+i[0];var j=m.attr("link");var k=typeof j==="undefined"?{}:{statsType:j.split(",")[1],region:j.split(",")[2]};
var n=m.attr("toolText").match(/(from|in) (.*)/);return new e({regionName:n[2],total:l,link:k});}});return b;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);
}});define("conversion/models/country",["jquery","underscore","backbone","backbonenested"],function(c,a,e,d){var b=e.NestedModel.extend({defaults:{countryName:"",total:0,conversionRates:[]}});
return b;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/collections/merchantdata",["jquery","underscore","backbone","conversion/models/country"],function(b,a,e,c){var d=e.Collection.extend({model:c,reverseDirection:true,conversionTypes:["Authorised","Completed","Abandoned"],initialize:function(){a.bindAll(this,"getReverseDirection");
},sortByMerchant:function(){this.comparator=this.compareFunction;this.reverseDirection=!this.reverseDirection;this.sortKey="name";
this.sort();},sortByVolume:function(){this.comparator=this.compareFunction;this.reverseDirection=!this.reverseDirection;this.sortKey="total";
this.sort();},sortByAuth:function(){this.comparator=this.comparePercentage;this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";
this.sortSubKey="authorised";b(this.models).each(b.proxy(function(h,g){var j=g.get(this.sortKey);var k=a.findWhere(j,{name:this.sortSubKey});
var f=j.indexOf(k);j.splice(0,0,j.splice(f,1)[0]);},this));this.sort();},sortByComp:function(){this.comparator=this.comparePercentage;
this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";this.sortSubKey="completed";b(this.models).each(b.proxy(function(h,g){var j=g.get(this.sortKey);
var k=a.findWhere(j,{name:this.sortSubKey});var f=j.indexOf(k);j.splice(0,0,j.splice(f,1)[0]);},this));this.sort();},sortByAban:function(){this.comparator=this.comparePercentage;
this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";this.sortSubKey="abandoned";b(this.models).each(b.proxy(function(h,g){var j=g.get(this.sortKey);
var k=a.findWhere(j,{name:this.sortSubKey});var f=j.indexOf(k);j.splice(0,0,j.splice(f,1)[0]);},this));this.sort();},getReverseDirection:function(){return this.reverseDirection;
},compareFunction:function(g,f){var i=g.get(this.sortKey),h=f.get(this.sortKey);if(this.reverseDirection){if(i>h){return -1;
}if(h>i){return 1;}return 0;}else{if(i<h){return -1;}if(h<i){return 1;}return 0;}},comparePercentage:function(h,f){var l=h.get(this.sortKey),j=f.get(this.sortKey);
var m=a.findWhere(l,{name:this.sortSubKey});var k=a.findWhere(j,{name:this.sortSubKey});var i=m.value/h.get("total");var g=k.value/f.get("total");
if(this.reverseDirection){if(i>g){return -1;}if(g>i){return 1;}return 0;}else{if(i<g){return -1;}if(g<i){return 1;}return 0;
}}});return d;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/models/conversiontime",["jquery","underscore","backbone","backbonenested"],function(b,a,e,c){var d=e.NestedModel.extend({defaults:{date:0,total:0,conversionRates:[]}});
return d;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/models/company",["jquery","underscore","backbone","backbonenested"],function(b,a,e,c){var d=e.NestedModel.extend({defaults:{name:"",total:0,conversionRates:[],merchants:[]}});
return d;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/views/charts/volumetime",["jquery","underscore","backbone","d3","chartlib/vertstacked","chartlib/events/appstateevents","backbonesuper","chartutil/d3utils"],function(a,g,f,h,b,c,d,i){var e=b.extend({el:".volumetime-chart",granularityFormats:[],defaults:{margin:{top:5,left:45,bottom:20,right:0},xAttr:"date",yAttr:"total",yNestAttr:"conversionRates",percentile:false,xScale:"linear",yScale:"linear",barPadding:0.1,tooltip:true},initialize:function(){g.bindAll(this,"formatXAxis");
this.granularityFormats.day="%d";this.granularityFormats.week="wk %W";this.granularityFormats.month="%b";this._super();},addListeners:function(){f.on(c.RENDER_CHARTS,this.render);
},setXScale:function(){this.scales.x=h.time.scale().range([0,this.width],this.options.barPadding);},calibrateXScale:function(){var j=this,k=this.collection.granularity;
this.scales.x.ticks(h.time[k],1);this.scales.x.tickFormat(j.granularityFormats[k]);this.scales.x.domain(h.extent(this.collection.models,function(l){return j.getX(l);
}));},formatXAxis:function(){},formatYAxis:function(){var k=this,j=this.axes.y;j.ticks(5).tickFormat(function(m,l){return i.thousandsFormatter(m,l,k.scales.y);
});},render:function(){if(this.collection.total>0){this._super(arguments);}},renderTooltipContent:function(j){this.tip.html(function(){return"<strong>"+j.name+":</strong> <span>"+j.value+"</span>";
});},renderXAxis:function(){var l=this.axes.x,m=this.collection.granularity,k=this;l.scale(this.scales.x).tickSize(0).ticks(h.time[m+"s"],1).tickFormat(function(p,n){if(m==="week"){return"wk "+p.getWeek(true);
}var o=h.time.format(k.granularityFormats[m]);return o(p);});this.xAxis.call(l).transition().duration(500).delay(500).ease("exp-in-out").attr("transform","translate( 0,"+this.height+")");
var j=(this.width/this.collection.length);this.xAxis.selectAll(".tick").attr("transform",function(o,n){return"translate("+((j*(n+1))-(j/2))+",0)";
}).select("text").attr("y",10);},renderYAxis:function(){this.formatYAxis();this._super();},renderData:function(){var n=this,q=this.scales.x,o=this.scales.y,l=this.options.percentile,k=(this.width/this.collection.length),r=k*(1-this.options.barPadding);
n.collection.models.forEach(function(t){var s=0;a.each(t.get(n.options.yNestAttr),function(u,v){if(!l){v.startY=s;v.endY=(s+v.value);
}else{v.startY=s/t.get("total");v.endY=(s+v.value)/t.get("total");}s+=v.value;});});var m=this.svg.selectAll(".bar").data(n.collection.models);
m.enter().append("g").attr("class","bar").attr("transform",function(t,s){return"translate("+((k*(s+1))-(k/2))+",0)";});m.transition().delay(500).attr("transform",function(t,s){return"translate("+((k*(s+1))-(k/2))+",0)";
});var p=m.selectAll("rect").data(function(s){return s.get(n.options.yNestAttr);},function(s){return s.name;});p.enter().append("rect").attr("class",function(s){return"stack "+s.name;
}).attr("width",r).attr("height",0).attr("y",function(s){return o(s.startY);}).attr("transform",function(t,s){return"translate(-"+(r/2)+",0)";
}).transition().duration(500).delay(function(t,s){return 500+(s*500);}).attr("y",function(s){return o(s.endY);}).attr("height",function(s){return o(s.startY)-o(s.endY);
});if(this.options.tooltip){m.classed("active",true);p.on("mouseover",function(s){n.showTooltip(s,this,false);}).on("mouseout",this.tip.hide).classed("active",true);
}p.attr("transform",function(t,s){return"translate(-"+(r/2)+",0)";}).transition().duration(500).delay(function(t,s){return 500+(s*500);
}).attr("width",r).attr("y",function(s){return o(s.endY);}).attr("height",function(s){return o(s.startY)-o(s.endY);});var j=m.exit().transition();
j.attr("transform",function(s){return"translate(0,0)";}).select("rect").attr("width",0);j.remove();}});return e;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);
}});define("conversion/views/charts/conversionrates",["jquery","underscore","backbone","chartlib/stackedbarchart","chartlib/events/appstateevents","d3","chartutil/numberutils"],function(g,a,h,b,d,c,f){var e=b.extend({el:".conversionrates-chart",defaults:{yScale:"ordinal",totalLabelOffset:70,margin:{top:0,left:10,bottom:20,right:20},barPadding:0.1,xAttr:"total",yAttr:"countryName",joinAttr:"countryName",xNestAttr:"conversionRates",tooltip:true},addListeners:function(){if(this.collection){this.listenTo(this.collection,"sort",this.render);
}h.on(d.RENDER_CHARTS,this.render);},render:function(){if(this.collection.total>0){this._super(arguments);}},renderTooltipContent:function(i){this.tip.html(function(k){var j=c.format("0,000");
var l=j(k.value);if(typeof window.SVGElement==="undefined"){return"<strong>"+i.pmName+" - "+i.name+":</strong> <span>"+f.decimalFormatter(i.width*100)+"%</span>";
}return"<strong>"+i.name+":</strong> <span>"+f.decimalFormatter(i.width*100)+"%</span> ("+l+" sessions)";});this.tip.direction("n");
this.tip.offset([-10,0]);},renderXAxis:function(){this._super();this.xAxis.selectAll("text").attr("transform",function(){return"translate(0,7)";
});},renderYAxis:function(){}});return e;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);
}});define("conversion/views/charts/companytotalbar",["jquery","underscore","chartlib/stackedbarchart","d3","chartutil/numberutils"],function(e,a,b,c,d){var f=b.extend({renderXAxis:function(){},renderYAxis:function(){},renderTooltipContent:function(h){var g=this;
this.tip.html(function(){return"<strong>"+h.name+":</strong> <span>"+d.decimalFormatter(h.width*100)+"%</span>";});},renderData:function(){b.prototype.renderData.apply(this,arguments);
var h=this,g=this.scales.x,j=this.scales.y;var i=this.svg.selectAll(".bar").selectAll("text").data(this.collection.models,this.joinData);
i.enter().append("text").attr("class","company total-text").attr("x",0).style("text-anchor","start").text(function(k){return k.get("total");
}).transition().delay(500).duration(500).attr("x",function(k){return g(1)+10;}).attr("y",8);}});return f;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);
}});define("conversion/views/charts/countryvolume",["jquery","underscore","backbone","chartlib/barchart","chartlib/events/appstateevents","d3","chartutil/d3utils"],function(g,a,h,f,e,d,c){var b=f.extend({el:".countryvolume-chart",defaults:{yScale:"ordinal",totalLabelOffset:70,margin:{top:0,left:90,bottom:20,right:5},barPadding:0.1,xAttr:"total",yAttr:"countryName",joinAttr:"countryName",tooltip:true,showTipFromText:true},addListeners:function(){if(this.collection){this.listenTo(this.collection,"sort",this.render);
}h.on(e.RENDER_CHARTS,this.render);},renderTooltipContent:function(j){var i=this;this.tip.html(function(k){return"<strong>"+i.getY(j)+":</strong> <span>"+i.getX(j)+"</span>";
});this.tip.direction("n");this.tip.offset([-10,0]);},formatXAxis:function(){var i=this,j=this.axes.x;j.tickFormat(function(l,k){return c.thousandsFormatter(l,k,i.scales.x);
});},render:function(){if(this.collection.total>0){this._super(arguments);}},renderXAxis:function(){this._super();this.xAxis.selectAll("text").attr("transform",function(){return"translate(0,7)";
});},formatYAxis:function(){var i=this.axes.y;i.tickFormat(function(j){return(j.length>14)?g.trim(j).substring(0,11).trim(this)+"...":j;
});}});return b;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);}});define("conversion/views/ui/merchantui",["jquery","underscore","backbone","chartlib/ui/baseui"],function(d,b,e,c){var a=c.extend({initialize:function(){b.bindAll(this,"sortOnVolume","sortOnMerchant","sortOnAuth","sortOnComp","sortOnAban");
this.listenTo(this.collection,"reset",this.render);this.merchantButton=this.$el.find(".merchantui.sort-merchant-button");
this.volumeButton=this.$el.find(".merchantui.sort-volume-button");this.authButton=this.$el.find(".sort-auth-button");this.compButton=this.$el.find(".sort-comp-button");
this.abanButton=this.$el.find(".sort-aban-button");this.buttons.push(this.merchantButton);this.buttons.push(this.volumeButton);
this.buttons.push(this.authButton);this.buttons.push(this.compButton);this.buttons.push(this.abanButton);this.volumeButton.on("click",this.sortOnVolume);
this.merchantButton.on("click",this.sortOnMerchant);this.authButton.on("click",this.sortOnAuth);this.compButton.on("click",this.sortOnComp);
this.abanButton.on("click",this.sortOnAban);},sortOnVolume:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByVolume();
},sortOnMerchant:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByMerchant();},sortOnAuth:function(f){this.renderButtons(d(f.currentTarget));
this.collection.sortByAuth();},sortOnComp:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByComp();
},sortOnAban:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByAban();}});return a;});define("conversion/views/company",["jquery","underscore","backbone","chartlib/ui/collapsibleview","conversion/views/charts/countryvolume","conversion/views/charts/conversionrates","conversion/views/ui/merchantui","conversion/views/charts/companytotalbar"],function(c,h,g,e,d,i,f,b){var a=e.extend({tagName:"li",className:"panel companies-list company",constructor:function(){this.collapsible=[];
this.collapsed=true;e.apply(this,arguments);},render:function(){this.collection=this.model.get("merchants");this.renderHeader();
this.renderIcon();this.renderTotalBar();this.renderUI();this.renderCompanyChart();this.renderConversionChart();this.collection.trigger("sort");
this.resizeContainers();e.prototype.render.apply(this,arguments);if(this.collection.total<=0){this.disable();}return this;
},renderHeader:function(){this.header=c("<div></div>");this.header.addClass("header");var j=c("<h2></h2>");j.text(this.model.get("name"));
this.header.append(j);this.$el.append(this.header);},renderIcon:function(){this.icon=c("<div></div>");this.icon.addClass("arrow");
this.header.append(this.icon);},renderTotalBar:function(){var l=100;var k=((this.model.get("total")/this.options.total)*700)+l;
var m=c("<div></div>");m.addClass("total-bar");m.width(k);this.header.append(m);var n=new g.Collection();var j=new b({el:m,collection:n,yScale:"ordinal",totalLabelOffset:70,margin:{top:0,left:0,bottom:0,right:l},barPadding:0.1,xAttr:"value",yAttr:"total",joinAttr:"name",xNestAttr:"conversionRates",tooltip:true});
this.model.get("conversionRates").reverse();n.reset(this.model);},renderUI:function(){this.content=c("<div></div>");this.content.addClass("content");
this.$el.append(this.content);this.collapsible.push(this.content);this.ui=c('<div id="merchantUI" class="ui"><button id="sortMerchantBtn" class="merchantui sort-button sort-merchant-button"><i class="arrow"></i>Merchant</button><button id="sortVolumeBtn" class="merchantui sort-button sort-volume-button"><i class="arrow"></i>Volume</button><button id="sortAuthBtn" class="merchantui sort-button sort-auth-button"><i class="arrow"></i>Authorised</button><button id="sortCompBtn" class="merchantui sort-button sort-comp-button"><i class="arrow"></i>Completed</button><button id="sortAbanBtn" class="merchantui sort-button sort-aban-button"><i class="arrow"></i>Abandoned</button></div>');
var j=new f({el:this.ui,collection:this.model.get("merchants")});this.content.append(j.el);},renderCompanyChart:function(){var j=c("<div></div>");
j.addClass("company-chart");this.content.append(j);this.companyChart=new d({el:j[0],collection:this.model.get("merchants"),margin:{top:10,left:100,bottom:30,right:10},barPadding:0.2,barHeight:15,xAttr:"total",yAttr:"name",joinAttr:"name",yScale:"ordinal",tooltip:true});
},renderConversionChart:function(){var j=c("<div></div>");j.addClass("conversionrates-chart");this.content.append(j);this.conversionRates=new i({el:j[0],collection:this.model.get("merchants"),yScale:"ordinal",totalLabelOffset:70,margin:{top:10,left:10,bottom:30,right:20},barPadding:0.2,barHeight:15,xAttr:"total",yAttr:"name",joinAttr:"name",xNestAttr:"conversionRates",tooltip:true});
},resizeContainers:function(){var j=[this.companyChart,this.conversionRates];c.each(j,function(k,l){l.$el.height((l.collection.length*l.options.barHeight)+l.options.margin.top+l.options.margin.bottom);
});}});return a;});define("conversion/models/merchant",["jquery","underscore","backbone","backbonenested"],function(b,a,e,c){var d=e.NestedModel.extend({defaults:{name:"",total:0,conversionRates:[]}});
return d;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/collections/conversiontimedata",["jquery","underscore","backbone","d3","conversion/models/conversiontime","chartlib/events/appstateevents","chartlib/chartBaseEvents","chartutil/dateUtils_CET"],function(d,h,g,i,a,e,f,c){var b=g.Collection.extend({model:a,percentages:[],granularityFormats:[],granularity:"",year:"",statsType:"CONVERSION_PER_TIMEINTERVAL",total:0,initialize:function(){h.bindAll(this,"parse","calculateTotalPercentages","loadRegion","onLoaded","onError");
this.granularityFormats.day="%b %d";this.granularityFormats.week="%Y wk%W %w";this.granularityFormats.month="%b'%y";g.on(e.STATE_CHANGED,this.loadRegion);
},loadRegion:function(k){this.loaded=d.Deferred();this.total=0;var j=h.pick(k.attributes,"region","ccs","granularity","bdate","edate");
j.statsType=this.statsType;this.url=(k.get("stub"))?adyen.jsbase+"/chart/charts/mainConversion/dummy-data/conversionTime.xml?"+new Date().getTime():k.get("url")+d.param(j)+"&cb="+new Date().getTime();
this.granularity=k.get("granularity");this.beginYear=i.time.format("%Y-%m-%d").parse(k.get("bdate")).getFullYear();this.endYear=i.time.format("%Y-%m-%d").parse(k.get("edate")).getFullYear();
this.fetch({reset:true});},fetch:function(j){j||(j={});j.dataType="xml";j.success=this.onLoaded;j.error=this.onError;this._super(j);
g.trigger(f.REGISTER_DEFERRED,this.loaded,"conversionTimeData",this);},parse:function(p){var n=this,k=[],l,o,m,j=false;d(p).find("category").each(function(s,u){o=d(u);
l=o.attr("label");var t=new a();d(p).find("dataset").each(function(w,y){y=d(y);m=Math.max(0,+y.find('[toolText*="'+l+'"]').attr("value"));
t.set("total",t.get("total")+m);t.get("conversionRates").push({name:y.attr("seriesName").toLowerCase(),value:m});});if(n.granularity==="week"){var r=+l.replace("wk","");
t.set("date",c.getDateOfISOWeek(r,n.beginYear));}else{t.set("date",i.time.format(n.granularityFormats[n.granularity]).parse(l));
}if(n.granularity!=="month"){var q=d(k).get(s-1);if(q&&q.get("date").getMonth()>t.get("date").getMonth()&&j===false){j=true;
}if(j){t.get("date").setFullYear(n.endYear);}else{t.get("date").setFullYear(n.beginYear);}if(n.granularity==="week"){var v=t.get("date").getDay();
if(v!==0){c.trueRoundToWeek(t.get("date"));}}}k.push(t);});this.calculateTotalPercentages(k);if(this.total<=0){this.trigger(f.DATA_FAILED);
}return k;},calculateTotalPercentages:function(l){this.percentages=[];this.total=0;var k=0;var j=0;var m=0;d(l).each(d.proxy(function(n,o){this.total+=Math.max(0,o.get("total"));
d(o.get("conversionRates")).each(function(p,q){switch(q.name){case"authorised":k+=Math.max(0,q.value);break;case"completed":j+=Math.max(0,q.value);
break;case"abandoned":m+=Math.max(0,q.value);break;}});},this));this.percentages.push({name:"authorised",percentage:this.total>0?(k/this.total):0});
this.percentages.push({name:"completed",percentage:this.total>0?(j/this.total):0});this.percentages.push({name:"abandoned",percentage:this.total>0?(m/this.total):0});
this.percentages=h.sortBy(this.percentages,function(n){return n.percentage;});this.percentages.unshift({name:"total",percentage:1});
},getTotalPercentages:function(){return this.percentages;},onError:function(l,j,k){if(window.console&&console.log){console.log("conversionTimeData load error: ",l,j.getResponseHeader("content-type"),k);
}this.loaded.reject(j);},onLoaded:function(){this.loaded.resolve();}});return b;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);
}});define("conversion_views/ui/conversionui",["jquery","underscore","backbone"],function(b,a,d){var c=d.View.extend({el:".conversionUI",initialize:function(){a.bindAll(this,"sortOnAuth","sortOnComp","sortOnAban");
this.listenTo(this.collection,"reset",this.render);this.authButton=b(".sort-auth-button");this.compButton=b(".sort-comp-button");
this.abanButton=b(".sort-aban-button");this.authButton.on("click",this.sortOnAuth);this.compButton.on("click",this.sortOnComp);
this.abanButton.on("click",this.sortOnAban);},sortOnAuth:function(){this.collection.sortByAuth();},sortOnComp:function(){this.collection.sortByComp();
},sortOnAban:function(){this.collection.sortByAban();}});return c;});define("conversion/views/ui//mappanel",["d3","backbone","jquery","underscore","map/views/ui/mappanel","map/events/worldevents","chartlib/events/appstateevents"],function(c,h,e,b,a,f,d){var g=a.extend({el:e(".panel.world"),setTotal:function(j){var i=c.format("0,000");
var k=i(j);if(j===0&&this.atCountryLevel){k=i(this.clickedMapBarValue);this.totalTxt.html("Total "+this.dataType+": <b>"+k+"</b>");
h.trigger(f.TOTAL_SESSIONS,this.clickedMapBarValue,0,"mapdata");}else{if(this.$(".world-button").length===1){return;}this.totalTxt.html("Total "+this.dataType+": <b>"+k+"</b>");
}}});return g;});define("conversion/collections/conversioncountrydata",["jquery","underscore","backbone","conversion/models/country","chartlib/events/appstateevents","chartlib/chartBaseEvents"],function(e,a,g,d,c,f){var b=g.Collection.extend({model:d,reverseDirection:false,statsType:"CONVERSION_PER_COUNTRY",conversionTypes:["Authorised","Completed","Abandoned"],total:0,initialize:function(){a.bindAll(this,"parse","getReverseDirection","loadRegion","onLoaded","onError");
g.on(c.STATE_CHANGED,this.loadRegion);this.comparator=this.compareFunction;this.sortKey="total";},loadRegion:function(i){this.loaded=e.Deferred();
this.total=0;var h=a.pick(i.attributes,"region","ccs","granularity","bdate","edate");h.statsType=this.statsType;this.url=(i.get("stub"))?adyen.jsbase+"/chart/charts/mainConversion/dummy-data/conversionPerCountry.xml?"+new Date().getTime():i.get("url")+e.param(h)+"&cb="+new Date().getTime();
this.fetch({reset:true});},fetch:function(h){h||(h={});h.dataType="xml";h.success=this.onLoaded;h.error=this.onError;this._super(h);
g.trigger(f.REGISTER_DEFERRED,this.loaded,"conversionCountryData",this);},parse:function(h){this.countryDict={};this.xmlData=h;
e(this.conversionTypes).each(e.proxy(this.parseCountry,this));this.countryDict=a.toArray(this.countryDict);if(this.total<=0){this.trigger(f.DATA_FAILED);
}return this.countryDict;},parseCountry:function(k,j){var l;var h=e(this.xmlData).find('[seriesName="'+j+'"]');j=j.toLowerCase();
h.children().each(e.proxy(function(m,o){l=e(o);var n=l.attr("toolText").match(/([^\,]+)/)[0];this.countryDict[n]||(this.countryDict[n]=new d());
this.countryDict[n].set("countryName",n);this.countryDict[n].set("total",this.countryDict[n].get("total")+(+l.attr("value")));
this.countryDict[n].get("conversionRates").push({name:j,value:Math.max(0,+l.attr("value"))});this.total+=this.countryDict[n].get("total");
},this));},onError:function(k,i,j){if(window.console&&console.log){console.log("conversionCountryData load error: ",k,i.getResponseHeader("content-type"),j);
}this.loaded.reject(i);},onLoaded:function(){this.loaded.resolve();},getReverseDirection:function(){return this.reverseDirection;
},sortByCountry:function(){this.comparator=this.compareFunction;this.reverseDirection=!this.reverseDirection;this.sortKey="countryName";
this.sort();},sortByVolume:function(){this.comparator=this.compareFunction;this.reverseDirection=!this.reverseDirection;this.sortKey="total";
this.sort();},sortByAuth:function(){this.comparator=this.comparePercentage;this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";
this.sortSubKey="authorised";e(this.models).each(e.proxy(function(k,j){var l=j.get(this.sortKey);var m=a.findWhere(l,{name:this.sortSubKey});
var h=l.indexOf(m);l.splice(0,0,l.splice(h,1)[0]);},this));this.sort();},sortByComp:function(){this.comparator=this.comparePercentage;
this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";this.sortSubKey="completed";e(this.models).each(e.proxy(function(k,j){var l=j.get(this.sortKey);
var m=a.findWhere(l,{name:this.sortSubKey});var h=l.indexOf(m);l.splice(0,0,l.splice(h,1)[0]);},this));this.sort();},sortByAban:function(){this.comparator=this.comparePercentage;
this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";this.sortSubKey="abandoned";e(this.models).each(e.proxy(function(k,j){var l=j.get(this.sortKey);
var m=a.findWhere(l,{name:this.sortSubKey});var h=l.indexOf(m);l.splice(0,0,l.splice(h,1)[0]);},this));this.sort();},compareFunction:function(i,h){var k=i.get(this.sortKey),j=h.get(this.sortKey);
if(this.reverseDirection){if(k>j){return -1;}if(j>k){return 1;}return 0;}else{if(k<j){return -1;}if(j<k){return 1;}return 0;
}},comparePercentage:function(j,h){var n=j.get(this.sortKey),l=h.get(this.sortKey);var o=a.findWhere(n,{name:this.sortSubKey});
var m=a.findWhere(l,{name:this.sortSubKey});var k=o.value/j.get("total");var i=m.value/h.get("total");if(this.reverseDirection){if(k>i){return -1;
}if(i>k){return 1;}return 0;}else{if(k<i){return -1;}if(i<k){return 1;}return 0;}}});return b;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);
}});define("conversion/views/charts/conversionpercentage",["jquery","underscore","backbone","chartlib/barchart","chartlib/events/appstateevents","d3","chartutil/numberutils"],function(g,a,h,e,d,b,f){var c=e.extend({el:".conversionpercentage-chart",defaults:{yScale:"ordinal",totalLabelOffset:5,margin:{top:5,left:100,bottom:20,right:10},barPadding:0,xAttr:"percentage",yAttr:"name",joinAttr:"name",tooltip:true},addListeners:function(){h.on(d.RENDER_CHARTS,this.render);
},calibrateXScale:function(){var i=a.pluck(a.filter(this.collection.getTotalPercentages(),function(j){return j.name!=="total";
}),"percentage");this.scales.x.domain([0,b.max(i)]).rangeRound([0,this.width]);},formatXAxis:function(){var i=this.axes.x;
i.ticks(5).tickFormat(function(k,j){return(j>0)?(k*100):k+"%";});},calibrateYScale:function(){this.scales.y.domain(a.pluck(this.collection.getTotalPercentages(),this.options.yAttr)).rangeRoundBands([this.height,0],this.options.barPadding);
},render:function(){if(this.collection.total>0){this._super(arguments);}},renderTooltipContent:function(j){var i=this;this.tip.html(function(){return"<strong>"+i.getY(j)+":</strong> <span>"+f.decimalFormatter(i.getX(j)*100)+"%</span>";
});},renderData:function(){var l=this,i=this.scales.x,o=this.scales.y;var m=this.svg.selectAll(".bar").data(this.collection.getTotalPercentages(),this.joinData);
m.transition().duration(500).delay(500).ease("cubic-in-out").attr("transform",function(p){return"translate(0,"+o(l.getY(p))+")";
}).select("rect").attr("width",function(p){return(p.name==="total")?0:i(l.getX(p));}).attr("height",function(p){return o.rangeBand();
});var n=m.enter().append("g").attr("class","bar").attr("transform",function(p){return"translate(0,"+o(l.getY(p))+")";}).append("rect").attr("class",function(p){return"rect "+p.name;
}).attr("width",0);m.select("rect").transition().duration(500).delay(500).ease("cubic-in-out").attr("width",function(p){return(p.name==="total")?0:Number(i(l.getX(p).toFixed(2)));
}).attr("height",function(p){return o.rangeBand();});if(this.options.tooltip){m.classed("active",true);n.on("mouseover",function(p){l.showTooltip(p,this,false);
}).on("mouseout",this.tip.hide).classed("active",true);}var k=this.svg.selectAll(".percentage-label").data(this.collection.getTotalPercentages(),this.joinData);
k.enter().append("text").attr("class","percentage-label").attr("y",function(p){return o(l.getY(p))+(o.rangeBand()/2);}).attr("x",function(p){return -l.options.totalLabelOffset;
}).attr("dy",".32em").style("text-anchor","end").text(function(p){return p.name+" "+f.decimalFormatter(l.getX(p)*100)+"%";
});k.attr("y",function(p){return o(l.getY(p))+(o.rangeBand()/2);}).text(function(p){return p.name+" "+f.decimalFormatter(l.getX(p)*100)+"%";
});k.exit().remove();var j=m.exit().transition().attr("transform",function(p){return"translate(0,"+l.height+")";});j.select("rect").attr("width",0).remove();
j.remove();},renderXAxis:function(){this._super();this.svg.select(".x.axis").selectAll("text").attr("y",10);},renderYAxis:function(){}});
return c;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/collections/conversioncountrynolimitdata",["jquery","underscore","backbone","conversion/models/country"],function(c,a,e,b){var d=e.Collection.extend({model:b,reverseDirection:false,statsType:"CONVERSION_PER_COUNTRY_NO_LIMIT",conversionTypes:["Authorised","Completed","Abandoned"],total:0});
return d;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/models/appstate",["d3","jquery","underscore","backbone","chartlib/models/appstate","chartlib/models/state","chartlib/events/appstateevents","chartutil/arrayutils","timeline/events/timelineEvents"],function(j,b,f,e,a,g,c,h,i){var d=a.extend({notifyStateChange:function(k){e.trigger(c.REQUEST_STATE_CHANGE,k);
},addConfigValues:function(l,k){},setStubValues:function(k){k.set("stub",this.get("stub"));k.set("stubURL","/chart/charts/paymentMethods/dummy-data/");
}});return d;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});define("conversion/collections/conversionmerchantdata",["jquery","underscore","backbone","d3","conversion/collections/merchantdata","conversion/models/company","conversion/models/merchant","chartlib/events/appstateevents","chartlib/chartBaseEvents"],function(b,h,g,j,e,a,i,c,d){var f=g.Collection.extend({model:a,statsType:"CONVERSION_PER_MERCHANT",initialize:function(){h.bindAll(this,"parse","loadRegion","onLoaded","onError");
this.comparator=function(k){return -k.get("total");};g.on(c.STATE_CHANGED,this.loadRegion);},loadRegion:function(l){this.loaded=b.Deferred();
var k=h.pick(l.attributes,"region","ccs","granularity","bdate","edate");k.statsType=this.statsType;this.url=(l.get("stub"))?adyen.jsbase+"/chart/charts/mainConversion/dummy-data/conversionMerchant.xml?"+new Date().getTime():l.get("url")+b.param(k)+"&cb="+new Date().getTime();
this.fetch({reset:true});},fetch:function(k){k||(k={});k.dataType="xml";k.success=this.onLoaded;k.error=this.onError;this._super(k);
g.trigger(d.REGISTER_DEFERRED,this.loaded,"conversionMerchantData",this);},parse:function(m){var k=[];var l=b(m).find("category:first").children("category");
b(l).each(function(q,p){var o=new a();o.set("name",b(p).attr("label"));o.set("total",+b(p).attr("hoverText").match(/([\d]+)/)[0]);
o.set("merchants",new e());var r=0;var n;var s=b(p).find("category:first").attr("label");if(b.inArray(s,["Abandoned","Authorised","Completed"])>-1){n=p;
}else{n=b(p).children("category");}b(n).each(function(t,w){var v=new i();v.set("name",b(w).attr("label"));v.set("total",+b(w).attr("value"));
var u=b(w).children("category");b(u).each(function(y,B){var A={};A.name=b(B).attr("label").toLowerCase();A.value=Math.max(0,+b(B).attr("value"));
r+=A.value;v.get("conversionRates").push(A);var z=b.grep(o.get("conversionRates"),function(C,x){return C.name===A.name;})[0];
if(!z){z={name:"",value:0};o.get("conversionRates").push(z);}z.name=A.name;z.value+=A.value;});o.get("merchants").add(v);
o.get("merchants").total=r;});k.push(o);});this.setTotal(+b(m).find("category:first").attr("value"));return k;},setTotal:function(k){this.total=k;
},getTotal:function(){return this.total;},onError:function(m,k,l){if(window.console&&window.console.log){window.console.log("conversionMerchantData load error: ",m,k.getResponseHeader("content-type"),l);
}this.loaded.reject(k);},onLoaded:function(){this.loaded.resolve();}});return f;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);
}});define("conversion/views/ui/countryui",["jquery","underscore","backbone","chartlib/ui/baseui"],function(d,b,e,c){var a=c.extend({el:"#countryUI",events:{"click .sort-country-button":"sortOnCountry","click .sort-volume-button":"sortOnVolume","click .sort-auth-button":"sortOnAuth","click .sort-comp-button":"sortOnComp","click .sort-aban-button":"sortOnAban"},initialize:function(){this.listenTo(this.collection,"reset",this.render);
this.countryButton=d(".countryui.sort-country-button");this.volumeButton=d(".countryui.sort-volume-button");this.authButton=d(".sort-auth-button");
this.compButton=d(".sort-comp-button");this.abanButton=d(".sort-aban-button");this.buttons.push(this.countryButton);this.buttons.push(this.volumeButton);
this.buttons.push(this.authButton);this.buttons.push(this.compButton);this.buttons.push(this.abanButton);},sortOnVolume:function(f){this.renderButtons(d(f.currentTarget));
this.collection.sortByVolume();},sortOnCountry:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByCountry();
},sortOnAuth:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByAuth();},sortOnComp:function(f){this.renderButtons(d(f.currentTarget));
this.collection.sortByComp();},sortOnAban:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByAban();
}});return a;});define("conversion/views/companieslist",["jquery","underscore","backbone","conversion/views/company","chartlib/events/appstateevents"],function(d,b,f,e,c){var a=f.View.extend({el:".companies-list",initialize:function(){b.bindAll(this,"removeCompanies","addCompanies");
f.on(c.RENDER_CHARTS,this.render,this);},render:function(){var h=d(".panel.companies-list.company");var g=h.length;if(g===0){this.addCompanies();
return;}d.each(d(h).get().reverse(),d.proxy(function(j,i){var k={};k.duration=500;if(j===(g-1)){k.complete=this.removeCompanies;
}d(i).delay(400*j).fadeOut(k);},this));},removeCompanies:function(){d(".panel.companies-list.company").remove();this.addCompanies();
},addCompanies:function(){this.collection.each(d.proxy(function(g,i){var h=new e({model:g,total:this.collection.getTotal()});
this.$el.append(h.el);h.render();h.$el.hide();h.$el.delay(400*i).fadeIn();},this));}});return a;});define("conversion/views/app",["jquery","underscore","backbone","d3","conversion/views/ui//mappanel","map/views/ui/mapui","map/views/charts/mapchart","timeline/views/timelineFacade","timeline/util/timelineConstants","chartlib/ui/csvdownload","conversion/views/ui/countryui","conversion/views/charts/countryvolume","conversion/views/charts/conversionrates","conversion/views/charts/volumetime","conversion/views/charts/conversionpercentage","conversion/views/companieslist","conversion/models/appstate","chartlib/chartLoadQueue","conversion/collections/conversioncountrydata","conversion/collections/conversioncountrynolimitdata","conversion/collections/mapdata","conversion/collections/conversiontimedata","conversion/collections/conversionmerchantdata","chartlib/events/appstateevents","chartlib/chartBaseEvents","map/events/worldevents"],function(i,z,b,x,r,k,s,d,o,j,l,w,g,f,m,t,n,y,h,p,e,a,A,v,q,c){var u=b.View.extend({el:i("#d3canvas"),hasLoadQueue:true,deferredArray:[],initialize:function(){z.bindAll(this,"enable","disable","detectRegion");
this.initModels();this.initCollections();b.on(v.CHANGE_REQUESTED,this.disable);b.on(v.STATE_CHANGED,this.detectRegion);b.on(q.REGISTER_DEFERRED,this.registerDeferred,this);
if(this.hasLoadQueue){b.on(v.RENDER_CHARTS,this.enable,this);}this.initViews();if(typeof window.SVGElement==="undefined"){i("#timelineHolder").remove();
i("#timelineModeButtonsHolder").remove();i("#timelineDatesHolder").remove();i("#calendarUI").css("margin","-35px 0 10px 0");
this.checkDocumentBody();}},initModels:function(){this.appState=new n();},initCollections:function(){if(this.hasLoadQueue){this.loadQueue=new y();
}this.mapData=new e();this.conversionCountryData=new h();this.conversionCountryNoLimitData=new p();this.conversionTimeData=new a();
this.conversionMerchantData=new A();},initViews:function(){var C=new r({collection:this.mapData,model:this.appState}).render();
var L=new k({collection:this.mapData});var B=new s({collection:this.mapData});var K=new l({collection:this.conversionCountryData});
var H=new w({collection:this.conversionCountryData});var F=new g({collection:this.conversionCountryData});var M=new f({collection:this.conversionTimeData});
var E=new m({collection:this.conversionTimeData});var I=new t({collection:this.conversionMerchantData});new j({el:".world-csvdownload",collection:this.mapData});
new j({el:".country-csvdownload",collection:this.conversionCountryNoLimitData});new j({el:".volumetime-csvdownload",collection:this.conversionTimeData});
this.timeline=new d({version:7,timeCollectionMode:o.__LAST_FULL,formatPeriod:o.__DAY_FORMAT,baseGranularity:o.__DAY_GRANULARITY,calendar:true,controls:true,loadQueue:this.hasLoadQueue,config:false,chartGranularity:o.__MINUTE_FORMAT,forceCET:false});
this.timeline.timeline.timelineWidgetContainer=i("#timelineComponent");var N=this.timeline.getDates();var J=x.time.format("%Y-%m-%d")(N[0]);
var D=x.time.format("%Y-%m-%d")(N[1]);var G=this;setTimeout(function(){var O=[J,D,G.timeline.getGranularity()];O=[O];G.timeline.timeline.timelineWidgetContainer.trigger("timelineTimespanSet",O);
},750);this.appState.addConfig({timeline:this.timeline,config:this.configUI,hasMap:true});},registerDeferred:function(D,B,C){var F=this.deferredArray;
F.push(D);var E=this;D.done(function(H,G){E.checkDeferredsCallback(F);}).fail(function(H,G){E.checkDeferredsCallback(F);});
},checkDeferredsCallback:function(B){var C=z.every(B,function(D){return D.state()==="resolved"||D.state()==="rejected";});
if(C){this.dataAttempted(B);}},dataAttempted:function(B){var C=this;if(!this.hasLoadQueue){setTimeout(function(){b.trigger(q.DATA_LOADED);
C.enable();},10);}else{b.trigger(q.DATA_LOADED);}},detectRegion:function(F){if(window.console&&console.log){console.log("### app::detectRegion:: loading new state region=",F.get("label"));
}if(F.get("label")==="world"){var C=this.timeline.getDates();var B=x.time.format("%Y-%m-%d")(C[0]);var E=x.time.format("%Y-%m-%d")(C[1]);
var D=[B,E,this.timeline.getGranularity()];D=[D];this.timeline.timeline.timelineWidgetContainer.trigger("timelineTimespanSet",D);
}},enable:function(){this.$el.css("pointer-events","auto");this.$("svg rect").css("pointer-events","auto");this.$("svg text").css("pointer-events","auto");
this.$el.fadeTo(500,1);if(typeof window.SVGElement==="undefined"){var B=i("#ie8_d3CanvasCover");B.css("display","none");}},disable:function(){this.$el.css("pointer-events","none");
this.$("svg rect").css("pointer-events","none");this.$("svg text").css("pointer-events","none");this.$el.fadeTo(0,0.35);if(typeof window.SVGElement==="undefined"){var B=i("#ie8_d3CanvasCover");
B.css("height",this.$el.height());B.css("display","block");}this.deferredArray=[];},checkDocumentBody:function(){var C=this;
var B=i("body").find("div")[0];var D=B.style.cssText;if(D.toLowerCase().indexOf("clip")>-1){i(B).remove();}else{setTimeout(function(){C.checkDocumentBody();
},10);}}});return u;});define("conversion/views/ui/mapui",["jquery","underscore","backbone","chartlib/ui/baseui"],function(d,a,e,c){var b=c.extend({el:"#worldUI",events:{"click .sort-region-button":"onRegionClick","click .sort-volume-button":"onVolumeClick"},initialize:function(){this.listenTo(this.collection,"reset",this.render);
this.regionButton=d(".worldui.sort-region-button");this.volumeButton=d(".worldui.sort-volume-button");this.buttons.push(this.regionButton);
this.buttons.push(this.volumeButton);},onVolumeClick:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByVolume();
},onRegionClick:function(f){this.renderButtons(d(f.currentTarget));this.collection.sortByRegion();}});return b;});define("conversion/models/region",["jquery","underscore","backbone"],function(c,a,d){var b=d.Model.extend({defaults:{regionName:"",total:0}});
return b;},function(a){if(window.console&&console.log){console.log("APP JS ERROR =",a);}});