define("pmc/views/charts/paymentMethodCountryVolume",["jquery","backbone","underscore","chartlib/barchart","chartlib/events/appstateevents"],function(e,f,b,d,c){var a=d.extend({el:"#pmCountryVolume",defaults:{yScale:"ordinal",totalLabelOffset:70,margin:{top:0,left:40,bottom:20,right:10},barPadding:0.1,xAttr:"total",yAttr:"pmName",joinAttr:"pmName",tooltip:true},barSize:11,spacer:2,addListeners:function(){f.on(c.RENDER_CHARTS,this.render);
},renderTooltipContent:function(i){var h=this;var g=d3.format("0,000");this.tip.html(function(k){var j=i.get("country");if(j==="RoR"){j="'rest-of-region'";
}return"<strong>"+j+":</strong> <span>"+g(h.getX(i))+"</span> sessions";});this.tip.direction("n");this.tip.offset([-10,0]);
},calibrateXScale:function(){var g=[];this.collection.forEach(function(i){var h=i.get("countries");h.forEach(function(j){g.push(j);
});});this.scales.x.domain([0,d3.max(g,function(h){return Number(h.get("total"));})]);this.scales.x.nice();},formatXAxis:function(){this.axes.x.ticks(5);
},renderXAxis:function(){this._super();this.xAxis.selectAll("text").attr("transform",function(){return"translate(0,7)";});
},formatYAxis:function(){var g=this.axes.y;g.tickFormat(function(h){return(h.length>14)?e.trim(h).substring(0,11).trim(this)+"...":h;
});},renderYAxis:function(){},renderData:function(){var p=this,u=this.scales.x,r=this.scales.y,t=500;var n=this.svg.selectAll(".bar").data(this.collection.models,this.joinData);
var m=n.enter().append("g").attr("class",function(v){return"bar "+v.get("pmName");}).attr("transform",function(v){return"translate(0,"+r(p.getY(v))+")";
});var j=n.transition().duration(t).attr("transform",function(v){return"translate(0,"+r(p.getY(v))+")";});var k=n.exit().transition().duration(t).attr("transform",function(v){return"translate(0,"+p.height+")";
}).remove();k.selectAll("text").attr("fill-opacity",0);k.selectAll("rect").attr("height",0);var g=n.selectAll(".bar-country").data(function(v){return v.get("countries");
},function(v){return v.get("country");});var s=g.enter().append("g").attr("class","bar-country").attr("transform",function(w){var v=p.getYPos(w);
return"translate("+0+","+(v)+")";});var h=s.append("text").attr("class","pm-country-chart-text").attr("x","-30").attr("y",function(v){return p.barSize-1;
}).attr("fill-opacity",0).text(function(v){return v.get("country");});var q=s.append("rect").attr("class","sub-bar full").attr("width",0).attr("height",this.barSize);
var i=g.select(".pm-country-chart-text").text(function(v){return v.get("country");});var o=g.transition().duration(t).attr("transform",function(w){var v=p.getYPos(w);
return"translate("+0+","+(v)+")";});o.select(".pm-country-chart-text").attr("fill-opacity",1);o.select("rect").attr("width",function(v){return u(p.getX(v));
});var l=g.exit().transition().duration(t).attr("transform",function(v){return"translate("+0+","+(r.rangeBand())+")";}).remove();
l.select(".pm-country-chart-text").attr("fill-opacity",0);l.selectAll("rect").attr("height",0);if(this.options.tooltip){q.on("mouseover",function(v){p.showTooltip(v,this,false);
}).on("mouseout",function(v){p.hideTooltip(false);}).classed("active",true);}},getYPos:function(k,j){var g=k.get("order");
var l=g*this.barSize;var i=this.spacer*g;return l+i;}});return a;});