define("pmc/views/charts/paymentMethodCountryBarPie",["jquery","backbone","underscore","chartlib/stackedbarchart","d3","chartutil/numberutils","chartlib/events/appstateevents"],function(g,h,a,c,d,f,e){var b=c.extend({el:"#pmCountryBarPie",defaults:{yScale:"ordinal",totalLabelOffset:5,margin:{top:0,left:80,bottom:20,right:10},barPadding:0.1,xAttr:"total",yAttr:"pmName",joinAttr:"pmName",tooltip:false},barSize:11,spacer:0,addListeners:function(){h.on(e.RENDER_CHARTS,this.render);
},calibrateXScale:function(){var i=[];this.collection.forEach(function(j){var k=j.get("percentages");k.forEach(function(l){if(l.country.toLowerCase()!=="total"){i.push(Number(l.percentage.toFixed(2)));
}});});this.scales.x.domain([0,d.max(i)]).rangeRound([0,this.width]);},formatXAxis:function(){var i=this.axes.x;i.ticks(5).tickFormat(function(k,j){return(j>0)?d.format("r")(k*100):k+"%";
});},renderXAxis:function(){this._super();this.svg.select(".x.axis").selectAll("text").attr("transform",function(){return"translate(0,7)";
});},formatYAxis:function(){var i=this.axes.y;i.tickFormat(function(j){return(j.length>14)?g.trim(j).substring(0,11).trim(this)+"...":j;
});},renderData:function(){var q=this,v=this.scales.x,s=this.scales.y,u=500;var o=this.svg.selectAll(".bar").data(this.collection.models,this.joinData);
var n=o.enter().append("g").attr("class","bar").attr("transform",function(x){return"translate(0,"+s(q.getY(x))+")";});var k=o.transition().duration(u).attr("transform",function(x){return"translate(0,"+s(q.getY(x))+")";
});var l=o.exit().transition().duration(u).attr("transform",function(x){return"translate(0,"+q.height+")";}).remove();l.selectAll("text").attr("fill-opacity",0);
l.selectAll("rect").attr("height",0);var i=o.selectAll(".country-bar-pie").data(function(x){return x.get("percentages");},function(x){return x.country;
});var t=i.enter().append("g").attr("class","country-bar-pie").attr("transform",function(y){var x=q.getYPos(y);return"translate("+0+","+(x)+")";
});t.append("text").attr("class","pm-session-bar-pie-text country").attr("x",-40).attr("y",function(x){return q.barSize-1;
}).attr("fill-opacity",0).style("text-anchor","end").text(function(x){return x.country;});t.append("text").attr("class","pm-session-bar-pie-text percent").attr("x",-5).attr("y",function(x){return q.barSize-1;
}).attr("fill-opacity",0).style("text-anchor","end").text(function(x){return" "+Math.round(x.percentage*100)+"%";});var r=t.append("rect").attr("class",function(x){return"bar-pie-rect-"+x.order;
}).attr("width",0).attr("height",this.barSize);if(this.options.tooltip){r.on("mouseover",function(x){q.showTooltip(x,this,false);
}).on("mouseout",this.tip.hide);}var w=i.select(".pm-session-bar-pie-text.country").text(function(x){return x.country;});
var j=i.select(".pm-session-bar-pie-text.percent").text(function(x){return" "+f.decimalFormatter(x.percentage*100)+"%";});
var p=i.transition().duration(u).attr("transform",function(y){var x=q.getYPos(y);return"translate("+0+","+(x)+")";});p.select(".pm-session-bar-pie-text.country").attr("fill-opacity",1);
p.select(".pm-session-bar-pie-text.percent").attr("fill-opacity",1);p.select("rect").attr("width",function(x){return(x.country.toLowerCase()==="total")?0:Number(v(x.percentage.toFixed(2)));
});var m=i.exit().transition().duration(u).attr("transform",function(x){return"translate("+0+","+(s.rangeBand())+")";}).remove();
m.selectAll("text").attr("fill-opacity",0);m.selectAll("rect").attr("height",0);},getYPos:function(l,k){var i=l.order;var m=i*this.barSize;
var j=this.spacer*i;return m+j;},renderYAxis:function(){}});return b;});