define("pmc/collections/paymentMethodVolumeData",["jquery","underscore","backbone","pmc/models/paymentMethod","chartlib/events/appstateevents","pmc/events/pmEvents","chartlib/chartBaseEvents"],function(f,b,h,c,e,a,g){var d=h.Collection.extend({model:c,reverseDirection:false,conversionTypes:["Authorised","Completed","Abandoned"],hasParsedData:false,hasData:false,addAbandonedFlag:false,localURL:"volume_all.xml",statsType:"CONVERSION_PER_PAYMENTMETHOD",initialize:function(j,i){this.isLinked=i.isLinked;
b.bindAll(this,"parse","getReverseDirection","loadPmVolData","reorderCollection","onLoaded","onError");h.on(e.STATE_CHANGED,this.loadPmVolData);
h.on(a.COLLECTION_SORTED,this.reorderCollection);this.on("sort",function(){if(arguments[0].sortKey!=="order"){h.trigger(a.COLLECTION_SORTED,this.models,this);
}});this.listenTo(this,"error",function(){this.trigger(g.DATA_FAILED);});this.comparator=this.compareFunction;this.sortKey="total";
},loadPmVolData:function(l){this.loaded=f.Deferred();this.hasParsedData=false;this.hasData=false;this.addAbandonedFlag=false;
var i=b.pick(l.attributes,"statsType","region","ccs","granularity","bdate","edate");i.statsType=this.statsType;var j=l.get("label").toLowerCase();
if(j.length){j=j+"/";}var k=l.get("stubURL")?l.get("stubURL"):"/chart/charts/paymentMethods/dummy-data/";this.url=(l.get("stub"))?adyen.jsbase+k+j+this.localURL+"?"+new Date().getTime():l.get("url")+f.param(i)+"&cb="+new Date().getTime();
this.fetch({reset:true});},fetch:function(i){i||(i={});i.dataType="xml";i.success=this.onLoaded;i.error=this.onError;this._super(i);
h.trigger(g.REGISTER_DEFERRED,this.loaded,"paymentMethodVolumeData",this);},parse:function(j){if(window.console&&window.console.log){window.console.log("### paymentMethodVolumeData::parse:: START PARSE");
}this.pmVolDict={};this.xmlData=j;f(this.conversionTypes).each(f.proxy(this.parsePM,this));this.pmVolDict=b.toArray(this.pmVolDict);
this.hasParsedData=true;this.totalVolume=0;var i=this;if(this.pmVolDict.length){this.hasData=true;b.each(this.pmVolDict,function(k){i.totalVolume+=k.get("total");
});h.trigger(a.VOLUME_TOTAL,this.totalVolume,this.pmVolDict.length,"PaymentMethodVolumeData");}else{this.trigger(g.DATA_FAILED);
return null;}return this.pmVolDict;},parsePM:function(l,k){var m;var j=f(this.xmlData).find('[seriesName="'+k+'"]');k=k.toLowerCase();
j.children().each(f.proxy(function(n,q){m=f(q);var o;var p=m.attr("toolText");if(p.indexOf(":")>-1){o=m.attr("toolText").match(/([^\:]+)/)[0];
}else{o=m.attr("toolText").match(/([^\,]+)/)[0];}if(o.toLowerCase()==="no_pmm"){o="no selection";}this.pmVolDict[o]||(this.pmVolDict[o]=new c());
this.pmVolDict[o].set("id",o);this.pmVolDict[o].set("pmName",o);this.pmVolDict[o].set("total",this.pmVolDict[o].get("total")+Math.max(0,(+m.attr("value"))));
this.pmVolDict[o].get("conversionRates").push({name:k,value:Math.max(0,+m.attr("value"))});this.pmVolDict[o].set("order",0);
},this));},onLoaded:function(){this.loaded.resolve();},onError:function(k,i,j){if(window.console&&window.console.log){window.console.log("paymentMethodVolumeData load error: ",k,i.getResponseHeader("content-type"),j);
}this.loaded.reject(i);},addDroppedOutItem:function(k){if(window.console&&window.console.log){window.console.log("### paymentMethodVolumeData::addDroppedOutItem:: this.addAbandonedFlag=",this.addAbandonedFlag);
}if(!this.addAbandonedFlag){this.addAbandonedFlag=true;var m=Math.max(0,k-this.totalVolume);var l="no selection";var j=new c();
j.set("pmName",l);j.set("total",m);j.set("order",0);var i=[];b.each(this.conversionTypes,function(n){var p=n.toLowerCase();
var o={};o.name=p;o.pmName=l;if(p==="abandoned"){o.startX=0;o.value=m;o.width=1;}else{o.startX=0;o.value=0;o.width=0;}i.push(o);
});j.set("conversionRates",i);this.add(j);if(window.console&&window.console.log){window.console.log("### paymentMethodVolumeData::addAbandonedItem:: pm=",j);
window.console.log("### paymentMethodVolumeData::addAbandonedItem:: models=",this.models);}}},reorderCollection:function(k,j){if(j===this){return;
}else{h.trigger(g.RENDER_BUTTONS,null);}var i=0;var l=this;k.forEach(function(m){l.forEach(function(n){if(n.get("pmName")===m.get("pmName")){i++;
n.set("order",i);}});});this.sortByOrder();},getReverseDirection:function(){return this.reverseDirection;},sortByOrder:function(){this.comparator=this.compareFunction;
this.reverseDirection=false;this.sortKey="order";this.sort();},sortByVolume:function(){this.comparator=this.compareFunction;
this.reverseDirection=!this.reverseDirection;this.sortKey="total";this.sort();},sortByAuth:function(){this.comparator=this.comparePercentage;
this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";this.sortSubKey="authorised";f(this.models).each(f.proxy(function(l,k){var m=k.get(this.sortKey);
var n=b.findWhere(m,{name:this.sortSubKey});var j=m.indexOf(n);m.splice(0,0,m.splice(j,1)[0]);},this));this.sort();},sortByComp:function(){this.comparator=this.comparePercentage;
this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";this.sortSubKey="completed";f(this.models).each(f.proxy(function(l,k){var m=k.get(this.sortKey);
var n=b.findWhere(m,{name:this.sortSubKey});var j=m.indexOf(n);m.splice(0,0,m.splice(j,1)[0]);},this));this.sort();},sortByAban:function(){this.comparator=this.comparePercentage;
this.reverseDirection=!this.reverseDirection;this.sortKey="conversionRates";this.sortSubKey="abandoned";f(this.models).each(f.proxy(function(l,k){var m=k.get(this.sortKey);
var n=b.findWhere(m,{name:this.sortSubKey});var j=m.indexOf(n);m.splice(0,0,m.splice(j,1)[0]);},this));this.sort();},compareFunction:function(j,i){var l=j.get(this.sortKey),k=i.get(this.sortKey);
if(this.reverseDirection){if(l>k){return -1;}if(k>l){return 1;}return 0;}else{if(l<k){return -1;}if(k<l){return 1;}return 0;
}},comparePercentage:function(k,i){var o=k.get(this.sortKey),m=i.get(this.sortKey);var p=b.findWhere(o,{name:this.sortSubKey});
var n=b.findWhere(m,{name:this.sortSubKey});var l=p.value/k.get("total");var j=n.value/i.get("total");if(this.reverseDirection){if(l>j){return -1;
}if(j>l){return 1;}return 0;}else{if(l<j){return -1;}if(j<l){return 1;}return 0;}}});return d;});