define("baselinerates/views/charts/baseLineStackedChart",["jquery","underscore","d3","backbone","chartlib/vertstacked","chartutil/d3utils","chartutil/dateUtils_CET","chartlib/events/appstateevents"],function(b,f,h,e,c,i,a,d){var g=c.extend({granularityFormats:[],renderAsUTC:true,defaults:{xScale:"ordinal",barPadding:0.2,margin:{top:5,right:50,bottom:30,left:50},tooltip:true},initialize:function(){this.granularityFormats.month=h.time.format.utc("%b");
this.granularityFormats.week=function(j){return"wk "+j.getWeek();};this.granularityFormats.day=h.time.format.utc("%e");this.granularityFormats.hour=function(k){var j=a.getAmsterdamDSTOffset(k);
return new Date(k.getTime()+j*60*1000).getUTCHours();};this._super(arguments);},addListeners:function(){e.on(d.RENDER_CHARTS,this.render);
},setXScale:function(){this.scales.x=h.time.scale().range([0,this.width],this.options.barPadding);},calibrateXScale:function(){var j=this.collection.getDateExtent();
this.scales.x.domain(j);this.scales.x.ticks(this.collection.getIntervalFormat(),1);},setXAxis:function(){this.axes.x=h.svg.axis().scale(this.scales.x).orient("bottom").tickSize(0);
},formatXAxis:function(){var l=this,k=this.axes.x,m=this.collection.getGranularity(),j=l.scales.x.ticks(h.time[m].utc,1).length;
if(j>40){m="month";}this.axisGranularity=m;k.ticks(h.time[m].utc,1).tickFormat(l.granularityFormats[m]);},renderXAxis:function(){this.formatXAxis();
this._super();i.spreadTimeAxisTicks(this);var j=[];if(this.axisGranularity==="month"){this.collection.models.forEach(function(l){j.push(l.attributes);
});var k=this.xAxis.selectAll(".tick");this.$el.trigger("fetchExistingData",{ticks:k,baselineData:j});}else{this.$el.trigger("fetchExistingData",{ticks:null,baselineData:null});
}},formatYAxis:function(){var j=this;if(this.options.percentile){this.axes.y.tickFormat(h.format("%"));}else{this.axes.y.tickFormat(function(l,k){return i.thousandsFormatter(l,k,j.scales.y);
});}},renderYAxis:function(){this.formatYAxis();this._super();if(this.options.percentile){i.percentageFormat(this.yAxis);
}},renderData:function(){var q=this,o=this.options.percentile,t=this.scales.x,s=this.scales.y,p=this.collection.getGranularity(),k=(this.renderAsUTC)?t.ticks(h.time[p].utc,1).length:t.ticks(h.time[p],1).length,m=(q.width/k),v=(m*(1-this.options.barPadding))/2;
q.collection.models.forEach(function(x){var w=0;b.each(x.get(q.options.yNestAttr),function(y,z){if(!o){z.startY=w;z.endY=(w+z.value);
}else{z.startY=w/x.get("total");z.endY=(w+z.value)/x.get("total");}w+=z.value;});});var n=this.svg.selectAll(".bar").data(q.collection.models,this.joinData);
var l=n.enter().append("g").attr("class","bar");n.transition().attr("transform",function(x,w){return"translate("+((m*(w+1))-(m/2))+",0)";
});var r=n.selectAll("rect").data(function(w){return w.get(q.options.yNestAttr);},function(w){return w.name;});var u=r.enter().append("rect").attr("class",function(w){return"stack "+w.name;
}).attr("height",0).attr("y",function(w){return s(w.startY);});r.attr("width",v).attr("transform",function(x,w){return"translate(-"+(v/2)+",0)";
}).transition().duration(500).delay(function(x,w){return 500+(w*500);}).attr("y",function(w){return s(w.endY);}).attr("height",function(w){return s(w.startY)-s(w.endY);
});r.exit().remove();var j=n.exit().transition();j.attr("transform",function(w){return"translate(0,0)";}).select("rect").transition().attr("width",0);
j.remove();},renderTooltipContent:function(k){var j=this;j.tip.html(function(m){var l="<div class='csr-col' style='width:220px'>";
l+="<div class='csr-col two a'><b>authorisations:</b></div><div class='csr-col two a'>"+m.get("authorisations")+"</div>";
l+="<div class='csr-col two a'><b>total:</b></div><div class='csr-col two a'>"+m.get("total")+"</div>";l+="</div>";return l;
});this.tip.attr("class","d3-tip");this.tip.direction("n");this.tip.offset([-10,0]);}});return g;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR =",a);
}});