define("baselinerates/views/charts/baseLineChart",["jquery","underscore","backbone","chartlib/linechart","d3","chartutil/d3utils","baselinerates/events/baselineevents","chartlib/events/appstateevents","chartutil/dateUtils_CET"],function(d,h,g,a,i,j,f,e,c){var b=a.extend({granularityFormats:[],chartType:"total",defaults:{margin:{top:5,right:50,bottom:20,left:50},tooltip:true},initialize:function(){var k=this;
h.bindAll(this,"chartTypeSelected");this.granularityFormats.month=i.time.format.utc("%b");this.granularityFormats.week=function(l){return"wk "+l.getWeek();
};this.granularityFormats.day=i.time.format.utc("%e");this.granularityFormats.hour=function(m){var l=c.getAmsterdamDSTOffset(m);
return new Date(m.getTime()+l*60*1000).getUTCHours();};g.on(f.CHART_TYPE_SELECTED,function(l){if(k.options.percentile){k.chartTypeSelected(l);
}});this._super(arguments);},addListeners:function(){g.on(e.RENDER_CHARTS,this.render);},chartTypeSelected:function(k){if(k===this.chartType){return;
}this.chartType=k;this.render();},setXScale:function(){this.scales.x=i.time.scale().range([0,this.width],this.options.barPadding);
},calibrateXScale:function(){var k=this.collection.getDateExtent();this.scales.x.domain(k);this.scales.x.ticks(this.collection.getIntervalFormat(),1);
},setYScale:function(){this.scales.y=i.scale[this.options.yScale]();},calibrateYScale:function(){var l=this;this.scales.y.range([this.height-1,2],this.options.barPadding);
var k=this.collection.filter(function(m){return m.get("utcdate").getTime()<=l.collection.getLastModelDate().getTime();});
k=h.invoke(k,"get",l.options.yAttr);if(l.options.percentile){switch(l.chartType){case"zoom":this.scales.y.domain([i.min(k),i.max(k)]);
break;case"total":default:this.scales.y.domain([0,1]);break;}}else{this.scales.y.domain([0,i.max(k)]);}},setXAxis:function(){this.axes.x=i.svg.axis().scale(this.scales.x).orient("bottom").tickSize(0);
},formatXAxis:function(){var m=this,l=this.axes.x,n=this.collection.getGranularity(),k=m.scales.x.ticks(i.time[n].utc,1).length;
if(k>40){n="month";}l.ticks(i.time[n].utc,1).tickFormat(m.granularityFormats[n]);},renderXAxis:function(){var l=this,k=this.axes.x;
this.formatXAxis();this.xAxis.call(k).transition().attr("opacity",1).duration(500).delay(500).ease("exp-in-out").attr("transform","translate( 0,"+this.height+")");
j.spreadTimeAxisTicks(this);},formatYAxis:function(){var k=this;if(this.options.percentile){this.axes.y.tickFormat(i.format("%"));
}else{this.axes.y.tickFormat(function(m,l){return j.thousandsFormatter(m,l,k.scales.y);});}},renderYAxis:function(){this.formatYAxis();
this._super(arguments);if(this.options.percentile){j.percentageFormat(this.yAxis);}},renderData:function(){var n=this,k=this.scales.x,o=this.scales.y;
var m=i.svg.line().interpolate("linear").x(function(p){return k(n.getX(p))+((n.width/2)-k(n.getX(p)))/n.collection.models.length;
}).y(function(p){return o(n.getY(p));}).defined(function(p){return !isNaN(n.getY(p));});var l=i.svg.line().interpolate("linear").x(function(p){return k(n.getX(p))+((n.width/2)-k(n.getX(p)))/n.collection.models.length;
}).y(function(p){return o(p.get(n.options.averageAttr));});this.line=this.line||this.svg.append("g").append("path").style("stroke",function(){return csr.palette.authorised;
}).attr("class","line");this.line.datum(this.collection.filter(function(p){return p.get("utcdate").getTime()<=n.collection.getLastModelDate().getTime();
})).transition().attr("d",m);this.averageLine=this.averageLine||this.svg.append("g").append("path").attr("class","line average");
this.averageLine.datum(this.collection.filter(function(p){return(p.get(n.options.averageAttr)!==null&&p.get("utcdate").getTime()<=n.collection.getLastModelDate().getTime());
})).transition().attr("d",l);}});return b;},function(a){if(window.console&&window.console.log){window.console.log("APP JS ERROR = "+a);
}});