define("chart/widgetFramework/chartTypes/brushableBarChart",["jquery","underscore","d3","chart/widgetFramework/core/mixins/formats","hogan","util/Functional","util/ObjectSuper","chartutil/numberutils","chart/widgetFramework/core/constants/UIConstants","chart/widgetFramework/core/constants/WidgetConstants","chart/widgetFramework/core/drivers/axisBaseView"],function(d,j,l,c,f,b,g,k,i,e,a){function h(r,m,p){var o;
var q={numBars:10};var n=j.defaults(r,q);o=a(n,m,p);var s=g(o);o.init=function(){s.init();if(typeof this.options.allowScrolling==="undefined"){this.options.allowScrolling=true;
}this.options.outerPadding=0;if(this.options.numBars<=0){this.options.numBars=q.numBars;}};o.renderData=function(){if(b.falsy(this.data)){this.hideCharts("no data to display");
return;}if(o.data.length>this.options.numBars){var w=this.scales[this.options.xAttr],u=this.scales[this.options.yAttr];var t;
if(this.options.variation===e.VERTICAL){t=this.barUtils.containerBarsVertical(this.chartGroup,this.getData(),this.getPrimaryDataJoin(),this.barPositioningFn,true).barVertical(this.options.yAttr,u,this.barSize);
}else{t=this.barUtils.containerBarsHorizontal(this.chartGroup,this.getData(),this.getPrimaryDataJoin(),this.barPositioningFn,true).barHorizontal(this.options.xAttr,w,this.barSize);
}this.axisGroup.remove();l.select("#"+this.$el[0].id).style("display","inline");if(this.options.allowScrolling){var v=l.behavior.zoom().on("zoom",null);
o.mainGroup.call(v).on("wheel.zoom",function(){o.scrollOrdinal();}).on("mousedown.zoom",null).on("touchstart.zoom",null).on("touchmove.zoom",null).on("touchend.zoom",null);
}o.zoomScale=l.scale.linear().range([0,o.options.height-o.options.margin.top-o.options.margin.bottom]).domain([0,o.options.height-o.options.margin.top-o.options.margin.bottom]);
o.brush=o.addBrush();}else{l.select("#"+this.$el[0].id).style("display","none");}};o.setBandSizes=function(){this.barSize=this.vertBarSize=o.scales[o.options.yAttr].rangeBand();
this.bandSize=this.barSize*(1+o.options.barPadding);};o.sortData=function(t){this.$el[0].__axisHorizontal.graphOptions.dimension=t;
};o.addBrush=function(){o.chartGroup.select("g.brush").remove();var w=o.scales[o.options.xAttr],v=o.scales[o.options.yAttr];
var x;if(o.data.length<=this.options.numBars){x=o.data.length;}else{x=Math.min(16,Math.max(this.options.numBars,Math.round(o.data.length*0.2)));
}x=x-1;var t;if(o.options.variation==="horizontal"){if(o.options.yScale==="ordinal"){t=v.range().concat().sort(function(z,y){return z-y;
});o.brushExtent=o.brushExtent||[t[0],t[x]];o.brush=l.svg.brush().y(v).extent(o.brushExtent).on("brush",function(){o.brushmoveOrdinal();
}).on("brushend",function(){o.brushendOrdinal();});}else{t=v.domain().concat().sort(function(z,y){return z-y;});o.brushExtent=o.brushExtent||[t[0],t[x]];
o.brush=l.svg.brush().y(v).extent(o.brushExtent).on("brush",function(){o.brushmoveQuantitative();}).on("brushend",function(){o.brushendQuantitative();
});}}else{if(o.options.xScale==="ordinal"){t=w.range().concat().sort(function(z,y){return z-y;});o.brushExtent=o.brushExtent||[t[0],t[x]];
o.brush=l.svg.brush().x(w).extent(o.brushExtent).on("brush",function(){o.brushmoveOrdinal();}).on("brushend",function(){o.brushendOrdinal();
});}else{t=w.domain().concat().sort(function(z,y){return z-y;});o.brushExtent=o.brushExtent||[t[0],t[x]];o.brush=l.svg.brush().x(w).extent(o.brushExtent).on("brush",function(){o.brushmoveQuantitative();
}).on("brushend",function(){o.brushendQuantitative();});}}o.gBrush=o.chartGroup.append("g").attr("class","brush").call(o.brush);
var u;if(o.options.variation==="horizontal"){u=o.options.width-o.options.margin.left-o.options.margin.right;o.gBrush.selectAll(".resize").append("line").attr("x2",u);
o.gBrush.selectAll(".resize").append("path").attr("d",l.svg.symbol().type("triangle-up").size(20)).attr("transform",function(z,y){return y?"translate("+(u/2)+","+4+") rotate(180)":"translate("+(u/2)+","+-4+") rotate(0)";
});o.gBrush.selectAll("rect").attr("width",u);if(o.options.yScale==="ordinal"){o.gBrush.select(".background").on("mousedown.brush",function(){o.brushcenterOrdinal();
});}}else{u=o.options.height-o.options.margin.top-o.options.margin.bottom;o.gBrush.selectAll(".resize").append("line").attr("y2",u);
o.gBrush.selectAll(".resize").append("path").attr("d",l.svg.symbol().type("triangle-up").size(20)).attr("transform",function(z,y){return y?"translate("+-7+","+u/2+") rotate(-90)":"translate("+7+","+u/2+") rotate(90)";
});o.gBrush.selectAll("rect").attr("width",u);if(o.options.xScale==="ordinal"){o.gBrush.select(".background").on("mousedown.brush",function(){o.brushcenterOrdinal();
});}}o.startBrush();return o.brush;};o.startBrush=function(){if(o.gBrush){o.gBrush.call(o.brush.event);}};o.brushmoveOrdinal=function(){var y,u,t;
if(o.options.variation==="horizontal"){y=o.scales[o.options.yAttr];u=o.options.yAttr;}else{y=o.scales[o.options.xAttr];u=o.options.xAttr;
}var w=o.brush.extent();var v=y.domain().filter(function(A){return(w[0]-y.rangeBand()+0.01<=y(A))&&(y(A)<=w[1]-0.01);});o.chartGroup.selectAll(".bar").select("rect").classed({"brush-selected":false,"brush-unselected":true}).filter(function(A){return v.indexOf(A[u])>-1;
}).classed({"brush-selected":true,"brush-unselected":false});var x=o.zoomScale.range();o.zoomScale.domain(w);var z=[o.zoomScale(x[1]),o.zoomScale(x[0])];
this.$el.trigger(i.CHART_TO_VIEW_EVENT,{type:"brushableBarChartData",data:{newScale:z,selected:v,numSelected:v.length}});
};o.brushcenterOrdinal=function(){var A=(o.options.variation==="horizontal"?o.scales[o.options.yAttr]:o.scales[o.options.xAttr]);
var z=l.event.target,y=o.brush.extent(),x=y[1]-y[0],w=A.range(),v=l.min(w)+x/2,u=l.max(w)+A.rangeBand()-x/2,t=Math.max(v,Math.min(u,l.mouse(z)[1]));
l.event.stopPropagation();o.gBrush.call(o.brush.extent([t-x/2,t+x/2])).call(o.brush.event);};o.brushmoveQuantitative=function(){};
o.brushendOrdinal=function(){};o.brushendQuantitative=function(){};o.scrollOrdinal=function(A){A=A?A:(o.options.variation==="horizontal"?l.event.deltaY:l.event.deltaX);
var z=(o.options.variation==="horizontal"?o.scales[o.options.yAttr]:o.scales[o.options.xAttr]);var y=o.brush.extent(),w=y[1]-y[0],v=z.range(),u=l.min(v),t=l.max(v)+z.rangeBand(),x;
if(y[0]-A<u){x=u;}else{if(y[1]-A>t){x=t-w;}else{x=y[0]-A;}}l.event.stopPropagation();l.event.preventDefault();o.gBrush.call(o.brush.extent([x,x+w])).call(o.brush.event);
};return o;}return h;});