define("chart/widgetFramework/chartTypes/lineChart",["jquery","underscore","d3","hogan","util/Functional","chartutil/d3utils","chartutil/stringutils","util/ObjectSuper","chart/widgetFramework/core/drivers/axisBaseView"],function(c,f,i,d,a,j,b,e,g){var h=function(o,q,s,r){var k="Default Line Name";
var p;var m={};var t=f.defaults(o,m);p=g(t,q);var n=e(p);p.isBarChart=false;p.timeline=s;p.tranTime=500;p.toggleLineChar="\u2716";
p.defaultLineClass="line-holder";var l=true;p.init=function(){n.init();this.$resetBtn=this.$el.find(".reset-line-icon");setTimeout(function(){p.$resetBtn.css("display","none");
},10);this.$resetBtn.on("click",function(){p.data=p.masterData;p.render();p.$resetBtn.css("display","none");});};p.initRender=function(){n.initRender();
this.$resetBtn.css("left",(this.$el.width()-(20))+"px");};p.feedData=function(u){var v=n.feedData(u);this.masterData=this.data;
if(this.timeline){this.configData.granularity=this.timeline.getGranularity();}if(a.falsy(this.data)){if(l){l=false;var w=a.notFalsy(this.options.nestedAttr)?this.options.nestedAttr:"lineValues";
this.setNestedAttr(w,true);}return;}this.setNestedAttr(this.data,true);return v;};p.setBandSizes=function(){if(a.notFalsy(this.data)){this.maxLinePoints=0;
f.each(this.data,function(v){var u=v[p.nestedAttr].length;if(u>p.maxLinePoints){p.maxLinePoints=u;}});this.bandSize=(this.width/this.maxLinePoints);
this.barSize=this.horizBarSize=(this.bandSize*(1-this.options.barPadding));}};p.xAccessor=function(w){var u=this.scales[this.options.xAttr],v=this.options.centerPoints;
if(v){return function(y,x){return((p.bandSize*x)+(p.bandSize/2));};}else{return function(x){return u(p.getXAttrVal(x));};
}};p.yAccessor=function(u){var v=this.scales[this.options.yAttr];return function(w){return v(p.getYAttrVal(w));};};p.getLineData=function(u){return u[this.nestedAttr];
};p.renderData=function(){this.dropEmptyData();if(a.falsy(this.data)){this.hideCharts("no data to display");return;}var K=this.scales[this.options.xAttr],H=this.scales[this.options.yAttr],J=this.tranTime,w=this.options.centerPoints,u=this.options.lineDataProp||this.options.joinAttr||"",F=this.options.interpolate||"linear",v=[],G,E,I=[];
var D=this.chartGroup.selectAll("."+this.defaultLineClass).data(this.getData(),this.getPrimaryDataJoin());var C=D.enter().append("g").attr("class",this.defaultLineClass).append("path").attr("class","line");
if(this.options.allowToggleLine){var L=D.transition().duration(J).ease("exp-in-out").style("opacity",1);}D.attr("class",function(x){return p.getClassName("",x[u]);
});D.select(".line").attr("d",function(x){return p.lineUtils.lineCreator("L",F,p.getLineData(x),p.xAccessor(x),p.yAccessor(x),"enter",i.select(this));
}).transition().duration(J).ease("exp-in-out").style("opacity",1).attr("d",function(x){return p.lineUtils.lineCreator("L",F,p.getLineData(x),p.xAccessor(x),p.yAccessor(x),"update");
});p.performLineExit(D,F,J);if(this.options.hasDots){G=D.selectAll("."+this.defaultLineClass+"-dot").data(function(x){return p.getLineData(x);
});var M=G.enter().append("circle").attr("class",p.defaultLineClass+"-dot").attr("cx",function(y,x){if(w){return((p.bandSize*x)+(p.bandSize/2));
}else{return K(p.getXAttrVal(y));}}).attr("cy",function(x){return 0;}).attr("r",3);G.attr("class",function(x){return p.getClassName("-dot",x[u]);
});G.transition().duration(J).ease("exp-in-out").each(function(O){var y=c(i.select(this).node());var x=O[u];if(!x){x=k;}var N=b.lowerCaseReplaceSpace(x,"-");
if(N.length&&N!=="undefined"){y.attr("data-id",N);}}).attr("cx",function(y,x){if(w){return((p.bandSize*x)+(p.bandSize/2));
}else{return K(p.getXAttrVal(y));}}).attr("cy",function(x){return H(x[p.options.yAttr]);}).style("opacity",1);var A=G.exit().transition().duration(J).attr("cy",function(x){return p.height+10;
}).style("opacity",0).remove();}else{G=D.selectAll("."+this.defaultLineClass+"-dot").transition().duration(J).attr("cy",function(x){return p.height+10;
}).style("opacity",0).remove();}if(this.options.hasLabels){var B;E=this.chartGroup.selectAll("."+this.defaultLineClass+"-label").data(this.getData(),this.getPrimaryDataJoin());
E.enter().append("text").attr("class",function(x){this.masterD=x;return p.defaultLineClass+"-label";}).style("cursor",function(x){if(p.options.allowToggleLine){c(this).attr("data-col",c(this).css("fill"));
return"pointer";}else{return"auto";}}).attr("dy",".35em").attr("y",0).on("mousedown",function(x){if(p.options.allowToggleLine){p.hideLine(this.masterD,this);
p.$resetBtn.css("display","inline");}else{return null;}});E.attr("class",function(x){return p.getClassName("-label",x[u]);
}).datum(function(O){var y=O[p.nestedAttr];if(a.falsy(y)){O.labelPosValue=-1;return O;}var N=f.findLast(y,function(P){return P[p.options.yAttr]!==null;
});var x=N[p.options.yAttr];O.labelPosValue=x;return O;}).sort(function(y,x){return y.labelPosValue<x.labelPosValue;}).transition().duration(J).attr("x",this.width+10).attr("y",function(y){var x=p.lineUtils.checkLabelPos(H(y.labelPosValue),v,y.labelPosValue,y[p.options.lineDataProp]);
y.yPos=x;return x;}).text(function(x){if(x.labelPosValue===-1){return"";}if(p.options.allowToggleLine){B=p.getLabelName(x);
return B+" "+p.toggleLineChar;}else{B=p.getLabelName(x);return B;}});if(this.options.allowToggleLine){E.style("opacity",1).style("cursor","pointer");
}else{E.style("cursor","initial");}var z=E.exit().transition().duration(J).attr("y",function(){if(p.options.allowToggleLine){return -5;
}return p.height+10;}).style("opacity",function(x){if(p.options.allowToggleLine){return 0.2;}return 0;}).style("cursor","default").each(function(){if(p.data.length===p.masterData.length){i.select(this).remove();
}});}else{E=this.chartGroup.selectAll("."+this.defaultLineClass+"-label").transition().duration(J).attr("y",function(x){return p.height+10;
}).style("opacity",0).remove();}};p.dropEmptyData=function(){if(this.data){var v=this.data.length;for(var u=v-1;u>-1;u--){if(a.falsy(this.data[u][this.nestedAttr])){this.data.splice(u,1);
}}}};p.performLineExit=function(w,v,u){};p.getClassName=function(u,w){if(!w){w=k;}var v=b.lowerCaseReplaceSpace(w,"-");if(w&&v.length){return this.defaultLineClass+u+" "+v;
}else{return this.defaultLineClass+u;}};p.getLabelName=function(w){var u=this.options.lineDataProp||this.options.joinAttr||"";
var v=w[u];if(!v){v=k;}return b.lowerCaseReplaceSpace(v,"-");};p.hideLine=function(A,y){var x=c(y).attr("class");var v=x.match(/\s(.*)/)[1];
var u="."+this.defaultLineClass+".";var w=v.replace(/\s+/g,".");if(v.length){var z=this.$el.find(u+w);z.fadeTo(250,0);this.filterData(A);
}};p.filterData=function(v){var u=this.options.lineDataProp||this.options.joinAttr;var w=f.filter(this.data,function(x){return x[u]!==v[u];
});this.data=w;this.render();};return p;};return h;});