define("chart/widgetFramework/composed/baseline/AggregateDataFD",["jqueryExtended","underscore","d3","chartutil/dateUtils_CET","chart/widgetFramework/core/constants/DataConstants"],function(f,a,b,e,d){function c(h,g){this.data=h;
this.options=g;this.formattedData={};this.ticks=this.data.ticks;this.baselineData=this.data.baselineData;this.comparator=this.compareFunction;
this.reverseDirection=false;this.sortKey=null;}c.prototype.formatData=function(){if(!this.ticks){this.aggregatedData=[];return this.aggregatedData;
}this.aggregatedData=this.createAggregateData();var h=a.max(this.aggregatedData,function(i){return i.tx;});var g=h.tx;this.aggregatedData.forEach(function(j){var i=0;
f.each(j.barArray,function(l,n){if(j.pmName){n.pmName=j.pmName;}n.startX=j.total>0?i:0;var k=j.total>0?Math.max(0,n.value)/j.total:0;
var m=g*k;n.endX=n.startX+m;i+=m;});});if(this.sortKey){this.reverseDirection=!this.reverseDirection;this.sortData(this.sortKey,true);
}return{chartData:this.aggregatedData};};c.prototype.createAggregateData=function(){var j=["authorised","abandoned"];var g=[];
var h=this;this.ticks.each(function(n,q){n=e.trueRoundToDay(n);var t=n.toFormattedString();var p=t.substring(0,t.lastIndexOf("-"));
var o=h.getTotalsByMonth(p,q===0);var m=h.getAuthsByMonth(p);var u=h.getRatesByMonth(p);var r=(q===0)?"%b '%y":"%b";var l=b.format("0,000");
var k={};k.tx=l(o);k.auths=l(m);k.authRate=Number(b.format(".1f")(u));k.pmName=b.time.format("%b")(n);var s={};s.date=n;s.auths=m;
s.tx=o;s.authRate=Number(b.format(".1f")(u));s.pmName=b.time.format(r)(n);s.totalsArray=[];s.totalsArray.push(k);s.barArray=[];
j.forEach(function(w){var v={};v.name=w;if(w==="authorised"){v.value=m;}else{if(w==="abandoned"){v.value=o-m;}}s.barArray.push(v);
});g.push(s);});var i=a.max(a.pluck(g,"tx"));g.forEach(function(k){k.barArray.push({name:"rest",value:i-k.tx});k.total=i;
});return g;};c.prototype.getTotalsByMonth=function(h,i){var g=this.getAmountByMonth(h,"total",i);return g;};c.prototype.getAuthsByMonth=function(h){var g=this.getAmountByMonth(h,"authorisations");
return g;};c.prototype.getRatesByMonth=function(g){var h=(this.getAuthsByMonth(g)/this.getTotalsByMonth(g))||0;return h*100;
};c.prototype.getAmountByMonth=function(i,l,k){var j=0;var h=a.map(this.baselineData,function(m){if(m.amsDate&&m.amsDate.toFormattedString().indexOf(i)>-1){j+=m[l];
return m[l];}return false;});var g=a.reduceRight(h,function(m,n){return m+n;},0);return g;};c.prototype.sortData=function(g,i){this.sortKey=g;
this.reverseDirection=!this.reverseDirection;var h=a.sortBy(this.aggregatedData,g);if(this.reverseDirection){h.reverse();
}this.aggregatedData=h;if(i===true){return;}this.$el.trigger(d.FORMATTER_INFORM_WIDGET,{type:d.SORTED_DATA,data:{chartData:this.aggregatedData}});
};c.prototype.compareFunction=function(g){return g[this.sortKey];};c.prototype.getData=function(){return(this.aggregatedData)?this.aggregatedData:this.formatData();
};c.prototype.setRawData=function(g){this.data=g;this.ticks=this.data.ticks;this.baselineData=this.data.baselineData;};c.prototype.setOptions=function(g){this.options=g;
};return c;});