define("map/events/worldevents",[],function(){var a={};a.BASE="world:";a.BREADCRUMB_SELECTED=a.BASE+"breadcrumbSelected";
a.TOTAL_SESSIONS=a.BASE+"totalSessions";a.AT_COUNTRY_LEVEL=a.BASE+"countryLevel";a.BAR_CLICKED=a.BASE+"barClicked";return a;
});define("map/views/ui/mappanel",["d3","backbone","jquery","underscore","chartlib/ui/collapsibleview","map/events/worldevents","chartlib/events/appstateevents"],function(d,h,f,c,b,g,e){var a=b.extend({el:f(".panel.world"),collapsed:false,dataType:"Sessions",clickedMapBarValue:0,atCountryLevel:false,initialize:function(){c.bindAll(this,"renderButtons");
this.header=this.$el.find(".header");this.collapsible.push(this.$el.find(".content"));this.icon=this.$el.find(".header > .arrow");
this.totalTxt=this.$("#worldVolumeTotalText");if(typeof arguments[0].dataType!=="undefined"){this.dataType=arguments[0].dataType;
}h.on(e.STATE_CHANGED,this.renderButtons);h.on(g.TOTAL_SESSIONS,this.setTotal,this);h.on(g.AT_COUNTRY_LEVEL,this.setCountryLevel,this);
h.on(g.BAR_CLICKED,this.mapBarClicked,this);},setTotal:function(j){var i=d.format("0,000");var k=i(j);if(j===0&&this.atCountryLevel){k=i(this.clickedMapBarValue);
this.totalTxt.html("Total "+this.dataType+": <b>"+k+"</b>");h.trigger(g.TOTAL_SESSIONS,this.clickedMapBarValue,0,"mapdata");
}else{this.totalTxt.html("Total "+this.dataType+": <b>"+k+"</b>");}},setCountryLevel:function(i){this.atCountryLevel=i;},mapBarClicked:function(i){this.clickedMapBarValue=i.get("total");
},renderButtons:function(m,n,l,k){this.totalTxt.html("Total "+this.dataType+": <b>"+0+"</b>");var i=this.header.find(".world-breadcrumb");
var j=i.find("button[targetLabel]");j.remove();f.each(this.model.get("stateMap"),f.proxy(function(p,q){var r=(p>0)?'<i class="icon-chevron-right"></i> ':"";
r+=this.collection.getRegionNameByLabel(q.get("label"))||"World";var o=f("<button></button>");o.addClass("world-button");
o.html(r);o.attr("targetLabel",q.get("label"));o.attr("targetType",q.get("statsType"));o.attr("targetRegion",q.get("region")||q.get("ccs"));
i.append(o);this.initButton(o);},this));if(i.find("button[targetLabel]").length===3){h.trigger(g.AT_COUNTRY_LEVEL,true);}else{h.trigger(g.AT_COUNTRY_LEVEL,false);
}},initButton:function(i){i.on("click",f.proxy(function(k){k.stopPropagation();h.trigger(g.BREADCRUMB_SELECTED);var j=f(k.currentTarget).attr("targetLabel")||"world";
h.trigger(e.CHANGE_REQUESTED,j,f(k.currentTarget).attr("targetType"),f(k.currentTarget).attr("targetRegion"));},this));}});
return a;});define("map/models/appstate",["jquery","underscore","backbone","chartlib/events/appstateevents","chartutil/objectutils"],function(c,a,f,b,e){var d=f.Model.extend({defaults:{baseURL:null,stateMap:{}},initialize:function(){a.bindAll(this,"changeState");
f.on(b.CHANGE_REQUESTED,this.changeState);},changeState:function(h){if(h==="world"){this.set("stateMap",{});}else{e.removeFrom(this.get("stateMap"),h);
this.get("stateMap")[h]="";}var g=this.get("baseURL")+e.joinKeys(this.get("stateMap"),"/");f.trigger(b.STATE_CHANGED,g,h);
}});return d;});define("map/models/region",["jquery","underscore","backbone","backbonenested"],function(c,a,e,d){var b=e.NestedModel.extend({defaults:{regionName:"",total:0,link:{statsType:"",region:""},chargeback:0}});
return b;});define("map/views/charts/mapchart",["jquery","underscore","backbone","chartlib/barchart","d3","map/events/worldevents","chartlib/events/appstateevents","chartutil/d3utils"],function(c,g,f,b,h,a,d,i){var e=b.extend({el:".worldvolume-chart",defaults:{joinAttr:"regionName",barHeight:15,barPadding:0.2,margin:{top:0,left:100,bottom:30,right:10},xAttr:"total",yAttr:"regionName",yScale:"ordinal",tooltip:true,showTipFromText:true,dataType:"sessions",isClickable:true,clickFromText:true},initialize:function(){g.bindAll(this,"onBarClicked");
this._super();},addListeners:function(){if(this.collection){this.listenTo(this.collection,"sort",this.render);}f.on(d.STATE_CHANGED,this.transitionOut,this);
f.on(d.RENDER_CHARTS,this.render);},render:function(){if(!this.collection.hasViewableData){return;}var j=(this.collection.length*this.options.barHeight)+this.options.margin.top+this.options.margin.bottom;
h.select(this.el).transition().style("height",j+"px");this._super();},onBarClicked:function(j){this.hideTooltip(false);if(j.get("link").statsType&&j.get("link").region){f.trigger(a.BAR_CLICKED,j);
f.trigger(d.CHANGE_REQUESTED,j.get("label"),j.get("link").statsType,j.get("link").region);}},transitionOut:function(){this.xAxis.transition().duration(500).delay(0).ease("exp-in-out").attr("transform","translate(0,0)");
},renderTooltipContent:function(l){var k=this;var j=h.format("0,000");var m=j(k.getX(l));this.tip.html(function(n){return"<strong>"+k.getY(l)+":</strong> <span>"+m+"</span> "+k.options.dataType;
});this.tip.direction("e");this.tip.offset([2,10]);},calibrateXScale:function(){this._super();this.scales.x.nice();},formatXAxis:function(){var k=this,j=this.axes.x;
j.tickFormat(function(n,m){var l=i.thousandsFormatter(n,m,k.scales.x);return l;});},renderXAxis:function(){this._super();
this.xAxis.selectAll("text").attr("transform",function(){return"translate(0,7)";});},calibrateYScale:function(){this.scales.y.domain(this.collection.pluck(this.options.yAttr)).rangeBands([this.height,0],this.options.barPadding);
},formatYAxis:function(){var j=this.axes.y;j.tickFormat(function(k){return(k.length>14)?c.trim(k).substring(0,12).trim(this)+"...":k;
});},showToolTip_fromText:function(j){var k=this._super(j);if(typeof window.SVGElement==="undefined"){return;}k.select("rect").classed("textTip",true);
},hideToolTip_fromText:function(j){var k=this._super(j);k.select("rect").classed("textTip",false);}});return e;});define("map/views/ui/mapui",["jquery","underscore","backbone","chartlib/ui/baseui","chartlib/events/appstateevents","backbonesuper"],function(f,a,g,e,d,b){var c=e.extend({el:"#worldUI",events:{"click .sort-region-button":"onRegionClick","click .sort-volume-button":"onVolumeClick","click .sort-chargeback-button":"onChargebackClick"},initialize:function(){this.listenTo(this.collection,"reset",this.render);
this.regionButton=f(".worldui.sort-region-button");this.volumeButton=f(".worldui.sort-volume-button");this.chargebackButton=f(".worldui.sort-chargeback-button");
this.buttons.push(this.regionButton);this.buttons.push(this.volumeButton);this.buttons.push(this.chargebackButton);},render:function(){this._super(arguments);
},onVolumeClick:function(h){this.renderButtons(f(h.currentTarget));this.collection.sortByVolume();},onRegionClick:function(h){this.renderButtons(f(h.currentTarget));
this.collection.sortByRegion();},onChargebackClick:function(h){this.renderButtons(f(h.currentTarget));this.collection.sortByChargeback();
}});return c;});define("map/collections/mapdata",["jquery","underscore","backbone","map/models/region","chartutil/objectutils","chartlib/events/appstateevents","chartlib/chartBaseEvents","map/events/worldevents"],function(c,h,g,i,b,d,f,a){var e=g.Collection.extend({model:i,reverseDirection:false,regionNameMap:{},urlParamProps:["statsType","region","ccs","granularity","bdate","edate"],initialize:function(){h.bindAll(this,"parse","loadRegion","getReverseDirection","getRegionNameByLabel","formatRegion","onLoaded","onError");
g.on(d.STATE_CHANGED,this.loadRegion);this.listenTo(this,"error",function(){this.trigger(f.DATA_FAILED);});this.comparator=this.compareFunction;
this.sortKey="total";},loadRegion:function(m){this.loaded=c.Deferred();var j=h.pick(m.attributes,this.urlParamProps);var l=m.get("label");
if(l.length){l=l+"/";}var k=m.get("stubURL")?m.get("stubURL"):"/chart/charts/paymentMethods/dummy-data/";this.url=(m.get("stub"))?adyen.jsbase+k+l+"map.xml?"+new Date().getTime():m.get("url")+c.param(j)+"&cb="+new Date().getTime();
this.fetch({reset:true});},fetch:function(j){j||(j={});j.dataType="xml";j.success=this.onLoaded;j.error=this.onError;this._super(j);
g.trigger(f.REGISTER_DEFERRED,this.loaded,"mapdata",this);},parse:function(p){var k=[],o;var q=0;var j=0,n=100000000;var m=false;
this.hasViewableData=true;c(p).find("entity").each(c.proxy(function(s,v){m=true;o=c(v);var r=Number(o.attr("toolText").match(/([^\s]+)/)[0]);
if(isNaN(r)){r=o.attr("toolText").match(/:\s(.*?)\s/);r=(r)?Number(r[1]):0;}if(r>0){if(r>j){j=r;}if(r<n){n=r;}q+=r;var u=this.formatRegion(o);
var t=o.attr("label").toLowerCase();u.set("label",t);k.push(u);this.regionNameMap[t.toLowerCase()]=u.get("regionName");}},this));
g.trigger(a.TOTAL_SESSIONS,q,0,"mapdata");var l=h.every(k,function(r){return isNaN(r.get("total"))||r.get("total")<=0;});
if(l&&m){this.hasViewableData=false;this.trigger(f.DATA_FAILED);}return k;},formatRegion:function(j){return new i({regionName:j.attr("toolText").match(/from (.*)/)[1],total:+j.attr("toolText").match(/([^\s]+)/)[0],link:{statsType:j.attr("link")?j.attr("link").split(",")[1]:"",region:j.attr("link")?j.attr("link").split(",")[2]:""}});
},addUrlParamProps:function(j){this.urlParamProps=this.urlParamProps.concat(j);},onError:function(l,j,k){if(window.console&&window.console.log){window.console.log("MapData load error: ",l,j.getResponseHeader("content-type"),k);
}this.loaded.reject(j);},onLoaded:function(){this.loaded.resolve();},getReverseDirection:function(){return this.reverseDirection;
},getRegionNameByLabel:function(j){return this.regionNameMap[j];},sortByRegion:function(){this.comparator=this.compareFunction;
this.reverseDirection=!this.reverseDirection;this.sortKey="regionName";this.sort();},sortByVolume:function(){this.comparator=this.compareFunction;
this.reverseDirection=!this.reverseDirection;this.sortKey="total";this.sort();},sortByChargeback:function(){this.comparator=this.compareFunction;
this.reverseDirection=!this.reverseDirection;this.sortKey="chargeback";this.sort();},compareFunction:function(k,j){var m=k.get(this.sortKey),l=j.get(this.sortKey);
if(this.reverseDirection){if(m>l){return -1;}if(l>m){return 1;}return 0;}else{if(m<l){return -1;}if(l<m){return 1;}return 0;
}}});return e;});