define("timeline/views/ui/timelineUI_v7",["jquery","underscore","backbone","d3","chartutil/dateUtils_CET","timeline/events/timelineEvents","timeline/util/timelineConstants","chartlib/events/appstateevents","chartlib/chartBaseEvents","chartutil/domUtils","util/Analytics"],function(c,j,i,l,b,k,f,d,g,a,h){var e=i.View.extend({el:"#timelineUI",events:{"click #monthsBtn":"onModeButtonClick","click #weeksBtn":"onModeButtonClick","click #daysBtn":"onModeButtonClick","click #hoursBtn":"onModeButtonClick","click #minutesBtn":"onModeButtonClick","change #timelineChartGranularity":"onConfigChange","change #timelinePresetsSelect":"onPreset"},version:4,hasControls:false,hasChartPresets:false,allowDynamicPresets:false,initialize:function(){this._super();
j.bindAll(this,"onPeriodJump","onOutputURL");this.presets=this.$("#timelinePresets");this.presetsSelect=this.$("#timelinePresetsSelect");
this.monthsBtn=this.$("#monthsBtn");this.weeksBtn=this.$("#weeksBtn");this.daysBtn=this.$("#daysBtn");this.hoursBtn=this.$("#hoursBtn");
this.minutesBtn=this.$("#minutesBtn");this.daysTxt=this.$("#numDaysMove");this.minutesTxt=this.$("#numMinutesMove");this.datesTxt=this.$("#dateSelected");
this.loader=c("#timelineLoader");this.controls=c("#timelineControls");this.tzWarning=c("#amsTimeWarning");this.uid=this.collection.getValue("uid");
i.on(k.SET_DISPLAY,this.configureDisplay,this);i.on(k.SET_DAYS,this.displayDays,this);i.on(k.TIMESPAN_SET,this.displayDates,this);
i.on(k.TIMESPAN_SET_UTC,this.displayDates,this);i.on(k.SET_GRANULARITY,this.hideModeButtons,this);i.on(k.SET_CHART_GRAN_SELECT,this.setChartGranularity,this);
i.on(d.STATE_CHANGED,this.showLoader,this);if(arguments[0].loadQueue){i.on(d.RENDER_CHARTS,this.hideLoader,this);}else{i.on(g.DATA_LOADED,this.hideLoader,this);
}if(this.collection.getValue("dynamicGranularityDisabling")&&this.collection.getValue("config")){i.on(k.TIMESPAN_SET,this.dynamicGranularityDisabling,this);
}if(this.collection.getValue("config")===true){var m=this.collection.getValue("chartGranularity");var p=this.collection.getValue("baseGranularity");
var q=this.$("#timelineConfigUI");q.css("display","block");this.$(".tl-config-opt").each(function(w,y){var v=c(y);var x=Number(v.attr("data-rel"));
if(x<p){v.remove();}});this.chartGranSelect=this.$("#timelineChartGranularity");this.setChartGranularity(m,false);this.chartGranDisabled=this.collection.getValue("chartGranularityDisabled");
if(this.chartGranDisabled){this.chartGranSelect.attr("disabled",true);this.$("#timelineChartGranularity + span").css("display","none");
var o=this.$("#timelineChartGranularity option:selected").text();this.$("#timelineChartGranularity option:selected").text("Show in: "+o);
}}if(this.collection.getValue("controls")===true){this.hasControls=true;this.controls.css("display","block");i.on(k.DISABLE_CONTROLS,this.disableControls,this);
i.on(k.ENABLE_CONTROLS,this.enableControls,this);var s=c("#jumpBackBtn");s.attr("data-action",f.__BACK);s.on("click",this.onPeriodJump);
this.extentEndBtn=c("#jumpExtentEndBtn");this.extentEndBtn.attr("data-action",f.__END_EXTENT);this.extentEndBtn.on("click",this.onPeriodJump);
this.extentStartBtn=c("#jumpExtentStartBtn");this.extentStartBtn.attr("data-action",f.__START_EXTENT);this.extentStartBtn.on("click",this.onPeriodJump);
var n=c("#jumpFwdBtn");n.attr("data-action",f.__FWD);n.on("click",this.onPeriodJump);this.controlBtns={};this.controlBtns[f.__BACK]=s;
this.controlBtns[f.__FWD]=n;this.controlBtns[f.__END_EXTENT]=this.extentEndBtn;this.controlBtns[f.__START_EXTENT]=this.extentStartBtn;
this.disableControls("startup");var t=this;c("body").keydown(function(v){if(v.keyCode===85&&v.ctrlKey){i.trigger(k.OUTPUT_URL,true);
}});c("#outputURL").css("display","block");c("#outputURL").on("click",this.onOutputURL);}var u=this.collection.getValue("presets");
if(u.length){this.hasChartPresets=true;var r;this.presets.css("display","block");if(j.contains(u,f.__PRESET_LAST_7_DAYS)){r='<option value="'+f.__PRESET_LAST_7_DAYS+'">Last 7 days</option>';
this.presetsSelect.append(r);}if(j.contains(u,f.__PRESET_LAST_4_WEEKS)){r='<option value="'+f.__PRESET_LAST_4_WEEKS+'">Last 4 weeks</option>';
this.presetsSelect.append(r);}if(j.contains(u,f.__PRESET_LAST_30_DAYS)){r='<option value="'+f.__PRESET_LAST_30_DAYS+'">Last 30 days</option>';
this.presetsSelect.append(r);}if(j.contains(u,f.__PRESET_LAST_YEAR)){r='<option value="'+f.__PRESET_LAST_YEAR+'">Last year</option>';
this.presetsSelect.append(r);}}this.allowDynamicPresets=this.collection.getValue("allowDynamicPresets");if(this.allowDynamicPresets){this.presets.css("display","block");
}if(this.hasControls||this.collection.getValue("forceCET")===true){this.increaseHeight();}c("body").keydown(function(v){if(v.altKey){i.trigger(k.ALT_KEY_PRESS,true);
}});c("body").keyup(function(v){if(v.keyCode===18){i.trigger(k.ALT_KEY_UP,false);}});},dynamicGranularityDisabling:function(){var p=this.collection.getValue("extent");
var m=Math.floor(b.getNumDays(p[1],p[0]));var r=this.collection.getValue("granularityDisablingConstraints");for(var q in r){var o=this.chartGranSelect.find('option[value="'+q+'"]');
if(m<=r[q]){var n=this.chartGranSelect.val();if(n===q&&o.prev()&&o.prev()[0].index>0){this.setChartGranularity(o.prev().val(),true);
}o.addClass("disabled");}else{o.removeClass("disabled");o.prop("disabled",false);}}},increaseHeight:function(){var r=this.$el.parent();
var n=r.height();var o=c("#configUI").height();var p=(o)?15:5;this.$el.parent().css("height",(n+20)+"px");var m=a.getComputedProperties(this.loader);
var q=parseInt(m.top);this.loader.css("top",(q+o+p)+"px");this.loader.css("display","none");},setChartGranularity:function(m,n){if(this.chartGranSelect&&!this.chartGranDisabled){this.chartGranSelect.val(m);
}if(n){this.collection.setValue("chartGranularity",m);}},onModeButtonClick:function(n){var p=c(n.currentTarget);var o=p.attr("data-action");
var m=p.text().toLowerCase();var q=m.substring(0,m.length-1);this.setChartGranularity(q,true);if(o!==""){h.trackEvent("Timeline_"+this.uid,"timeline.event.granularity-button-"+c(n.currentTarget).attr("id"));
i.trigger(k.MODE_CHANGED,c(n.currentTarget).attr("id"),o);}},onConfigChange:function(m){if(window.console&&console.log){console.log("### timelineUI_v7::onConfigChange:: VALUE=",c(m.currentTarget).val());
}if(c(m.currentTarget).val()==="default"){return;}this.collection.setValue("chartGranularity",c(m.currentTarget).val());i.trigger(d.CHANGE_REQUESTED);
},onOutputURL:function(){i.trigger(k.OUTPUT_URL,true);},configureDisplay:function(){var p=this.collection.getValue("formatPeriod");
var q='<i class="icon-chevron-left"></i>';var m='<i class="icon-chevron-right"></i>';var n=c("#jumpBackBtn");var o=c("#jumpFwdBtn");
n.show();o.show();switch(p){case f.__MINUTE_FORMAT:this.minutesBtn.toggleClass("disabled",true);this.monthsBtn.toggleClass("disabled",false);
this.weeksBtn.toggleClass("disabled",false);this.daysBtn.toggleClass("disabled",false);this.hoursBtn.toggleClass("disabled",false);
this.monthsBtn.attr("data-action","jumpOut");this.weeksBtn.attr("data-action","jumpOut");this.daysBtn.attr("data-action","jumpOut");
this.hoursBtn.attr("data-action","jumpOut");this.minutesBtn.attr("data-action","");n.html(q+" previous 60 mins");o.html("next 60 mins "+m);
if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_MINUTE,"Latest minute");}break;case f.__HOUR_FORMAT:this.hoursBtn.toggleClass("disabled",true);
this.monthsBtn.toggleClass("disabled",false);this.weeksBtn.toggleClass("disabled",false);this.daysBtn.toggleClass("disabled",false);
this.minutesBtn.toggleClass("disabled",false);this.monthsBtn.attr("data-action","jumpOut");this.weeksBtn.attr("data-action","jumpOut");
this.daysBtn.attr("data-action","jumpOut");this.minutesBtn.attr("data-action","jumpIn");this.hoursBtn.attr("data-action","");
n.html(q+" previous 48 hours");o.html("next 48 hours "+m);if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_HOUR,"Latest hour");
}break;case f.__DAY_FORMAT:this.daysBtn.toggleClass("disabled",true);this.monthsBtn.toggleClass("disabled",false);this.weeksBtn.toggleClass("disabled",false);
this.hoursBtn.toggleClass("disabled",false);this.minutesBtn.toggleClass("disabled",false);this.monthsBtn.attr("data-action","jumpOut");
this.weeksBtn.attr("data-action","jumpOut");this.hoursBtn.attr("data-action","jumpIn");this.minutesBtn.attr("data-action","jumpIn");
this.daysBtn.attr("data-action","");n.html(q+" previous 31 days");o.html("next 31 days "+m);if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_DAY,"Latest day");
}break;case f.__WEEK_FORMAT:this.weeksBtn.toggleClass("disabled",true);this.monthsBtn.toggleClass("disabled",false);this.daysBtn.toggleClass("disabled",false);
this.hoursBtn.toggleClass("disabled",false);this.minutesBtn.toggleClass("disabled",false);this.monthsBtn.attr("data-action","jumpOut");
this.daysBtn.attr("data-action","jumpIn");this.hoursBtn.attr("data-action","jumpIn");this.minutesBtn.attr("data-action","jumpIn");
this.weeksBtn.attr("data-action","");n.html(q+" previous 12 weeks");o.html("next 12 weeks "+m);if(this.allowDynamicPresets){this.addDynamicPreset(f.__PRESET_THIS_WEEK,"Latest week");
}break;case f.__MONTH_FORMAT:this.monthsBtn.toggleClass("disabled",true);this.daysBtn.toggleClass("disabled",false);this.weeksBtn.toggleClass("disabled",false);
this.hoursBtn.toggleClass("disabled",false);this.minutesBtn.toggleClass("disabled",false);this.weeksBtn.attr("data-action","jumpIn");
this.daysBtn.attr("data-action","jumpIn");this.hoursBtn.attr("data-action","jumpIn");this.minutesBtn.attr("data-action","jumpIn");
this.monthsBtn.attr("data-action","");n.hide();o.hide();if(this.allowDynamicPresets){this.addDynamicPreset(null);}break;}if(this.hasControls){if(p===f.__MINUTE_FORMAT){this.extentEndBtn.css("display","inline-block");
this.extentStartBtn.css("display","inline-block");}else{this.extentEndBtn.css("display","none");this.extentStartBtn.css("display","none");
}}},displayDays:function(o,n){if(o===0){var m=this.collection.getValue("extent");o=Math.floor(b.getNumDays(m[1],m[0]));n=Math.floor(b.getNumMinutes(m[1],m[0]));
}this.daysTxt.html('numDays:  <span style="color:#000">'+o+"<span>");this.minutesTxt.html('numMinutes:  <span style="color:#000">'+n+"<span>");
},displayDates:function(){this.showLoader();this.tzWarning.css("display","none");var m=(this.collection&&typeof this.collection.getValue("forceCET")!=="undefined")?this.collection.getValue("forceCET"):true;
if(m&&((this.collection.getValue("formatPeriod")===f.__HOUR_FORMAT||this.collection.getValue("formatPeriod")===f.__MINUTE_FORMAT))){this.tzWarning.css("display","block");
}},hideModeButtons:function(){var m=this.collection.getValue("baseGranularity");switch(m){case f.__HOUR_GRANULARITY:this.minutesBtn.remove();
break;case f.__DAY_GRANULARITY:this.hoursBtn.remove();this.minutesBtn.remove();break;case f.__WEEK_GRANULARITY:this.daysBtn.remove();
this.hoursBtn.remove();this.minutesBtn.remove();break;case f.__MONTH_GRANULARITY:this.weeksBtn.remove();this.daysBtn.remove();
this.hoursBtn.remove();this.minutesBtn.remove();break;}},showLoader:function(){this.loader.css("display","block");},hideLoader:function(){this.loader.css("display","none");
},onPeriodJump:function(n){this.disableControls("periodJump");var m=c("#timelineHolder");var p=this.$el.parent().find(".block");
l.selectAll(p).classed("gaussian-blur-x",true);var o=c(n.currentTarget).attr("data-action");switch(o){case f.__THEN:case f.__BACK:m.addClass("translateBack");
break;case f.__NOW:case f.__FWD:m.addClass("translateFwd");break;}i.trigger(k.JUMP_PERIOD,o);},disableControls:function(m){j.each(this.controlBtns,function(o,p,n){n[p].addClass("disabled");
});},enableControls:function(m){this.controlBtns[m].removeClass("disabled");},addDynamicPreset:function(n,p){var m=this.presetsSelect.find('[data-rel="latest-period"]');
if(m.length){m.remove();}if(n){var o='<option data-rel="latest-period" value="'+n+'">'+p+"</option>";this.presetsSelect.append(o);
}},onPreset:function(p){var o=c(p.currentTarget).val();var m;if(o===f.__PRESET_LAST_7_DAYS){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_7_DAYS);
this.setChartGranularity(f.__DAY_FORMAT,true);}if(o===f.__PRESET_LAST_4_WEEKS){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_4_WEEKS);
this.setChartGranularity(f.__WEEK_FORMAT,true);}if(o===f.__PRESET_LAST_30_DAYS){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_30_DAYS);
this.setChartGranularity(f.__DAY_FORMAT,true);}if(o===f.__PRESET_LAST_YEAR){i.trigger(k.PRESET_PERIOD,f.__PRESET_LAST_YEAR);
this.setChartGranularity(f.__MONTH_FORMAT,true);}var n=(this.collection.getValue("mondayWeek"))?1:0;if(o===f.__PRESET_THIS_MINUTE){if(this.collection.getValue("timeCollectionMode")===f.__LATEST){f.recalculateDatesAsLatest(true,n);
}i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_MINUTE);this.setChartGranularity(f.__MINUTE_FORMAT,true);}if(o===f.__PRESET_THIS_HOUR){if(this.collection.getValue("timeCollectionMode")===f.__LATEST){f.recalculateDatesAsLatest(true,n);
}i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_HOUR);this.setChartGranularity(f.__HOUR_FORMAT,true);}if(o===f.__PRESET_THIS_DAY){i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_DAY);
this.setChartGranularity(f.__DAY_FORMAT,true);}if(o===f.__PRESET_THIS_WEEK){i.trigger(k.PRESET_PERIOD,f.__PRESET_THIS_WEEK);
this.setChartGranularity(f.__WEEK_FORMAT,true);}this.presetsSelect.val("hgdfkj");}});return e;});