define("chart/widgetFramework/composed/chargebackReport/formatters/paymentMethodBarFormatter",["jqueryExtended","underscore","d3","chart/widgetFramework/core/constants/DataConstants","chartutil/stringutils","chartutil/domUtils"],function(g,b,c,e,f,d){function a(k,h,j,m){var i={};
i.data=k;i.options=h;i.formattedData={};i.comparator=null;i.reverseDirection=false;i.sortKey="chargebackCount";i.timeline=j;
i.id=m;i.dataType="chargebacks";i.rateDataType="count";i.formatData=function(){var n=(this.data&&b.has(this.data,"payment_method_statistics"))?this.data.payment_method_statistics:{};
this.formattedData=l(n);if(this.sortKey){this.reverseDirection=!this.reverseDirection;this.sortData(this.sortKey,true);}if(window.console&&console.log){console.log("### barDataFD::"+this.id+" formatData:: this.formattedData=",this.formattedData);
}return{chartData:this.formattedData};};var l=function(q){var r=c.format(",g4f");var o=[];var n,p;b.each(q,function(v){n={};
p=f.capitaliseAllFirstLetters(v.pm);var s=+v.authorisedEurAmount/100;var u=+v.chargebackEurAmount/100;var t=+v.nofEurAmount/100;
if(i.dataType==="chargebacks"){if(v.pm!==null&&v.chargebackCount>0){n.paymentMethodName=p;n.chargebackCount=+v.chargebackCount;
n.chargebackCountFormatted=r(+v.chargebackCount);n.chargebackEurAmount=u;if(i.rateDataType==="count"){n.chargebackRate=(+v.authorisedCount>0)?+v.chargebackCount/+v.authorisedCount*100:0;
}else{n.chargebackRate=(s>0)?u/s*100:0;}n.chargebackRate=Number(n.chargebackRate.toFixed(4));o.push(n);}}else{if(v.pm!==null&&v.nofCount>0){n.paymentMethodName=p;
n.chargebackCount=+v.nofCount;n.chargebackCountFormatted=r(+v.nofCount);n.chargebackEurAmount=t;if(i.rateDataType==="count"){n.chargebackRate=(+v.authorisedCount>0)?+v.nofCount/+v.authorisedCount*100:0;
}else{n.chargebackRate=(s>0)?t/s*100:0;}n.chargebackRate=Number(n.chargebackRate.toFixed(4));o.push(n);}}});return o;};i.reformatDataChargebacksNof=function(n){this.dataType=n.type;
var o=this.formatData();this.$el.trigger(e.FORMATTER_INFORM_WIDGET,{type:e.REFORMATTED_DATA,data:o});};i.reformatData=function(o){this.rateDataType=o;
var n=this.formatData();this.$el.trigger(e.FORMATTER_INFORM_WIDGET,{type:e.REFORMATTED_DATA,data:n});};i.sortData=function(n,p){this.sortKey=n;
if(this.sortKey===this.oldSortKey){this.reverseDirection=!this.reverseDirection;}else{this.reverseDirection=false;}this.oldSortKey=this.sortKey;
var o=b.sortBy(this.formattedData,n);if(this.reverseDirection){o.reverse();}this.formattedData=o;if(p===true){return;}this.$el.trigger(e.FORMATTER_INFORM_WIDGET,{type:e.SORTED_DATA,data:{chartData:this.formattedData}});
};i.compareFunction=function(n){return n[this.sortKey];};i.downloadCSV=function(){var o=["paymentMethodName","chargebackCount","chargebackEurAmount","chargebackRate"];
var p;var n;if(this.dataType==="chargebacks"){p=["Payment method","Chargeback count","Chargeback amount","Chargeback rate (based on "+this.rateDataType+")"];
n="ChargebacksByPaymentMethod";}else{p=["Payment method","Notifications of fraud count","Notifications of fraud amount","Notifications of fraud rate (based on "+this.rateDataType+")"];
n="NotificationsOfFraudByPaymentMethod";}d.createCSV(this.formattedData,o,p,n);};i.getData=function(){return(this.data)?this.data:this.formatData();
};i.setRawData=function(n){this.data=n;};i.retrieveData=function(n){return this.data[n];};return i;}return a;});