define("chart/widgetFramework/composed/riskReport/riskReportMediator",["jqueryExtended","d3","lodash","chart/widgetFramework/core/BasicMediator","util/ObjectSuper","chartutil/numberutils","chartutil/domUtils","chart/widgetFramework/composed/riskReport/constants/riskConstants","chart/widgetFramework/core/constants/UIConstants"],function(a,n,j,i,g,k,b,d,h){var m=adyen.config||{};
var c=false;var f=false;var e=false;var l=function(o){var p;p=i(o,true);var q=g(p);p.showChargebackLineFlag=true;p.init=function(){q.init();
this.actionCommanderExclusionArray=["actioncommander","timeline"];m.chargebackRowVis="tt-row-no-visible";};p.getAdditionalDOMElements=function(){q.getAdditionalDOMElements();
this.timelineInstances=[];this.$allTimelines=this.$el.find("[data-widget*=Timeline]");this.totalDomElements+=this.$allTimelines.length;
this.snapshotInstances=[];this.$allSnapshots=this.$el.find("[data-widget*=Snapshot]");this.totalDomElements+=this.$allSnapshots.length;
};p.getWidgets=function(){q.getWidgets();this.getWidgetInstances(this.$allTimelines,this.timelineInstances,"Timelines");this.getWidgetInstances(this.$allSnapshots,this.snapshotInstances,"Snapshots");
};p.onNotifiedFetcher=function(t,s){q.onNotifiedFetcher(t,s);if(s==="issuerCountriesFetcher"){var x,w=this.$el.find("#issuerCountry"),r=false;
x='<option value="">-- all Issuer Countries --</option>';j.each(t.changeObject.data,function(z){if(!z){return;}if(j.isObject(z)){if(p.storedIssuerCountry&&p.storedIssuerCountry===z.countryCode){r=true;
}x+='<option value="'+z.countryCode+'">'+z.countryName+"</option>";}else{if(p.storedIssuerCountry&&p.storedIssuerCountry===z){r=true;
}x+='<option value="'+z+'">'+z+"</option>";}});w.html(x);if(this.storedIssuerCountry&&r){a("#issuerCountry").val(this.storedIssuerCountry);
}}if(s==="activePaymentMethodsFetcher"){var y,u=this.$el.find("#paymentMethod"),v=false;y='<option value="">-- all Payment Methods --</option>';
j.each(t.changeObject.data,function(z){if(p.storedPaymentMethod&&p.storedPaymentMethod===z){v=true;}y+='<option value="'+z+'">'+z+"</option>";
});u.html(y);if(this.storedPaymentMethod&&v){a("#paymentMethod").val(this.storedPaymentMethod);}}};p.onNotifiedFormatter=function(s,x){q.onNotifiedFormatter(s,x);
if(x==="receivedTxCountStackedFormatter"){var y=0,t=0,v=0,u=0,r=0,z=n.format(",.2f"),w=n.format(",.0f");j.each(s.changeObject.data.chartData,function(A){v+=(A[d.RECEIVED_TX_TOTAL]);
u+=A[d.RECEIVED_TX_GPM_TOTAL];r+=A[d.RECEIVED_TX_REVPRO_TOTAL];});if(v>0){y=(u/v)*100;t=(r/v)*100;}if(a("#issuerCountry").val()!==""){a(".total-volume").fadeTo(1000,0);
}else{a(".total-volume").fadeTo(500,1);k.animateValue(a("#avgGuaranteed"),y,z);k.animateValue(a("#avgRevPro"),t,z);k.animateValue(a("#totalReceived"),v,w);
k.animateValue(a("#totalGuaranteed"),u,w);k.animateValue(a("#totalRevPro"),r,w);}}if(x==="lineFormatter"){this.lineFormatterRolloverData=s.changeObject.data.chartData.refusalAndChargebackRolloverData;
this.checkFormatterCallbacks();}if(x==="chargebackRateLineFormatter"){if(s.changeObject.data.chartData){this.chargebackLineFormatterData=s.changeObject.data.chartData[0].lineValues;
this.checkFormatterCallbacks();}}};p.checkFormatterCallbacks=function(t){if(this.lineFormatterRolloverData&&this.chargebackLineFormatterData){for(var s=0,r=this.lineFormatterRolloverData.length;
s<r;s++){var u=this.lineFormatterRolloverData[s];var v=this.chargebackLineFormatterData[s];if(u.dateStr===v.name){u.chargebackPercent=v.value;
}}if(!this.showChargebackLineFlag){this.feedDataToRefusalChargebacksLineRollover();}}};p.feedDataToRefusalChargebacksLineRollover=function(){var r=this.getInstanceById("#chargebackLineChartWidget");
var s=this.getInstanceById("#refusalChargebacksLineRollover");r.chart.renderXAxis();s.chart.feedData({config:{},chartData:{refusalAndChargebackRolloverData:this.lineFormatterRolloverData}});
s.chart.render();if(this.chargebackLineVisible){a(".thin-bar.two").css("display","inline");}else{a(".thin-bar.two").css("display","none");
}};p.onNotifiedViewCreator=function(t,r){q.onNotifiedViewCreator(t,r);var s=t.changeObject.type;if(r==="riskChecksStacked"&&(s===h.CHART_INITIALISED||s===h.CHART_UPDATED)){a("#riskChecksSpinner").hide();
a(".risk-check-element").stop();a(".risk-check-element").fadeTo(1000,1);a(".risk-checks-sort-holder").css("pointer-events","auto");
}if(r==="refusalRateLine"&&s===h.CHART_FIRST_RENDER){this.refusalRatesLineChartRendered=true;this.checkViewCallbacks();}if(r==="refusalChargebacksLineRollover"&&s===h.CHART_FIRST_RENDER){this.refusalChargebacksLineRolloverRendered=true;
this.checkViewCallbacks();}};p.checkViewCallbacks=function(){if(this.refusalRatesLineChartRendered&&this.refusalChargebacksLineRolloverRendered){var r=a("#refusalRateLine").height();
p.$el.trigger("setRolloverHeight",{state:"hidden",height:r});}};p.onTimeData=function(){this.lineFormatterRolloverData=null;
this.chargebackLineFormatterData=null;a("#riskChecksSpinner").show();a(".risk-check-element").stop();a(".risk-check-element").fadeTo(500,0);
a(".risk-checks-sort-holder").css("pointer-events","none");if(a("#issuerCountry").val()!==""){this.storedIssuerCountry=a("#issuerCountry").val();
}else{this.storedIssuerCountry=null;}if(a("#paymentMethod").val()!==""){this.storedPaymentMethod=a("#paymentMethod").val();
}else{this.storedPaymentMethod=null;}};p.toggleChargebackRate=function(){var s=a("#chargeback-rate-toggle");var t=a("#chargebackContent");
var u="Compare with chargeback rate";var r="Hide chargeback rate";t.slideToggle();a(".chargeback-panel h2").fadeToggle();
if(s.text()===u){this.chargebackLineVisible=true;if(this.showChargebackLineFlag){this.feedDataToRefusalChargebacksLineRollover();
this.showChargebackLineFlag=false;}a(".thin-bar.two").css("display","inline");s.text(r);m.chargebackRowVis="tt-row-visible";
p.$el.trigger("setRolloverHeight",{state:"shown"});}else{this.chargebackLineVisible=false;a(".thin-bar.two").css("display","none");
s.text(u);m.chargebackRowVis="tt-row-no-visible";p.$el.trigger("setRolloverHeight",{state:"hidden",height:a("#refusalRateLine").height()});
}};p.takeRiskChecksSnapshot=function(){var u=b.cloneNode(".risk-checks-legend-holder","riskChecksLegend");var t=["riskReport/css/widgetReport.css"];
b.applyStylesAsInline(u,t);var s=b.nodeToString(u);var r=this.getInstanceById("snapshotRiskCheck",this.snapshotInstances);
r.setHtmlStr(s);r.takeSnapshot();};p.takeFraudScoreStackSnapshot=function(){var u=b.cloneNode(".legend-wrapper","fraudScoreStackLegend");
document.body.appendChild(u);var t=["riskReport/css/widgetReport.css"];b.applyStylesAsInline(u,t);var s=b.nodeToString(u);
var r=this.getInstanceById("snapshotFraudScoreStack",this.snapshotInstances);r.setHtmlStr(s);r.takeSnapshot();};p.getInstance=function(){return this;
};p.init();o.ready();return p;};return l;});